"""Derivation for AELLO-C8-S5: every canonical artifact descends from solution/grounding.yaml.

WHAT THIS GENERATOR EMITS AND WHY IT LOOKS LIKE THIS. The checks below are written about a
thirteen-channel fusion over co-registered rasters -- twelve Sentinel-2 reflectance bands and one
elevation channel on the same grid -- and about a per-class IoU that drops absent classes instead
of crediting them. None of them would mean anything on a classifier, a detector or a forecaster.
The paths, band names and channel vocabulary they read live in grounding.yaml's corpus_layout
block and are substituted into the emitted prelude, so the derivation source really is the source
and the generator holds no corpus fact of its own.

Every compiled item carries a hand-written body. There is no generic fallback: an item without a
body is a refusal, because the fallback this generator used to carry looked up an obligation
record that nothing writes, and a check that consults nothing passes for the wrong reason.
"""
import json
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
# generator_common.py is VENDORED beside this file, not reached for outside the bundle. A staged
# tree could resolve seed/stage/<slug>/../../build; a DELIVERED tree at dataset/<uuid>/ cannot,
# and reaching outside would make the delivered bundle non-self-contained -- it would import in
# the stage and fail everywhere it actually ships.

SLOT_ID = 'AELLO-C8-S5'
TITLE = "# AELLO-C8-S5 -- what this task actually tests"
ITEM_KEYS = ('id', 'dimension', 'weight', 'evaluation_target', 'criterion', 'judgment', 'knockout',
             'mode')
ITEM_SCHEMA = frozenset(ITEM_KEYS + ('outcome_class',))
OUTCOME_CLASSES = frozenset(("EFFECT", "INVARIANT", "ABSENCE", "VALUE"))
RAMP = ("floor", "knee", "dichotomizing_threshold", "reward_gate_pass_threshold")
REQUIRE_FIRST = 'c = require_measured("floor", "knee", "dichotomizing_threshold")'


def read_identity(here):
    """Identity is an INPUT: the freeze computes it over the hashed tree and binds it into the
    carrier, which is hash-excluded, so reading it back keeps generation acyclic."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        if isinstance(doc.get("identity"), dict):
            return doc["identity"]
    return {"canonical_content_hash": None, "uuid": None,
            "normalization_domain": "aello.canary.norm/v1",
            "derivation": "uuid5(FORGE_TASK_NAMESPACE, canonical_content_hash)"}


def read_screening(here):
    """The screening instant and result are MEASURED OVER the frozen tree, so they are read back
    the way identity is; the carrier is hash-excluded, so binding them moves nothing."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        got = {k: doc[k] for k in ("screening_measured_at", "screening_expires_at",
                                   "screening_result") if k in doc}
        if got:
            return got
    return {"screening_measured_at": None, "screening_expires_at": None,
            "screening_result": None}


def load_grounding():
    with open(os.path.join(HERE, "grounding.yaml")) as fh:
        return yaml.safe_load(fh)


# ==========================================================================================
# The emitted checker. PRELUDE carries the corpus vocabulary and is substituted; BODIES are
# inserted verbatim under their own decorator; TAIL is the measurement machinery and is NOT
# substituted, because it contains percent formatting of its own.
# ==========================================================================================

PRELUDE = '''"""Compiled checks for %(slot_id)s. GENERATED by solution/recompute.py. DO NOT HAND-EDIT.

Thirteen input channels are graded here: the twelve BigEarthNet-S2 reflectance bands and one
co-registered elevation raster on the same grid. Every check below runs against delivered bytes --
the submitted mask archive, the graded tile archives, and the run record the graded run wrote --
and references no unmeasured quantity, except %(outcome_id)s, which raises ConstantUnmeasured
while tests/constants.json carries nulls.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
SUBMISSION = %(path)r

# The corpus layout, from solution/grounding.yaml. The graded rasters are agent-visible because
# the agent has to predict on them; the graded masks are not, and red line 1 is what keeps the
# distinction.
GRADED_SPECTRAL = os.path.join(BUNDLE, %(graded_spectral)r)
GRADED_ELEVATION = os.path.join(BUNDLE, %(graded_elevation)r)
BAND_STATISTICS = os.path.join(BUNDLE, %(band_statistics)r)
CLASS_INDEX = os.path.join(BUNDLE, %(class_index)r)
GRADED_MASKS = os.path.join(BUNDLE, %(graded_masks)r)
RUN_RECORD = os.path.join(BUNDLE, %(run_record)r)

BANDS = %(bands)r
VISIBLE_BANDS = %(visible_bands)r
SWIR_BANDS = %(swir_bands)r
ELEVATION_TOKENS = %(elevation_tokens)r
FUSION_STAGES = %(fusion_stages)r
GUARDED_WRITES = %(guarded_writes)r
REMOTE_ENCODER_TOKENS = %(remote_encoder_tokens)r

CHECKS = []


class ConstantUnmeasured(Exception):
    """Raised when a check needs a ramp constant that Phase 0 deliberately left null."""


def check(id, weight, knockout, kind):
    def deco(fn):
        CHECKS.append({"id": id, "weight": weight, "knockout": knockout, "kind": kind, "fn": fn})
        return fn
    return deco


def constants():
    with open(os.path.join(HERE, "constants.json")) as fh:
        return json.load(fh)


def require_measured(*names):
    c = constants()
    missing = [n for n in names if c.get(n) is None]
    if missing:
        raise ConstantUnmeasured(
            "%(slot_id)s: " + ", ".join(missing) + " are null. Phase 0 authors no measurement; "
            "the Phase 2 measurement wave writes these and this check becomes gradeable then.")
    return c


def evidence(**kw):
    return {"evaluation_target": kw.pop("target", "submitted_artifact"), "values": kw}
'''


TAIL = '''

# ------------------------------------------------------------------------------------------
# Reading the delivered bytes. Four archives and one record, each read the same way every
# check reads it: absent is reported, never guessed at.
# ------------------------------------------------------------------------------------------

def load_submission():
    """The keyed mask archive: one integer land-cover raster per graded tile id."""
    import numpy as np
    with np.load(SUBMISSION, allow_pickle=False) as archive:
        members = {name: archive[name] for name in archive.files}
    if not members:
        raise ValueError("the mask archive carries no members")
    return members


def archive_member_order():
    """Member names in the order the archive stores them. npz bytes depend on this order."""
    import numpy as np
    with np.load(SUBMISSION, allow_pickle=False) as archive:
        return list(archive.files)


def describe(obj):
    return ",".join("%s:%s" % (k, tuple(v.shape)) for k, v in sorted(obj.items())[:4])


def archive_shapes(path):
    """member -> shape for one of the shipped tile archives; empty when it will not read.

    Empty covers two cases and the checks distinguish them by what else is available: the
    archive has not landed in this tree, or it landed and no longer parses. The second is red
    line 1 happening in front of the verifier, so it must produce a report rather than an
    unhandled traceback -- an archive that will not open is a finding, not a crash.
    """
    import numpy as np
    if not os.path.exists(path):
        return {}
    try:
        with np.load(path, allow_pickle=False) as archive:
            return {name: tuple(archive[name].shape) for name in archive.files}
    except Exception:
        return {}


def spectral_grids():
    """tile id -> (rows, cols), the twelve-band stack with its band axis dropped."""
    return dict((tile, shape[-2:]) for tile, shape in archive_shapes(GRADED_SPECTRAL).items())


def elevation_grids():
    """tile id -> (rows, cols) of the co-registered elevation raster."""
    return dict((tile, shape[-2:]) for tile, shape in archive_shapes(GRADED_ELEVATION).items())


def graded_tile_ids():
    """The graded tile set: the private mask archive names it, the spectral stack stands in.

    Verifier-side both are mounted and they agree. In a staged tree neither may have landed,
    and every check that needs the tile set says so rather than passing over an empty one.
    """
    for path in (GRADED_MASKS, GRADED_SPECTRAL, GRADED_ELEVATION):
        shapes = archive_shapes(path)
        if shapes:
            return sorted(shapes)
    return []


def class_index():
    """The land-cover class ids the per-class mean runs over."""
    if not os.path.exists(CLASS_INDEX):
        return []
    try:
        with open(CLASS_INDEX) as handle:
            doc = json.load(handle)
        ids = doc.get("class_ids", doc.get("classes")) if isinstance(doc, dict) else doc
        if isinstance(ids, dict):
            ids = list(ids.values())
        return sorted(int(c) for c in ids)
    except Exception:
        return []


def vendored_band_statistics():
    """The per-band location and scale the corpus vendors, upper-cased by band name."""
    if not os.path.exists(BAND_STATISTICS):
        return {}
    try:
        with open(BAND_STATISTICS) as handle:
            doc = json.load(handle)
        doc = doc.get("bands", doc) if isinstance(doc, dict) else {}
        return dict((str(k).strip().upper(), v) for k, v in doc.items())
    except Exception:
        return {}


def band_scale(entry):
    """The scale a band declaration carries, whichever key it names it by."""
    if isinstance(entry, dict):
        for key in ("scale", "std", "stddev", "sigma"):
            if key in entry:
                return float(entry[key])
        raise KeyError("no scale key in band declaration")
    if isinstance(entry, (list, tuple)) and len(entry) == 2:
        return float(entry[1])
    return float(entry)


def run_record():
    """What the graded run declared about itself.

    The agent writes this file, so it can be absent, truncated, or not JSON at all. Every one
    of those is an empty record here: an unparseable declaration declares nothing, and each
    check then reports its own missing-declaration reason instead of taking the verifier down
    with a decode error and returning no report about anything.
    """
    if not os.path.exists(RUN_RECORD):
        return {}
    try:
        with open(RUN_RECORD) as handle:
            doc = json.load(handle)
    except Exception:
        return {}
    return doc if isinstance(doc, dict) else {}


def in_guarded_tree(path):
    """True when a written path lands in the checker tree or on a graded tile archive."""
    flat = "/" + str(path).replace("\\\\", "/").lstrip("./").lstrip("/")
    return any(token in flat for token in GUARDED_WRITES)


def archive_content_digest():
    """sha256 over member names, dtypes, shapes and raw bytes, in the archive's stored order.

    NOT the file digest. An npz is a zip and its member headers carry whatever timestamp
    convention the writing library uses, so hashing the file measures numpy's release as much
    as it measures the run. Stored order is inside this digest on purpose: member order IS a
    property of the run, and a solve that iterates a dictionary to write its tiles produces the
    same masks in a different archive.
    """
    import hashlib
    import numpy as np
    if not os.path.exists(SUBMISSION):
        return None
    digest = hashlib.sha256()
    with np.load(SUBMISSION, allow_pickle=False) as archive:
        for name in archive.files:
            member = np.ascontiguousarray(archive[name])
            digest.update(name.encode("utf-8"))
            digest.update(("%s%s" % (member.dtype.str, member.shape)).encode("utf-8"))
            digest.update(member.tobytes())
    return digest.hexdigest()


def aligned_prediction(submitted, tile, truth):
    """The submitted mask for one graded tile, or None when it is missing or off the grid.

    Off-grid is deliberately NOT resampled. A mask on another grid is not a weaker answer to
    this tile's question, it is an answer to a different one, and it scores as an empty
    prediction: full union, no intersection.
    """
    member = submitted.get(tile)
    if member is None:
        return None
    if tuple(getattr(member, "shape", ())) != tuple(truth.shape):
        return None
    return member


def measure():
    """Mean per-class IoU: pooled per land-cover class, absent classes dropped, not credited.

    Pooling is per class across the whole graded tile set, so a class that occurs in one tile
    out of a thousand still carries one full term of the mean. A class whose pooled union is
    empty contributes NO term: an empty intersection over an empty union is undefined, and
    scoring it 1.0 would pay for every class nobody predicted and no tile contained.
    """
    import numpy as np
    if not os.path.exists(GRADED_MASKS):
        raise ConstantUnmeasured(
            "the private graded mask archive is not mounted; mean per-class IoU is not "
            "measurable from these bytes and reporting a number would be inventing one")
    try:
        submitted = load_submission()
    except Exception:
        submitted = {}
    intersection, union = {}, {}
    with np.load(GRADED_MASKS, allow_pickle=False) as truth_archive:
        for tile in sorted(truth_archive.files):
            truth = np.asarray(truth_archive[tile])
            predicted = aligned_prediction(submitted, tile, truth)
            labels = set(int(v) for v in np.unique(truth))
            if predicted is not None:
                labels |= set(int(v) for v in np.unique(np.asarray(predicted)))
            for label in sorted(labels):
                hit = truth == label
                guess = (np.asarray(predicted) == label if predicted is not None
                         else np.zeros(truth.shape, dtype=bool))
                intersection[label] = intersection.get(label, 0) + int((hit & guess).sum())
                union[label] = union.get(label, 0) + int((hit | guess).sum())
    graded_classes = class_index() or sorted(union)
    per_class = [intersection.get(c, 0) / union[c] for c in graded_classes if union.get(c, 0)]
    if not per_class:
        raise ConstantUnmeasured("no land-cover class has a non-empty union over the graded tiles")
    return float(sum(per_class) / len(per_class))
'''


BODIES = {

    "mask_archive_lands": '''
    if not os.path.exists(SUBMISSION):
        return False, evidence(reason="submission_missing", path=SUBMISSION)
    try:
        members = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    not_rasters = []
    for name in sorted(members):
        member = members[name]
        kind = getattr(getattr(member, "dtype", None), "kind", "")
        if getattr(member, "ndim", 0) != 2 or kind not in ("i", "u"):
            not_rasters.append("%s:%s%s" % (name, getattr(member, "dtype", "?"),
                                            getattr(member, "shape", "?")))
    return (not not_rasters), evidence(path=SUBMISSION, tiles=len(members),
                                       shape=describe(members),
                                       not_integer_rasters=not_rasters[:6],
                                       reason=None if not not_rasters
                                       else "member_is_not_a_two_dimensional_label_raster")''',

    "coregistered_grid_agreement": '''
    try:
        members = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    tiles = graded_tile_ids()
    if not tiles:
        return False, evidence(reason="graded_tile_index_unavailable",
                               spectral=GRADED_SPECTRAL)
    spectral, elevation = spectral_grids(), elevation_grids()
    missing, off_spectral, off_elevation = [], [], []
    for tile in tiles:
        member = members.get(tile)
        if member is None:
            missing.append(tile)
            continue
        grid = tuple(getattr(member, "shape", ()))
        want_spectral, want_elevation = spectral.get(tile), elevation.get(tile)
        if want_spectral is not None and grid != tuple(want_spectral):
            off_spectral.append("%s:%s!=%s" % (tile, grid, tuple(want_spectral)))
        elif want_elevation is not None and grid != tuple(want_elevation):
            off_elevation.append("%s:%s!=%s" % (tile, grid, tuple(want_elevation)))
    reason = ("tile_absent_from_mask_archive" if missing else
              "mask_not_on_spectral_grid" if off_spectral else
              "mask_not_on_coregistered_elevation_grid" if off_elevation else None)
    return (reason is None), evidence(graded_tiles=len(tiles), missing_tiles=missing[:6],
                                      off_spectral_grid=off_spectral[:6],
                                      off_elevation_grid=off_elevation[:6], reason=reason)''',

    "land_cover_labels_within_class_index": '''
    try:
        members = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    index = class_index()
    if not index:
        return False, evidence(reason="class_index_unavailable", path=CLASS_INDEX)
    import numpy as np
    seen = set()
    for name in sorted(members):
        try:
            seen.update(int(v) for v in np.unique(np.asarray(members[name])))
        except Exception as exc:
            return False, evidence(reason="member_is_not_label_valued", member=name,
                                   error=str(exc))
    stray = sorted(seen - set(index))
    return (not stray), evidence(distinct_labels=len(seen), class_index_size=len(index),
                                 outside_class_index=stray[:8],
                                 reason=None if not stray else "label_outside_class_index")''',

    "thirteen_channel_fusion_order_declared": '''
    record = run_record()
    order = record.get("channel_fusion_order")
    if not order:
        return False, evidence(target="run_record", reason="no_channel_order_declared")
    names = [str(channel).strip().upper() for channel in order]
    if len(names) != len(set(names)):
        return False, evidence(target="run_record", declared=names[:16],
                               reason="channel_declared_more_than_once")
    bands = [n for n in names if n in BANDS]
    others = [n for n in names if n not in BANDS]
    absent = sorted(set(BANDS) - set(bands))
    if absent:
        return False, evidence(target="run_record", missing_bands=absent, declared_bands=bands,
                               reason="rgb_only_roster" if set(bands) <= set(VISIBLE_BANDS)
                               else "spectral_band_missing_from_roster")
    if len(others) != 1 or not any(t in others[0] for t in ELEVATION_TOKENS):
        return False, evidence(target="run_record", non_band_channels=others,
                               reason="elevation_channel_not_identified")
    stage = str(record.get("elevation_fusion_stage", "")).strip().lower()
    if stage not in FUSION_STAGES:
        return False, evidence(target="run_record", declared_stage=stage,
                               admitted=list(FUSION_STAGES), reason="fusion_stage_undeclared")
    return True, evidence(target="run_record", channels=len(names), spectral_bands=len(bands),
                          elevation_channel=others[0], fusion_stage=stage)''',

    "per_band_scaling_not_global": '''
    declaration = run_record().get("band_normalisation")
    if declaration is None:
        return False, evidence(target="run_record", reason="no_band_normalisation_declared")
    try:
        named = dict((str(k).strip().upper(), v) for k, v in dict(declaration).items())
    except Exception as exc:
        return False, evidence(target="run_record", reason="normalisation_unparseable",
                               error=str(exc))
    absent = sorted(b for b in BANDS if b not in named)
    if absent:
        return False, evidence(target="run_record", missing_bands=absent,
                               reason="normalisation_not_declared_per_band")
    try:
        scales = dict((b, band_scale(named[b])) for b in BANDS)
    except Exception as exc:
        return False, evidence(target="run_record", reason="band_scale_unreadable",
                               error=str(exc))
    if len(set(round(s, 9) for s in scales.values())) == 1:
        return False, evidence(target="run_record", scale=scales[BANDS[0]],
                               reason="one_global_statistic_for_twelve_bands")
    visible = set(round(scales[b], 9) for b in VISIBLE_BANDS)
    shared = [b for b in SWIR_BANDS if round(scales[b], 9) in visible]
    if shared:
        return False, evidence(target="run_record", swir_sharing_visible_scale=shared,
                               reason="swir_band_scaled_like_a_visible_band")
    vendored = vendored_band_statistics()
    unknown = sorted(b for b in BANDS if vendored and b not in vendored)
    return (not unknown), evidence(target="run_record", bands_scaled=len(scales),
                                   distinct_scales=len(set(round(s, 9)
                                                           for s in scales.values())),
                                   not_in_vendored_statistics=unknown,
                                   reason=None if not unknown
                                   else "band_absent_from_vendored_statistics")''',

    "elevation_heldout_tiles_untrained": '''
    record = run_record()
    spectral_train = record.get("training_tile_ids")
    elevation_train = record.get("elevation_read_tile_ids")
    if spectral_train is None or elevation_train is None:
        return False, evidence(target="run_record", declared=sorted(record),
                               reason="no_tile_provenance_declared")
    graded = set(graded_tile_ids())
    if not graded:
        return False, evidence(target="run_record", reason="graded_tile_index_unavailable")
    spectral_leak = sorted(graded & set(str(t) for t in spectral_train))
    elevation_leak = sorted(graded & set(str(t) for t in elevation_train))
    reason = ("graded_spectral_tile_used_as_training_signal" if spectral_leak else
              "graded_elevation_tile_used_as_training_signal" if elevation_leak else None)
    return (reason is None), evidence(target="run_record", graded_tiles=len(graded),
                                      training_tiles=len(spectral_train),
                                      elevation_tiles=len(elevation_train),
                                      spectral_leaks=spectral_leak[:6],
                                      elevation_leaks=elevation_leak[:6], reason=reason)''',

    "graded_tile_archives_untouched": '''
    record = run_record()
    manifest = record.get("paths_written")
    if manifest is None:
        return False, evidence(target="submitted_source", reason="no_write_manifest_declared")
    touched = set(str(p) for p in manifest if in_guarded_tree(p))
    touched |= set(str(p) for p in record.get("guarded_paths_touched", []))
    return (not touched), evidence(target="submitted_source", declared_writes=len(manifest),
                                   guarded=sorted(touched)[:6],
                                   reason=None if not touched
                                   else "wrote_into_checker_tree_or_graded_archive")''',

    "vendored_encoder_only": '''
    provenance = run_record().get("encoder_provenance")
    if provenance is None:
        return False, evidence(target="run_record", reason="no_encoder_provenance_declared")
    text = json.dumps(provenance) if isinstance(provenance, dict) else str(provenance)
    remote = [t for t in REMOTE_ENCODER_TOKENS if t in text.lower()]
    if remote:
        return False, evidence(target="run_record", declared=text[:200], remote_tokens=remote,
                               reason="encoder_declared_from_a_remote_host")
    path = provenance.get("path") if isinstance(provenance, dict) else str(provenance)
    if path is None or str(path).strip().lower() in ("from_scratch", "none", "null", ""):
        return True, evidence(target="run_record", encoder="trained_from_scratch")
    resolved = str(path) if os.path.isabs(str(path)) else os.path.join(BUNDLE, str(path))
    inside = os.path.abspath(resolved).startswith(os.path.abspath(BUNDLE) + os.sep)
    return inside, evidence(target="run_record", encoder_path=str(path)[:200], vendored=inside,
                            reason=None if inside else "encoder_not_vendored_in_the_bundle")''',

    "mask_member_order_deterministic": '''
    record = run_record()
    declared = record.get("mask_member_order")
    if not declared:
        return False, evidence(target="submitted_source", reason="no_member_order_declared")
    try:
        written = archive_member_order()
        first = archive_content_digest()
    except Exception as exc:
        return False, evidence(target="submitted_source", reason="submission_malformed",
                               error=str(exc))
    if [str(tile) for tile in declared] != written:
        return False, evidence(target="submitted_source", declared_members=len(declared),
                               written_members=len(written), first_written=written[:4],
                               reason="member_order_diverged_from_declaration")
    replay = record.get("replay_content_sha256")
    if replay is None:
        return False, evidence(target="submitted_source", reason="replay_digest_undeclared")
    return first == replay, evidence(target="submitted_source", members=len(written),
                                     submitted_content=first, replayed_content=replay,
                                     reason=None if first == replay else "replay_diverged")''',

    "tile_budget_declared": '''
    declaration = run_record().get("agent_budget_declaration")
    if declaration is None:
        return False, evidence(target="run_record", reason="no_agent_declaration")
    try:
        fields = json.loads(declaration) if isinstance(declaration, str) else dict(declaration)
    except Exception as exc:
        return False, evidence(target="run_record", reason="declaration_unparseable",
                               error=str(exc))
    absent = [k for k in ("train_tiles", "graded_run_seconds", "inference_stride")
              if k not in fields]
    if absent:
        return False, evidence(target="run_record", declared=sorted(fields), missing=absent,
                               reason="declaration_incomplete")
    try:
        stride = int(fields["inference_stride"])
    except Exception as exc:
        return False, evidence(target="run_record", reason="stride_is_not_an_integer",
                               error=str(exc))
    edges = [min(grid) for grid in spectral_grids().values()]
    edge = min(edges) if edges else stride
    ok = 0 < stride <= edge
    return ok, evidence(target="run_record", inference_stride=stride, tile_edge=edge,
                        train_tiles=fields["train_tiles"],
                        graded_run_seconds=fields["graded_run_seconds"],
                        reason=None if ok else "stride_outside_the_tile_edge")''',

    "mean_per_class_iou_ramp": '''
    c = require_measured("floor", "knee", "dichotomizing_threshold")
    # require_measured runs FIRST, before the submission is opened. A missing artifact read
    # ahead of it returns False, the unmeasured signal never fires, and the verifier then
    # reports gradeable=true with r_det=0.0 -- which asserts the agent scored zero when the
    # true claim is that the slot is not yet measurable.
    miou = measure()
    span = c["knee"] - c["floor"]
    s = 0.0 if span <= 0 else max(0.0, min(1.0, (miou - c["floor"]) / span))
    return miou >= c["dichotomizing_threshold"], evidence(mean_per_class_iou=miou, s_outcome=s)''',

}


def build_tests(g, prelude, bodies):
    """Assemble the compiled-check module. kind carries the item's own dimension."""
    chunks = [prelude]
    for raw in sorted(g["items"], key=lambda i: i["id"]):
        if raw["mode"] != "compiled":
            continue
        chunks.append('\n\n@check(id="%s", weight=%d, knockout=%s, kind="%s")\ndef test_%s():\n%s\n'
                      % (raw["id"], raw["weight"], raw["knockout"], raw["dimension"], raw["id"],
                         bodies[raw["id"]].strip("\n")))
    return "".join(chunks)


def build_truth(g, title):
    """Render solution/TRUTH.md from the frozen literals of solution/grounding.yaml."""
    n = g["truth_narrative"]
    lines = [title, "", "GENERATED SECTION. DO NOT HAND-EDIT.", "", n["opening"], "",
             "## The single most important insight", "", n["insight"], "",
             "## The ideal solve, step by step", ""]
    for i, step in enumerate(n["steps"], 1):
        lines += ["%d. **%s** %s" % (i, step["heading"], step["paragraph"]), ""]
    lines += ["## Traps that catch agents that are not thinking carefully", ""]
    lines += ["- " + t for t in n["traps"]]
    lines += ["", "---", "", "## Contract record (annex; not part of the narrative body)", "",
              "Retained under FORGE.md item 10e and Phase 2 item 7, which require this file to "
              "carry the ordered path through instruction.md with each satisfied checker "
              "identifier, and each rejected route bound to a measured known-wrong control. "
              "standards/truth-md-authoring-v1.md section 3 admits no fifth section, so this "
              "annex is a recorded deviation rather than an omission.", "", g["truth_annex"], ""]
    return "\n".join(lines) + "\n"


def build_rubrics(g, item_keys):
    """The 9g rubric carrier. The item schema is CLOSED at eight keys, so item 10f's outcome
    classification rides as a greppable prefix of the judgment rather than as a ninth key."""
    items = []
    for raw in g["items"]:
        item = {k: raw[k] for k in item_keys}
        item["judgment"] = "%s: %s" % (raw["outcome_class"], raw["judgment"])
        items.append(item)
    compiled = sum(i["weight"] for i in items if i["mode"] == "compiled")
    total = sum(i["weight"] for i in items)
    return {"$schema": "forge.rubric/v1",
            "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
            "generator": "solution/recompute.py",
            "compilation_floor": g["compilation_floor"],
            "compiled_weight_share": round(compiled / total, 6) if total else 0.0,
            "evaluation_target_vocabulary": sorted(g["evaluation_target_vocabulary"]),
            "items": sorted(items, key=lambda i: i["id"])}


def build_provenance(g, identity):
    p = g["provenance"]
    out = {
        "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
        "generator": "solution/recompute.py from solution/grounding.yaml",
        "schema_version": "1.0",
        "slot_id": g["slot_id"],
        "identity": identity,
        "corpus": p["corpus"],
        "anchors": p["anchors"],
        "shards": p["shards"],
        "narrative": p["narrative"],
        "supersedes": p["supersedes"],
        "upstream_provenance": p["upstream_record"],
        "reward_composition": p["reward_composition"],
        "screening_interval_days": p["screening_interval_days"],
        "screening_detector_version": p["screening_detector_version"],
        "derivation_instant": p["derivation_instant"],
        "screening_roots": p["screening_roots"],
        "empty_submission_result": p["empty_submission_result"],
        "resolved_closure": p["resolved_closure"],
        "applicability": p["applicability"],
        "measurement_tier": g["measurement_tier"],
        "gradeable": g["gradeable"],
        "knee_anchor_status": g["knee_anchor_status"],
        "dense_label_grading": True,
        "coregistered_channels": len(g["corpus_layout"]["bands"]) + 1,
    }
    out.update(read_screening(HERE))
    return out


def validate(grounding):
    """Refuse on a malformed derivation source rather than emitting from one.

    The family validator that stood here returned an empty list unconditionally, which is a
    check that consults nothing. These are the invariants the emitted checker actually depends
    on: without them a bad grounding produces a checker that imports and grades the wrong thing.
    """
    problems = []
    items = grounding.get("items") or []
    if not items:
        problems.append("no items to compile")
    seen = set()
    for item in items:
        iid = item.get("id", "<unnamed>")
        if iid in seen:
            problems.append("duplicate item id %r" % iid)
        seen.add(iid)
        if set(item) != ITEM_SCHEMA:
            problems.append("item %r does not carry the closed schema: %s"
                            % (iid, sorted(set(item) ^ ITEM_SCHEMA)))
            continue
        if item["outcome_class"] not in OUTCOME_CLASSES:
            problems.append("item %r has outcome_class %r" % (iid, item["outcome_class"]))
        if item["evaluation_target"] not in grounding["evaluation_target_vocabulary"]:
            problems.append("item %r evaluates %r, which the vocabulary does not admit"
                            % (iid, item["evaluation_target"]))
        if not isinstance(item["weight"], int) or item["weight"] <= 0:
            problems.append("item %r carries weight %r" % (iid, item["weight"]))
    outcome = [i["id"] for i in items if i.get("dimension") == "outcome"]
    if len(outcome) != 1:
        problems.append("expected exactly one outcome item, found %r" % outcome)
    for name in RAMP:
        if grounding["constants"].get(name) is not None:
            problems.append("constant %r is authored at Phase 0; it is measured, not authored"
                            % name)
    layout = grounding.get("corpus_layout") or {}
    bands = layout.get("bands") or []
    if len(bands) != 12 or len(set(bands)) != 12:
        problems.append("the spectral roster must name twelve distinct bands, found %d"
                        % len(bands))
    for key in ("visible_bands", "swir_bands"):
        stray = sorted(set(layout.get(key) or []) - set(bands))
        if stray:
            problems.append("%s names %s, which the band roster does not" % (key, stray))
    return problems


def main():
    g = load_grounding()
    # The validator runs FIRST and refuses rather than emitting: a generator that writes a
    # carrier it knows is malformed hands the drift check a moving target.
    problems = validate(g)
    if problems:
        raise SystemExit("AELLO-C8-S5 grounding is not well-formed: " + "; ".join(problems))

    layout = g["corpus_layout"]
    outcome_id = [i["id"] for i in g["items"] if i["dimension"] == "outcome"][0]
    subst = {"slot_id": SLOT_ID, "path": g["deliverable"]["path"], "outcome_id": outcome_id,
             "graded_spectral": layout["graded_spectral"],
             "graded_elevation": layout["graded_elevation"],
             "band_statistics": layout["band_statistics"], "class_index": layout["class_index"],
             "graded_masks": layout["graded_masks"], "run_record": layout["run_record"],
             "bands": tuple(layout["bands"]), "visible_bands": tuple(layout["visible_bands"]),
             "swir_bands": tuple(layout["swir_bands"]),
             "elevation_tokens": tuple(layout["elevation_channel_tokens"]),
             "fusion_stages": tuple(layout["fusion_stages"]),
             "guarded_writes": tuple(layout["guarded_writes"]),
             "remote_encoder_tokens": tuple(layout["remote_encoder_tokens"])}

    # EVERY compiled item carries a written body. The generic obligation lookup that used to
    # stand here is gone: it consulted a run-record key nothing writes, so an item that fell
    # through to it graded nothing at all and said so in no report.
    bodies = dict(BODIES)
    for it in g["items"]:
        if it["mode"] == "compiled" and it["id"] not in bodies:
            raise SystemExit("AELLO-C8-S5: no body written for compiled item %r; the generator "
                             "refuses rather than emitting a check that consults nothing"
                             % it["id"])
    # The outcome check must SAY the slot is unmeasurable before it reads anything. Reading the
    # artifact first lets a missing-file failure mask the unmeasured signal, and the verifier
    # then reports gradeable=true with r_det=0.0.
    statements = [ln.strip() for ln in bodies[outcome_id].splitlines()
                  if ln.strip() and not ln.strip().startswith("#")]
    if not statements or statements[0] != REQUIRE_FIRST:
        raise SystemExit("AELLO-C8-S5: %r must call require_measured as its first statement, "
                         "before it reads the submission" % outcome_id)

    tests_dir = os.path.join(BUNDLE, "tests")
    os.makedirs(tests_dir, exist_ok=True)

    # solution/TRUTH.md and solution/rubrics.json are PRIVATE_CARRIERS: seed/identity.py plants a
    # canary block into them at freeze, and canary normalisation is what keeps planting from
    # moving identity. A generator that rewrote them plainly would DROP the planted tripwire, and
    # the next content_hash would differ from the frozen one. So the planted block is carried
    # across the regeneration rather than recreated.
    truth_path = os.path.join(HERE, "TRUTH.md")
    truth = build_truth(g, TITLE).rstrip("\n") + "\n"
    keep = None
    if os.path.exists(truth_path):
        import re as _re
        m = _re.search(r"<!-- AELLO-CANARY-BLOCK.*?-->\n?", open(truth_path).read(), _re.S)
        keep = m.group(0) if m else None
    with open(truth_path, "w") as fh:
        fh.write(truth + ("\n" + keep if keep else ""))

    rub_path = os.path.join(HERE, "rubrics.json")
    rub = build_rubrics(g, ITEM_KEYS)
    if os.path.exists(rub_path):
        try:
            prev = json.load(open(rub_path))
            if "canary" in prev:
                rub["canary"] = prev["canary"]
        except Exception:
            pass
    with open(rub_path, "w") as fh:
        json.dump(rub, fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "rubrics.json"), "w") as fh:
        json.dump(build_rubrics(g, ITEM_KEYS), fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "test_output.py"), "w") as fh:
        # The tail arrives FINAL and is NOT substituted: it is family-shaped, it has already
        # resolved every placeholder it owns, and it legitimately contains percent signs of its
        # own, so formatting it a second time raises TypeError. Only the prelude is substituted.
        fh.write(build_tests(g, PRELUDE % subst, bodies) + TAIL)
    with open(os.path.join(tests_dir, "constants.json"), "w") as fh:
        json.dump(g["constants"], fh, indent=1, sort_keys=True)
        fh.write("\n")
    # ORDER MATTERS. `with open(path, "w")` truncates BEFORE its body's arguments are evaluated,
    # so calling read_identity() inside the with-statement reads the file this line just emptied
    # and writes nulls over the frozen identity. Read first, then open.
    prov = build_provenance(g, read_identity(HERE))
    with open(os.path.join(HERE, "provenance.yaml"), "w") as fh:
        # MATCH seed/build/screen_bind.py and the frozen generators exactly: sort_keys=True,
        # default_flow_style=False, width=100. The screen writes this carrier after the freeze,
        # so a generator using a different dump convention reorders the keys on the next
        # regeneration and reports as drift even though no value changed.
        yaml.safe_dump(prov, fh, sort_keys=True, default_flow_style=False, width=100,
                       allow_unicode=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
