"""Derivation for C4-S3: every canonical artifact descends from solution/grounding.yaml.

WHAT THIS GENERATOR EMITS AND WHY IT LOOKS LIKE THIS. The checks below are written about a
QUANTIZATION RECIPE and the export it produces: an average bits-per-weight recomputed from the
size of the shard files on disk rather than from the manifest that describes them, a format cost
table priced at payload_bits + (scale_bits + zero_point_bits) / group_size, a per-layer dequant
invocation counter that says whether the packed buffer was ever served, a traced stage-entry
order compared against a declared one, and a decode throughput that is the geometric mean of two
batch sizes rather than a rate at one of them. Not one of them would mean anything on a
classifier, a detector, a forecaster or a calibration slot. The bit budget, the format contract,
the decode protocol and the guarded paths all live in solution/grounding.yaml and are substituted
into the emitted prelude, so the derivation source really is the source and this file holds no
task fact of its own.

Every compiled item carries a hand-written body. There is no generic fallback: an item without a
body is a refusal here, because the fallback that used to stand in this position looked up an
obligation record that nothing in the bundle ever writes, so an item that fell through to it
graded nothing at all and reported that it had passed.
"""
import hashlib
import json
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
# Nothing outside the bundle is imported. A staged tree could resolve seed/stage/<slug>/../../build
# and a DELIVERED tree at dataset/<uuid>/ cannot, so reaching outside would make the bundle
# non-self-contained: it would regenerate in the stage and fail everywhere it actually ships.

SLOT_ID = "C4-S3"
TITLE = "# C4-S3 -- what this task actually tests"
ITEM_KEYS = ("id", "dimension", "weight", "evaluation_target", "criterion", "judgment",
             "knockout", "mode")
ITEM_SCHEMA = frozenset(ITEM_KEYS + ("outcome_class",))
OUTCOME_CLASSES = frozenset(("EFFECT", "INVARIANT", "ABSENCE", "VALUE", "DIVERGENCE", "ORDERING"))
RAMP_CONSTANTS = ("floor", "knee", "dichotomizing_threshold", "reward_gate_pass_threshold")
OUTCOME_ITEM = "speedup_over_bf16_baseline_through_the_ramp"
OUTCOME_DIMENSION = "throughput_outcome"
REQUIRE_FIRST = 'c = require_measured("floor", "knee", "dichotomizing_threshold")'
PASSTHROUGH_FORMAT = "bf16_passthrough"


def load_grounding():
    with open(os.path.join(HERE, "grounding.yaml")) as handle:
        return yaml.safe_load(handle)


def read_identity(here):
    """Identity is an INPUT: the freeze computes it over the hashed tree and binds it into the
    carrier, which is hash-excluded, so reading it back keeps generation acyclic."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        if isinstance(doc.get("identity"), dict):
            return doc["identity"]
    return {"canonical_content_hash": None, "uuid": None,
            "normalization_domain": "aello.canary.norm/v1",
            "derivation": "uuid5(FORGE_TASK_NAMESPACE, canonical_content_hash)"}


def read_screening(here):
    """The screening instant and result are MEASURED OVER the frozen tree, so they are read back
    the way identity is; the carrier is hash-excluded, so binding them moves nothing."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        got = {k: doc[k] for k in ("screening_measured_at", "screening_expires_at",
                                   "screening_result") if k in doc}
        if got:
            return got
    return {"screening_measured_at": None, "screening_expires_at": None,
            "screening_result": None}


def render(template, bindings):
    """Substitute {{NAME}} placeholders. Deliberately not printf formatting: the emitted module
    is full of percent signs of its own and a second format pass over it raised TypeError on the
    first slot that carried one."""
    out = template
    for name, value in bindings.items():
        out = out.replace("{{%s}}" % name, value)
    left = [line for line in out.split("\n") if "{{" in line]
    if left:
        raise SystemExit("%s: unresolved placeholder in the emitted prelude: %r"
                         % (SLOT_ID, left[0].strip()[:70]))
    return out


PRELUDE = '''"""Compiled checks for {{SLOT}}. GENERATED by solution/recompute.py. DO NOT HAND-EDIT.

The graded artifact is a QUANTIZED MODEL EXPORT and the recipe that produced it, not a set of
predictions. Every check below runs against three things the graded run leaves behind: the export
manifest at the declared path, the packed shard bytes as the filesystem reports them, and the
harness run record. None of them reads an unmeasured quantity except {{OUTCOME}}, which calls
require_measured before it opens anything at all.
"""
import hashlib
import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
MANIFEST = {{MANIFEST}}
EXPORT_ROOT = {{EXPORT_ROOT}}
RECIPE = {{RECIPE}}
SHARD_DIR = {{SHARD_DIR}}
RUN_RECORD = {{RUN_RECORD}}
CHECKS = []

# THE PINNED CHECKPOINT. Qwen2.5-1.5B-Instruct carries {{BLOCKS}} transformer blocks and seven
# linear projections in each of them, so the roster the export must cover is exactly
# {{LAYERS}} names. The recipe converts this checkpoint; it never replaces it.
PINNED_CHECKPOINT = {{PINNED_CHECKPOINT}}
TRANSFORMER_BLOCKS = {{BLOCKS}}
PROJECTIONS = {{PROJECTIONS}}
LINEAR_LAYERS = {{LAYERS}}
# The shapes of the pinned checkpoint, so the DENOMINATOR of the average bits per weight is a fact
# about the model rather than a number the manifest supplies about itself. hidden 1536,
# intermediate 8960, 12 attention heads and 2 key-value heads at head_dim 128.
WEIGHT_COUNTS = {{WEIGHT_COUNTS}}
LINEAR_WEIGHT_TOTAL = {{WEIGHT_TOTAL}}

# PUBLISHED BOUNDS. Every one is disclosed to the agent in instruction.md and not one is a
# measurement: the four measured constants live in constants.json and stay null until the Phase 2
# wave writes them on the grading host.
BIT_BUDGET = {{BIT_BUDGET}}                 # average bits per weight, recomputed from packed bytes
CALIBRATION_BUDGET_S = {{CALIB_S}}          # the recipe's own wall clock, harness-measured
PPL_GATE = {{PPL_GATE}}                     # p = ppl_export / ppl_bf16 on the private PG-19 slice
PPL_STARTER = {{PPL_STARTER}}               # at or above this there is no gain over the starter
SUB_GATE_CEILING = {{SUB_GATE}}             # the consolation band never competes with throughput
RETENTION_GAP_BOUND = {{GAP_BOUND}}         # |retention(PG-19) - retention(C4 sibling)|
REEXEC_PPL_TOL = {{REEXEC_TOL}}             # regeneration compares perplexity, never packed bytes
IQR_BAND = {{IQR_BAND}}                     # trial spread as a fraction of the trial median
MAX_REMEASURES = {{MAX_REMEASURES}}
WARMUP_STEPS = {{WARMUP}}
DECODE_STEPS = {{DECODE_STEPS}}
TRIALS = {{TRIALS}}
BATCH_SIZES = {{BATCH_SIZES}}
STAGE_VOCABULARY = {{STAGES}}

# THE RUNTIME FORMAT CONTRACT. One row per format the provided mixed-precision decode runtime has
# a kernel for. Each row prices at payload_bits + (scale_bits + zero_point_bits) / group_size,
# which is exact integer arithmetic and carries no noise: int4_group128_sym comes to 4.125 bits,
# above the budget, and int4_group256_sym to 4.0625, under it.
FORMAT_CONTRACT = {{FORMAT_CONTRACT}}
PASSTHROUGH_FORMAT = {{PASSTHROUGH}}
DECOY_FORMAT = {{DECOY}}
CHEAPEST_UNIFORM_THAT_FITS = {{CHEAPEST}}

# WHAT THE GRADED RUN MAY NOT TOUCH.
GUARDED_PREFIXES = {{GUARDED}}
HELDOUT_PREFIX = {{HELDOUT}}
EGRESS_ALLOWLIST = {{ALLOWLIST}}
MODEL_HUB_HOSTS = {{HUBS}}


class ConstantUnmeasured(Exception):
    """Raised when a check needs a ramp constant that Phase 0 deliberately left null."""


def check(id, weight, knockout, kind):
    def deco(fn):
        CHECKS.append({"id": id, "weight": weight, "knockout": knockout, "kind": kind, "fn": fn})
        return fn
    return deco


def constants():
    with open(os.path.join(HERE, "constants.json")) as handle:
        return json.load(handle)


def require_measured(*names):
    c = constants()
    missing = [n for n in names if c.get(n) is None]
    if missing:
        raise ConstantUnmeasured(
            "{{SLOT}}: " + ", ".join(missing) + " are null. Phase 0 authors no measurement; the "
            "Phase 2 wave measures the speedup distribution on the grading host, writes these, "
            "and this check becomes gradeable then.")
    return c


def evidence(**kw):
    return {"evaluation_target": kw.pop("target", "export_manifest"), "values": kw}
'''


TAIL = '''

# ----------------------------------------------------------------------------------------------
# Reading the export. The manifest is read as a claim and the shard bytes as the fact; the two
# are compared, and where they disagree the bytes win.
# ----------------------------------------------------------------------------------------------


def manifest():
    with open(MANIFEST) as handle:
        doc = json.load(handle)
    if not isinstance(doc, dict):
        raise ValueError("the export manifest must be an object")
    return doc


def layer_rows():
    rows = manifest().get("layers")
    if not isinstance(rows, list):
        raise ValueError("the manifest carries no per-layer format map")
    return [row for row in rows if isinstance(row, dict)]


def pinned_roster():
    """The linear projections of the pinned checkpoint, in block-then-projection order."""
    return ["model.layers.%d.%s" % (block, projection)
            for block in range(TRANSFORMER_BLOCKS) for projection in PROJECTIONS]


def price_of(fmt):
    """Bits per weight for one published format, priced from that format's own fields.

    Payload, plus the group's amortised scale and zero point. Nothing here is a measurement: the
    table is exact arithmetic over integers the runtime contract publishes, which is why the
    vendor notes' uniform INT4 group-128 recommendation can be refused without running anything.
    """
    spec = FORMAT_CONTRACT.get(fmt)
    if spec is None:
        return None
    group = int(spec["group_size"])
    if group <= 0:
        raise ValueError("format %r declares a non-positive group size" % fmt)
    amortised = float(spec["scale_bits"]) + float(spec["zero_point_bits"])
    return float(spec["payload_bits"]) + amortised / group


def shard_files():
    names = []
    for shard in manifest().get("shards") or []:
        name = shard.get("file") if isinstance(shard, dict) else shard
        names.append(os.path.join(SHARD_DIR, os.path.basename(str(name))))
    return names


def on_disk_packed_bytes():
    """The size of the export as the filesystem reports it.

    The manifest's own per-layer byte counts are read separately and compared against this. They
    are never substituted for it, because the padding-inflated packing route works precisely by
    declaring a byte count the packer did not write.
    """
    total = 0
    for path in shard_files():
        if not os.path.exists(path):
            raise ValueError("the manifest names a shard that is not on disk: %s" % path)
        total += os.path.getsize(path)
    if not total:
        raise ValueError("the export packs no bytes at all")
    return total


def total_weight_count(rows):
    total = 0
    for row in rows:
        try:
            total += int(row.get("weight_count", 0))
        except (TypeError, ValueError):
            continue
    return total


def format_map_digest():
    """SHA-256 over the per-layer format map in ROSTER order, not in listing order.

    The map is an ordered assignment of a format to each projection of the pinned checkpoint, so
    a manifest that shuffles its own rows is the same map and must digest the same. Re-execution
    is compared against this digest and never against the packed bytes.
    """
    rows = {str(row.get("name")): row for row in layer_rows()}
    lines = []
    for name in pinned_roster():
        row = rows.get(name) or {}
        lines.append("%s\\t%s\\t%s" % (name, row.get("format"), row.get("group_size")))
    return hashlib.sha256("\\n".join(lines).encode("utf-8")).hexdigest()


# ----------------------------------------------------------------------------------------------
# Reading the harness run record. Every quantity a red line turns on is measured by the harness,
# so it is read from here rather than from anything the recipe reported about itself.
# ----------------------------------------------------------------------------------------------


def run_record():
    path = os.path.join(HERE, "..", RUN_RECORD)
    if not os.path.exists(path):
        return {}
    with open(path) as handle:
        return json.load(handle)


def as_float(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def ratio_of(numerator, denominator):
    top, bottom = as_float(numerator), as_float(denominator)
    if top is None or bottom is None or bottom <= 0:
        return None
    return top / bottom


def throughput_trials(kind):
    table = run_record().get("throughput_trials")
    if not isinstance(table, dict):
        raise ValueError("the run record carries no decode trial table")
    side = table.get(kind)
    if not isinstance(side, dict):
        raise ValueError("the trial table has no %r side" % kind)
    return side


def trial_rates(kind, batch):
    try:
        rows = throughput_trials(kind).get(str(batch)) or []
    except ValueError:
        return []
    rates = []
    for row in rows:
        value = as_float(row.get("tokens_per_second")) if isinstance(row, dict) else None
        if value is not None:
            rates.append(value)
    return rates


def all_trials():
    """Every timed trial, with the side and batch size it belongs to attached."""
    rows = []
    for kind in ("export", "bf16_baseline"):
        try:
            side = throughput_trials(kind)
        except ValueError:
            continue
        for batch in BATCH_SIZES:
            for row in side.get(str(batch)) or []:
                if isinstance(row, dict):
                    entry = dict(row)
                    entry.setdefault("batch_size", batch)
                    entry["kind"] = kind
                    rows.append(entry)
    return rows


def median(values):
    ordered = sorted(values)
    count = len(ordered)
    if not count:
        raise ValueError("a median needs at least one trial")
    middle = count // 2
    return ordered[middle] if count % 2 else 0.5 * (ordered[middle - 1] + ordered[middle])


def interquartile_range(values):
    """Nearest-rank quartiles, so five trials give a q1 and a q3 that a trial actually produced
    rather than an interpolation between two of them."""
    ordered = sorted(values)
    count = len(ordered)
    if not count:
        raise ValueError("an interquartile range needs at least one trial")
    low = ordered[max(0, int(math.ceil(0.25 * count)) - 1)]
    high = ordered[max(0, int(math.ceil(0.75 * count)) - 1)]
    return high - low


def batch_medians(kind):
    """The median rate at each published batch size, or a refusal if a batch is short of trials."""
    out = {}
    for batch in BATCH_SIZES:
        rates = trial_rates(kind, batch)
        if len(rates) != TRIALS:
            raise ValueError("%s at batch %d carries %d trials, not %d"
                             % (kind, batch, len(rates), TRIALS))
        out[batch] = median(rates)
    return out


def geometric_mean(per_batch):
    """The geometric mean across batch sizes.

    This is the shape of the metric and not a stylistic choice about averaging. Doubling the rate
    at one batch size while halving it at the other leaves the geometric mean where it started,
    so a recipe that wins the launch-bound regime by giving up the memory-bound one gains nothing.
    """
    product = 1.0
    for batch in sorted(per_batch):
        rate = per_batch[batch]
        if rate <= 0:
            raise ValueError("the decode rate at batch %s is not positive" % batch)
        product *= rate
    return product ** (1.0 / len(per_batch)) if per_batch else 0.0


def normalized_speedup():
    """s = T / T0, both sides the same statistic under the same protocol in the same run."""
    export = geometric_mean(batch_medians("export"))
    baseline = geometric_mean(batch_medians("bf16_baseline"))
    if baseline <= 0:
        raise ValueError("the bf16 baseline throughput was not measured in this run")
    return export / baseline
'''


BODIES = {

"export_manifest_and_packed_shards_present": '''\
    if not os.path.exists(MANIFEST):
        return False, evidence(target="export_manifest", reason="deliverable_absent",
                               declared_path=MANIFEST)
    try:
        doc = manifest()
    except Exception as exc:
        return False, evidence(target="export_manifest", reason="manifest_unparseable",
                               error=str(exc))
    missing = [] if os.path.exists(RECIPE) else [RECIPE]
    declared = doc.get("shards") or []
    if not declared:
        missing.append("<the manifest declares no packed shard at all>")
    for shard in declared:
        name = shard.get("file") if isinstance(shard, dict) else shard
        where = os.path.join(SHARD_DIR, os.path.basename(str(name)))
        if not os.path.exists(where):
            missing.append(where)
    ok = not missing
    return ok, evidence(target="export_manifest", export_root=EXPORT_ROOT,
                        declared_shards=len(declared), missing=missing[:8],
                        reason=None if ok else "deliverable_absent")''',

"layer_roster_covers_all_196_linear_projections": '''\
    try:
        rows = layer_rows()
    except Exception as exc:
        return False, evidence(target="export_manifest", reason="manifest_unreadable",
                               error=str(exc))
    named = [str(row.get("name")) for row in rows]
    roster = pinned_roster()
    duplicated = sorted({name for name in named if named.count(name) > 1})
    outside = sorted(set(named) - set(roster))
    never = sorted(set(roster) - set(named))
    # The weight count is the DENOMINATOR of the bit budget, so it is checked against the pinned
    # checkpoint's own shapes rather than believed. A manifest that inflates its denominator
    # divides the same packed bits by more weights and reports a compliant average.
    miscounted = []
    for row in rows:
        name = str(row.get("name"))
        want = WEIGHT_COUNTS.get(name.split(".", 3)[-1] if name.count(".") > 2 else "")
        if want is None:
            continue
        try:
            got = int(row.get("weight_count"))
        except (TypeError, ValueError):
            got = None
        if got != want:
            miscounted.append({"layer": name, "declared": got, "checkpoint": want})
    total = total_weight_count(rows)
    adds_up = total == LINEAR_WEIGHT_TOTAL
    ok = (len(named) == LINEAR_LAYERS and not duplicated and not outside and not never
          and not miscounted and adds_up)
    reason = None
    if len(named) != LINEAR_LAYERS or duplicated or outside or never:
        reason = "layer_roster_mismatch"
    elif miscounted or not adds_up:
        reason = "weight_count_disagrees_with_the_pinned_checkpoint"
    return ok, evidence(target="export_manifest", declared=len(named), roster=LINEAR_LAYERS,
                        blocks=TRANSFORMER_BLOCKS, projections_per_block=len(PROJECTIONS),
                        duplicated=duplicated[:6], not_in_roster=outside[:6],
                        never_declared=never[:6], miscounted=miscounted[:5],
                        declared_weights=total, checkpoint_weights=LINEAR_WEIGHT_TOTAL,
                        reason=reason)''',

"bits_per_weight_recomputed_from_packed_bytes": '''\
    try:
        rows = layer_rows()
        on_disk = on_disk_packed_bytes()
    except Exception as exc:
        return False, evidence(target="packed_export", reason="packed_export_unreadable",
                               error=str(exc))
    weights = total_weight_count(rows)
    if weights <= 0:
        return False, evidence(target="packed_export", reason="no_weight_count_declared")
    recomputed = on_disk * 8.0 / weights
    declared_bytes = sum(int(row.get("packed_bytes") or 0) for row in rows)
    undeclared = on_disk - declared_bytes
    claimed = as_float(manifest().get("declared_bits_per_weight"))
    agrees = claimed is not None and abs(claimed - recomputed) <= 1e-9
    within = recomputed <= BIT_BUDGET
    reason = None
    if not within:
        reason = "bit_budget_exceeded"
    elif undeclared or not agrees:
        reason = "padpack_inflated_manifest"
    return (within and not undeclared and agrees), evidence(
        target="packed_export", bits_per_weight=recomputed, budget=BIT_BUDGET,
        on_disk_bytes=on_disk, manifest_declared_bytes=declared_bytes,
        undeclared_bytes=undeclared, weights=weights, manifest_claim=claimed, reason=reason)''',

"uniform_int4_group128_prices_above_the_budget": '''\
    decoy = price_of(DECOY_FORMAT)
    cheapest = price_of(CHEAPEST_UNIFORM_THAT_FITS)
    if decoy is None or cheapest is None:
        return False, evidence(target="export_manifest", reason="format_table_incomplete",
                               decoy=DECOY_FORMAT, cheapest=CHEAPEST_UNIFORM_THAT_FITS)
    table_holds = decoy > BIT_BUDGET and cheapest <= BIT_BUDGET
    try:
        rows = layer_rows()
    except Exception as exc:
        return False, evidence(target="export_manifest", reason="manifest_unreadable",
                               error=str(exc))
    mispriced = []
    for row in rows:
        table = price_of(str(row.get("format")))
        stated = as_float(row.get("bits_per_weight"))
        if table is None or stated is None:
            continue
        if abs(stated - table) > 1e-9:
            mispriced.append({"layer": row.get("name"), "stated": stated, "table": table})
    ok = table_holds and not mispriced
    reason = None
    if not table_holds:
        reason = "format_table_arithmetic_wrong"
    elif mispriced:
        reason = "layer_price_disagrees_with_the_table"
    return ok, evidence(target="export_manifest", int4_group128_sym=decoy,
                        cheapest_uniform_that_fits=cheapest, budget=BIT_BUDGET,
                        mispriced=mispriced[:5], reason=reason)''',

"every_layer_format_is_inside_the_runtime_envelope": '''\
    try:
        rows = layer_rows()
    except Exception as exc:
        return False, evidence(target="export_manifest", reason="manifest_unreadable",
                               error=str(exc))
    outside = []
    for row in rows:
        fmt = str(row.get("format"))
        spec = FORMAT_CONTRACT.get(fmt)
        if spec is None:
            outside.append({"layer": row.get("name"), "format": fmt,
                            "why": "no_kernel_for_this_format"})
            continue
        try:
            group = int(row.get("group_size"))
        except (TypeError, ValueError):
            group = None
        if group != int(spec["group_size"]):
            outside.append({"layer": row.get("name"), "format": fmt, "group_size": group,
                            "kernel_serves": spec["group_size"],
                            "why": "group_size_the_kernel_does_not_serve"})
    ok = bool(rows) and not outside
    return ok, evidence(target="export_manifest", offending=len(outside), first=outside[:5],
                        admitted_formats=sorted(FORMAT_CONTRACT),
                        reason=None if ok else "format_envelope_violation")''',

"pg19_perplexity_ratio_within_the_gate": '''\
    measured = run_record().get("perplexity")
    if not isinstance(measured, dict):
        return False, evidence(target="run_record", reason="perplexity_unrecorded")
    if measured.get("bf16_reference_measured_in_run") is not True:
        return False, evidence(target="run_record", reason="bf16_reference_not_from_this_run",
                               declared=measured.get("bf16_reference_measured_in_run"))
    p = ratio_of(measured.get("pg19_export"), measured.get("pg19_bf16"))
    if p is None:
        return False, evidence(target="run_record", reason="perplexity_unrecorded",
                               export=measured.get("pg19_export"),
                               bf16=measured.get("pg19_bf16"))
    ok = p <= PPL_GATE
    return ok, evidence(target="run_record", p=p, gate=PPL_GATE,
                        export_ppl=measured.get("pg19_export"),
                        bf16_ppl=measured.get("pg19_bf16"),
                        reason=None if ok else "perplexity_gate_failed")''',

"sub_gate_band_credit_stays_below_the_graded_axis": '''\
    measured = run_record().get("perplexity")
    if not isinstance(measured, dict):
        return False, evidence(target="run_record", reason="perplexity_unrecorded")
    p = ratio_of(measured.get("pg19_export"), measured.get("pg19_bf16"))
    if p is None:
        return False, evidence(target="run_record", reason="perplexity_unrecorded")
    if p >= PPL_STARTER:
        band, credit = "no_gain_over_starter", 0.0
    elif p > PPL_GATE:
        band = "sub_gate"
        credit = SUB_GATE_CEILING * (PPL_STARTER - p) / (PPL_STARTER - PPL_GATE)
    else:
        band, credit = "graded_axis", SUB_GATE_CEILING
    claimed = run_record().get("reward_band")
    consistent = claimed is None or str(claimed) == band
    bounded = credit <= SUB_GATE_CEILING + 1e-12
    ok = consistent and bounded
    reason = None
    if not consistent:
        reason = "reward_band_disagrees_with_the_measured_perplexity"
    elif not bounded:
        reason = "sub_gate_credit_above_its_ceiling"
    return ok, evidence(target="run_record", p=p, band=band, credit=credit,
                        ceiling=SUB_GATE_CEILING, gate=PPL_GATE, starter=PPL_STARTER,
                        claimed_band=claimed, reason=reason)''',

"cross_corpus_retention_gap_within_two_hundredths": '''\
    measured = run_record().get("perplexity")
    if not isinstance(measured, dict):
        return False, evidence(target="run_record", reason="perplexity_unrecorded")
    graded = ratio_of(measured.get("pg19_bf16"), measured.get("pg19_export"))
    sibling = ratio_of(measured.get("c4_sibling_bf16"), measured.get("c4_sibling_export"))
    if graded is None or sibling is None:
        return False, evidence(target="run_record", reason="sibling_slice_unmeasured",
                               pg19_retention=graded, c4_sibling_retention=sibling)
    gap = abs(graded - sibling)
    ok = gap <= RETENTION_GAP_BOUND
    return ok, evidence(target="run_record", pg19_retention=graded,
                        c4_sibling_retention=sibling, gap=gap, bound=RETENTION_GAP_BOUND,
                        reason=None if ok else "calibration_overfit")''',

"traced_stage_order_equals_the_declared_recipe_order": '''\
    try:
        declared = [str(stage) for stage in manifest().get("recipe_stages") or []]
    except Exception as exc:
        return False, evidence(target="run_record", reason="manifest_unreadable",
                               error=str(exc))
    if not declared:
        return False, evidence(target="run_record", reason="no_stage_order_declared")
    traced = [str(stage) for stage in run_record().get("traced_stage_order") or []]
    unknown = sorted(set(declared) - set(STAGE_VOCABULARY))
    never_entered = [stage for stage in declared if stage not in traced]
    ok = not unknown and not never_entered and declared == traced
    reason = None
    if unknown:
        reason = "stage_outside_the_published_vocabulary"
    elif never_entered:
        reason = "declared_stage_never_entered"
    elif declared != traced:
        reason = "recipe_order_divergence"
    return ok, evidence(target="run_record", declared=declared, traced=traced,
                        never_entered=never_entered, unknown=unknown, reason=reason)''',

"reexecution_regenerates_the_format_map_not_the_bytes": '''\
    rerun = run_record().get("reexecution")
    if not isinstance(rerun, dict):
        return False, evidence(target="recipe_source", reason="reexecution_unrecorded")
    try:
        submitted = format_map_digest()
    except Exception as exc:
        return False, evidence(target="recipe_source", reason="format_map_unreadable",
                               error=str(exc))
    regenerated = str(rerun.get("format_map_sha256"))
    submitted_ppl = (run_record().get("perplexity") or {}).get("pg19_export")
    drift = ratio_of(rerun.get("pg19_perplexity"), submitted_ppl)
    if drift is None:
        return False, evidence(target="recipe_source",
                               reason="reexecution_perplexity_unrecorded")
    same_map = regenerated == submitted
    close_enough = abs(drift - 1.0) <= REEXEC_PPL_TOL
    ok = same_map and close_enough
    return ok, evidence(target="recipe_source", submitted_format_map=submitted,
                        regenerated_format_map=regenerated, perplexity_ratio=drift,
                        tolerance=REEXEC_PPL_TOL, packed_bytes_compared=False,
                        reason=None if ok else "recipe_export_divergence")''',

"throughput_is_the_geometric_mean_across_both_batch_sizes": '''\
    try:
        export = batch_medians("export")
        baseline = batch_medians("bf16_baseline")
    except Exception as exc:
        return False, evidence(target="run_record", reason="decode_trials_unreadable",
                               error=str(exc))
    try:
        geomean = geometric_mean(export)
        baseline_t = geometric_mean(baseline)
    except ValueError as exc:
        return False, evidence(target="run_record", reason="decode_rate_not_positive",
                               error=str(exc))
    arithmetic = sum(export.values()) / len(export)
    claimed = as_float(run_record().get("throughput_tokens_per_second"))
    agrees = claimed is None or abs(claimed - geomean) <= 1e-6 * max(1.0, geomean)
    covered = sorted(export) == list(BATCH_SIZES) and sorted(baseline) == list(BATCH_SIZES)
    ok = agrees and covered and baseline_t > 0
    reason = None
    if not covered:
        reason = "a_published_batch_size_was_not_measured"
    elif not agrees:
        reason = "recorded_throughput_is_not_the_published_geomean"
    elif baseline_t <= 0:
        reason = "bf16_baseline_not_measured_in_this_run"
    return ok, evidence(target="run_record", per_batch_median=export, geometric_mean=geomean,
                        arithmetic_mean_for_contrast=arithmetic,
                        baseline_geometric_mean=baseline_t, recorded=claimed,
                        batch_sizes=list(BATCH_SIZES), reason=reason)''',

"decode_window_is_512_steps_after_64_warmup": '''\
    trials = all_trials()
    if not trials:
        return False, evidence(target="run_record", reason="no_timed_trial_recorded")
    malformed = []
    for row in trials:
        warm, steps = row.get("warmup_steps"), row.get("measured_steps")
        elapsed = as_float(row.get("measured_elapsed_s"))
        rate = as_float(row.get("tokens_per_second"))
        batch = as_float(row.get("batch_size"))
        where = {"kind": row.get("kind"), "trial": row.get("trial"),
                 "batch_size": row.get("batch_size")}
        if warm != WARMUP_STEPS or steps != DECODE_STEPS:
            where.update(warmup_steps=warm, measured_steps=steps,
                         why="window_is_not_the_published_shape")
            malformed.append(where)
            continue
        if elapsed is None or rate is None or batch is None or elapsed <= 0:
            where["why"] = "trial_was_not_timed"
            malformed.append(where)
            continue
        recomputed = DECODE_STEPS * batch / elapsed
        if abs(rate - recomputed) > 1e-3 * max(1.0, recomputed):
            where.update(recorded=rate, recomputed=recomputed,
                         why="rate_does_not_come_from_the_measured_window")
            malformed.append(where)
    ok = not malformed
    return ok, evidence(target="run_record", timed_trials=len(trials),
                        malformed=len(malformed), first=malformed[:5],
                        warmup_steps=WARMUP_STEPS, measured_steps=DECODE_STEPS,
                        reason=None if ok else "decode_window_malformed")''',

"trial_spread_inside_the_iqr_admissibility_band": '''\
    spreads, wide = {}, []
    for kind in ("export", "bf16_baseline"):
        for batch in BATCH_SIZES:
            rates = trial_rates(kind, batch)
            if len(rates) != TRIALS:
                return False, evidence(target="run_record", reason="trial_count_is_not_five",
                                       kind=kind, batch_size=batch, recorded=len(rates),
                                       want=TRIALS)
            middle, spread = median(rates), interquartile_range(rates)
            spreads["%s/batch%d" % (kind, batch)] = 0.0 if middle <= 0 else spread / middle
            if middle <= 0 or spread > IQR_BAND * middle:
                wide.append({"kind": kind, "batch_size": batch, "iqr": spread,
                             "median": middle})
    remeasures = int(run_record().get("remeasures") or 0)
    ok = not wide and remeasures <= MAX_REMEASURES
    reason = None
    if wide:
        reason = "measurement_unstable"
    elif remeasures > MAX_REMEASURES:
        reason = "remeasure_budget_exhausted"
    return ok, evidence(target="run_record", relative_iqr=spreads, band=IQR_BAND,
                        remeasures=remeasures, remeasures_allowed=MAX_REMEASURES,
                        wide=wide[:4], reason=reason)''',

"every_declared_quantized_layer_dequantizes_at_decode": '''\
    try:
        rows = layer_rows()
    except Exception as exc:
        return False, evidence(target="run_record", reason="manifest_unreadable",
                               error=str(exc))
    counters = run_record().get("dequant_invocations")
    if not isinstance(counters, dict):
        return False, evidence(target="run_record", reason="dequant_counters_unrecorded")
    quantized, served_in_fp16 = 0, []
    for row in rows:
        if str(row.get("format")) == PASSTHROUGH_FORMAT:
            continue
        quantized += 1
        name = str(row.get("name"))
        try:
            count = int(counters.get(name) or 0)
        except (TypeError, ValueError):
            count = 0
        if count <= 0:
            served_in_fp16.append(name)
    if not quantized:
        return False, evidence(target="run_record", reason="nothing_was_quantized",
                               passthrough_format=PASSTHROUGH_FORMAT, layers=len(rows))
    ok = not served_in_fp16
    return ok, evidence(target="run_record", declared_quantized=quantized,
                        never_dequantized=served_in_fp16[:8],
                        reason=None if ok else "unquantized_layer_served")''',

"calibration_wall_clock_within_eight_minutes": '''\
    record = run_record()
    seconds = as_float(record.get("recipe_wall_clock_s"))
    source = str(record.get("recipe_wall_clock_source"))
    graded_phase = as_float(record.get("graded_phase_wall_clock_s"))
    if seconds is None:
        return False, evidence(target="run_record", reason="recipe_wall_clock_unrecorded")
    if source != "harness":
        return False, evidence(target="run_record", reason="wall_clock_is_self_reported",
                               clock_source=source)
    if graded_phase is None:
        return False, evidence(target="run_record",
                               reason="graded_phase_clock_not_kept_separate")
    ok = seconds <= CALIBRATION_BUDGET_S
    return ok, evidence(target="run_record", recipe_wall_clock_s=seconds,
                        budget_s=CALIBRATION_BUDGET_S,
                        headroom_s=CALIBRATION_BUDGET_S - seconds,
                        graded_phase_wall_clock_s=graded_phase, clock_source=source,
                        reason=None if ok else "calibration_budget_exceeded")''',

"no_foreign_quantized_checkpoint_and_no_private_slice_read": '''\
    record = run_record()
    # AN ABSENCE HAS TO BE RECORDED TO BE PROVEN. Reading four missing keys as four empty lists
    # is how an absence check passes on a run that produced no evidence at all, so the ledger the
    # harness writes must be present before anything in it is believed.
    ledger = ("foreign_quantized_checkpoints", "heldout_paths_opened", "guarded_paths_touched",
              "egress_hosts_contacted")
    unrecorded = [key for key in ledger if key not in record]
    if unrecorded:
        return False, evidence(target="run_record", reason="absence_ledger_unrecorded",
                               missing_keys=unrecorded)
    foreign = [str(p) for p in record.get("foreign_quantized_checkpoints") or []]
    opened = [str(p) for p in record.get("heldout_paths_opened") or []]
    touched = [str(p) for p in record.get("guarded_paths_touched") or []]
    hosts = [str(h).lower() for h in record.get("egress_hosts_contacted") or []]
    off_allowlist = sorted(h for h in hosts if h not in EGRESS_ALLOWLIST)
    hubs = sorted(h for h in hosts if h in MODEL_HUB_HOSTS)
    private = sorted(p for p in opened if p.startswith(HELDOUT_PREFIX)) or opened
    guarded = sorted(p for p in touched
                     if any(p.startswith(g) for g in GUARDED_PREFIXES)) or touched
    reason = None
    if foreign:
        reason = "foreign_quantized_checkpoint_on_disk"
    elif private:
        reason = "heldout_read"
    elif guarded:
        reason = "verifier_tree_written"
    elif off_allowlist:
        reason = "egress_violation"
    return reason is None, evidence(
        target="run_record", foreign_checkpoints=foreign[:5], private_slices_opened=private[:5],
        guarded_paths_touched=guarded[:5], off_allowlist_hosts=off_allowlist[:5],
        model_hub_hosts_contacted=hubs, allowlist=sorted(EGRESS_ALLOWLIST), reason=reason)''',

"pinned_checkpoint_digest_unchanged_by_the_recipe": '''\
    record = run_record()
    before = str(record.get("checkpoint_weight_digest_before"))
    after = str(record.get("checkpoint_weight_digest_after"))
    try:
        pinned = manifest().get("upstream_checkpoint") or {}
    except Exception as exc:
        return False, evidence(target="run_record", reason="manifest_unreadable",
                               error=str(exc))
    declared = str(pinned.get("weight_digest"))
    revision = pinned.get("revision")
    if not revision or "None" in (before, after, declared):
        return False, evidence(target="run_record", reason="checkpoint_pin_unrecorded",
                               revision=revision, digest_before=before, digest_after=after,
                               manifest_digest=declared)
    ok = before == after == declared
    return ok, evidence(target="run_record", checkpoint=PINNED_CHECKPOINT, revision=revision,
                        digest_before=before, digest_after=after, manifest_digest=declared,
                        reason=None if ok else "pinned_checkpoint_replaced")''',

"calibration_seconds_declared_per_stage_and_add_up": '''\
    try:
        doc = manifest()
    except Exception as exc:
        return False, evidence(target="export_manifest", reason="manifest_unreadable",
                               error=str(exc))
    stages = [str(stage) for stage in doc.get("recipe_stages") or []]
    accounting = doc.get("calibration_seconds")
    if not isinstance(accounting, dict) or not accounting:
        return False, evidence(target="export_manifest", reason="no_agent_declaration")
    missing = [stage for stage in stages if stage not in accounting]
    stray = sorted(set(accounting) - set(stages) - {"total"})
    per_stage = {}
    for stage in stages:
        value = as_float(accounting.get(stage))
        if value is None or value < 0:
            return False, evidence(target="export_manifest", reason="declaration_unparseable",
                                   stage=stage, value=accounting.get(stage))
        per_stage[stage] = value
    total = as_float(accounting.get("total"))
    if total is None:
        return False, evidence(target="export_manifest", reason="no_declared_total")
    summed = sum(per_stage.values())
    adds_up = abs(summed - total) <= 0.5
    reason = None
    if missing or stray:
        reason = "declaration_does_not_cover_the_declared_stages"
    elif not adds_up:
        reason = "declared_stages_do_not_sum_to_the_declared_total"
    elif total > CALIBRATION_BUDGET_S:
        reason = "declared_budget_over_the_calibration_cap"
    return reason is None, evidence(
        target="export_manifest", per_stage=per_stage, declared_total=total, summed=summed,
        budget_s=CALIBRATION_BUDGET_S, missing=missing, stray=stray, reason=reason)''',

"seed_is_derived_from_the_frozen_content_hash": '''\
    record = run_record()
    seed = record.get("seed")
    source = str(record.get("seed_source"))
    replay = (record.get("reexecution") or {}).get("seed")
    if seed is None:
        return False, evidence(target="recipe_source", reason="seed_unrecorded")
    if source != "canonical_content_hash":
        return False, evidence(target="recipe_source", reason="seed_not_derived_from_bytes",
                               seed_source=source)
    ok = replay is not None and int(replay) == int(seed)
    return ok, evidence(target="recipe_source", seed=seed, reexecution_seed=replay,
                        seed_source=source,
                        reason=None if ok else "reexecution_ran_under_a_different_seed")''',

"speedup_over_bf16_baseline_through_the_ramp": '''\
    c = require_measured("floor", "knee", "dichotomizing_threshold")
    # require_measured FIRST, before the run record is opened. Opening it first lets a missing or
    # malformed artifact raise a file error, the verifier records a failed check rather than an
    # unmeasured one, and the report reads gradeable=true with r_det=0.0 -- which asserts the
    # agent scored zero rather than that this slot is not yet measurable. Those are two different
    # claims and the null-constant convention exists to keep them apart.
    s = normalized_speedup()
    span = c["knee"] - c["floor"]
    ramp = 0.0 if span <= 0 else max(0.0, min(1.0, (s - c["floor"]) / span))
    return s >= c["dichotomizing_threshold"], evidence(
        target="run_record", speedup=s, s_outcome=ramp, floor=c["floor"], knee=c["knee"],
        batch_sizes=list(BATCH_SIZES), bit_budget=BIT_BUDGET)''',

}


def build_tests(grounding, prelude, bodies):
    """Assemble the compiled-check module. `kind` is the item's own dimension, so a failing
    check names the obligation it belongs to rather than the word 'process'."""
    chunks = [prelude]
    for item in sorted(grounding["items"], key=lambda i: i["id"]):
        if item["mode"] != "compiled":
            continue
        chunks.append('\n\n@check(id="%s", weight=%d, knockout=%s, kind="%s")\ndef test_%s():\n%s\n'
                      % (item["id"], item["weight"], item["knockout"], item["dimension"],
                         item["id"], bodies[item["id"]]))
    return "".join(chunks)


def build_annex(grounding):
    """The contract annex, rendered from the derivation source rather than authored beside it.

    It used to be a hand-written string in grounding.yaml that numbered the items alphabetically,
    which is not a path through anything. Here the ordered path is the narrative's own steps, each
    one carrying the compiled checks it satisfies, so the annex cannot drift from the items.
    """
    lines = ["Retained under FORGE.md item 10e and Phase 2 item 7, which require this file to "
             "carry the ordered path through instruction.md with each satisfied checker "
             "identifier, and each rejected route bound to a measured known-wrong control. "
             "standards/truth-md-authoring-v1.md section 3 admits no fifth section, so this "
             "annex is a recorded deviation rather than an omission.", ""]

    lines += ["### Ordered path, with the compiled check each step discharges", ""]
    for n, step in enumerate(grounding["truth_narrative"]["steps"], 1):
        satisfied = ", ".join("`%s`" % i for i in step["satisfies"])
        lines += ["%d. **%s** -- %s" % (n, step["heading"], satisfied), ""]

    lines += ["### Rejected routes, each bound to the control that measures it wrong", ""]
    for route in grounding["rejected_routes"]:
        lines += ["- %s" % route["route"], "  Controlled by: %s" % route["controlled_by"], ""]

    lines += ["### Control ladder recorded in seed/contract.yaml", ""]
    for control in grounding["control_ladder"]:
        lines += ["- `%s` (recorded score %s) -- %s"
                  % (control["id"], control["recorded_score"], control["targets"]), ""]

    lines += ["### The compiled surface", ""]
    total = sum(i["weight"] for i in grounding["items"])
    knockouts = [i["id"] for i in grounding["items"] if i["knockout"]]
    lines += ["%d compiled checks carrying %d weight, of which %d are knockouts. Every one runs "
              "against the export manifest, the packed shard bytes on disk, the submitted recipe "
              "or the harness run record."
              % (len(grounding["items"]), total, len(knockouts)), ""]
    for item in sorted(grounding["items"], key=lambda i: (-i["weight"], i["id"])):
        lines += ["- `%s` (%s, weight %d%s) -- %s"
                  % (item["id"], item["dimension"], item["weight"],
                     ", knockout" if item["knockout"] else "", item["criterion"].strip())]
    lines += [""]

    lines += ["### Behavioural rubrics, graded downstream and never inside r_det", ""]
    for rubric in grounding["council_rubrics"]:
        lines += ["- `%s` -- %s" % (rubric["id"], rubric["asks"].strip()), ""]

    deliverable = grounding["deliverable"]
    companions = ", ".join(deliverable["companion_paths"])
    lines += ["### Deliverable manifest", "",
              "%s (%s): %s. Companions the checks also read: %s."
              % (deliverable["path"], deliverable["kind"], deliverable["shape"].strip(),
                 companions), ""]
    return "\n".join(lines)


def build_truth(grounding, title):
    """Render solution/TRUTH.md from the frozen literals of solution/grounding.yaml."""
    narrative = grounding["truth_narrative"]
    lines = [title, "", "GENERATED SECTION. DO NOT HAND-EDIT.", "", narrative["opening"], "",
             "## The single most important insight", "", narrative["insight"], "",
             "## The ideal solve, step by step", ""]
    for n, step in enumerate(narrative["steps"], 1):
        lines += ["%d. **%s** %s" % (n, step["heading"], step["paragraph"]), ""]
    lines += ["## Traps that catch agents that are not thinking carefully", ""]
    lines += ["- " + trap for trap in narrative["traps"]]
    lines += ["", "---", "", "## Contract record (annex; not part of the narrative body)", "",
              build_annex(grounding), ""]
    return "\n".join(lines) + "\n"


def build_rubrics(grounding, item_keys):
    """The 9g rubric carrier. The item schema is CLOSED at eight keys, so item 10f's outcome
    classification rides as a greppable prefix of the judgment rather than as a ninth key."""
    items = []
    for raw in grounding["items"]:
        item = {key: raw[key] for key in item_keys}
        item["criterion"] = " ".join(raw["criterion"].split())
        item["judgment"] = "%s: %s" % (raw["outcome_class"], " ".join(raw["judgment"].split()))
        items.append(item)
    compiled = sum(i["weight"] for i in items if i["mode"] == "compiled")
    total = sum(i["weight"] for i in items)
    return {"$schema": "forge.rubric/v1",
            "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
            "generator": "solution/recompute.py",
            "compilation_floor": grounding["compilation_floor"],
            "compiled_weight_share": round(compiled / total, 6) if total else 0.0,
            "evaluation_target_vocabulary": sorted(grounding["evaluation_target_vocabulary"]),
            "items": sorted(items, key=lambda i: i["id"])}


def build_provenance(grounding, identity):
    record = grounding["provenance"]
    out = {
        "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
        "generator": "solution/recompute.py from solution/grounding.yaml",
        "schema_version": "1.0",
        "slot_id": grounding["slot_id"],
        "identity": identity,
        "corpus": record["corpus"],
        "anchors": record["anchors"],
        "shards": record["shards"],
        "narrative": record["narrative"],
        "supersedes": record["supersedes"],
        "upstream_provenance": record["upstream_record"],
        "reward_composition": record["reward_composition"],
        "screening_interval_days": record["screening_interval_days"],
        "screening_detector_version": record["screening_detector_version"],
        "derivation_instant": record["derivation_instant"],
        "screening_roots": record["screening_roots"],
        "empty_submission_result": record["empty_submission_result"],
        "resolved_closure": record["resolved_closure"],
        "applicability": record["applicability"],
        "measurement_tier": grounding["measurement_tier"],
        "gradeable": grounding["gradeable"],
        "knee_anchor_status": grounding["knee_anchor_status"],
        "corpus_layout_status": grounding["corpus_layout"]["status"],
        "bit_budget_bits_per_weight": grounding["published_bounds"]["bit_budget_bits_per_weight"],
        "calibration_budget_seconds": grounding["published_bounds"]["calibration_budget_seconds"],
    }
    out.update(read_screening(HERE))
    return out


def validate(grounding):
    """Refuse to emit from a derivation source this slot cannot honestly compile.

    Every rule below is a defect that has actually shipped somewhere in this batch:

      1. An item without a body used to fall through to a generic obligation lookup that read a
         run-record key nothing writes, so the check consulted nothing and reported a pass.
      2. The outcome item must call require_measured as its FIRST statement. Reading the run
         record first lets a missing-file error mask the unmeasured signal, and the verifier then
         reports gradeable=true with r_det=0.0, collapsing "not yet measurable" into "the agent
         scored zero".
      3. The four measured constants stay null at Phase 0. A generator that emitted an authored
         floor would be inventing the measurement the whole convention exists to withhold.
      4. The format cost table has to price the decoy over the budget and the cheapest uniform row
         under it. If that arithmetic ever stopped holding, the vendor-notes control would stop
         being a control and the slot would have no measured-wrong popular route at all.
      5. The layer roster has to multiply out. blocks x projections is the denominator of the
         average bits per weight, and a wrong denominator is a silently wrong budget check.
    """
    problems = []
    items = grounding.get("items") or []
    if not items:
        problems.append("no items to compile")

    seen = set()
    for item in items:
        iid = item.get("id", "<unnamed>")
        if iid in seen:
            problems.append("duplicate item id %r" % iid)
        seen.add(iid)
        if set(item) != ITEM_SCHEMA:
            problems.append("item %r does not carry the closed schema: %s"
                            % (iid, sorted(set(item) ^ ITEM_SCHEMA)))
            continue
        if item["outcome_class"] not in OUTCOME_CLASSES:
            problems.append("item %r carries outcome_class %r" % (iid, item["outcome_class"]))
        if item["evaluation_target"] not in grounding["evaluation_target_vocabulary"]:
            problems.append("item %r evaluates %r, which the vocabulary does not admit"
                            % (iid, item["evaluation_target"]))
        if not isinstance(item["weight"], int) or item["weight"] <= 0:
            problems.append("item %r carries weight %r" % (iid, item["weight"]))

    compiled = {i["id"] for i in items if i["mode"] == "compiled"}
    for iid in sorted(compiled - set(BODIES)):
        problems.append("compiled item %r carries no body; this generator refuses rather than "
                        "emitting a check that consults nothing" % iid)
    for iid in sorted(set(BODIES) - compiled):
        problems.append("body %r belongs to no compiled item" % iid)

    outcome = [i for i in items if i["dimension"] == OUTCOME_DIMENSION]
    if [i["id"] for i in outcome] != [OUTCOME_ITEM]:
        problems.append("expected exactly one %r item named %r, found %r"
                        % (OUTCOME_DIMENSION, OUTCOME_ITEM, [i["id"] for i in outcome]))
    elif OUTCOME_ITEM in BODIES:
        statements = [line.strip() for line in BODIES[OUTCOME_ITEM].split("\n")
                      if line.strip() and not line.strip().startswith("#")]
        head = statements[0] if statements else ""
        if head != REQUIRE_FIRST:
            problems.append("%s must call require_measured on floor, knee and "
                            "dichotomizing_threshold as its first statement, before it reads the "
                            "run record; its first statement is %r" % (OUTCOME_ITEM, head[:70]))

    for name in RAMP_CONSTANTS:
        if grounding["constants"].get(name) is not None:
            problems.append("measured constant %r was authored at Phase 0; it is measured on the "
                            "grading host, not written here" % name)

    bounds = grounding["published_bounds"]
    roster = bounds["transformer_blocks"] * len(bounds["projections_per_block"])
    if roster != bounds["linear_layer_count"]:
        problems.append("the layer roster does not multiply out: %d blocks x %d projections is "
                        "%d, not the declared %d"
                        % (bounds["transformer_blocks"], len(bounds["projections_per_block"]),
                           roster, bounds["linear_layer_count"]))

    hidden = int(bounds["hidden_size"])
    counts = bounds["weight_count_by_projection"]
    expected = {
        "self_attn.q_proj": hidden * hidden,
        "self_attn.o_proj": hidden * hidden,
        "self_attn.k_proj": hidden * int(bounds["key_value_heads"]) * int(bounds["head_dim"]),
        "self_attn.v_proj": hidden * int(bounds["key_value_heads"]) * int(bounds["head_dim"]),
        "mlp.gate_proj": hidden * int(bounds["intermediate_size"]),
        "mlp.up_proj": hidden * int(bounds["intermediate_size"]),
        "mlp.down_proj": hidden * int(bounds["intermediate_size"]),
    }
    if int(bounds["attention_heads"]) * int(bounds["head_dim"]) != hidden:
        problems.append("%d attention heads at head_dim %d do not span hidden_size %d"
                        % (bounds["attention_heads"], bounds["head_dim"], hidden))
    for projection, want in sorted(expected.items()):
        if counts.get(projection) != want:
            problems.append("projection %r is declared at %r weights, but the pinned shapes give "
                            "%d" % (projection, counts.get(projection), want))
    if sorted(counts) != sorted(bounds["projections_per_block"]):
        problems.append("the weight-count table and the projection roster name different layers")
    summed = sum(counts.values()) * int(bounds["transformer_blocks"])
    if summed != int(bounds["linear_weight_total"]):
        problems.append("the per-block weight counts sum to %d over %d blocks, not the declared "
                        "%d" % (summed, bounds["transformer_blocks"],
                                bounds["linear_weight_total"]))

    contract = grounding["runtime_format_contract"]
    priced = {}
    for row in contract["rows"]:
        group = int(row["group_size"])
        if group <= 0:
            problems.append("format %r declares a non-positive group size" % row["format"])
            continue
        priced[row["format"]] = (float(row["payload_bits"])
                                 + (float(row["scale_bits"])
                                    + float(row["zero_point_bits"])) / group)
    budget = float(bounds["bit_budget_bits_per_weight"])
    decoy = priced.get(contract["decoy_row"])
    cheapest = priced.get(contract["cheapest_uniform_row_that_fits"])
    if decoy is None or decoy <= budget:
        problems.append("the decoy row %r prices at %r, which does not exceed the %r budget it is "
                        "supposed to fail" % (contract["decoy_row"], decoy, budget))
    if cheapest is None or cheapest > budget:
        problems.append("the cheapest uniform row %r prices at %r, which does not fit the %r "
                        "budget" % (contract["cheapest_uniform_row_that_fits"], cheapest, budget))
    if contract["per_format_decode_throughput"] is not None:
        problems.append("per-format decode throughput was authored at Phase 0; it is measured on "
                        "the grading host with the runtime's own kernels")
    if priced.get(PASSTHROUGH_FORMAT) is None:
        problems.append("the format contract has no %r row, so a layer left unquantized could "
                        "not be declared at all" % PASSTHROUGH_FORMAT)

    shares = grounding["contract_recorded_projections"]["reference_allocation_weight_mass_shares"]
    if abs(sum(shares.values()) - 1.0) > 1e-9:
        problems.append("the reference allocation shares sum to %r, not to one"
                        % sum(shares.values()))
    reference = sum(priced.get(fmt, 0.0) * share for fmt, share in shares.items())
    if reference > budget:
        problems.append("the reference allocation prices at %r, above its own %r budget"
                        % (reference, budget))

    cited = set()
    for step in grounding["truth_narrative"]["steps"]:
        cited.update(step["satisfies"])
    stray = sorted(cited - {i["id"] for i in items})
    if stray:
        problems.append("the narrative cites checks that do not exist: %s" % stray)
    uncited = sorted({i["id"] for i in items} - cited)
    if uncited:
        problems.append("no narrative step reaches these checks: %s" % uncited)

    return problems


def main():
    grounding = load_grounding()
    # The validator runs FIRST and refuses rather than emitting: a generator that writes a carrier
    # it knows is malformed hands the drift check a moving target.
    problems = validate(grounding)
    if problems:
        raise SystemExit("%s grounding is not well-formed: %s" % (SLOT_ID, "; ".join(problems)))

    layout = grounding["corpus_layout"]
    bounds = grounding["published_bounds"]
    contract = grounding["runtime_format_contract"]
    formats = {row["format"]: {"payload_bits": row["payload_bits"],
                               "scale_bits": row["scale_bits"],
                               "zero_point_bits": row["zero_point_bits"],
                               "group_size": row["group_size"]}
               for row in contract["rows"]}

    prelude = render(PRELUDE, {
        "SLOT": SLOT_ID,
        "OUTCOME": OUTCOME_ITEM,
        "MANIFEST": repr(grounding["deliverable"]["path"]),
        "EXPORT_ROOT": repr(layout["export_root"]),
        "RECIPE": repr(layout["recipe_program"]),
        "SHARD_DIR": repr(layout["shard_dir"]),
        "RUN_RECORD": repr(layout["run_record"]),
        "PINNED_CHECKPOINT": repr(layout["pinned_checkpoint"]),
        "BLOCKS": repr(bounds["transformer_blocks"]),
        "PROJECTIONS": repr(tuple(bounds["projections_per_block"])),
        "LAYERS": repr(bounds["linear_layer_count"]),
        "WEIGHT_COUNTS": json.dumps(bounds["weight_count_by_projection"], indent=4,
                                    sort_keys=True),
        "WEIGHT_TOTAL": repr(int(bounds["linear_weight_total"])),
        "BIT_BUDGET": repr(float(bounds["bit_budget_bits_per_weight"])),
        "CALIB_S": repr(float(bounds["calibration_budget_seconds"])),
        "PPL_GATE": repr(float(bounds["perplexity_gate_ratio"])),
        "PPL_STARTER": repr(float(bounds["starter_perplexity_ratio"])),
        "SUB_GATE": repr(float(bounds["sub_gate_credit_ceiling"])),
        "GAP_BOUND": repr(float(bounds["retention_gap_bound"])),
        "REEXEC_TOL": repr(float(bounds["reexecution_perplexity_tolerance"])),
        "IQR_BAND": repr(float(bounds["trial_iqr_band"])),
        "MAX_REMEASURES": repr(int(bounds["max_remeasures"])),
        "WARMUP": repr(int(bounds["warmup_steps"])),
        "DECODE_STEPS": repr(int(bounds["measured_decode_steps"])),
        "TRIALS": repr(int(bounds["trials"])),
        "BATCH_SIZES": repr(tuple(bounds["batch_sizes"])),
        "STAGES": repr(tuple(bounds["recipe_stage_vocabulary"])),
        "FORMAT_CONTRACT": json.dumps(formats, indent=4, sort_keys=True),
        "PASSTHROUGH": repr(PASSTHROUGH_FORMAT),
        "DECOY": repr(contract["decoy_row"]),
        "CHEAPEST": repr(contract["cheapest_uniform_row_that_fits"]),
        "GUARDED": repr(tuple(layout["guarded_prefixes"])),
        "HELDOUT": repr(layout["heldout_prefix"]),
        # SORTED TUPLES, not repr(frozenset(...)). A frozenset's repr orders by hash, which moves
        # with PYTHONHASHSEED, so the generator emitted a different byte sequence on every run and
        # the freeze's "regeneration is not canary-preserving" refusal fired on a set literal.
        "ALLOWLIST": "frozenset(%r)" % (tuple(sorted(layout["declared_egress_allowlist"])),),
        "HUBS": "frozenset(%r)" % (tuple(sorted(layout["model_hub_hosts"])),),
    })

    tests_dir = os.path.join(BUNDLE, "tests")
    os.makedirs(tests_dir, exist_ok=True)

    # EVERYTHING IS COMPUTED BEFORE ANY OUTPUT FILE IS OPENED. `with open(path, "w")` truncates
    # before its body's arguments are evaluated, so a read inside the with-statement reads the
    # file that line just emptied. That shipped once here, over the frozen identity block.
    truth = build_truth(grounding, TITLE).rstrip("\n") + "\n"
    rubrics = build_rubrics(grounding, ITEM_KEYS)
    module = build_tests(grounding, prelude, BODIES) + TAIL
    provenance = build_provenance(grounding, read_identity(HERE))

    # solution/TRUTH.md and solution/rubrics.json are PRIVATE_CARRIERS: seed/identity.py plants a
    # canary block into them at freeze, and canary normalisation is what keeps planting from
    # moving identity. A generator that rewrote them plainly would DROP the planted tripwire, and
    # the next content hash would differ from the frozen one. So the planted block is carried
    # across the regeneration rather than recreated.
    truth_path = os.path.join(HERE, "TRUTH.md")
    planted = None
    if os.path.exists(truth_path):
        import re as _re
        found = _re.search(r"<!-- AELLO-CANARY-BLOCK.*?-->\n?", open(truth_path).read(), _re.S)
        planted = found.group(0) if found else None

    rubrics_path = os.path.join(HERE, "rubrics.json")
    if os.path.exists(rubrics_path):
        try:
            previous = json.load(open(rubrics_path))
            if "canary" in previous:
                rubrics["canary"] = previous["canary"]
        except Exception:
            pass

    with open(truth_path, "w") as handle:
        handle.write(truth + ("\n" + planted if planted else ""))
    with open(rubrics_path, "w") as handle:
        json.dump(rubrics, handle, indent=1, sort_keys=True)
        handle.write("\n")
    with open(os.path.join(tests_dir, "rubrics.json"), "w") as handle:
        json.dump(build_rubrics(grounding, ITEM_KEYS), handle, indent=1, sort_keys=True)
        handle.write("\n")
    with open(os.path.join(tests_dir, "test_output.py"), "w") as handle:
        handle.write(module)
    with open(os.path.join(tests_dir, "constants.json"), "w") as handle:
        json.dump(grounding["constants"], handle, indent=1, sort_keys=True)
        handle.write("\n")
    with open(os.path.join(HERE, "provenance.yaml"), "w") as handle:
        # MATCH seed/build/screen_bind.py and the frozen generators exactly: sort_keys=True,
        # default_flow_style=False, width=100. The screen writes this carrier after the freeze,
        # so a generator using a different dump convention reorders the keys on the next
        # regeneration and reports as drift even though no value changed.
        yaml.safe_dump(provenance, handle, sort_keys=True, default_flow_style=False, width=100,
                       allow_unicode=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
