"""Derivation for A5-03: every canonical artifact descends from solution/grounding.yaml.

The graded object of this slot is a STREAMING CTC RECOGNIZER, delivered as an export directory the
verifier loads and RUNS. That is why none of the checks below reads a prediction array: an array of
labels cannot be perturbed, and this slot's hardest constraint -- at most 320 ms of algorithmic
right context -- is only meaningful as a perturbation probe over a running model. The bytes these
checks read are the export manifest, the serialized parameter file, the shipped permuted label
vocabulary, the pinned held-out digest table, and the record the HARNESS wrote while the graded run
executed: its probe results, its op trace, its edit-operation counts and the front-end constants it
watched train.py compute.

The thirteen judged "obligation" items that used to stand in the items list are gone. Each restated
a checker id from seed/contract.yaml and then fell through to a generic lookup at
run_record()["obligations"][<ID>], a key nothing in the harness writes, so each graded nothing at
all while reporting a clean False. Every item is compiled now and every compiled item carries a
body written for this slot; main() REFUSES rather than falling through.
"""
import json
import os
import sys

import yaml

sys.dont_write_bytecode = True

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
# generator_common.py is VENDORED beside this file, not reached for outside the bundle. A staged
# tree could resolve seed/stage/<slug>/../../build; a DELIVERED tree at dataset/<uuid>/ cannot,
# and reaching outside would make the delivered bundle non-self-contained -- it would import in
# the stage and fail everywhere it actually ships.

ITEM_KEYS = ('id', 'dimension', 'weight', 'evaluation_target', 'criterion', 'judgment', 'knockout',
             'mode')
ITEM_SCHEMA = frozenset(ITEM_KEYS + ('outcome_class',))
OUTCOME_CLASSES = frozenset(("EFFECT", "INVARIANT", "ABSENCE", "VALUE", "ORDERING", "DIVERGENCE"))
RAMP = ("floor", "knee", "dichotomizing_threshold", "reward_gate_pass_threshold")
REQUIRE_FIRST = 'c = require_measured("floor", "knee", "dichotomizing_threshold")'
SLOT_ID = 'A5-03'
TITLE = "# A5-03 -- what this task actually tests"


def read_identity(here):
    """Identity is an INPUT: the freeze computes it over the hashed tree and binds it into the
    carrier, which is hash-excluded, so reading it back keeps generation acyclic."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        if isinstance(doc.get("identity"), dict):
            return doc["identity"]
    return {"canonical_content_hash": None, "uuid": None,
            "normalization_domain": "aello.canary.norm/v1",
            "derivation": "uuid5(FORGE_TASK_NAMESPACE, canonical_content_hash)"}


def read_screening(here):
    """The screening instant and result are MEASURED OVER the frozen tree, so they are read back
    the way identity is; the carrier is hash-excluded, so binding them moves nothing."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        got = {k: doc[k] for k in ("screening_measured_at", "screening_expires_at",
                                   "screening_result") if k in doc}
        if got:
            return got
    return {"screening_measured_at": None, "screening_expires_at": None,
            "screening_result": None}


def load_grounding():
    with open(os.path.join(HERE, "grounding.yaml")) as fh:
        return yaml.safe_load(fh)


# ==========================================================================================
# The emitted checker. PRELUDE carries this slot's export vocabulary and IS substituted from
# corpus_layout; BODIES go in verbatim under their own decorator; TAIL is the reading machinery
# and is NOT substituted, because it carries percent formatting of its own.
# ==========================================================================================

PRELUDE = '''"""Compiled checks for %(slot_id)s. GENERATED by solution/recompute.py. DO NOT HAND-EDIT.

The graded deliverable is an EXPORT DIRECTORY holding a streaming CTC recognizer: a manifest, the
serialized parameter file it names, and the train.py that produced it. The verifier loads that
export and runs it over private audio it holds. So the delivered bytes these checks read are the
export manifest, the parameter file's own size on disk, the shipped permuted label vocabulary, the
pinned held-out digest table, and the record the harness wrote while the graded run executed --
its causality-probe results, its op trace, its per-shard edit-operation counts, and the front-end
constants it watched train.py compute.

Nothing below imports or executes the submission. Nothing below reads a quality value the agent
reports: reward_log.jsonl is read in exactly one check, %(log_check)s, and only to be compared
against what the harness measured.

Every check runs against those bytes and references no unmeasured quantity, except
%(outcome_id)s, which raises ConstantUnmeasured while tests/constants.json carries nulls.
"""
import hashlib
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SUBMISSION = %(export_dir)r
CHECKS = []

# --- what the agent delivers --------------------------------------------------------------
MANIFEST_NAME = %(manifest_name)r
MANIFEST_KEYS = %(manifest_keys)r
TRAIN_ENTRYPOINT = %(train_entrypoint)r

# --- the streaming contract, in frames and milliseconds ------------------------------------
RIGHT_CONTEXT_MS = %(right_context_ms)r
RIGHT_CONTEXT_FRAMES = %(right_context_frames)r
FRAME_SHIFT_MS = %(frame_shift_ms)r

# --- the CTC decode contract ---------------------------------------------------------------
COLLAPSE_ORDER = %(collapse_order)r
FORBIDDEN_DECODE_SYMBOLS = %(forbidden_decode_symbols)r
ENVELOPE = %(operator_envelope)r
REQUIRED_FRONTEND_OPS = %(required_frontend_ops)r

# --- the front end that must live INSIDE the export ----------------------------------------
FRONTEND_FIELDS = %(frontend_fields)r
LABEL_VOCABULARY = %(label_vocabulary)r

# --- the graded shards, and what a WER row has to carry ------------------------------------
SHARDS = %(graded_shards)r
LS_A = %(librispeech_a)r
LS_B = %(librispeech_b)r
CV = %(commonvoice)r
WER_FIELDS = %(wer_fields)r

# --- verifier-held tables the graded run may not read --------------------------------------
HELDOUT_DIGEST_TABLE = %(heldout_digest_table)r
PROBE_OFFSETS = %(probe_offsets)r
SHIPPED_TRANSCRIPT_DIGESTS = %(shipped_transcript_digests)r

# --- what the harness records, and where ----------------------------------------------------
RUN_RECORD = %(run_record)r
GUARDED = %(guarded)r
PARAMETER_EDIT_OPS = %(parameter_edit_ops)r
STATISTICS_OP = %(statistics_op)r
REPLAY_DIGEST_KEYS = ("parameter_file", "export_manifest", "hypotheses_private_a")

# --- declared bounds. None of these is a ramp constant; the ramp constants are null. --------
PARAM_BYTE_CEILING = %(parameter_byte_ceiling)r
BUDGET_SECONDS = %(budget_seconds)r
SIBLING_GAP_BOUND = %(sibling_shard_gap_bound)r
PERMUTATION_TAU = %(permutation_reward_tau)r
WER_TOLERANCE = %(wer_recomputation_tolerance)r
LOG_WER_TOLERANCE = %(log_wer_tolerance)r
LOG_ELAPSED_TOLERANCE = %(log_elapsed_tolerance_fraction)r


class ConstantUnmeasured(Exception):
    """Raised when a check needs a ramp constant that Phase 0 deliberately left null."""


def check(id, weight, knockout, kind):
    def deco(fn):
        CHECKS.append({"id": id, "weight": weight, "knockout": knockout, "kind": kind, "fn": fn})
        return fn
    return deco


def constants():
    with open(os.path.join(HERE, "constants.json")) as fh:
        return json.load(fh)


def require_measured(*names):
    c = constants()
    missing = [n for n in names if c.get(n) is None]
    if missing:
        raise ConstantUnmeasured(
            "%(slot_id)s: " + ", ".join(missing) + " are null. Phase 0 authors no measurement; "
            "the Phase 2 measurement wave writes these and this check becomes gradeable then.")
    return c


def evidence(**kw):
    return {"evaluation_target": kw.pop("target", "submitted_artifact"), "values": kw}
'''


TAIL = '''

# ------------------------------------------------------------------------------------------
# Reading the delivered bytes. Five sources: the export directory the agent wrote, the shipped
# permuted label vocabulary, the verifier-held tables under tests/heldout/, the harness's own
# run record, and the agent's reward_log.jsonl -- which is read in exactly one check and only
# to be compared against the harness. Each source is read the same way everywhere: an absent
# one is REPORTED under its own name, never guessed at and never allowed to look like a pass.
# ------------------------------------------------------------------------------------------

def bundle(rel):
    """A path relative to the bundle root, from the checker tree."""
    return os.path.normpath(os.path.join(HERE, "..", rel))


def heldout(name):
    """A verifier-side table. Lives under tests/heldout/ and the graded run may not read it."""
    return os.path.join(HERE, "heldout", os.path.basename(name))


def read_json(path):
    if not path or not os.path.exists(path):
        return None
    try:
        with open(path) as handle:
            return json.load(handle)
    except Exception:
        return None


def heldout_json(name):
    return read_json(heldout(name))


def run_record():
    """Written by the HARNESS, never by the agent. An absent record is an empty dict, and every
    check that needs a field of it says so by name rather than reading the absence as a zero."""
    doc = read_json(os.path.normpath(os.path.join(HERE, RUN_RECORD)))
    return doc if isinstance(doc, dict) else {}


def manifest():
    doc = read_json(os.path.join(SUBMISSION, MANIFEST_NAME))
    return doc if isinstance(doc, dict) else None


def parameter_file_path():
    doc = manifest() or {}
    name = doc.get("parameter_file")
    if not isinstance(name, str) or not name:
        return None
    # The manifest names a file INSIDE the export directory. A name that climbs out of it is not
    # a parameter file, it is a way to have the byte ceiling measured against something else.
    candidate = os.path.normpath(os.path.join(SUBMISSION, name))
    if not candidate.startswith(os.path.normpath(SUBMISSION) + os.sep):
        return None
    return candidate


def decode_block():
    doc = manifest() or {}
    block = doc.get("decode")
    return block if isinstance(block, dict) else None


def declared_frontend():
    doc = manifest() or {}
    front = doc.get("frontend")
    return front if isinstance(front, dict) else None


def label_vocabulary():
    doc = read_json(bundle(LABEL_VOCABULARY))
    return doc if isinstance(doc, dict) else None


def vocabulary_indices(vocab):
    """Indices the shipped permuted vocabulary actually assigns to a character."""
    taken = set()
    for value in vocab.values():
        if isinstance(value, int) and not isinstance(value, bool):
            taken.add(value)
    return taken


def probe_offsets():
    """The offsets the verifier drew this attempt, or None when the table has not landed."""
    doc = heldout_json(PROBE_OFFSETS)
    if not isinstance(doc, dict):
        return None
    offsets = doc.get("offset_frames")
    return offsets if isinstance(offsets, list) else None


def shipped_transcript_digests():
    doc = heldout_json(SHIPPED_TRANSCRIPT_DIGESTS)
    if isinstance(doc, dict):
        values = doc.get("digests", doc)
        if isinstance(values, dict):
            return set(values.values())
        if isinstance(values, list):
            return set(values)
    if isinstance(doc, list):
        return set(doc)
    return None


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def wer_row(shard):
    rows = run_record().get("wer")
    if not isinstance(rows, dict):
        return None
    row = rows.get(shard)
    return row if isinstance(row, dict) else None


def wer_value(shard):
    row = wer_row(shard)
    if row is None:
        return None
    value = row.get("wer")
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return None
    return float(value)


def numbers_equal(a, b):
    """Front-end constants compare by value: 10 and 10.0 are the same frame shift, and 10 and
    12.5 are the failure this whole slot is built around."""
    if isinstance(a, bool) or isinstance(b, bool):
        return a is b
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return abs(float(a) - float(b)) <= 1e-9
    return a == b


def symbol_tokens(symbol):
    """Split an operator or key name into tokens, so `lm` matches `lm_weight` and never `mel`."""
    return {t for t in re.split(r"[^a-z0-9]+", str(symbol).lower()) if t}


def forbidden_hits(symbols):
    banned = set(FORBIDDEN_DECODE_SYMBOLS)
    return sorted({s for s in symbols if symbol_tokens(s) & banned})


def last_reward_log_record():
    """The agent's own channel. Read here and nowhere else, and only to be contradicted."""
    path = run_record().get("reward_log")
    if not isinstance(path, str) or not path:
        return None
    resolved = path if os.path.isabs(path) else bundle(path)
    if not os.path.exists(resolved):
        return None
    last = None
    try:
        with open(resolved) as handle:
            for line in handle:
                line = line.strip()
                if not line:
                    continue
                parsed = json.loads(line)
                if isinstance(parsed, dict):
                    last = parsed
    except Exception:
        return None
    return last


def measure():
    """The binding per-corpus quality, on a higher-is-better axis.

    The reward map is a PRODUCT over the read-speech axis and the volunteer-speech axis, so the
    worse corpus binds and the graded quantity is min(1 - WER) across the two. Both values come
    from the harness's own measurement of the frozen export's greedy hypotheses under the pinned
    normalizer; nothing the agent reports enters here.
    """
    if not run_record():
        raise ConstantUnmeasured("the harness produced no run record, so no word error rate has "
                                 "been measured for this slot yet")
    qualities = []
    for shard in (LS_A, CV):
        wer = wer_value(shard)
        # An export that decoded nothing is NOT an unmeasured slot: it is the worst anchor, which
        # the contract fixes at WER 1.000 on both shards.
        qualities.append(1.0 - (1.0 if wer is None else float(wer)))
    return min(qualities)
'''


# ==========================================================================================
# BODIES. Every compiled item carries one, written for THIS slot. The generic obligation
# lookup that used to fill this gap is gone: it read run_record()["obligations"][<ID>], a key
# nothing in the harness writes, so an item that fell through to it consulted nothing at all
# and still reported a clean False. The generator now REFUSES on a missing body.
# ==========================================================================================

BODIES = {

    "export_manifest_binds_parameters_frontend_and_decode": '''
    if not os.path.isdir(SUBMISSION):
        return False, evidence(reason="export_absent", path=SUBMISSION,
                               detail="the deliverable is an export directory the verifier loads "
                                      "and runs, not a file of saved predictions")
    doc = manifest()
    if doc is None:
        return False, evidence(reason="manifest_unreadable",
                               path=os.path.join(SUBMISSION, MANIFEST_NAME))
    absent = [key for key in MANIFEST_KEYS if key not in doc]
    if absent:
        return False, evidence(reason="manifest_incomplete", missing=absent)
    param = parameter_file_path()
    if param is None or not os.path.exists(param):
        return False, evidence(reason="parameter_file_absent",
                               declared=doc.get("parameter_file"))
    front = declared_frontend() or {}
    unstated = [field for field in FRONTEND_FIELDS if field not in front]
    ops = doc.get("graph_ops")
    look = doc.get("layer_right_context_frames")
    ok = (not unstated and isinstance(ops, list) and bool(ops)
          and isinstance(look, list) and bool(look) and isinstance(doc.get("decode"), dict))
    return ok, evidence(parameter_file=os.path.basename(param),
                        frontend_fields_unstated=unstated,
                        graph_op_count=len(ops) if isinstance(ops, list) else None,
                        layer_count=len(look) if isinstance(look, list) else None,
                        train_entrypoint=doc.get("train_entrypoint"),
                        reason=None if ok else "manifest_incomplete")
''',

    "chk_op_envelope": '''
    doc = manifest()
    if doc is None:
        return False, evidence(reason="manifest_unreadable")
    ops = doc.get("graph_ops")
    if not isinstance(ops, list) or not ops:
        return False, evidence(reason="graph_ops_absent",
                               detail="an export that lists no operators declares no front end")
    outside = sorted({str(op) for op in ops if str(op) not in ENVELOPE})
    frontend_missing = [op for op in REQUIRED_FRONTEND_OPS if op not in [str(x) for x in ops]]
    ok = not outside and not frontend_missing
    return ok, evidence(operators=len(ops), outside_envelope=outside,
                        frontend_ops_missing=frontend_missing,
                        detail=None if not frontend_missing else
                        "the log-mel front end runs outside the graded artifact, where its frame "
                        "shift and mel count cannot be compared against the training-time ones",
                        reason=None if ok else ("ENVELOPE_OP_REFUSED" if outside
                                                else "frontend_outside_the_export"))
''',

    "greedy_argmax_decode_carries_no_beam_lexicon_or_lm": '''
    dec = decode_block()
    if dec is None:
        return False, evidence(reason="decode_block_absent")
    method = dec.get("method")
    banned_keys = forbidden_hits(dec.keys())
    graph = [str(op) for op in ((manifest() or {}).get("graph_ops") or [])]
    observed = [str(s) for s in (run_record().get("observed_decode_symbols") or [])]
    banned_symbols = forbidden_hits(graph + observed)
    width = dec.get("beam_width")
    ok = method == "greedy" and not banned_keys and not banned_symbols and width is None
    return ok, evidence(method=method, forbidden_keys=banned_keys,
                        forbidden_symbols=banned_symbols, beam_width=width,
                        decode_symbols_observed=len(observed),
                        detail="a beam of width one is still a beam and is refused by name",
                        reason=None if ok else "DECODE_CONTRACT_VIOLATED")
''',

    "repeat_collapse_precedes_blank_removal": '''
    dec = decode_block()
    if dec is None:
        return False, evidence(reason="decode_block_absent")
    seq = dec.get("collapse")
    if not isinstance(seq, list) or not seq:
        return False, evidence(reason="collapse_sequence_absent",
                               detail="a CTC decode with no declared collapse is not a decode")
    seq = [str(step) for step in seq]
    merge, remove = COLLAPSE_ORDER
    if merge not in seq or remove not in seq:
        return False, evidence(reason="collapse_incomplete", collapse=seq,
                               required=list(COLLAPSE_ORDER))
    ok = seq.index(merge) < seq.index(remove)
    return ok, evidence(collapse=seq, merge_repeats_at=seq.index(merge),
                        remove_blank_at=seq.index(remove),
                        detail="removing blanks first merges the two l of hello across the blank "
                               "frame the model emits to hold them apart",
                        reason=None if ok else "blank_removed_before_repeats_merged")
''',

    "blank_index_reserved_outside_the_label_vocabulary": '''
    dec = decode_block()
    if dec is None:
        return False, evidence(reason="decode_block_absent")
    blank = dec.get("blank_index")
    if isinstance(blank, bool) or not isinstance(blank, int):
        return False, evidence(reason="blank_index_undeclared", declared=blank)
    vocab = label_vocabulary()
    if vocab is None:
        return False, evidence(reason="label_vocabulary_absent", path=LABEL_VOCABULARY,
                               detail="the permuted vocabulary has not landed, so the reservation "
                                      "cannot be proved and is not assumed")
    taken = vocabulary_indices(vocab)
    observed = run_record().get("observed_training_blank_index")
    aliased = blank in taken
    if aliased:
        reason = "blank_aliases_a_label"
    elif isinstance(observed, bool) or not isinstance(observed, int):
        reason = "training_blank_index_unrecorded"
    elif observed != blank:
        reason = "blank_index_moved_between_training_and_export"
    else:
        reason = None
    return reason is None, evidence(blank_index=blank, aliases_a_character=aliased,
                                    training_blank_index=observed, vocabulary_size=len(taken),
                                    reason=reason)
''',

    "chk_param_bytes": '''
    param = parameter_file_path()
    if param is None:
        return False, evidence(reason="manifest_names_no_parameter_file")
    if not os.path.exists(param):
        return False, evidence(reason="parameter_file_absent", path=param)
    measured = os.path.getsize(param)
    declared = (manifest() or {}).get("parameter_bytes")
    ok = measured <= PARAM_BYTE_CEILING
    return ok, evidence(measured_bytes=measured, ceiling_bytes=PARAM_BYTE_CEILING,
                        declared_bytes=declared,
                        declaration_disagrees=(declared is not None and declared != measured),
                        detail="counted off the delivered file, including the in-export mel "
                               "filterbank, never off the declared field",
                        reason=None if ok else "PARAM_BYTES_EXCEEDED")
''',

    "declared_layer_lookahead_sums_within_the_right_context_bound": '''
    doc = manifest()
    if doc is None:
        return False, evidence(reason="manifest_unreadable")
    look = doc.get("layer_right_context_frames")
    valid = (isinstance(look, list) and bool(look)
             and all(isinstance(v, int) and not isinstance(v, bool) and v >= 0 for v in look))
    if not valid:
        return False, evidence(reason="layer_lookahead_undeclared", declared=look,
                               detail="right context is a sum down the stack, so it cannot be "
                                      "declared as a single number for the whole encoder")
    total = sum(look)
    shift = (declared_frontend() or {}).get("frame_shift_ms")
    span_ms = None
    if isinstance(shift, (int, float)) and not isinstance(shift, bool):
        span_ms = round(total * float(shift), 3)
    observed = run_record().get("observed_right_context_frames")
    within = total <= RIGHT_CONTEXT_FRAMES and (span_ms is None or span_ms <= RIGHT_CONTEXT_MS)
    if not within:
        reason = "right_context_sum_exceeds_bound"
    elif isinstance(observed, bool) or not isinstance(observed, int):
        reason = "observed_right_context_unrecorded"
    elif observed != total:
        reason = "declared_right_context_is_not_the_observed_one"
    else:
        reason = None
    return reason is None, evidence(per_layer_frames=look, declared_sum_frames=total,
                                    bound_frames=RIGHT_CONTEXT_FRAMES, declared_ms=span_ms,
                                    bound_ms=RIGHT_CONTEXT_MS, observed_frames=observed,
                                    reason=reason)
''',

    "chk_causality": '''
    probes = run_record().get("causality_probe")
    if not isinstance(probes, list) or not probes:
        return False, evidence(target="exported_recognizer", reason="causality_probe_unrecorded",
                               detail="an unprobed export is unproved, never proved")
    seen = {}
    for entry in probes:
        if not isinstance(entry, dict) or "offset_frames" not in entry:
            return False, evidence(target="exported_recognizer",
                                   reason="causality_probe_malformed", entry=entry)
        seen[entry["offset_frames"]] = bool(entry.get("prefix_bit_identical"))
    expected = probe_offsets()
    uncovered = sorted(set(expected) - set(seen)) if expected is not None else []
    violated = sorted(off for off, identical in seen.items() if not identical)
    diverged = next((e.get("first_divergent_frame") for e in probes
                     if not e.get("prefix_bit_identical")), None)
    ok = not violated and not uncovered
    return ok, evidence(target="exported_recognizer", offsets_probed=sorted(seen),
                        offsets_expected=expected, offsets_uncovered=uncovered,
                        offsets_violated=violated, first_divergent_frame=diverged,
                        detail="every output frame at or before the offset must return "
                               "bit-identical when the audio beyond the right-context bound is "
                               "replaced; this is an exact predicate with no noise band",
                        reason=None if ok else "NONCAUSAL_CONTEXT")
''',

    "export_frontend_constants_equal_the_training_frontend_constants": '''
    declared = declared_frontend()
    if declared is None:
        return False, evidence(target="run_record", reason="export_frontend_undeclared")
    observed = run_record().get("training_frontend_constants")
    if not isinstance(observed, dict):
        return False, evidence(target="run_record", reason="training_frontend_unobserved",
                               detail="an unobserved training front end cannot be compared, and "
                                      "an uncompared one is exactly this failure mode")
    divergent = {}
    for field in FRONTEND_FIELDS:
        a, b = declared.get(field), observed.get(field)
        if a is None or b is None or not numbers_equal(a, b):
            divergent[field] = {"export": a, "training": b}
    ok = not divergent
    return ok, evidence(target="run_record", fields=list(FRONTEND_FIELDS), divergent=divergent,
                        detail="a 10 ms training shift reimplemented at 12.5 ms inside the export "
                               "raises nothing, exports cleanly and roughly doubles graded WER",
                        reason=None if ok else "frontend_constants_diverged")
''',

    "training_transcripts_digest_to_the_shipped_permuted_bytes": '''
    used = run_record().get("training_transcript_digests")
    if not isinstance(used, list) or not used:
        return False, evidence(target="run_record", reason="supervision_undigested",
                               detail="the harness recorded no transcript bytes read as "
                                      "supervision, so the source of the labels is unproved")
    pinned = shipped_transcript_digests()
    if pinned is None:
        return False, evidence(target="run_record", reason="shipped_transcript_table_absent",
                               path=SHIPPED_TRANSCRIPT_DIGESTS)
    foreign = sorted({str(d) for d in used} - {str(d) for d in pinned})
    ok = not foreign
    return ok, evidence(target="run_record", supervision_digests=len(used),
                        pinned_digests=len(pinned), foreign_digest_count=len(foreign),
                        foreign_digests=foreign[:8],
                        detail="pseudo-transcripts from a teacher downloaded during the "
                               "open-egress phase digest to nothing in the pinned table",
                        reason=None if ok else "EXTERNAL_SUPERVISION")
''',

    "no_graded_writes": '''
    rec = run_record()
    if "guarded_paths_touched" not in rec:
        return False, evidence(target="run_record", reason="guarded_path_record_absent",
                               detail="an unrecorded write set is not an empty one")
    touched = rec.get("guarded_paths_touched") or []
    hits = sorted(str(p) for p in touched
                  if any(str(p).startswith(prefix) for prefix in GUARDED))
    ok = not hits
    return ok, evidence(target="run_record", guarded_prefixes=list(GUARDED), touched=hits,
                        detail="both sibling LibriSpeech partitions, the Common Voice shard, the "
                               "probe offsets and the pinned normalizer all live under tests/heldout/",
                        reason=None if ok else "GRADING_TREE_WRITE")
''',

    "chk_heldout_digest": '''
    pinned = heldout_json(HELDOUT_DIGEST_TABLE)
    if not isinstance(pinned, dict) or not pinned:
        return False, evidence(target="run_record", reason="heldout_digest_table_absent",
                               path=os.path.join("tests", "heldout", HELDOUT_DIGEST_TABLE),
                               detail="an absent table is reported, never read as an empty one "
                                      "that trivially passes")
    observed = run_record().get("heldout_digests")
    missing, mismatched = [], []
    for rel in sorted(pinned):
        path = heldout(rel)
        if not os.path.exists(path):
            missing.append(rel)
        elif sha256_file(path) != pinned[rel]:
            mismatched.append(rel)
    disagreed = ([] if not isinstance(observed, dict)
                 else sorted(rel for rel in pinned if observed.get(rel) != pinned[rel]))
    ok = (not missing and not mismatched and isinstance(observed, dict) and not disagreed)
    return ok, evidence(target="run_record", pinned_entries=len(pinned), missing=missing,
                        mismatched=mismatched, harness_disagreed=disagreed,
                        harness_recorded=isinstance(observed, dict),
                        reason=None if ok else "HELDOUT_DIGEST_MISMATCH")
''',

    "one_export_decodes_both_corpora": '''
    ctx = run_record().get("decode_context")
    if not isinstance(ctx, dict):
        return False, evidence(target="exported_recognizer", reason="decode_context_unrecorded")
    read_speech, volunteer = ctx.get(LS_A), ctx.get(CV)
    if not isinstance(read_speech, dict) or not isinstance(volunteer, dict):
        return False, evidence(target="exported_recognizer", reason="decode_context_incomplete",
                               shards_recorded=sorted(ctx))
    divergent = {}
    if read_speech.get("parameter_sha256") != volunteer.get("parameter_sha256"):
        divergent["parameter_sha256"] = {LS_A: read_speech.get("parameter_sha256"),
                                         CV: volunteer.get("parameter_sha256")}
    for field in FRONTEND_FIELDS:
        if not numbers_equal(read_speech.get(field), volunteer.get(field)):
            divergent[field] = {LS_A: read_speech.get(field), CV: volunteer.get(field)}
    ok = not divergent and read_speech.get("parameter_sha256") is not None
    return ok, evidence(target="exported_recognizer", divergent=divergent,
                        parameter_sha256=read_speech.get("parameter_sha256"),
                        detail="a per-corpus branch or a second parameter file is two "
                               "recognizers, and the reward is a product over the outputs of one",
                        reason=None if ok else "two_recognizers_were_graded_as_one")
''',

    "chk_shard_gap": '''
    a, b = wer_value(LS_A), wer_value(LS_B)
    if a is None or b is None:
        return False, evidence(target="graded_hypotheses", reason="sibling_shard_unmeasured",
                               wer_private_a=a, wer_private_b=b)
    gap = abs(a - b)
    ok = gap <= SIBLING_GAP_BOUND
    return ok, evidence(target="graded_hypotheses", wer_private_a=a, wer_private_b=b,
                        gap=round(gap, 6), bound=SIBLING_GAP_BOUND,
                        detail="the four pinned partitions are maximally disjoint in accent, "
                               "gender balance and recording condition, and the pair rotates",
                        reason=None if ok else "SHARD_GAP_EXCEEDED")
''',

    "chk_transfer_null": '''
    perm = run_record().get("second_permutation")
    if not isinstance(perm, dict):
        return False, evidence(target="exported_recognizer", reason="second_permutation_unrun")
    first, second = perm.get("r_det_first"), perm.get("r_det_second")
    numeric = [v for v in (first, second)
               if isinstance(v, (int, float)) and not isinstance(v, bool)]
    if len(numeric) != 2:
        return False, evidence(target="exported_recognizer",
                               reason="second_permutation_incomplete",
                               r_det_first=first, r_det_second=second)
    shift = abs(float(first) - float(second))
    ok = shift <= PERMUTATION_TAU
    return ok, evidence(target="exported_recognizer", r_det_first=first, r_det_second=second,
                        reward_shift=round(shift, 6), tau=PERMUTATION_TAU,
                        detail="a public output vocabulary has never seen this bijection, so a "
                               "downloaded head moves far more than tau",
                        reason=None if ok else "PRECOMPUTED_PARAMS")
''',

    "normalization_statistics_reestimated_after_the_last_parameter_edit": '''
    seq = run_record().get("observed_op_sequence")
    if not isinstance(seq, list) or not seq:
        return False, evidence(target="run_record", reason="op_sequence_unobserved")
    seq = [str(op) for op in seq]
    edits = [i for i, op in enumerate(seq) if op in PARAMETER_EDIT_OPS]
    stats = [i for i, op in enumerate(seq) if op == STATISTICS_OP]
    if not edits:
        reason = None
    elif not stats:
        reason = "statistics_never_reestimated_after_pruning"
    elif max(stats) < max(edits):
        reason = "statistics_stale_after_the_last_parameter_edit"
    else:
        reason = None
    return reason is None, evidence(target="run_record", parameter_edit_ops_at=edits,
                                    statistics_reestimation_at=stats,
                                    last_parameter_edit_at=max(edits) if edits else None,
                                    detail="pruning shifts every downstream activation "
                                           "distribution while the stored running mean and "
                                           "variance keep describing the dense model",
                                    reason=reason)
''',

    "budget_timer_opens_at_first_data_touch": '''
    rec = run_record()
    start, done = rec.get("first_data_touch_epoch_s"), rec.get("export_complete_epoch_s")
    if isinstance(start, bool) or not isinstance(start, (int, float)):
        return False, evidence(target="run_record", reason="first_data_touch_unrecorded",
                               detail="the zero of this clock is the first read under "
                                      "environment/data, not process start")
    if isinstance(done, bool) or not isinstance(done, (int, float)):
        return False, evidence(target="run_record", reason="export_never_completed",
                               detail="an export that first exists after the kill is not an export")
    elapsed = float(done) - float(start)
    if elapsed <= 0.0:
        reason = "export_precedes_first_data_touch"
    elif elapsed > BUDGET_SECONDS:
        reason = "budget_exceeded_before_export_completed"
    else:
        reason = None
    return reason is None, evidence(target="run_record", first_data_touch=start,
                                    export_complete=done, elapsed_seconds=round(elapsed, 3),
                                    budget_seconds=BUDGET_SECONDS, reason=reason)
''',

    "chk_attempt_order": '''
    attempts = run_record().get("attempts")
    if not isinstance(attempts, list) or not attempts:
        return False, evidence(target="run_record", reason="attempts_unrecorded")
    indices = [a.get("index") if isinstance(a, dict) else None for a in attempts]
    typed = all(isinstance(i, int) and not isinstance(i, bool) for i in indices)
    ordered = typed and all(b > a for a, b in zip(indices, indices[1:]))
    without_pair = []
    for entry, index in zip(attempts[1:], indices[1:]):
        prior = entry.get("prior_attempt_summary") if isinstance(entry, dict) else None
        carried = (isinstance(prior, dict)
                   and isinstance(prior.get("wer_librispeech"), (int, float))
                   and isinstance(prior.get("wer_commonvoice"), (int, float)))
        if not carried:
            without_pair.append(index)
    if not ordered:
        reason = "attempt_indices_not_strictly_increasing"
    elif without_pair:
        reason = "prior_wer_pair_not_carried"
    else:
        reason = None
    return reason is None, evidence(target="run_record", attempt_indices=indices,
                                    attempts_without_prior_pair=without_pair,
                                    detail="the ranking taken at a fifth of the budget inverts by "
                                           "the full budget, so the prior pair is what an attempt "
                                           "needs in order to see the inversion",
                                    reason=reason)
''',

    "chk_log_fidelity": '''
    rec = run_record()
    claim = last_reward_log_record()
    if claim is None:
        return False, evidence(target="run_record", reason="reward_log_unreadable",
                               path=rec.get("reward_log"))
    measured_ls, measured_cv = wer_value(LS_A), wer_value(CV)
    start, done = rec.get("first_data_touch_epoch_s"), rec.get("export_complete_epoch_s")
    if measured_ls is None or measured_cv is None:
        return False, evidence(target="run_record", reason="harness_wer_unmeasured")
    if not all(isinstance(v, (int, float)) and not isinstance(v, bool) for v in (start, done)):
        return False, evidence(target="run_record", reason="harness_elapsed_unmeasured")
    measured_elapsed = float(done) - float(start)
    claimed = [claim.get("wer_librispeech"), claim.get("wer_commonvoice"),
               claim.get("elapsed_seconds")]
    if not all(isinstance(v, (int, float)) and not isinstance(v, bool) for v in claimed):
        return False, evidence(target="run_record", reason="reward_log_incomplete", record=claim)
    gap_ls = abs(float(claimed[0]) - measured_ls)
    gap_cv = abs(float(claimed[1]) - measured_cv)
    gap_s = (abs(float(claimed[2]) - measured_elapsed) / measured_elapsed
             if measured_elapsed > 0 else 1.0)
    ok = (gap_ls <= LOG_WER_TOLERANCE and gap_cv <= LOG_WER_TOLERANCE
          and gap_s <= LOG_ELAPSED_TOLERANCE)
    return ok, evidence(target="run_record", claimed_wer_librispeech=claimed[0],
                        measured_wer_librispeech=measured_ls, wer_librispeech_gap=round(gap_ls, 6),
                        claimed_wer_commonvoice=claimed[1], measured_wer_commonvoice=measured_cv,
                        wer_commonvoice_gap=round(gap_cv, 6), wer_tolerance=LOG_WER_TOLERANCE,
                        claimed_seconds=claimed[2], measured_seconds=round(measured_elapsed, 3),
                        elapsed_relative_gap=round(gap_s, 6),
                        elapsed_tolerance=LOG_ELAPSED_TOLERANCE,
                        reason=None if ok else "LOG_DIVERGENCE")
''',

    "replay_reproduces_export_and_greedy_hypotheses": '''
    rec = run_record()
    first, again = rec.get("first_run_digests"), rec.get("replay_digests")
    if not isinstance(first, dict) or not isinstance(again, dict):
        return False, evidence(target="run_record", reason="replay_unavailable",
                               first_run_recorded=isinstance(first, dict),
                               replay_recorded=isinstance(again, dict))
    diverged = sorted(key for key in REPLAY_DIGEST_KEYS
                      if first.get(key) is None or first.get(key) != again.get(key))
    ok = not diverged
    return ok, evidence(target="run_record", digests=list(REPLAY_DIGEST_KEYS), diverged=diverged,
                        first_run={k: first.get(k) for k in REPLAY_DIGEST_KEYS},
                        replay={k: again.get(k) for k in REPLAY_DIGEST_KEYS},
                        detail="greedy decoding is a deterministic function of the export, so a "
                               "hypothesis digest that moves while the parameter digest holds "
                               "means the decode path carries a random source",
                        reason=None if ok else "EXPORT_NONDETERMINISTIC")
''',

    "wer_divides_edit_operations_by_reference_words": '''
    rows = run_record().get("wer")
    if not isinstance(rows, dict) or not rows:
        return False, evidence(target="graded_hypotheses", reason="edit_counts_unrecorded",
                               detail="WER without its edit-operation counts cannot be checked "
                                      "for the denominator it used")
    divergent, recomputed = {}, {}
    for shard in SHARDS:
        row = rows.get(shard)
        if not isinstance(row, dict) or any(field not in row for field in WER_FIELDS):
            divergent[shard] = "edit_counts_incomplete"
            continue
        words = row["reference_words"]
        if isinstance(words, bool) or not isinstance(words, int) or words <= 0:
            divergent[shard] = "reference_words_not_a_positive_count"
            continue
        counts = [row["substitutions"], row["deletions"], row["insertions"]]
        if not all(isinstance(v, int) and not isinstance(v, bool) and v >= 0 for v in counts):
            divergent[shard] = "edit_operations_not_counts"
            continue
        derived = sum(counts) / float(words)
        recomputed[shard] = round(derived, 9)
        if abs(derived - float(row["wer"])) > WER_TOLERANCE:
            divergent[shard] = "recorded_wer_is_not_S_D_I_over_reference_words"
    ok = not divergent
    return ok, evidence(target="graded_hypotheses", shards=list(SHARDS),
                        recomputed=recomputed, divergent=divergent, tolerance=WER_TOLERANCE,
                        detail="the denominator is the reference word count, never the hypothesis "
                               "length and never the longer of the two, so a WER above 1.0 is "
                               "legal and a value clipped into the unit interval is not",
                        reason=None if ok else "wer_denominator_is_not_reference_words")
''',

    "greedy_path_is_not_all_blank": '''
    rec = run_record()
    fraction = rec.get("non_blank_frame_fraction_private_a")
    non_empty = rec.get("non_empty_hypothesis_count")
    total = rec.get("hypothesis_count")
    numeric = (isinstance(fraction, (int, float)) and not isinstance(fraction, bool)
               and isinstance(non_empty, int) and not isinstance(non_empty, bool)
               and isinstance(total, int) and not isinstance(total, bool))
    if not numeric:
        return False, evidence(target="graded_hypotheses", reason="greedy_path_unrecorded",
                               non_blank_frame_fraction=fraction,
                               non_empty_hypotheses=non_empty, hypotheses=total)
    ok = float(fraction) > 0.0 and non_empty > 0 and total > 0
    return ok, evidence(target="graded_hypotheses", non_blank_frame_fraction=fraction,
                        non_empty_hypotheses=non_empty, hypotheses=total,
                        detail="a model still in the CTC alignment plateau puts all its mass on "
                               "blank, decodes every utterance to the empty string and reaches "
                               "WER exactly 1.000 on both shards",
                        reason=None if ok else "blank_only_greedy_path")
''',

    "word_error_rate_pair_on_both_private_shards_ramp": '''
    # require_measured FIRST, before any hypothesis is read. Reading first lets an absent export
    # report as an ordinary failure, which makes the verifier say gradeable=true with r_det=0.0 --
    # collapsing "this slot is not yet measurable" into "the agent scored zero".
    # seed/build/freeze_batch.py refuses to freeze a bundle that does this.
    c = require_measured("floor", "knee", "dichotomizing_threshold")
    quality = measure()
    span = c["knee"] - c["floor"]
    s = 0.0 if span <= 0 else max(0.0, min(1.0, (quality - c["floor"]) / span))
    return quality >= c["dichotomizing_threshold"], evidence(
        target="graded_hypotheses", binding_quality=quality,
        wer_librispeech=wer_value(LS_A), wer_commonvoice=wer_value(CV),
        binding_corpus=(LS_A if (wer_value(LS_A) or 1.0) >= (wer_value(CV) or 1.0) else CV),
        floor=c["floor"], knee=c["knee"], s_outcome=s)
''',
}


def build_tests(g, prelude, bodies):
    """Assemble the compiled-check module. kind carries the item's own dimension."""
    chunks = [prelude]
    for raw in sorted(g["items"], key=lambda i: i["id"]):
        if raw["mode"] != "compiled":
            continue
        chunks.append('\n\n@check(id="%s", weight=%d, knockout=%s, kind="%s")\ndef test_%s():\n%s\n'
                      % (raw["id"], raw["weight"], raw["knockout"], raw["dimension"], raw["id"],
                         bodies[raw["id"]].strip("\n")))
    return "".join(chunks)


def build_truth(g, title):
    """Render solution/TRUTH.md from the frozen literals of solution/grounding.yaml."""
    n = g["truth_narrative"]
    lines = [title, "", "GENERATED SECTION. DO NOT HAND-EDIT.", "", n["opening"], "",
             "## The single most important insight", "", n["insight"], "",
             "## The ideal solve, step by step", ""]
    for i, step in enumerate(n["steps"], 1):
        lines += ["%d. **%s** %s" % (i, step["heading"], step["paragraph"]), ""]
    lines += ["## Traps that catch agents that are not thinking carefully", ""]
    lines += ["- " + t for t in n["traps"]]
    lines += ["", "---", "", "## Contract record (annex; not part of the narrative body)", "",
              "Retained under FORGE.md item 10e and Phase 2 item 7, which require this file to "
              "carry the ordered path through instruction.md with each satisfied checker "
              "identifier, and each rejected route bound to a measured known-wrong control. "
              "standards/truth-md-authoring-v1.md section 3 admits no fifth section, so this "
              "annex is a recorded deviation rather than an omission.", "", g["truth_annex"], ""]
    return "\n".join(lines) + "\n"


def build_rubrics(g, item_keys):
    """The 9g rubric carrier. The item schema is CLOSED at eight keys, so item 10f's outcome
    classification rides as a greppable prefix of the judgment rather than as a ninth key."""
    items = []
    for raw in g["items"]:
        item = {k: raw[k] for k in item_keys}
        item["judgment"] = "%s: %s" % (raw["outcome_class"], raw["judgment"])
        items.append(item)
    compiled = sum(i["weight"] for i in items if i["mode"] == "compiled")
    total = sum(i["weight"] for i in items)
    return {"$schema": "forge.rubric/v1",
            "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
            "generator": "solution/recompute.py",
            "compilation_floor": g["compilation_floor"],
            "compiled_weight_share": round(compiled / total, 6) if total else 0.0,
            "evaluation_target_vocabulary": sorted(g["evaluation_target_vocabulary"]),
            "items": sorted(items, key=lambda i: i["id"])}


def build_provenance(g, identity):
    p = g["provenance"]
    out = {
        "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
        "generator": "solution/recompute.py from solution/grounding.yaml",
        "schema_version": "1.0",
        "slot_id": g["slot_id"],
        "identity": identity,
        "corpus": p["corpus"],
        "anchors": p["anchors"],
        "shards": p["shards"],
        "narrative": p["narrative"],
        "supersedes": p["supersedes"],
        "upstream_provenance": p["upstream_record"],
        "reward_composition": p["reward_composition"],
        "screening_interval_days": p["screening_interval_days"],
        "screening_detector_version": p["screening_detector_version"],
        "derivation_instant": p["derivation_instant"],
        "screening_roots": p["screening_roots"],
        "empty_submission_result": p["empty_submission_result"],
        "resolved_closure": p["resolved_closure"],
        "applicability": p["applicability"],
        "measurement_tier": g["measurement_tier"],
        "gradeable": g["gradeable"],
        "knee_anchor_status": g["knee_anchor_status"],
        "graded_object": "a streaming CTC acoustic encoder, delivered as an export directory the "
                         "verifier loads and runs over private audio; the log-mel front end is "
                         "inside the export and the decode is greedy",
        "corpus_layout_status": g["corpus_layout"]["status"],
        "timed_axis": True,
    }
    out.update(read_screening(HERE))
    return out


def validate(grounding):
    """Refuse on a malformed derivation source rather than emitting a checker from one.

    The family validator that stood here asserted one thing -- that some item evaluated the run
    record -- which was true of a bundle whose every obligation item graded nothing. These are the
    invariants the emitted checker actually depends on.
    """
    problems = []
    items = grounding.get("items") or []
    if not items:
        problems.append("no items to compile")
    seen = set()
    for item in items:
        iid = item.get("id", "<unnamed>")
        if iid in seen:
            problems.append("duplicate item id %r" % iid)
        seen.add(iid)
        if set(item) != ITEM_SCHEMA:
            problems.append("item %r does not carry the closed schema: %s"
                            % (iid, sorted(set(item) ^ ITEM_SCHEMA)))
            continue
        if item["outcome_class"] not in OUTCOME_CLASSES:
            problems.append("item %r has outcome_class %r" % (iid, item["outcome_class"]))
        if item["evaluation_target"] not in grounding["evaluation_target_vocabulary"]:
            problems.append("item %r evaluates %r, which the vocabulary does not admit"
                            % (iid, item["evaluation_target"]))
        if not isinstance(item["weight"], int) or item["weight"] <= 0:
            problems.append("item %r carries weight %r" % (iid, item["weight"]))

    outcome = [i["id"] for i in items if i.get("dimension") == "outcome"]
    if len(outcome) != 1:
        problems.append("expected exactly one outcome item, found %r" % outcome)

    # A timed axis is graded on harness measurement, never on a self-reported duration.
    targets = {i.get("evaluation_target") for i in items}
    if "run_record" not in targets:
        problems.append("a timed slot must grade against the harness run record")

    for name in RAMP:
        if grounding["constants"].get(name) is not None:
            problems.append("constant %r is authored at Phase 0; it is measured, not authored"
                            % name)

    if grounding["deliverable"].get("kind") != "streaming_ctc_export":
        problems.append("the graded deliverable of this slot is a loadable streaming export, "
                        "not %r" % grounding["deliverable"].get("kind"))

    layout = grounding.get("corpus_layout") or {}
    bounds = layout.get("bounds") or {}

    # The frame count and the millisecond bound must be the SAME bound. If they drift apart, a
    # submission is measured against whichever of the two the check happens to read.
    frames, shift, span = (bounds.get("right_context_frames"), bounds.get("frame_shift_ms"),
                           bounds.get("right_context_ms"))
    if not all(isinstance(v, (int, float)) for v in (frames, shift, span)):
        problems.append("the right-context bound is not fully declared in corpus_layout bounds")
    elif abs(frames * shift - span) > 1e-9:
        problems.append("right_context_frames %r at frame_shift_ms %r is %r ms, not the declared "
                        "%r ms" % (frames, shift, frames * shift, span))

    envelope = set(layout.get("operator_envelope") or [])
    stray = sorted(set(layout.get("required_frontend_ops") or []) - envelope)
    if stray:
        problems.append("required_frontend_ops names %s, which the operator envelope does not"
                        % stray)
    if not envelope:
        problems.append("the operator envelope is empty, so no export could ever be refused")

    collapse = layout.get("collapse_order") or []
    if len(collapse) != 2 or len(set(collapse)) != 2:
        problems.append("collapse_order must name two distinct CTC steps, not %r" % (collapse,))

    if layout.get("statistics_reestimation_op") in set(layout.get("parameter_edit_ops") or []):
        problems.append("the statistics re-estimation op is also listed as a parameter edit op, "
                        "so the ordering check would compare an op against itself")

    for key in ("graded_shards", "wer_fields", "frontend_fields", "guarded_prefixes",
                "forbidden_decode_symbols"):
        if not layout.get(key):
            problems.append("corpus_layout %s is empty" % key)

    for key in ("sibling_shard_gap_bound", "permutation_reward_tau",
                "log_elapsed_tolerance_fraction"):
        value = bounds.get(key)
        if not isinstance(value, float) or not 0.0 < value <= 1.0:
            problems.append("corpus_layout bound %s is %r, which is not a fraction in (0,1]"
                            % (key, value))
    return problems


def main():
    g = load_grounding()
    # The validator runs FIRST and refuses rather than emitting: a generator that writes a
    # carrier it knows is malformed hands the drift check a moving target.
    problems = validate(g)
    if problems:
        raise SystemExit("A5-03 grounding is not well-formed: " + "; ".join(problems))

    layout = g["corpus_layout"]
    bounds = layout["bounds"]
    outcome_id = [i["id"] for i in g["items"] if i["dimension"] == "outcome"][0]
    subst = {
        "slot_id": SLOT_ID,
        "outcome_id": outcome_id,
        "log_check": "chk_log_fidelity",
        "export_dir": g["deliverable"]["path"],
        "manifest_name": g["deliverable"]["manifest_name"],
        "manifest_keys": tuple(sorted(g["deliverable"]["manifest_keys"])),
        "train_entrypoint": layout["train_entrypoint"],
        "run_record": layout["run_record"],
        "guarded": tuple(layout["guarded_prefixes"]),
        "operator_envelope": tuple(layout["operator_envelope"]),
        "required_frontend_ops": tuple(layout["required_frontend_ops"]),
        "forbidden_decode_symbols": tuple(layout["forbidden_decode_symbols"]),
        "collapse_order": tuple(layout["collapse_order"]),
        "parameter_edit_ops": tuple(layout["parameter_edit_ops"]),
        "statistics_op": layout["statistics_reestimation_op"],
        "frontend_fields": tuple(layout["frontend_fields"]),
        "label_vocabulary": layout["label_vocabulary"],
        "graded_shards": tuple(layout["graded_shards"]),
        "librispeech_a": layout["graded_shards"][0],
        "librispeech_b": layout["graded_shards"][1],
        "commonvoice": layout["graded_shards"][2],
        "wer_fields": tuple(layout["wer_fields"]),
        "heldout_digest_table": os.path.basename(layout["heldout_digest_table"]),
        "probe_offsets": os.path.basename(layout["causality_probe_offsets"]),
        "shipped_transcript_digests": os.path.basename(layout["shipped_transcript_digests"]),
        "right_context_ms": bounds["right_context_ms"],
        "right_context_frames": bounds["right_context_frames"],
        "frame_shift_ms": bounds["frame_shift_ms"],
        "parameter_byte_ceiling": bounds["parameter_byte_ceiling"],
        "budget_seconds": bounds["budget_seconds"],
        "sibling_shard_gap_bound": bounds["sibling_shard_gap_bound"],
        "permutation_reward_tau": bounds["permutation_reward_tau"],
        "wer_recomputation_tolerance": bounds["wer_recomputation_tolerance"],
        "log_wer_tolerance": bounds["log_wer_tolerance"],
        "log_elapsed_tolerance_fraction": bounds["log_elapsed_tolerance_fraction"],
    }

    # EVERY compiled item carries a written body. The generic obligation lookup that used to
    # stand here read run_record()["obligations"][<ID>], a key nothing writes, so any item
    # falling through to it graded nothing at all and said so in no report. Refuse instead.
    bodies = dict(BODIES)
    for it in g["items"]:
        if it["mode"] == "compiled" and it["id"] not in bodies:
            raise SystemExit("A5-03: no body written for compiled item %r; the generator refuses "
                             "rather than emitting a check that consults nothing" % it["id"])

    # The outcome check must SAY the slot is unmeasurable before it reads anything at all. If it
    # reads first, an absent export reports as an ordinary failure and the verifier then says
    # gradeable=true with r_det=0.0, collapsing two different claims into one.
    statements = [ln.strip() for ln in bodies[outcome_id].splitlines()
                  if ln.strip() and not ln.strip().startswith("#")]
    if not statements or statements[0] != REQUIRE_FIRST:
        raise SystemExit("A5-03: %r must call require_measured as its first statement, before it "
                         "reads any hypothesis" % outcome_id)

    tests_dir = os.path.join(BUNDLE, "tests")
    os.makedirs(tests_dir, exist_ok=True)

    # solution/TRUTH.md and solution/rubrics.json are PRIVATE_CARRIERS: seed/identity.py plants a
    # canary block into them at freeze, and canary normalisation is what keeps planting from
    # moving identity. A generator that rewrote them plainly would DROP the planted tripwire, and
    # the next content_hash would differ from the frozen one. So the planted block is carried
    # across the regeneration rather than recreated. Compute the new text BEFORE opening for
    # write: open(p, "w") truncates before its body runs.
    truth_path = os.path.join(HERE, "TRUTH.md")
    truth = build_truth(g, TITLE).rstrip("\n") + "\n"
    keep = None
    if os.path.exists(truth_path):
        import re as _re
        m = _re.search(r"<!-- AELLO-CANARY-BLOCK.*?-->\n?", open(truth_path).read(), _re.S)
        keep = m.group(0) if m else None
    with open(truth_path, "w") as fh:
        fh.write(truth + ("\n" + keep if keep else ""))

    rub_path = os.path.join(HERE, "rubrics.json")
    rub = build_rubrics(g, ITEM_KEYS)
    if os.path.exists(rub_path):
        try:
            prev = json.load(open(rub_path))
            if "canary" in prev:
                rub["canary"] = prev["canary"]
        except Exception:
            pass
    with open(rub_path, "w") as fh:
        json.dump(rub, fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "rubrics.json"), "w") as fh:
        json.dump(build_rubrics(g, ITEM_KEYS), fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "test_output.py"), "w") as fh:
        # The tail arrives FINAL and UNSUBSTITUTED. It carries percent formatting of its own
        # inside the emitted helpers, so formatting it a second time here raised TypeError on
        # the first slot that carried one. Only the prelude is substituted.
        fh.write(build_tests(g, PRELUDE % subst, bodies) + TAIL)
    with open(os.path.join(tests_dir, "constants.json"), "w") as fh:
        json.dump(g["constants"], fh, indent=1, sort_keys=True)
        fh.write("\n")
    # ORDER MATTERS. `with open(path, "w")` truncates BEFORE its body's arguments are evaluated,
    # so calling read_identity() inside the with-statement reads the file this line just emptied
    # and writes nulls over the frozen identity. Read first, then open.
    prov = build_provenance(g, read_identity(HERE))
    with open(os.path.join(HERE, "provenance.yaml"), "w") as fh:
        # MATCH seed/build/screen_bind.py and the frozen generators exactly: sort_keys=True,
        # default_flow_style=False, width=100. The screen writes this carrier after the freeze,
        # so a generator using a different dump convention reorders the keys on the next
        # regeneration and reports as drift even though no value changed.
        yaml.safe_dump(prov, fh, sort_keys=True, default_flow_style=False, width=100,
                       allow_unicode=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
