"""Derivation for AELLO-C8-S2: every canonical artifact descends from solution/grounding.yaml.

The graded object here is a PROGRAM the verifier executes once per graded configuration, plus a
2,048-byte store that survives between those runs, so every compiled check below is about a
program, a memory channel or a host measurement rather than about the contents of a submitted
array. The parameters they read -- the configuration roster, the attempt schedule, the closed
carry schema and its per-field tolerances, the eight-attempt time to live, the timer epsilon, the
source caps and the guarded paths -- live in grounding.yaml's corpus_layout block and are
substituted into the emitted module, so no check carries a bound this file's reader cannot find in
the grounding.

Wired through seed/build/generator_common.py, which carries the five slot-agnostic functions
verified byte-for-byte against the three frozen generators. build_provenance stays here, per
family, for the reason recorded in that module.
"""
import json
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
# generator_common.py is VENDORED beside this file, not reached for outside the bundle. A staged
# tree could resolve seed/stage/<slug>/../../build; a DELIVERED tree at dataset/<uuid>/ cannot,
# and reaching outside would make the delivered bundle non-self-contained -- it would import in
# the stage and fail everywhere it actually ships.

SLOT_ID = 'AELLO-C8-S2'
TITLE = "# AELLO-C8-S2 -- what this task actually tests"
ITEM_KEYS = ('id', 'dimension', 'weight', 'evaluation_target', 'criterion', 'judgment', 'knockout',
             'mode')
ITEM_SCHEMA = frozenset(ITEM_KEYS + ('outcome_class',))
OUTCOME_CLASSES = frozenset(("EFFECT", "INVARIANT", "ABSENCE", "VALUE"))
RAMP = ("floor", "knee", "dichotomizing_threshold", "reward_gate_pass_threshold")
REQUIRE_FIRST = 'c = require_measured("floor", "knee", "dichotomizing_threshold")'
CARRY_SCHEMA_KEYS = ("max_bytes", "scalar_fields", "src_field", "src_observed", "src_predicted",
                     "optional_tag_field", "tag_max_bytes", "forbidden_fields", "stamp_field")
SCHEDULE_KEYS = ("attempts_total", "graded_per_attempt", "final_attempt",
                 "final_attempt_configurations", "stride", "offsets", "modulus")


def read_identity(here):
    """Identity is an INPUT: the freeze computes it over the hashed tree and binds it into the
    carrier, which is hash-excluded, so reading it back keeps generation acyclic."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        if isinstance(doc.get("identity"), dict):
            return doc["identity"]
    return {"canonical_content_hash": None, "uuid": None,
            "normalization_domain": "aello.canary.norm/v1",
            "derivation": "uuid5(FORGE_TASK_NAMESPACE, canonical_content_hash)"}


def read_screening(here):
    """The screening instant and result are MEASURED OVER the frozen tree, so they are read back
    the way identity is; the carrier is hash-excluded, so binding them moves nothing."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        got = {k: doc[k] for k in ("screening_measured_at", "screening_expires_at",
                                   "screening_result") if k in doc}
        if got:
            return got
    return {"screening_measured_at": None, "screening_expires_at": None,
            "screening_result": None}


def load_grounding():
    with open(os.path.join(HERE, "grounding.yaml")) as fh:
        return yaml.safe_load(fh)


# --------------------------------------------------------------------------------------------
# The emitted checker module. PRELUDE is percent-substituted from corpus_layout, so it carries no
# literal percent sign of its own. TAIL is not substituted at all.
# --------------------------------------------------------------------------------------------

PRELUDE = '''"""Compiled checks for %(slot_id)s. GENERATED by solution/recompute.py. DO NOT HAND-EDIT.

What is graded here is a PROGRAM and a MEMORY, not an array. train.py is executed once per graded
configuration and timed host-side; carry/notes.json is the only byte-durable channel between one
attempt and the next, and it is 2,048 bytes wide, closed-schema and expiring. These checks
establish that the program is a program rather than a serialized model, that the store is a
calibration table rather than a weight cache or a forged provenance record, that the clock opened
where it was supposed to, and that the configurations graded are the ones the published schedule
selects -- before any speed is credited. Every check runs against delivered bytes and references
no unmeasured quantity, except %(outcome_id)s, which raises ConstantUnmeasured while
tests/constants.json carries nulls.
"""
import ast
import hashlib
import json
import math
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)

# The submitted program: executed by the verifier, read here.
PROGRAM = %(path)r

# The memory channel, both ends of it. PROPOSED is what this attempt wrote; DELIVERED is the
# read-only copy of what the previous attempt's verifier persisted. The canonical state itself is
# harness-private and is named only so the isolation check can say what must not be written.
PROPOSED_CARRY = os.path.join(BUNDLE, %(proposed_carry)r)
PROPOSED_CARRY_ARG = %(proposed_carry)r
DELIVERED_CARRY = os.path.join(BUNDLE, %(delivered_carry)r)
CANONICAL_CARRY_STATE = %(canonical_carry)r

RUN_RECORD = os.path.join(BUNDLE, %(run_record)r)
REWARD_LOG = os.path.join(BUNDLE, %(reward_log)r)

# The live thirty-two-configuration family, pinned here before any measurement. The shipped decoy
# corpus reuses these identifiers for a retired parameterization, which is why an entry claiming
# to be observed is checked against what this run actually graded.
CONFIG_ROSTER = %(config_roster)s
CONFIGURATION_COUNT = %(configuration_count)d
LAUNCH_FLAGS = %(launch_flags)r

# The published schedule. Recomputed from the rule rather than tabulated, so the check reads what
# instruction.md publishes rather than an answer authored beside it.
SCHEDULE_STRIDE = %(stride)d
SCHEDULE_OFFSETS = %(offsets)r
SCHEDULE_MODULUS = %(modulus)d
GRADED_PER_ATTEMPT = %(graded_per_attempt)d
FINAL_ATTEMPT = %(final_attempt)d
FINAL_ATTEMPT_CONFIGURATIONS = %(final_attempt_configurations)d

# The closed carry schema.
CARRY_MAX_BYTES = %(carry_max_bytes)d
SCALAR_FIELDS = %(scalar_fields)r
SRC_FIELD = %(src_field)r
SRC_OBSERVED = %(src_observed)d
SRC_PREDICTED = %(src_predicted)d
TAG_FIELD = %(tag_field)r
TAG_MAX_BYTES = %(tag_max_bytes)d
STAMP_FIELD = %(stamp_field)r
FLIP_VALUES = %(flip_values)r
OFF_MIN = %(off_min)d
OFF_MAX = %(off_max)d
SCALE_MIN = %(scale_min)r
SCALE_MAX = %(scale_max)r
RHO_MIN = %(rho_min)r
AMB_MIN = %(amb_min)r
AMB_MAX = %(amb_max)r
TOLERANCES = %(tolerances)r
CARRY_TTL_ATTEMPTS = %(carry_ttl)d
LIFECYCLE_ORDER = %(lifecycle_order)r

# The harness attempt record.
BLOCK_KEYS = %(block_keys)r
GATE_OUTCOMES = %(gate_outcomes)r
CLEARED_GATE = %(cleared_gate)r
BELOW_BAR_GATE = %(below_bar_gate)r
SIBLING_GAP_GATE = %(sibling_gap_gate)r
HARD_GATES = %(hard_gates)r
SIBLING_GAP_MAX = %(sibling_gap_max)r
TIMER_EPSILON_S = %(timer_epsilon)r
LOG_ACCURACY_TOLERANCE = %(log_accuracy)r
LOG_ELAPSED_FRACTION = %(log_elapsed_fraction)r
SOURCE_LIMITS = %(source_limits)r
SEED_EPSILON = %(seed_epsilon)r
BUDGET_KEYS = %(budget_keys)r
GUARDED_WRITES = %(guarded_writes)r

CHECKS = []


class ConstantUnmeasured(Exception):
    """Raised when a check needs a ramp constant that Phase 0 deliberately left null."""


def check(id, weight, knockout, kind):
    def deco(fn):
        CHECKS.append({"id": id, "weight": weight, "knockout": knockout, "kind": kind, "fn": fn})
        return fn
    return deco


def constants():
    with open(os.path.join(HERE, "constants.json")) as fh:
        return json.load(fh)


def require_measured(*names):
    c = constants()
    missing = [n for n in names if c.get(n) is None]
    if missing:
        raise ConstantUnmeasured(
            "%(slot_id)s: " + ", ".join(missing) + " are null. Phase 0 authors no measurement; "
            "the Phase 2 measurement wave writes these and this check becomes gradeable then.")
    return c


def evidence(**kw):
    return {"evaluation_target": kw.pop("target", "harness_attempt_record"), "values": kw}
'''


TAIL = '''

# ------------------------------------------------------------------------------------------
# Reading the delivered bytes. A submitted program, two ends of a memory channel, one harness
# record and one agent log. Absent is reported, never guessed at, and never passed over: a file
# that will not open is a finding about the submission, not a crash in the checker.
# ------------------------------------------------------------------------------------------

def read_bytes(path):
    if not os.path.exists(path):
        return None
    try:
        with open(path, "rb") as handle:
            return handle.read()
    except OSError:
        return None


def program_source():
    """The submitted program's source text, or None when it is absent or is not text."""
    raw = read_bytes(PROGRAM)
    if raw is None:
        return None
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError:
        return None


def program_tree():
    """The submitted program's syntax tree, or None when it is absent or will not parse."""
    source = program_source()
    if source is None:
        return None
    try:
        return ast.parse(source)
    except SyntaxError:
        return None


def json_document(path):
    """(raw bytes, parsed document, error token). Every arm is reported, none of them raises."""
    raw = read_bytes(path)
    if raw is None:
        return None, None, "absent"
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return raw, None, "not_utf8"
    try:
        return raw, json.loads(text), None
    except ValueError:
        return raw, None, "not_json"


def proposed_store():
    return json_document(PROPOSED_CARRY)


def delivered_store():
    return json_document(DELIVERED_CARRY)


def attempt_record():
    """What the graded attempt recorded about itself.

    The harness fills the per-configuration blocks and the isolation, lifecycle and replay
    fields; the agent fills the budget declaration. The file can be absent, truncated or not JSON
    at all, and every one of those is an empty record here so that each check reports its own
    missing-record reason rather than taking the verifier down.
    """
    _raw, doc, _err = json_document(RUN_RECORD)
    return doc if isinstance(doc, dict) else {}


def graded_blocks():
    """One block per configuration this attempt graded, in the order the harness recorded them."""
    got = attempt_record().get("graded")
    if not isinstance(got, list):
        return []
    return [b for b in got if isinstance(b, dict) and b.get("config_id") is not None]


def attempt_index():
    value = numeric(attempt_record().get("attempt_index"))
    if value is None or value != int(value) or value < 1:
        return None
    return int(value)


def numeric(value):
    """A finite float, or None for anything that is not one -- including bools and NaN.

    A bool is an int in Python, and True would otherwise read as a src bit of one or an attempt
    index of one.
    """
    if isinstance(value, bool) or value is None:
        return None
    try:
        out = float(value)
    except (TypeError, ValueError):
        return None
    if out != out or out in (float("inf"), float("-inf")):
        return None
    return out


def token(value):
    """A declared vocabulary word, normalised the one way every roster here is written."""
    return str(value).strip().lower().replace("-", "_").replace(" ", "_")


def as_list(value):
    return [v for v in value] if isinstance(value, list) else []


def store_entries(doc):
    """config_id -> entry, for the entries that are objects at all."""
    if not isinstance(doc, dict):
        return {}
    return dict((str(k), v) for k, v in doc.items() if isinstance(v, dict))


def flag_value(argv, flag):
    """The value passed after a flag on a recorded command line, or None."""
    for i, item in enumerate(argv):
        if item == flag and i + 1 < len(argv):
            return argv[i + 1]
        if item.startswith(flag + "="):
            return item[len(flag) + 1:]
    return None


def sha256_bytes(raw):
    return hashlib.sha256(raw).hexdigest()


def in_guarded_tree(path):
    """True when a written path lands in the checker tree, the private shards or the carry state."""
    flat = "/" + str(path).replace("\\\\", "/").lstrip("./").lstrip("/")
    return any(marker in flat for marker in GUARDED_WRITES)


def config_index(config_id):
    """The roster index of a configuration id, or None when it is not one of ours."""
    try:
        return CONFIG_ROSTER.index(config_id)
    except ValueError:
        return None


def scheduled_configs(attempt):
    """The configurations the published rule grades at an attempt in 1..FINAL_ATTEMPT-1."""
    return tuple(CONFIG_ROSTER[(SCHEDULE_STRIDE * attempt + o) % SCHEDULE_MODULUS]
                 for o in SCHEDULE_OFFSETS)


def last_visit_table(through_attempt):
    """config_id -> the last attempt at or before through_attempt that the schedule visited it."""
    table = {}
    for attempt in range(1, int(through_attempt) + 1):
        for config_id in scheduled_configs(attempt):
            table[config_id] = attempt
    return table


def oldest_visited(count, through_attempt):
    """The count configurations whose last scheduled visit is oldest, ties by ascending id."""
    table = last_visit_table(through_attempt)
    ranked = sorted(table.items(), key=lambda kv: (kv[1], kv[0]))
    return tuple(config_id for config_id, _ in ranked[:int(count)])


def numeric_literal_sizes(tree):
    """The element count of every numeric literal collection in the source.

    Counted recursively, so a list of lists of weights is one array of the size of its leaves
    rather than an array of three rows.
    """
    sizes = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.List, ast.Tuple, ast.Set)):
            count = count_numeric_leaves(node)
            if count:
                sizes.append(count)
    return sizes


def count_numeric_leaves(node):
    """Numeric constants under one collection literal, or 0 if anything else is in it."""
    total = 0
    for element in getattr(node, "elts", []):
        if isinstance(element, ast.Constant) and isinstance(element.value, (int, float)) \\
                and not isinstance(element.value, bool):
            total += 1
        elif isinstance(element, (ast.List, ast.Tuple, ast.Set)):
            nested = count_numeric_leaves(element)
            if nested == 0:
                return 0
            total += nested
        elif isinstance(element, ast.UnaryOp) and isinstance(element.operand, ast.Constant) \\
                and isinstance(element.operand.value, (int, float)):
            total += 1
        else:
            return 0
    return total


BASE64ISH = re.compile(r"^[A-Za-z0-9+/=\\s]+$")


def base64_literal_sizes(tree):
    """The byte length of every long base64-shaped string literal in the source."""
    sizes = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            text = node.value
            if len(text) >= 64 and BASE64ISH.match(text):
                sizes.append(len(text.encode("utf-8")))
    return sizes


def docstring_nodes(tree):
    """The Constant nodes that are docstrings, which are prose rather than data."""
    found = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            body = getattr(node, "body", [])
            if body and isinstance(body[0], ast.Expr) and isinstance(body[0].value, ast.Constant) \\
                    and isinstance(body[0].value.value, str):
                found.add(id(body[0].value))
    return found


def source_string_literals(tree):
    """Every string literal in the source that is not a docstring."""
    skip = docstring_nodes(tree)
    out = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str) and id(node) not in skip:
            out.append(node.value)
    return out


def paths_carrying(doc, field, prefix=""):
    """Every path in a nested document at which a given key appears."""
    found = []
    if isinstance(doc, dict):
        for key, value in doc.items():
            where = (prefix + "." + str(key)) if prefix else str(key)
            if str(key) == field:
                found.append(where)
            found.extend(paths_carrying(value, field, where))
    elif isinstance(doc, list):
        for i, value in enumerate(doc):
            found.extend(paths_carrying(value, field, "%s[%d]" % (prefix, i)))
    return found


def out_of_domain(field, value):
    """The reason a stored scalar is outside its published domain, or None."""
    if field == "flip" and value not in [float(v) for v in FLIP_VALUES]:
        return "label_orientation_is_not_a_bit"
    if field == "ofs" and (value != int(value) or value < OFF_MIN or value > OFF_MAX):
        return "crop_offset_is_not_a_lattice_index"
    if field == "scale" and not SCALE_MIN <= value <= SCALE_MAX:
        return "crop_scale_outside_the_published_band"
    if field == "rho" and value < RHO_MIN:
        return "prior_skew_below_one"
    if field == "amb" and not AMB_MIN <= value <= AMB_MAX:
        return "ambiguity_level_outside_the_unit_interval"
    if field == "chan" and value <= 0:
        return "channel_gain_is_not_positive"
    return None


def cleared_attempts():
    """config_id -> the attempts at which the harness recorded that configuration clearing."""
    got = attempt_record().get("bar_cleared_history")
    if not isinstance(got, dict):
        return {}
    out = {}
    for key, value in got.items():
        attempts = [int(numeric(v)) for v in as_list(value) if numeric(v) is not None]
        out[str(key)] = attempts
    return out


def reward_log_lines():
    """(parsed lines, indices of lines that were not JSON objects)."""
    raw = read_bytes(REWARD_LOG)
    if raw is None:
        return None, []
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return [], [0]
    lines, malformed = [], []
    for i, line in enumerate(text.splitlines()):
        if not line.strip():
            continue
        try:
            doc = json.loads(line)
        except ValueError:
            malformed.append(i + 1)
            continue
        if isinstance(doc, dict):
            lines.append(doc)
        else:
            malformed.append(i + 1)
    return lines, malformed


def measure(unreachable_seconds):
    """Mean bar-gated wall clock over the attempt's graded configurations, in seconds.

    The elapsed is the HARNESS measurement, never the submission's own: red line 7 is reporting an
    elapsed the host did not measure, and an axis that read the agent's number would be grading
    the declaration it exists to distrust.

    A configuration whose gate did not clear contributes the ramp's slow anchor rather than its
    own elapsed. That ordering is the gate: a run that missed its bar, broke the sibling gap,
    exceeded the ceiling or exported something inadmissible cannot buy the ramp by being fast, and
    a fast wrong run is worth what the slowest right one is worth and no more.
    """
    blocks = graded_blocks()
    if not blocks:
        raise ConstantUnmeasured(
            "the harness recorded no graded configuration; there is no wall clock to grade")
    seconds = []
    for block in blocks:
        if token(block.get("gate")) != CLEARED_GATE:
            seconds.append(float(unreachable_seconds))
            continue
        elapsed = numeric(block.get("elapsed_s"))
        if elapsed is None or elapsed <= 0:
            raise ConstantUnmeasured(
                "configuration %s cleared its gate and carries no measured wall clock"
                % block.get("config_id"))
        seconds.append(elapsed)
    return sum(seconds) / len(seconds)


def ramp(seconds, floor, knee):
    """The published descending logarithmic ramp, clipped into the unit interval.

    Logarithmic because the reward map is: halving a 240 s run is worth what halving a 120 s one
    is, and a linear ramp on seconds would price the first second saved at the ceiling the same as
    the last one saved at the knee.
    """
    if floor is None or knee is None or floor <= 0 or knee <= 0 or floor <= knee:
        return 0.0
    span = math.log(floor) - math.log(knee)
    return max(0.0, min(1.0, (math.log(floor) - math.log(max(seconds, 1e-9))) / span))
'''


# --------------------------------------------------------------------------------------------
# BODIES. Every compiled item carries one, written for this slot. There is no generic obligation
# lookup behind them: the fallback that used to stand here read a run-record key nothing writes,
# so an item that fell through to it graded nothing at all and reported that it had passed.
# --------------------------------------------------------------------------------------------

BODIES = {
    "train_program_lands_and_compiles": '''
    raw = read_bytes(PROGRAM)
    if raw is None:
        return False, evidence(target="submitted_program", path=PROGRAM, reason="no_submission")
    try:
        source = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        return False, evidence(target="submitted_program", bytes=len(raw),
                               error=str(exc), reason="train_py_is_not_text")
    try:
        compile(source, PROGRAM, "exec")
    except SyntaxError as exc:
        return False, evidence(target="submitted_program", bytes=len(raw), error=str(exc),
                               reason="train_py_does_not_parse")
    return True, evidence(target="submitted_program", path=PROGRAM, bytes=len(raw),
                          lines=source.count(chr(10)) + 1)''',

    "program_consumes_every_flag_the_verifier_passes": '''
    source = program_source()
    if source is None:
        return False, evidence(target="submitted_program", reason="no_readable_program")
    unnamed = [flag for flag in LAUNCH_FLAGS if flag not in source]
    findings = []
    for block in graded_blocks():
        config_id = str(block.get("config_id"))
        argv = [str(a) for a in as_list(block.get("argv"))]
        if not argv:
            findings.append({"config_id": config_id, "reason": "launch_argv_unrecorded"})
            continue
        missing = [flag for flag in LAUNCH_FLAGS if flag_value(argv, flag) is None]
        if missing:
            findings.append({"config_id": config_id, "missing": missing,
                             "reason": "flag_not_passed_to_the_run"})
            continue
        if flag_value(argv, "--config-id") != config_id:
            findings.append({"config_id": config_id,
                             "passed": flag_value(argv, "--config-id"),
                             "reason": "config_id_flag_does_not_match_the_graded_block"})
        elif flag_value(argv, "--carry") != PROPOSED_CARRY_ARG:
            findings.append({"config_id": config_id, "passed": flag_value(argv, "--carry"),
                             "reason": "carry_flag_is_not_the_published_store_path"})
    ok = not unnamed and not findings
    return ok, evidence(target="submitted_program", launch_flags=list(LAUNCH_FLAGS),
                        flags_absent_from_the_source=unnamed, launch_findings=findings,
                        reason=None if ok else ("launch_flag_not_consumed" if unnamed
                                                else findings[0]["reason"]))''',

    "source_tree_carries_no_smuggled_weights": '''
    raw = read_bytes(PROGRAM)
    if raw is None:
        return False, evidence(target="submitted_program", reason="no_submission")
    declared = numeric(attempt_record().get("source_tree_bytes"))
    size = int(max(len(raw), declared or 0))
    tree = program_tree()
    if tree is None:
        return False, evidence(target="submitted_program", size_bytes=size,
                               reason="train_py_does_not_parse")
    arrays = sorted(n for n in numeric_literal_sizes(tree)
                    if n > SOURCE_LIMITS["max_numeric_literal_array"])
    blobs = sorted(n for n in base64_literal_sizes(tree)
                   if n > SOURCE_LIMITS["max_base64_literal_bytes"])
    oversize = size > SOURCE_LIMITS["max_bytes"]
    ok = not oversize and not arrays and not blobs
    return ok, evidence(target="submitted_program", size_bytes=size, limits=SOURCE_LIMITS,
                        oversized_numeric_arrays=arrays, oversized_base64_literals=blobs,
                        reason=None if ok else "source_payload_violation")''',

    "hardcoded_per_configuration_constants_are_provenanced": '''
    tree = program_tree()
    if tree is None:
        return False, evidence(target="submitted_program", reason="no_readable_program")
    named = sorted(set(source_string_literals(tree)) & set(CONFIG_ROSTER))
    if not named:
        return True, evidence(target="submitted_program", config_ids_in_source=[],
                              note="no per-configuration constant is written into the source")
    _raw, doc, err = proposed_store()
    observed = sorted(config_id for config_id, entry in store_entries(doc).items()
                      if numeric(entry.get(SRC_FIELD)) == float(SRC_OBSERVED))
    unprovenanced = sorted(set(named) - set(observed))
    ok = not unprovenanced
    return ok, evidence(target="submitted_program", config_ids_in_source=named,
                        observed_entries=observed, unprovenanced=unprovenanced,
                        carry_store_error=err,
                        reason=None if ok else "constants_unprovenanced")''',

    "carry_store_fits_the_two_kilobyte_channel": '''
    raw, doc, err = proposed_store()
    if raw is None:
        # An absent store is admissible: the first attempt has none, and NC-AMNESIC runs with
        # none deliberately. What is not admissible is a present one over the cap.
        return True, evidence(target="proposed_carry_store", store_absent=True,
                              cap_bytes=CARRY_MAX_BYTES)
    size = len(raw)
    if size > CARRY_MAX_BYTES:
        return False, evidence(target="proposed_carry_store", bytes=size, cap_bytes=CARRY_MAX_BYTES,
                               reason="carry_store_invalid")
    if err is not None or not isinstance(doc, dict):
        return False, evidence(target="proposed_carry_store", bytes=size, error=err,
                               reason="carry_store_invalid")
    if len(doc) > CONFIGURATION_COUNT:
        return False, evidence(target="proposed_carry_store", bytes=size, entries=len(doc),
                               configurations=CONFIGURATION_COUNT, reason="carry_store_invalid")
    return True, evidence(target="proposed_carry_store", bytes=size, cap_bytes=CARRY_MAX_BYTES,
                          entries=len(doc),
                          bytes_per_entry=round(size / max(len(doc), 1), 1))''',

    "carry_entries_carry_the_six_named_scalars_and_nothing_else": '''
    raw, doc, err = proposed_store()
    if raw is None:
        return True, evidence(target="proposed_carry_store", store_absent=True)
    if err is not None or not isinstance(doc, dict):
        return False, evidence(target="proposed_carry_store", error=err,
                               reason="carry_store_invalid")
    findings = []
    for config_id in sorted(str(k) for k in doc):
        entry = doc[config_id]
        if config_id not in CONFIG_ROSTER:
            findings.append({"config_id": config_id, "reason": "unknown_config_id"})
            continue
        if not isinstance(entry, dict):
            findings.append({"config_id": config_id, "reason": "entry_is_not_an_object"})
            continue
        keys = set(str(k) for k in entry)
        missing = [f for f in SCALAR_FIELDS if f not in keys]
        unknown = sorted(keys - set(SCALAR_FIELDS) - set([SRC_FIELD, TAG_FIELD]))
        if missing:
            findings.append({"config_id": config_id, "missing": missing,
                             "reason": "entry_missing_a_named_scalar"})
        if unknown:
            findings.append({"config_id": config_id, "unknown": unknown,
                             "reason": "unknown_key_in_a_closed_schema"})
        for field in SCALAR_FIELDS:
            if field not in entry:
                continue
            value = entry[field]
            if isinstance(value, (list, dict)):
                findings.append({"config_id": config_id, "field": field,
                                 "reason": "array_or_object_field"})
                continue
            got = numeric(value)
            if got is None:
                findings.append({"config_id": config_id, "field": field,
                                 "reason": "field_is_not_a_finite_scalar"})
                continue
            outside = out_of_domain(field, got)
            if outside:
                findings.append({"config_id": config_id, "field": field, "value": got,
                                 "reason": outside})
        if numeric(entry.get(SRC_FIELD)) not in (float(SRC_OBSERVED), float(SRC_PREDICTED)):
            findings.append({"config_id": config_id, "src": entry.get(SRC_FIELD),
                             "reason": "src_is_not_one_bit"})
        if TAG_FIELD in entry:
            tag = entry[TAG_FIELD]
            if not isinstance(tag, str) or len(tag.encode("utf-8")) > TAG_MAX_BYTES:
                findings.append({"config_id": config_id,
                                 "reason": "encoder_tag_is_not_a_short_string"})
    ok = not findings
    return ok, evidence(target="proposed_carry_store", schema_findings=findings,
                        scalar_fields=list(SCALAR_FIELDS), src_field=SRC_FIELD,
                        reason=None if ok else "carry_store_invalid")''',

    "agent_store_writes_no_last_confirmed_stamp": '''
    raw, doc, err = proposed_store()
    if raw is None:
        return True, evidence(target="proposed_carry_store", store_absent=True)
    if err is not None:
        return False, evidence(target="proposed_carry_store", error=err,
                               reason="carry_store_invalid")
    stamped = sorted(paths_carrying(doc, STAMP_FIELD))
    ok = not stamped
    return ok, evidence(target="proposed_carry_store", stamp_field=STAMP_FIELD,
                        stamps_in_the_submitted_store=stamped,
                        reason=None if ok else "carry_stamp_forged")''',

    "observed_entries_name_configurations_this_run_graded": '''
    raw, doc, err = proposed_store()
    if raw is None:
        return True, evidence(target="proposed_carry_store", store_absent=True)
    if err is not None:
        return False, evidence(target="proposed_carry_store", error=err,
                               reason="carry_store_invalid")
    history = set(str(c) for c in as_list(attempt_record().get("graded_config_history")))
    if not history:
        return False, evidence(target="proposed_carry_store",
                               reason="graded_config_history_unrecorded")
    measured = dict((str(b.get("config_id")), b.get("measured_constants") or {})
                    for b in graded_blocks())
    findings, exempt = [], []
    for config_id, entry in sorted(store_entries(doc).items()):
        if numeric(entry.get(SRC_FIELD)) != float(SRC_OBSERVED):
            # Predicted entries are exempt by construction: generalising across the latent family
            # is the rewarded route, and only the provenance claim is policed.
            exempt.append(config_id)
            continue
        if config_id not in history:
            findings.append({"config_id": config_id,
                             "reason": "observed_entry_for_a_configuration_no_attempt_graded"})
            continue
        truth = measured.get(config_id)
        if not truth:
            continue
        for field in SCALAR_FIELDS:
            stored, actual = numeric(entry.get(field)), numeric(truth.get(field))
            if stored is None or actual is None:
                findings.append({"config_id": config_id, "field": field,
                                 "reason": "observed_field_not_comparable"})
                continue
            if abs(stored - actual) > TOLERANCES[field]:
                findings.append({"config_id": config_id, "field": field, "stored": stored,
                                 "measured": actual, "tolerance": TOLERANCES[field],
                                 "reason": "observed_value_outside_tolerance"})
    ok = not findings
    return ok, evidence(target="proposed_carry_store", provenance_findings=findings,
                        predicted_entries_exempt=exempt, tolerances=TOLERANCES,
                        reason=None if ok else "carry_fabricated")''',

    "stamps_are_verifier_written_and_expire_after_eight_attempts": '''
    raw, doc, err = delivered_store()
    if raw is None:
        return True, evidence(target="delivered_carry_store", store_absent=True,
                              note="the first attempt of a run is delivered no store")
    if err is not None or not isinstance(doc, dict):
        return False, evidence(target="delivered_carry_store", error=err,
                               reason="carry_delivery_mismatch")
    attempt = attempt_index()
    if attempt is None:
        return False, evidence(target="delivered_carry_store", reason="attempt_index_unrecorded")
    cleared = cleared_attempts()
    findings = []
    for config_id, entry in sorted(store_entries(doc).items()):
        stamp = entry.get(STAMP_FIELD)
        if stamp is None:
            if numeric(entry.get(SRC_FIELD)) == float(SRC_OBSERVED):
                findings.append({"config_id": config_id,
                                 "reason": "observed_entry_carries_no_verifier_stamp"})
            continue
        value = numeric(stamp)
        if value is None or value != int(value) or value < 1 or value > attempt:
            findings.append({"config_id": config_id, "stamp": stamp,
                             "reason": "stamp_is_not_an_attempt_index_of_this_run"})
            continue
        if int(value) not in cleared.get(config_id, []):
            findings.append({"config_id": config_id, "stamp": int(value),
                             "reason": "stamp_names_an_attempt_that_did_not_clear_the_bar"})
            continue
        if attempt - int(value) > CARRY_TTL_ATTEMPTS:
            findings.append({"config_id": config_id, "stamp": int(value),
                             "age_in_attempts": attempt - int(value),
                             "reason": "expired_entry_was_delivered"})
    ok = not findings
    return ok, evidence(target="delivered_carry_store", attempt_index=attempt,
                        ttl_attempts=CARRY_TTL_ATTEMPTS, stamp_findings=findings,
                        reason=None if ok else "carry_lifecycle_violation")''',

    "carry_lifecycle_validates_stamps_expires_persists_then_reports": '''
    record = attempt_record()
    trace = tuple(token(step) for step in as_list(record.get("carry_lifecycle_trace")))
    if not trace:
        return False, evidence(reason="carry_lifecycle_untraced")
    order_holds = trace == LIFECYCLE_ORDER
    attempt = attempt_index()
    incoming = record.get("incoming_store_stamps")
    reported = record.get("expired_identifiers")
    if attempt is None or not isinstance(incoming, dict) or not isinstance(reported, list):
        return False, evidence(trace=list(trace), order_holds=order_holds,
                               reason="expiry_report_unrecorded")
    recomputed = sorted(str(config_id) for config_id, stamp in incoming.items()
                        if numeric(stamp) is not None
                        and attempt - numeric(stamp) > CARRY_TTL_ATTEMPTS)
    reported_ids = sorted(str(c) for c in reported)
    ok = order_holds and reported_ids == recomputed
    return ok, evidence(trace=list(trace), bound_order=list(LIFECYCLE_ORDER),
                        order_holds=order_holds, reported_expired=reported_ids,
                        recomputed_expired=recomputed,
                        reason=None if ok else "carry_lifecycle_violation")''',

    "delivered_store_is_byte_identical_to_the_persisted_one": '''
    raw, _doc, _err = delivered_store()
    persisted = attempt_record().get("persisted_carry_sha256")
    attempt = attempt_index()
    if raw is None and not persisted:
        return True, evidence(target="delivered_carry_store", attempt_index=attempt,
                              note="nothing was persisted and nothing was delivered")
    if raw is None:
        return False, evidence(target="delivered_carry_store", delivered_sha256=None,
                               persisted_sha256=persisted, reason="carry_delivery_mismatch")
    digest = sha256_bytes(raw)
    ok = bool(persisted) and digest == persisted
    return ok, evidence(target="delivered_carry_store", delivered_sha256=digest,
                        persisted_sha256=persisted, bytes=len(raw),
                        reason=None if ok else "carry_delivery_mismatch")''',

    "timer_opens_at_the_first_private_data_read": '''
    blocks = graded_blocks()
    if not blocks:
        return False, evidence(reason="no_graded_configuration_recorded")
    findings = []
    for block in blocks:
        config_id = str(block.get("config_id"))
        opened = numeric(block.get("timer_open_s"))
        first_read = numeric(block.get("first_private_read_s"))
        closed = numeric(block.get("timer_close_s"))
        wrote = numeric(block.get("export_write_s"))
        elapsed = numeric(block.get("elapsed_s"))
        if None in (opened, first_read, closed, wrote, elapsed):
            findings.append({"config_id": config_id, "reason": "timer_stamps_unrecorded"})
            continue
        if abs(opened - first_read) > TIMER_EPSILON_S:
            findings.append({"config_id": config_id, "timer_open_s": opened,
                             "first_private_read_s": first_read,
                             "reason": "timer_order_violation"})
            continue
        if closed + TIMER_EPSILON_S < wrote:
            findings.append({"config_id": config_id, "timer_close_s": closed,
                             "export_write_s": wrote, "reason": "timer_order_violation"})
            continue
        if elapsed <= 0 or abs(elapsed - (closed - opened)) > TIMER_EPSILON_S:
            findings.append({"config_id": config_id, "elapsed_s": elapsed,
                             "close_minus_open": closed - opened,
                             "reason": "elapsed_is_not_close_minus_open"})
            continue
        stages = block.get("pre_read_stages")
        late = sorted(name for name, stamp in (stages or {}).items()
                      if isinstance(stages, dict) and numeric(stamp) is not None
                      and numeric(stamp) > first_read)
        if late:
            # Setup before the first private-data read is legitimate and is stated as such. A
            # stage DECLARED as pre-read and stamped after it is a false declaration, not a
            # timing violation, and it is named as the former.
            findings.append({"config_id": config_id, "stages": late,
                             "reason": "pre_read_stage_stamped_after_the_first_read"})
    ok = not findings
    return ok, evidence(timer_findings=findings, epsilon_s=TIMER_EPSILON_S,
                        reason=None if ok else findings[0]["reason"])''',

    "graded_roster_is_the_published_schedule_and_the_eight_oldest_at_the_last_attempt": '''
    attempt = attempt_index()
    if attempt is None:
        return False, evidence(reason="attempt_index_unrecorded")
    graded = sorted(str(b.get("config_id")) for b in graded_blocks())
    if not graded:
        return False, evidence(attempt_index=attempt, reason="no_graded_configuration_recorded")
    if attempt >= FINAL_ATTEMPT:
        expected = sorted(oldest_visited(FINAL_ATTEMPT_CONFIGURATIONS, FINAL_ATTEMPT - 1))
        rule = "the eight configurations whose last scheduled visit is oldest"
    else:
        expected = sorted(scheduled_configs(attempt))
        rule = "the three configurations the published stride schedules at this attempt"
    outside = sorted(set(graded) - set(CONFIG_ROSTER))
    ok = graded == expected and not outside
    return ok, evidence(attempt_index=attempt, rule=rule, graded=graded, expected=expected,
                        outside_the_roster=outside,
                        reason=None if ok else "graded_roster_is_not_the_published_schedule")''',

    "gate_outcomes_recompute_from_the_shard_accuracies": '''
    blocks = graded_blocks()
    if not blocks:
        return False, evidence(reason="no_graded_configuration_recorded")
    findings = []
    for block in blocks:
        config_id = str(block.get("config_id"))
        a = numeric(block.get("balanced_accuracy_a"))
        b = numeric(block.get("balanced_accuracy_b"))
        bar = numeric(block.get("bar"))
        gate = token(block.get("gate"))
        if gate not in GATE_OUTCOMES:
            findings.append({"config_id": config_id, "gate": gate,
                             "reason": "unrecognised_gate_outcome"})
            continue
        if gate in HARD_GATES:
            # An invalid export or a run past the ceiling is gated before accuracy is read, and
            # neither is recomputable from the two accuracies, so neither is second-guessed here.
            continue
        if a is None or b is None or bar is None:
            findings.append({"config_id": config_id, "reason": "accuracies_or_bar_unrecorded"})
            continue
        if not (0.0 <= a <= 1.0 and 0.0 <= b <= 1.0):
            findings.append({"config_id": config_id, "accuracy_a": a, "accuracy_b": b,
                             "reason": "balanced_accuracy_outside_the_unit_interval"})
            continue
        gap = abs(a - b)
        if gap > SIBLING_GAP_MAX and gate != SIBLING_GAP_GATE:
            findings.append({"config_id": config_id, "sibling_gap": gap, "gate": gate,
                             "reason": "sibling_gap_not_recorded_as_a_violation"})
        elif gap <= SIBLING_GAP_MAX and gate == SIBLING_GAP_GATE:
            findings.append({"config_id": config_id, "sibling_gap": gap,
                             "reason": "sibling_gap_violation_recorded_without_a_gap"})
        elif gap <= SIBLING_GAP_MAX and a < bar and gate != BELOW_BAR_GATE:
            findings.append({"config_id": config_id, "accuracy_a": a, "bar": bar, "gate": gate,
                             "reason": "accuracy_below_the_bar_recorded_as_cleared"})
        elif gap <= SIBLING_GAP_MAX and a >= bar and gate == BELOW_BAR_GATE:
            findings.append({"config_id": config_id, "accuracy_a": a, "bar": bar,
                             "reason": "accuracy_clears_the_bar_but_is_recorded_below_it"})
    ok = not findings
    return ok, evidence(gate_findings=findings, sibling_gap_max=SIBLING_GAP_MAX,
                        reason=None if ok else "gate_outcome_contradicts_its_own_accuracies")''',

    "exported_parameters_move_with_the_verifier_supplied_seed": '''
    attempt = attempt_index()
    if attempt is None:
        return False, evidence(reason="attempt_index_unrecorded")
    if attempt < FINAL_ATTEMPT:
        return True, evidence(attempt_index=attempt, final_attempt=FINAL_ATTEMPT,
                              note="the second-seed re-run is recorded at the scored attempt")
    replay = attempt_record().get("seed_replay")
    if not isinstance(replay, dict) or not replay:
        return False, evidence(attempt_index=attempt, reason="seed_replay_unrecorded")
    config_id = str(replay.get("config_id"))
    block = None
    for candidate in graded_blocks():
        if str(candidate.get("config_id")) == config_id:
            block = candidate
    if block is None:
        return False, evidence(config_id=config_id,
                               reason="seed_replay_names_an_ungraded_configuration")
    reasons = []
    first_seed = numeric(block.get("init_seed"))
    second_seed = numeric(replay.get("init_seed"))
    if first_seed is None or second_seed is None or first_seed == second_seed:
        reasons.append("the_two_runs_do_not_use_distinct_seeds")
    if block.get("export_sha256") is not None \\
            and block.get("export_sha256") == replay.get("export_sha256"):
        reasons.append("seed_independent_parameters")
    delta = numeric(replay.get("mean_abs_param_delta"))
    if delta is None or delta <= SEED_EPSILON:
        reasons.append("seed_independent_parameters")
    bar = numeric(block.get("bar"))
    first_acc = numeric(block.get("balanced_accuracy_a"))
    second_acc = numeric(replay.get("balanced_accuracy_a"))
    if None in (bar, first_acc, second_acc) or first_acc < bar or second_acc < bar:
        reasons.append("a_seed_replay_that_does_not_clear_the_bar_proves_nothing")
    ok = not reasons
    return ok, evidence(config_id=config_id, first_seed=first_seed, second_seed=second_seed,
                        mean_abs_param_delta=delta, epsilon=SEED_EPSILON,
                        reason=None if ok else reasons[0])''',

    "reward_log_agrees_with_the_harness_within_the_published_tolerances": '''
    blocks = graded_blocks()
    if not blocks:
        return False, evidence(target="agent_reward_log",
                               reason="no_graded_configuration_recorded")
    lines, malformed = reward_log_lines()
    if lines is None:
        return False, evidence(target="agent_reward_log", path=REWARD_LOG,
                               reason="no_reward_log")
    findings = []
    if malformed:
        findings.append({"lines": malformed, "reason": "reward_log_line_is_not_a_json_object"})
    claims = dict((str(line.get("config_id")), line) for line in lines)
    for block in blocks:
        config_id = str(block.get("config_id"))
        claim = claims.get(config_id)
        if claim is None:
            findings.append({"config_id": config_id,
                             "reason": "graded_configuration_absent_from_the_log"})
            continue
        measured_acc = numeric(block.get("balanced_accuracy_a"))
        measured_elapsed = numeric(block.get("elapsed_s"))
        claimed_acc = numeric(claim.get("balanced_accuracy"))
        claimed_elapsed = numeric(claim.get("elapsed_s"))
        if measured_acc is None or measured_elapsed is None or measured_elapsed <= 0:
            findings.append({"config_id": config_id, "reason": "harness_measurement_unrecorded"})
            continue
        if claimed_acc is None or claimed_elapsed is None:
            findings.append({"config_id": config_id,
                             "reason": "log_line_claims_no_accuracy_or_elapsed"})
            continue
        if abs(claimed_acc - measured_acc) > LOG_ACCURACY_TOLERANCE:
            findings.append({"config_id": config_id, "claimed": claimed_acc,
                             "measured": measured_acc, "tolerance": LOG_ACCURACY_TOLERANCE,
                             "reason": "log_fabrication"})
        elif abs(claimed_elapsed - measured_elapsed) > LOG_ELAPSED_FRACTION * measured_elapsed:
            findings.append({"config_id": config_id, "claimed": claimed_elapsed,
                             "measured": measured_elapsed,
                             "tolerance_fraction": LOG_ELAPSED_FRACTION,
                             "reason": "log_fabrication"})
    ok = not findings
    return ok, evidence(target="agent_reward_log", log_findings=findings,
                        accuracy_tolerance=LOG_ACCURACY_TOLERANCE,
                        elapsed_fraction=LOG_ELAPSED_FRACTION,
                        reason=None if ok else findings[0]["reason"])''',

    "heldout_shards_and_canonical_carry_state_unwritten": '''
    record = attempt_record()
    if not record:
        return False, evidence(reason="run_record_absent")
    harness = [p for p in as_list(record.get("guarded_paths_touched")) if in_guarded_tree(p)]
    declared = [p for p in as_list(record.get("paths_written")) if in_guarded_tree(p)]
    touched = sorted(set(harness) | set(declared))
    digests = [("heldout", record.get("heldout_digest_before"),
                record.get("heldout_digest_after")),
               ("canonical_carry", record.get("canonical_carry_digest_before"),
                record.get("canonical_carry_digest_after"))]
    unrecorded = [name for name, before, after in digests if not before or not after]
    moved = [name for name, before, after in digests if before and after and before != after]
    sockets = record.get("socket_syscalls_observed")
    socket_count = len(sockets) if isinstance(sockets, list) else numeric(sockets)
    gpus = numeric(record.get("visible_gpu_count"))
    reason = None
    if touched:
        reason = "grading_tree_mutated"
    elif moved:
        reason = "grading_tree_mutated"
    elif unrecorded:
        reason = "guarded_digests_unrecorded"
    elif socket_count is None or socket_count > 0:
        reason = "isolation_violation"
    elif gpus is None or gpus != 1:
        reason = "isolation_violation"
    return reason is None, evidence(guarded_paths_touched=touched, digests_moved=moved,
                                    digests_unrecorded=unrecorded, socket_syscalls=socket_count,
                                    visible_gpu_count=gpus,
                                    canonical_carry_state=CANONICAL_CARRY_STATE, reason=reason)''',

    "refresh_and_exploit_budget_declared_per_configuration": '''
    declaration = attempt_record().get("agent_budget_declaration")
    if declaration is None:
        return False, evidence(reason="no_agent_declaration")
    try:
        declared = (json.loads(declaration) if isinstance(declaration, str)
                    else dict(declaration))
    except Exception as exc:
        return False, evidence(reason="declaration_unparseable", error=str(exc))
    findings = []
    missing = [k for k in BUDGET_KEYS if k not in declared]
    if missing:
        findings.append({"missing": missing, "reason": "budget_not_declared_in_this_tasks_terms"})
    not_a_count = [k for k in BUDGET_KEYS if k in declared
                   and (numeric(declared[k]) is None or numeric(declared[k]) < 0)]
    if not_a_count:
        findings.append({"fields": not_a_count,
                         "reason": "budget_field_is_not_a_non_negative_number"})
    graded = len(graded_blocks())
    claimed = numeric(declared.get("graded_configurations"))
    if graded and claimed is not None and claimed != graded:
        findings.append({"declared": claimed, "graded": graded,
                         "reason": "declared_configuration_count_is_not_the_graded_count"})
    attempt = attempt_index()
    refreshing = numeric(declared.get("attempts_spent_refreshing"))
    exploiting = numeric(declared.get("attempts_spent_exploiting"))
    if attempt is not None and refreshing is not None and exploiting is not None \\
            and refreshing + exploiting > attempt:
        findings.append({"refreshing": refreshing, "exploiting": exploiting,
                         "attempt_index": attempt,
                         "reason": "more_attempts_declared_than_the_run_has_had"})
    ok = not findings
    return ok, evidence(declared=sorted(str(k) for k in declared), budget_keys=list(BUDGET_KEYS),
                        budget_findings=findings,
                        reason=None if ok else findings[0]["reason"])''',

    "bar_gated_wallclock_ramp_over_the_scored_attempt": '''
    # require_measured FIRST, before anything is read. Reading the record before saying the slot
    # is not yet measurable lets a missing-file error mask the unmeasured signal, and the verifier
    # then reports gradeable=true with r_det=0.0 -- which asserts the agent scored zero where the
    # honest claim is that the slot cannot yet be scored at all.
    c = require_measured("floor", "knee", "dichotomizing_threshold")
    seconds = measure(c["floor"])
    s = ramp(seconds, c["floor"], c["knee"])
    return seconds <= c["dichotomizing_threshold"], evidence(
        mean_gated_seconds=seconds, s_outcome=s, floor_seconds=c["floor"],
        knee_seconds=c["knee"], configurations=len(graded_blocks()))''',
}


def build_tests(g, prelude, bodies):
    """Assemble the compiled-check module. kind carries the item's own dimension."""
    chunks = [prelude]
    for raw in sorted(g["items"], key=lambda i: i["id"]):
        if raw["mode"] != "compiled":
            continue
        chunks.append('\n\n@check(id="%s", weight=%d, knockout=%s, kind="%s")\ndef test_%s():\n%s\n'
                      % (raw["id"], raw["weight"], raw["knockout"], raw["dimension"], raw["id"],
                         bodies[raw["id"]].strip("\n")))
    return "".join(chunks)


def build_truth(g, title):
    """Render solution/TRUTH.md from the frozen literals of solution/grounding.yaml."""
    n = g["truth_narrative"]
    lines = [title, "", "GENERATED SECTION. DO NOT HAND-EDIT.", "", n["opening"], "",
             "## The single most important insight", "", n["insight"], "",
             "## The ideal solve, step by step", ""]
    for i, step in enumerate(n["steps"], 1):
        lines += ["%d. **%s** %s" % (i, step["heading"], step["paragraph"]), ""]
    lines += ["## Traps that catch agents that are not thinking carefully", ""]
    lines += ["- " + t for t in n["traps"]]
    lines += ["", "---", "", "## Contract record (annex; not part of the narrative body)", "",
              "Retained under FORGE.md item 10e and Phase 2 item 7, which require this file to "
              "carry the ordered path through instruction.md with each satisfied checker "
              "identifier, and each rejected route bound to a measured known-wrong control. "
              "standards/truth-md-authoring-v1.md section 3 admits no fifth section, so this "
              "annex is a recorded deviation rather than an omission.", "", g["truth_annex"], ""]
    return "\n".join(lines) + "\n"


def build_rubrics(g, item_keys):
    """The 9g rubric carrier. The item schema is CLOSED at eight keys, so item 10f's outcome
    classification rides as a greppable prefix of the judgment rather than as a ninth key."""
    items = []
    for raw in g["items"]:
        item = {k: raw[k] for k in item_keys}
        item["judgment"] = "%s: %s" % (raw["outcome_class"], raw["judgment"])
        items.append(item)
    compiled = sum(i["weight"] for i in items if i["mode"] == "compiled")
    total = sum(i["weight"] for i in items)
    return {"$schema": "forge.rubric/v1",
            "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
            "generator": "solution/recompute.py",
            "compilation_floor": g["compilation_floor"],
            "compiled_weight_share": round(compiled / total, 6) if total else 0.0,
            "evaluation_target_vocabulary": sorted(g["evaluation_target_vocabulary"]),
            "items": sorted(items, key=lambda i: i["id"])}


def build_provenance(g, identity):
    p = g["provenance"]
    out = {
        "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
        "generator": "solution/recompute.py from solution/grounding.yaml",
        "schema_version": "1.0",
        "slot_id": g["slot_id"],
        "identity": identity,
        "corpus": p["corpus"],
        "anchors": p["anchors"],
        "shards": p["shards"],
        "narrative": p["narrative"],
        "supersedes": p["supersedes"],
        "upstream_provenance": p["upstream_record"],
        "reward_composition": p["reward_composition"],
        "screening_interval_days": p["screening_interval_days"],
        "screening_detector_version": p["screening_detector_version"],
        "derivation_instant": p["derivation_instant"],
        "screening_roots": p["screening_roots"],
        "empty_submission_result": p["empty_submission_result"],
        "resolved_closure": p["resolved_closure"],
        "applicability": p["applicability"],
        "measurement_tier": g["measurement_tier"],
        "gradeable": g["gradeable"],
        "knee_anchor_status": g["knee_anchor_status"],
        "timed_axis": True,
        "corpus_status": g["corpus_layout"]["corpus_status"],
        "memory_channel_bytes": g["corpus_layout"]["carry_schema"]["max_bytes"],
    }
    out.update(read_screening(HERE))
    return out


def roster_literal(roster, per_line=6):
    """A deterministic, readable Python tuple literal for the configuration roster."""
    rows, row = [], []
    for name in roster:
        row.append(repr(str(name)))
        if len(row) == per_line:
            rows.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        rows.append("    " + ", ".join(row) + ",")
    return "(\n" + "\n".join(rows) + "\n)"


def sorted_map(mapping):
    """A dict rebuilt in sorted key order, so its repr is stable across regenerations."""
    return dict((k, mapping[k]) for k in sorted(mapping))


def naive_dump_bytes(layout):
    """The size of the whole table written the obvious way, at full float precision.

    Measured rather than asserted, because the 2,048-byte cap is only a design pressure if the
    naive encoding actually overruns it. If a later edit widened the cap or narrowed the family
    until a raw dump fitted, CTL-NAIVE-DUMP would be measuring nothing and this generator would
    be emitting a check with no teeth. validate() refuses that.
    """
    schema = layout["carry_schema"]
    entry = dict((f, 0.12345678901234567) for f in schema["scalar_fields"])
    entry[schema["src_field"]] = schema["src_observed"]
    table = dict((config_id, entry) for config_id in layout["config_roster"])
    return len(json.dumps(table, sort_keys=True).encode("utf-8"))


def gcd(a, b):
    while b:
        a, b = b, a % b
    return a


def schedule_visits(layout, through_attempt):
    """config_id -> last scheduled visit at or before through_attempt, from the published rule."""
    schedule = layout["attempt_schedule"]
    roster = layout["config_roster"]
    table = {}
    for attempt in range(1, int(through_attempt) + 1):
        for offset in schedule["offsets"]:
            table[roster[(schedule["stride"] * attempt + offset) % schedule["modulus"]]] = attempt
    return table


def validate(grounding):
    """Refuse a grounding this generator cannot honestly compile.

    The refusals are this slot's own: a memory channel that does not bind, a schedule that does
    not reach every configuration, a time to live that does not actually expire the eight
    configurations the scored attempt is graded on. Each of those would leave a check in the
    emitted module asserting something no longer true of the design, which is worse than no check.
    """
    problems = []
    items = grounding["items"]
    ids = [i["id"] for i in items]
    if len(set(ids)) != len(ids):
        problems.append("duplicate item ids: %r" % sorted(set(x for x in ids if ids.count(x) > 1)))
    for item in items:
        if frozenset(item) != ITEM_SCHEMA:
            problems.append("item %r does not carry the closed item schema" % item.get("id"))
            continue
        if item["outcome_class"] not in OUTCOME_CLASSES:
            problems.append("item %r has outcome_class %r" % (item["id"], item["outcome_class"]))
        if item["evaluation_target"] not in grounding["evaluation_target_vocabulary"]:
            problems.append("item %r evaluates %r, which the vocabulary does not admit"
                            % (item["id"], item["evaluation_target"]))
        if not isinstance(item["weight"], int) or item["weight"] <= 0:
            problems.append("item %r carries weight %r" % (item["id"], item["weight"]))
        if item["mode"] != "compiled":
            problems.append("item %r is %r; this slot compiles every item"
                            % (item["id"], item["mode"]))
    targets = set(i["evaluation_target"] for i in items)
    for required in ("submitted_program", "proposed_carry_store", "harness_attempt_record"):
        if required not in targets:
            problems.append("no item evaluates %r, and this slot grades a program, a memory "
                            "channel and a host measurement" % required)
    unused = sorted(set(grounding["evaluation_target_vocabulary"]) - targets)
    if unused:
        problems.append("the vocabulary admits %s, which no item evaluates" % unused)
    outcome = [i["id"] for i in items if i["dimension"] == "outcome"]
    if len(outcome) != 1:
        problems.append("expected exactly one outcome item, found %r" % outcome)
    for name in RAMP:
        if grounding["constants"].get(name) is not None:
            problems.append("constant %r is authored at Phase 0; it is measured, not authored"
                            % name)

    layout = grounding.get("corpus_layout") or {}
    roster = layout.get("config_roster") or []
    count = layout.get("configuration_count")
    if len(roster) != count or len(set(roster)) != len(roster):
        problems.append("the configuration roster carries %d identifiers against a declared "
                        "count of %r, or repeats one" % (len(roster), count))
    schedule = layout.get("attempt_schedule") or {}
    for key in SCHEDULE_KEYS:
        if key not in schedule:
            problems.append("the attempt schedule does not publish %r" % key)
    if not problems:
        offsets = list(schedule["offsets"])
        modulus = int(schedule["modulus"])
        final = int(schedule["final_attempt"])
        wanted = int(schedule["final_attempt_configurations"])
        if modulus != len(roster):
            problems.append("the schedule's modulus %d is not the roster size %d"
                            % (modulus, len(roster)))
        if len(set(o % modulus for o in offsets)) != len(offsets):
            problems.append("the schedule's offsets collide modulo the roster size, so an "
                            "attempt would grade the same configuration twice")
        if len(offsets) != int(schedule["graded_per_attempt"]):
            problems.append("the schedule grades %d configurations an attempt but publishes %d "
                            "offsets" % (int(schedule["graded_per_attempt"]), len(offsets)))
        if gcd(int(schedule["stride"]), modulus) != 1:
            problems.append("the schedule's stride %d is not coprime with %d, so it never "
                            "reaches every configuration" % (int(schedule["stride"]), modulus))
        visits = schedule_visits(layout, final - 1)
        unvisited = sorted(set(roster) - set(visits))
        if unvisited:
            problems.append("the schedule never visits %s before the scored attempt" % unvisited)
        ranked = sorted(visits.items(), key=lambda kv: (kv[1], kv[0]))
        if wanted >= len(roster) or wanted < 1:
            problems.append("the scored attempt grades %d of %d configurations"
                            % (wanted, len(roster)))
        else:
            # The eight oldest must actually be stale. If the time to live outlived the gap
            # between a configuration's last scheduled visit and the scored attempt, the memory
            # would survive on the schedule alone and the archetype's decay would be decorative.
            oldest_age = final - ranked[0][1]
            youngest_of_the_eight = final - ranked[wanted - 1][1]
            if youngest_of_the_eight <= int(layout["carry_ttl_attempts"]):
                problems.append(
                    "the scored attempt's %d oldest-visited configurations are at most %d "
                    "attempts stale against a time to live of %d, so no entry ever expires on "
                    "the graded half of the table"
                    % (wanted, youngest_of_the_eight, int(layout["carry_ttl_attempts"])))
            if oldest_age < youngest_of_the_eight:
                problems.append("the oldest-visited ranking is inverted")
    schema = layout.get("carry_schema") or {}
    for key in CARRY_SCHEMA_KEYS:
        if key not in schema:
            problems.append("the carry schema does not publish %r" % key)
    if not problems:
        fields = list(schema["scalar_fields"])
        if len(fields) != 6 or len(set(fields)) != 6:
            problems.append("the carry schema names %d scalar fields; the design binds six "
                            "per-configuration constants" % len(fields))
        if schema["src_observed"] == schema["src_predicted"]:
            problems.append("the src field's two values are the same value")
        if schema["stamp_field"] not in list(schema["forbidden_fields"]):
            problems.append("the stamp field %r is not forbidden to the agent, and it is the one "
                            "field only the verifier may write" % schema["stamp_field"])
        if sorted(layout["carry_field_tolerances"]) != sorted(fields):
            problems.append("the per-field tolerances do not name exactly the six scalars")
        if any(numeric_or_none(v) is None or v < 0
               for v in layout["carry_field_tolerances"].values()):
            problems.append("a per-field tolerance is negative or is not a number")
        naive = naive_dump_bytes(layout)
        if naive <= int(schema["max_bytes"]):
            problems.append("the whole table dumps to %d bytes against a cap of %d, so the "
                            "channel does not bind and CTL-NAIVE-DUMP measures nothing"
                            % (naive, int(schema["max_bytes"])))
        if not schema["scale_min"] < schema["scale_max"]:
            problems.append("the published crop-scale band is empty")
    if tuple(layout.get("lifecycle_order") or ()) != ("validate", "stamp", "expire", "persist",
                                                      "report"):
        problems.append("the carry lifecycle order is %r; stamping after expiry would revive an "
                        "entry the rule had just dropped" % (layout.get("lifecycle_order"),))
    for key in ("carry_ttl_attempts", "timer_epsilon_s", "sibling_gap_max"):
        value = numeric_or_none(layout.get(key))
        if value is None or value <= 0:
            problems.append("%s is %r; it bounds a check and has to be a positive number"
                            % (key, layout.get(key)))
    gates = list(layout.get("gate_outcomes") or ())
    for key in ("cleared_gate", "below_bar_gate", "sibling_gap_gate"):
        if layout.get(key) not in gates:
            problems.append("%s is %r, which the published gate roster does not carry"
                            % (key, layout.get(key)))
    return problems


def numeric_or_none(value):
    if isinstance(value, bool) or value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def main():
    g = load_grounding()
    # The family validator runs FIRST and refuses rather than emitting: a generator that writes a
    # carrier it knows is malformed hands the drift check a moving target.
    problems = validate(g)
    if problems:
        raise SystemExit("AELLO-C8-S2 grounding is not well-formed: " + "; ".join(problems))

    layout = g["corpus_layout"]
    schema = layout["carry_schema"]
    schedule = layout["attempt_schedule"]
    outcome_id = [i["id"] for i in g["items"] if i["dimension"] == "outcome"][0]
    subst = {
        "slot_id": SLOT_ID,
        "outcome_id": outcome_id,
        "path": g["deliverable"]["path"],
        "proposed_carry": layout["proposed_carry_store"],
        "delivered_carry": layout["delivered_carry_store"],
        "canonical_carry": layout["canonical_carry_state"],
        "run_record": layout["run_record"],
        "reward_log": layout["reward_log"],
        "config_roster": roster_literal(layout["config_roster"]),
        "configuration_count": int(layout["configuration_count"]),
        "launch_flags": tuple(layout["launch_flags"]),
        "stride": int(schedule["stride"]),
        "offsets": tuple(schedule["offsets"]),
        "modulus": int(schedule["modulus"]),
        "graded_per_attempt": int(schedule["graded_per_attempt"]),
        "final_attempt": int(schedule["final_attempt"]),
        "final_attempt_configurations": int(schedule["final_attempt_configurations"]),
        "carry_max_bytes": int(schema["max_bytes"]),
        "scalar_fields": tuple(schema["scalar_fields"]),
        "src_field": schema["src_field"],
        "src_observed": int(schema["src_observed"]),
        "src_predicted": int(schema["src_predicted"]),
        "tag_field": schema["optional_tag_field"],
        "tag_max_bytes": int(schema["tag_max_bytes"]),
        "stamp_field": schema["stamp_field"],
        "flip_values": tuple(schema["flip_values"]),
        "off_min": int(schema["off_min"]),
        "off_max": int(schema["off_max"]),
        "scale_min": float(schema["scale_min"]),
        "scale_max": float(schema["scale_max"]),
        "rho_min": float(schema["rho_min"]),
        "amb_min": float(schema["amb_min"]),
        "amb_max": float(schema["amb_max"]),
        "tolerances": sorted_map(layout["carry_field_tolerances"]),
        "carry_ttl": int(layout["carry_ttl_attempts"]),
        "lifecycle_order": tuple(layout["lifecycle_order"]),
        "block_keys": tuple(layout["block_keys"]),
        "gate_outcomes": tuple(layout["gate_outcomes"]),
        "cleared_gate": layout["cleared_gate"],
        "below_bar_gate": layout["below_bar_gate"],
        "sibling_gap_gate": layout["sibling_gap_gate"],
        "hard_gates": tuple(sorted(set(layout["gate_outcomes"])
                                   - set([layout["cleared_gate"], layout["below_bar_gate"],
                                          layout["sibling_gap_gate"]]))),
        "sibling_gap_max": float(layout["sibling_gap_max"]),
        "timer_epsilon": float(layout["timer_epsilon_s"]),
        "log_accuracy": float(layout["log_tolerances"]["accuracy"]),
        "log_elapsed_fraction": float(layout["log_tolerances"]["elapsed_fraction"]),
        "source_limits": sorted_map(layout["source_limits"]),
        "seed_epsilon": float(layout["seed_divergence_epsilon"]),
        "budget_keys": tuple(layout["budget_keys"]),
        "guarded_writes": tuple(layout["guarded_writes"]),
    }

    # EVERY compiled item carries a written body, and the generator REFUSES when one does not.
    # The generic obligation lookup that used to stand here read a run-record key nothing writes,
    # so an item falling through to it consulted nothing and reported that it had passed.
    bodies = dict(BODIES)
    for it in g["items"]:
        if it["mode"] == "compiled" and it["id"] not in bodies:
            raise SystemExit("AELLO-C8-S2: no body written for compiled item %r; the generator "
                             "refuses rather than emitting a check that consults nothing"
                             % it["id"])
    stray = sorted(set(bodies) - set(i["id"] for i in g["items"]))
    if stray:
        raise SystemExit("AELLO-C8-S2: bodies %s belong to no item in the grounding" % stray)
    # The outcome check must SAY the slot is unmeasurable before it reads anything. Reading the
    # record first lets a missing-file failure mask the unmeasured signal, and the verifier then
    # reports gradeable=true with r_det=0.0. seed/build/freeze_batch.py refuses that bundle.
    statements = [ln.strip() for ln in bodies[outcome_id].splitlines()
                  if ln.strip() and not ln.strip().startswith("#")]
    if not statements or statements[0] != REQUIRE_FIRST:
        raise SystemExit("AELLO-C8-S2: %r must call require_measured as its first statement, "
                         "before it reads the attempt record" % outcome_id)

    tests_dir = os.path.join(BUNDLE, "tests")
    os.makedirs(tests_dir, exist_ok=True)

    # solution/TRUTH.md and solution/rubrics.json are PRIVATE_CARRIERS: seed/identity.py plants a
    # canary block into them at freeze, and canary normalisation is what keeps planting from
    # moving identity. A generator that rewrote them plainly would DROP the planted tripwire, and
    # the next content_hash would differ from the frozen one. So the planted block is carried
    # across the regeneration rather than recreated.
    truth_path = os.path.join(HERE, "TRUTH.md")
    truth = build_truth(g, TITLE).rstrip("\n") + "\n"
    keep = None
    if os.path.exists(truth_path):
        import re as _re
        m = _re.search(r"<!-- AELLO-CANARY-BLOCK.*?-->\n?", open(truth_path).read(), _re.S)
        keep = m.group(0) if m else None
    with open(truth_path, "w") as fh:
        fh.write(truth + ("\n" + keep if keep else ""))

    rub_path = os.path.join(HERE, "rubrics.json")
    rub = build_rubrics(g, ITEM_KEYS)
    if os.path.exists(rub_path):
        try:
            prev = json.load(open(rub_path))
            if "canary" in prev:
                rub["canary"] = prev["canary"]
        except Exception:
            pass
    with open(rub_path, "w") as fh:
        json.dump(rub, fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "rubrics.json"), "w") as fh:
        json.dump(build_rubrics(g, ITEM_KEYS), fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "test_output.py"), "w") as fh:
        # The tail arrives FINAL and is NOT substituted: it is family-shaped, it has already
        # resolved every placeholder it owns, and it legitimately contains percent signs of its
        # own, so formatting it a second time raises TypeError. Only the prelude is substituted.
        fh.write(build_tests(g, PRELUDE % subst, bodies) + TAIL)
    with open(os.path.join(tests_dir, "constants.json"), "w") as fh:
        json.dump(g["constants"], fh, indent=1, sort_keys=True)
        fh.write("\n")
    # ORDER MATTERS. `with open(path, "w")` truncates BEFORE its body's arguments are evaluated,
    # so calling read_identity() inside the with-statement reads the file this line just emptied
    # and writes nulls over the frozen identity. Read first, then open.
    prov = build_provenance(g, read_identity(HERE))
    with open(os.path.join(HERE, "provenance.yaml"), "w") as fh:
        # MATCH seed/build/screen_bind.py and the frozen generators exactly: sort_keys=True,
        # default_flow_style=False, width=100. The screen writes this carrier after the freeze,
        # so a generator using a different dump convention reorders the keys on the next
        # regeneration and reports as drift even though no value changed.
        yaml.safe_dump(prov, fh, sort_keys=True, default_flow_style=False, width=100,
                       allow_unicode=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
