"""Derivation for C3-S3: every canonical artifact descends from solution/grounding.yaml.

WHAT THIS GENERATOR EMITS AND WHY IT LOOKS LIKE THIS. The checks below are written about a
FOUR-DOMAIN mixture built to a hard 1.0B-token cap under a tokenizer the agent may not change,
graded on the WORST of four per-domain held-out bits-per-byte values. They read declared weights
against per-domain token counts the verifier recomputes by tracing spans to source digests, they
read domain labels out of the shipped source manifest rather than out of the submission, they
charge repeated spans to the budget every time they are emitted, and they reduce four values by
max in one fixed domain order. None of them would mean anything on a slot with one held-out
shard, one domain, or a tokenizer the agent builds.

The corpus has NOT landed in this bundle. Every path, domain label and disclosed parameter the
emitted checker names comes from grounding.yaml's corpus_layout block and is substituted into the
prelude, so the derivation source really is the source and this generator holds no corpus fact of
its own.

Every compiled item carries a hand-written body. There is no generic fallback: an item without a
body is a refusal, because the fallback this generator used to carry looked up
run_record()["obligations"][<ID>], a key nothing writes -- so an item that fell through to it
graded nothing at all and said so in no report.
"""
import json
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
# generator_common.py is VENDORED beside this file, not reached for outside the bundle. A staged
# tree could resolve seed/stage/<slug>/../../build; a DELIVERED tree at dataset/<uuid>/ cannot,
# and reaching outside would make the delivered bundle non-self-contained -- it would import in
# the stage and fail everywhere it actually ships.

SLOT_ID = 'C3-S3'
TITLE = "# C3-S3 -- what this task actually tests"
ITEM_KEYS = ('id', 'dimension', 'weight', 'evaluation_target', 'criterion', 'judgment', 'knockout',
             'mode')
ITEM_SCHEMA = frozenset(ITEM_KEYS + ('outcome_class',))
OUTCOME_CLASSES = frozenset(("EFFECT", "INVARIANT", "ABSENCE", "VALUE", "ORDERING"))
RAMP = ("floor", "knee", "dichotomizing_threshold", "reward_gate_pass_threshold")
OUTCOME_ITEM = "worst_domain_bits_per_byte_ramp"
DOMAINS = ("web", "encyclopedic", "scientific", "mathematical")


def read_identity(here):
    """Identity is an INPUT: the freeze computes it over the hashed tree and binds it into the
    carrier, which is hash-excluded, so reading it back keeps generation acyclic."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        if isinstance(doc.get("identity"), dict):
            return doc["identity"]
    return {"canonical_content_hash": None, "uuid": None,
            "normalization_domain": "aello.canary.norm/v1",
            "derivation": "uuid5(FORGE_TASK_NAMESPACE, canonical_content_hash)"}


def read_screening(here):
    """The screening instant and result are MEASURED OVER the frozen tree, so they are read back
    the way identity is; the carrier is hash-excluded, so binding them moves nothing."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        got = {k: doc[k] for k in ("screening_measured_at", "screening_expires_at",
                                   "screening_result") if k in doc}
        if got:
            return got
    return {"screening_measured_at": None, "screening_expires_at": None,
            "screening_result": None}


def load_grounding():
    with open(os.path.join(HERE, "grounding.yaml")) as fh:
        return yaml.safe_load(fh)


def _body(text):
    """A check body, inserted verbatim beneath `def test_<id>():`, so it keeps its own indent.

    Written as a block rather than as an escaped one-line literal: these bodies are the part of
    the bundle a reader has to be able to audit, and an escaped literal is unreadable exactly
    where reading matters most.
    """
    return text.strip("\n").rstrip()


# ==========================================================================================
# The emitted checker. PRELUDE carries the four-domain vocabulary and the disclosed task
# parameters and IS substituted; BODIES go in verbatim under their own decorator; TAIL is the
# reading machinery and is NOT substituted, because it carries percent formatting of its own.
# ==========================================================================================

PRELUDE = '''"""Compiled checks for %(slot_id)s. GENERATED by solution/recompute.py. DO NOT HAND-EDIT.

The graded object is a MIXTURE: a corpus drawn from four labelled source corpora to a hard token
cap, and the manifest that says in what proportion. The trainer, the evaluator and the tokenizer
are frozen and hash-pinned, so nothing below inspects a model. Every check reads delivered bytes --
the submitted manifest and span table, the shipped source manifest, or the harness's own record of
what the verifier measured and what the frozen trainer consumed -- and references no unmeasured
quantity, except %(outcome)s, which calls require_measured before it reads anything at all.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
SUBMISSION = %(path)r
CHECKS = []

# THE FOUR DOMAINS, in the fixed order the four per-domain values are reduced by max. The order is
# part of the grading contract and not a presentation choice: b_worst is an argmax over four
# floats, and a tie broken by dictionary order is a tie broken differently on a different build.
DOMAINS = %(domains)r

# The corpus layout, from solution/grounding.yaml's corpus_layout block. NOT LANDED in this
# bundle: these are the paths the landing wave writes to. Every reader below reports an absent
# path rather than guessing at what it would have contained.
SOURCE_MANIFEST = os.path.join(BUNDLE, %(source_manifest)r)
FROZEN_TOKENIZER = %(frozen_tokenizer)r
FROZEN_TRAINER = %(frozen_trainer)r
FINGERPRINTS = %(fingerprints)r
HELDOUT_SHARDS = %(heldout_shards)r
RUN_RECORD = os.path.join(BUNDLE, %(run_record)r)

# DISCLOSED TASK PARAMETERS, not measurements. Every one is published in instruction.md and none
# is a ramp constant: the cap is announced as a hard literal, and the four bits-per-byte values it
# is spent to lower never are.
TOKEN_BUDGET = %(token_budget)d
WEIGHT_TOLERANCE = %(weight_tolerance)r
BUILD_WALL_SECONDS = %(build_wall_seconds)d
TRAIN_WALL_SECONDS = %(train_wall_seconds)d
NGRAM_WIDTH = %(ngram_width)d
INTERLEAVE_BLOCKS = %(interleave_blocks)d

# The two real reference carriers the environment ships, plus the published tables the archetype
# expects to be recalled. Citing one is fine. Citing nothing else is the failure.
DECOY_TOKENS = %(decoy_tokens)r

# The closed reason set from seed/contract.yaml. A failing check names one of these or names a
# diagnostic of its own; the agent-visible surface still receives one float and at most one code.
ZERO_REASONS = %(zero_reasons)r


class ConstantUnmeasured(Exception):
    """Raised when a check needs a ramp constant that Phase 0 deliberately left null."""


def check(id, weight, knockout, kind):
    def deco(fn):
        CHECKS.append({"id": id, "weight": weight, "knockout": knockout, "kind": kind, "fn": fn})
        return fn
    return deco


def constants():
    with open(os.path.join(HERE, "constants.json")) as fh:
        return json.load(fh)


def require_measured(*names):
    c = constants()
    missing = [n for n in names if c.get(n) is None]
    if missing:
        raise ConstantUnmeasured(
            "%(slot_id)s: " + ", ".join(missing) + " are null. Phase 0 authors no measurement; "
            "the Phase 2 measurement wave writes these and this check becomes gradeable then.")
    return c


def evidence(**kw):
    return {"evaluation_target": kw.pop("target", "emitted_corpus"), "values": kw}
'''


TAIL = '''

# ------------------------------------------------------------------------------------------
# Reading the delivered bytes. One submission, one shipped source manifest, one harness record.
# Absent is REPORTED by every reader here, never guessed at and never allowed to look like a
# pass: on this slot an unproven attribution and a correct attribution are the same bytes.
# ------------------------------------------------------------------------------------------

def load_submission():
    """The graded artifact: the emitted order, the mixture that produced it, and its spans."""
    with open(SUBMISSION) as handle:
        doc = json.load(handle)
    if not isinstance(doc, dict):
        raise ValueError("the deliverable must be a JSON object carrying a mixture manifest")
    return doc


def describe(obj):
    return "keys=" + ",".join(sorted(obj)[:8])


def mixture_manifest():
    man = load_submission().get("mixture_manifest")
    if not isinstance(man, dict):
        raise ValueError("mixture_manifest is not an object")
    return man


def weights():
    """The declared per-domain sampling weights, as the submission wrote them."""
    w = mixture_manifest().get("weights")
    if not isinstance(w, dict) or not w:
        raise ValueError("mixture_manifest.weights is not a non-empty mapping")
    return dict((str(k), v) for k, v in w.items())


def repetition_epochs():
    """domain -> declared epoch count; 1 for anything the manifest does not name."""
    try:
        declared = mixture_manifest().get("repetition_epochs")
    except Exception:
        return {}
    if not isinstance(declared, dict):
        return {}
    out = {}
    for domain in DOMAINS:
        try:
            out[domain] = float(declared.get(domain, 1))
        except Exception:
            out[domain] = 1.0
    return out


def spans():
    """Per record, the list of (source_id, offset, length) triples it was assembled from.

    Recombination is permitted -- short scientific and mathematical fragments are meant to be
    packed into full-length records -- so a record carries a LIST of triples, not one triple.
    """
    table = load_submission().get("spans")
    if not isinstance(table, list) or not table:
        raise ValueError("spans is not a non-empty list")
    out = []
    for entry in table:
        out.append(entry if isinstance(entry, list) else [entry])
    return out


def span_fields(triple):
    """(source_id, offset, length, asserted_domain) from either shape a record may use."""
    if isinstance(triple, dict):
        source = triple.get("source_id")
        offset = triple.get("offset")
        length = triple.get("length")
        asserted = triple.get("domain")
    elif isinstance(triple, (list, tuple)) and len(triple) >= 3:
        source, offset, length = triple[0], triple[1], triple[2]
        asserted = triple[3] if len(triple) > 3 else None
    else:
        return None, None, None, None
    try:
        offset = int(offset)
        length = int(length)
    except Exception:
        return None, None, None, None
    if not isinstance(source, str) or not source:
        return None, None, None, None
    return source, offset, length, (str(asserted) if asserted is not None else None)


def source_manifest():
    """source_id -> domain, from the shipped four-corpus manifest.

    Empty when the corpus has not landed in this tree. Empty is not a pass anywhere: the checks
    that need attribution fall back to the verifier's own recorded resolution and fail closed
    when neither is present.
    """
    if not os.path.exists(SOURCE_MANIFEST):
        return {}
    try:
        with open(SOURCE_MANIFEST) as handle:
            doc = json.load(handle)
    except Exception:
        return {}
    if not isinstance(doc, dict):
        return {}
    doc = doc.get("sources", doc)
    out = {}
    for source_id, entry in doc.items() if isinstance(doc, dict) else []:
        domain = entry.get("domain") if isinstance(entry, dict) else entry
        if isinstance(domain, str):
            out[str(source_id)] = domain
    return out


def run_record():
    """What the graded run and the verifier recorded about the run.

    The agent writes part of this file, so it can be absent, truncated, or not JSON at all.
    Every one of those is an empty record here: an unparseable declaration declares nothing, and
    each check then reports its own missing-declaration reason instead of taking the verifier
    down with a decode error and returning no report about anything.
    """
    if not os.path.exists(RUN_RECORD):
        return {}
    try:
        with open(RUN_RECORD) as handle:
            doc = json.load(handle)
    except Exception:
        return {}
    return doc if isinstance(doc, dict) else {}


def measured():
    """The verifier's own measurements over the emitted corpus. Never an agent-reported number."""
    block = run_record().get("verifier_measured")
    return block if isinstance(block, dict) else {}


def integer_domain_map(name):
    """The four per-domain counts under `name`, as EXACT integers, or {} if that is not what they

    are. Integers are the point: per-domain weight realisation is exact token accounting, so a
    count arriving as 2.5e8 is a float proportion target wearing a count's name and the replay
    comparison it feeds could only ever have been approximate.
    """
    block = measured().get(name)
    if not isinstance(block, dict):
        return {}
    out = {}
    for domain in DOMAINS:
        value = block.get(domain)
        if isinstance(value, bool) or not isinstance(value, int):
            return {}
        out[domain] = value
    return out


def integer_map(block):
    """The same strictness applied to a mapping already in hand (the replay's own counts)."""
    if not isinstance(block, dict):
        return {}
    out = {}
    for domain in DOMAINS:
        value = block.get(domain)
        if isinstance(value, bool) or not isinstance(value, int):
            return {}
        out[domain] = value
    return out


def resolved_domain(source_id, manifest, recorded):
    return manifest.get(source_id, recorded.get(source_id))


def emitted_domain_order():
    """The domain of each emitted record, in emission order; [] when it cannot be resolved.

    A record recombines fragments; its domain is the domain of its spans. A record whose spans
    disagree is reported as 'mixed', which is a real answer rather than a failure to read: the
    interleave check cares whether every block puts all four domains in front of the trainer.
    """
    manifest = source_manifest()
    recorded = measured().get("span_domain_resolution") or {}
    if not isinstance(recorded, dict):
        recorded = {}
    if not manifest and not recorded:
        return []
    try:
        table = spans()
    except Exception:
        return []
    order = []
    for record in table:
        found = set()
        for triple in record:
            source_id = span_fields(triple)[0]
            if source_id is None:
                continue
            domain = resolved_domain(source_id, manifest, recorded)
            if domain is not None:
                found.add(domain)
        if len(found) == 1:
            order.append(found.pop())
        elif found:
            order.append("mixed")
        else:
            order.append(None)
    return order


def hex64(value):
    return (isinstance(value, str) and len(value) == 64
            and all(c in "0123456789abcdef" for c in value))


def as_float(value):
    try:
        number = float(value)
    except Exception:
        return None
    if number != number or number in (float("inf"), float("-inf")):
        return None
    return number


def measure():
    """(b_worst, argmax domain): the WORST of the four per-domain bits-per-byte values.

    All four are required. Reducing whichever domains happen to have been reported would let a
    three-domain report become a graded value, and the max-min structure is exactly the claim
    that three domains are not the score. The reduction runs in the fixed DOMAINS order so the
    argmax is stable in identity as well as in value.
    """
    block = measured().get("per_domain_bits_per_byte")
    if not isinstance(block, dict):
        raise ConstantUnmeasured(
            "the frozen evaluator reported no per-domain bits per byte; b_worst is a max over "
            "four and is undefined while any of them is missing")
    values = []
    for domain in DOMAINS:
        number = as_float(block.get(domain))
        if number is None:
            raise ConstantUnmeasured(
                "the frozen evaluator reported no finite bits per byte for the %s domain; "
                "b_worst is a max over four and is undefined while any of them is missing"
                % domain)
        values.append((domain, number))
    worst_domain, worst = values[0]
    for domain, number in values[1:]:
        if number > worst:
            worst_domain, worst = domain, number
    return worst, worst_domain
'''


BODIES = {

"mixture_manifest_declares_the_four_disclosed_domains": _body("""
    if not os.path.exists(SUBMISSION):
        return False, evidence(target="mixture_manifest", reason="no-submission", path=SUBMISSION)
    try:
        declared = weights()
    except Exception as exc:
        return False, evidence(target="mixture_manifest", error=str(exc),
                               reason="declared-mixture-divergence")
    unknown = sorted(label for label in declared if label not in DOMAINS)
    absent = [domain for domain in DOMAINS if domain not in declared]
    numeric = {}
    for label, value in declared.items():
        number = as_float(value)
        if number is not None:
            numeric[label] = number
    unusable = sorted(set(declared) - set(numeric))
    outside = sorted(label for label, number in numeric.items() if not 0.0 <= number <= 1.0)
    total = sum(numeric.get(domain, 0.0) for domain in DOMAINS)
    ok = not (unknown or absent or unusable or outside) and abs(total - 1.0) <= 1e-9
    return ok, evidence(target="mixture_manifest", declared_labels=sorted(declared),
                        unknown_labels=unknown, missing_domains=absent, non_numeric=unusable,
                        outside_unit_interval=outside, weight_total=total,
                        reason=None if ok else "declared-mixture-divergence")
"""),

"every_domain_receives_a_nonzero_token_share": _body("""
    realised = integer_domain_map("per_domain_tokens")
    if not realised:
        # An unmeasured count and a zero count are different claims, and only one of them is
        # about the agent. Neither is allowed to pass.
        return False, evidence(reason="realised-counts-unavailable",
                               detail="the verifier recorded no four-domain integer token counts")
    empty = [domain for domain in DOMAINS if realised[domain] <= 0]
    return (not empty), evidence(per_domain_tokens=realised, empty_domains=empty,
                                 reason=None if not empty else "domain-share-zero")
"""),

"per_domain_weights_are_post_dedup_token_shares": _body("""
    try:
        declared = weights()
        basis = str(mixture_manifest().get("weight_basis", "")).strip().lower()
    except Exception as exc:
        return False, evidence(target="mixture_manifest", error=str(exc),
                               reason="declared-mixture-divergence")
    realised = integer_domain_map("per_domain_tokens")
    if not realised:
        return False, evidence(target="mixture_manifest", reason="realised-counts-unavailable",
                               detail="the verifier recorded no four-domain integer token counts")
    total = sum(realised.values())
    if total <= 0:
        return False, evidence(target="mixture_manifest", reason="declared-mixture-divergence",
                               detail="the emitted corpus carries no tokens to take a share of")
    drift = {}
    for domain in DOMAINS:
        number = as_float(declared.get(domain))
        drift[domain] = (None if number is None
                         else abs(number - realised[domain] / float(total)))
    unusable = sorted(domain for domain in DOMAINS if drift[domain] is None)
    worst_drift = max([drift[d] for d in DOMAINS if drift[d] is not None] or [None])
    # WHICH WRONG BASIS. When the token comparison misses, the same comparison is run against
    # the two bases that produce a plausible-looking vector for free, so the report names the
    # mistake instead of only its size.
    matched_instead = []
    for name in ("per_domain_documents", "per_domain_pre_dedup_tokens"):
        other = integer_domain_map(name)
        other_total = sum(other.values()) if other else 0
        if other_total <= 0:
            continue
        spread = [abs(as_float(declared.get(d)) - other[d] / float(other_total))
                  for d in DOMAINS if as_float(declared.get(d)) is not None]
        if spread and max(spread) <= WEIGHT_TOLERANCE:
            matched_instead.append(name)
    ok = (not unusable) and basis == "post_dedup_tokens" and worst_drift is not None \\
        and worst_drift <= WEIGHT_TOLERANCE
    return ok, evidence(target="mixture_manifest", weight_basis=basis, tolerance=WEIGHT_TOLERANCE,
                        worst_absolute_drift=worst_drift, non_numeric_weights=unusable,
                        matched_basis_instead=matched_instead,
                        reason=None if ok else "declared-mixture-divergence")
"""),

"span_domain_read_from_the_source_manifest": _body("""
    try:
        table = spans()
    except Exception as exc:
        return False, evidence(target="source_manifest", error=str(exc), reason="no-submission")
    manifest = source_manifest()
    recorded = measured().get("span_domain_resolution") or {}
    if not isinstance(recorded, dict):
        recorded = {}
    if not manifest and not recorded:
        return False, evidence(target="source_manifest", reason="source-manifest-unavailable",
                               detail="neither the shipped source manifest nor the verifier's own "
                                      "resolution is present; unproven attribution is not proven "
                                      "attribution")
    malformed, unresolved, relabelled = [], [], []
    for position, record in enumerate(table):
        if not record:
            malformed.append(position)
            continue
        for triple in record:
            source_id, offset, length, asserted = span_fields(triple)
            if source_id is None or offset < 0 or length <= 0:
                malformed.append(position)
                continue
            actual = resolved_domain(source_id, manifest, recorded)
            if actual is None:
                unresolved.append(source_id)
            elif asserted is not None and asserted != actual:
                relabelled.append(source_id)
    if malformed or unresolved:
        reason = "foreign-content"
    elif relabelled:
        reason = "declared-mixture-divergence"
    else:
        reason = None
    return reason is None, evidence(target="source_manifest", records=len(table),
                                    malformed_records=sorted(set(malformed))[:8],
                                    unresolved_source_ids=sorted(set(unresolved))[:8],
                                    relabelled_source_ids=sorted(set(relabelled))[:8],
                                    reason=reason)
"""),

"repeated_spans_charged_to_the_budget_each_time": _body("""
    realised = integer_domain_map("per_domain_tokens")
    distinct = integer_domain_map("per_domain_distinct_span_tokens")
    consumed = measured().get("consumed_tokens")
    if not realised or not distinct or not isinstance(consumed, int) or isinstance(consumed, bool):
        return False, evidence(reason="repetition-accounting-unavailable",
                               detail="the verifier recorded no integer consumed count with the "
                                      "four realised and four distinct-span token counts")
    total = sum(realised.values())
    charged = total == consumed
    epochs = repetition_epochs()
    unpaid = [domain for domain in DOMAINS
              if epochs.get(domain, 1.0) > 1.0 and realised[domain] <= distinct[domain]]
    ok = charged and not unpaid
    reason = None
    if not charged:
        reason = "token-budget-accounting-divergence"
    elif unpaid:
        reason = "repetition-not-charged"
    return ok, evidence(per_domain_tokens=realised, per_domain_distinct_span_tokens=distinct,
                        consumed_tokens=consumed, declared_epochs=epochs,
                        domains_repeating_without_paying=unpaid, reason=reason)
"""),

"token_budget_counted_under_the_frozen_tokenizer": _body("""
    block = measured()
    counted = block.get("consumed_tokens")
    if not isinstance(counted, int) or isinstance(counted, bool):
        return False, evidence(reason="token-budget-unmeasured",
                               detail="the verifier recorded no integer count of its own encode of "
                                      "the emitted corpus")
    try:
        submitted = load_submission().get("consumed_tokens")
    except Exception:
        submitted = None
    digests = block.get("frozen_tokenizer_sha256")
    digests = digests if isinstance(digests, dict) else {}
    before, after = digests.get("before"), digests.get("after")
    tokenizer_held = hex64(before) and before == after
    within = counted <= TOKEN_BUDGET
    agrees = isinstance(submitted, int) and not isinstance(submitted, bool) and submitted == counted
    ok = within and agrees and tokenizer_held
    if not within:
        reason = "token-budget-exceeded"
    elif not tokenizer_held:
        reason = "frozen-trainer-modified"
    elif not agrees:
        reason = "declared-token-count-divergence"
    else:
        reason = None
    return ok, evidence(verifier_counted_tokens=counted, submitted_consumed_tokens=submitted,
                        budget=TOKEN_BUDGET, tokenizer_sha256_before=before,
                        tokenizer_sha256_after=after, tokenizer_path=FROZEN_TOKENIZER,
                        reason=reason)
"""),

"cross_domain_duplicates_charged_to_one_domain": _body("""
    try:
        policy = mixture_manifest().get("dedup")
    except Exception as exc:
        return False, evidence(target="mixture_manifest", error=str(exc),
                               reason="dedup-policy-undeclared")
    if not isinstance(policy, dict):
        return False, evidence(target="mixture_manifest", reason="dedup-policy-undeclared",
                               detail="mixture_manifest.dedup names no granularity for either scope")
    within = str(policy.get("within_domain_granularity", "")).strip().lower()
    across = str(policy.get("across_domain_granularity", "")).strip().lower()
    groups = measured().get("cross_domain_duplicate_groups")
    if not isinstance(groups, int) or isinstance(groups, bool):
        return False, evidence(target="mixture_manifest",
                               reason="cross-domain-duplicate-scan-unavailable",
                               within_domain_granularity=within,
                               across_domain_granularity=across)
    ok = bool(within) and across.startswith("document") and groups == 0
    return ok, evidence(target="mixture_manifest", within_domain_granularity=within,
                        across_domain_granularity=across, cross_domain_duplicate_groups=groups,
                        reason=None if ok else "cross-domain-duplicates-double-counted")
"""),

"four_domains_interleaved_across_the_single_pass": _body("""
    order = emitted_domain_order()
    if not order:
        return False, evidence(reason="emission-domains-unresolved",
                               detail="the emitted order carries no span domains to block up")
    block = measured()
    passes = block.get("consumption_passes")
    single_pass = (bool(block.get("consumption_order_matches_emission"))
                   and isinstance(passes, int) and not isinstance(passes, bool) and passes == 1)
    if len(order) < INTERLEAVE_BLOCKS * len(DOMAINS):
        return False, evidence(records=len(order), blocks=INTERLEAVE_BLOCKS,
                               reason="corpus-shorter-than-the-interleave-window",
                               detail="fewer records than one per domain per block, so an "
                                      "interleaved curriculum could not be expressed")
    size = (len(order) + INTERLEAVE_BLOCKS - 1) // INTERLEAVE_BLOCKS
    starved = {}
    for index in range(INTERLEAVE_BLOCKS):
        seen = set(order[index * size:(index + 1) * size])
        absent = [domain for domain in DOMAINS if domain not in seen]
        if absent:
            starved[index] = absent
    ok = single_pass and not starved
    return ok, evidence(records=len(order), blocks=INTERLEAVE_BLOCKS, block_size=size,
                        consumption_order_matches_emission=block.get(
                            "consumption_order_matches_emission"),
                        consumption_passes=passes,
                        blocks_missing_a_domain=dict((str(k), v) for k, v in starved.items()),
                        reason=None if ok else "emission-curriculum-not-interleaved")
"""),

"manifest_replay_reproduces_the_corpus_and_the_four_integer_counts": _body("""
    replay = run_record().get("manifest_replay")
    replay = replay if isinstance(replay, dict) else {}
    if not replay:
        return False, evidence(target="run_record", reason="recipe-corpus-divergence",
                               detail="the verifier recorded no re-execution of the mixture "
                                      "manifest")
    try:
        submitted_digest = load_submission().get("corpus_sha256")
    except Exception:
        submitted_digest = None
    produced = replay.get("corpus_sha256")
    fresh = bool(replay.get("fresh_checkout"))
    replay_counts = integer_map(replay.get("per_domain_tokens"))
    realised = integer_domain_map("per_domain_tokens")
    digest_ok = hex64(produced) and hex64(submitted_digest) and produced == submitted_digest
    counts_ok = bool(replay_counts) and bool(realised) and replay_counts == realised
    ok = fresh and digest_ok and counts_ok
    return ok, evidence(target="run_record", fresh_checkout=fresh,
                        submitted_corpus_sha256=submitted_digest, replayed_corpus_sha256=produced,
                        replayed_per_domain_tokens=replay_counts,
                        realised_per_domain_tokens=realised,
                        reason=None if ok else "recipe-corpus-divergence")
"""),

"heldout_thirteen_grams_absent_in_every_domain": _body("""
    block = measured()
    hits = block.get("fingerprint_hits")
    if not isinstance(hits, dict):
        return False, evidence(reason="eval-leak",
                               detail="no four-domain fingerprint scan is recorded; an unscanned "
                                      "corpus is not a clean one")
    counts, unscanned = {}, []
    for domain in DOMAINS:
        value = hits.get(domain)
        if not isinstance(value, int) or isinstance(value, bool):
            unscanned.append(domain)
        else:
            counts[domain] = value
    width = block.get("ngram_width")
    scope = block.get("fingerprint_scan_scope")
    attributed = block.get("fingerprint_scan_by")
    leaking = sorted(domain for domain, value in counts.items() if value != 0)
    ok = (not unscanned and not leaking and width == NGRAM_WIDTH
          and scope == "full_emitted_corpus" and attributed == "verifier")
    return ok, evidence(fingerprint_hits=counts, domains_unscanned=unscanned,
                        leaking_domains=leaking, ngram_width=width, scan_scope=scope,
                        scan_attributed_to=attributed, fingerprint_file=FINGERPRINTS,
                        reason=None if ok else "eval-leak")
"""),

"frozen_tokenizer_trainer_and_four_heldout_shards_unmoved": _body("""
    block = measured()
    before = block.get("frozen_digests_before")
    after = block.get("frozen_digests_after")
    before = before if isinstance(before, dict) else {}
    after = after if isinstance(after, dict) else {}
    required = (FROZEN_TRAINER, FROZEN_TOKENIZER, FINGERPRINTS) + tuple(HELDOUT_SHARDS)
    uncovered = [path for path in required if path not in before or path not in after]
    moved = sorted(path for path in before if after.get(path) != before[path])
    touched = sorted(str(path) for path in (run_record().get("guarded_paths_touched") or []))
    ok = not uncovered and not moved and not touched and set(before) == set(after)
    if touched:
        reason = "heldout-touched"
    elif moved:
        reason = "frozen-trainer-modified"
    elif uncovered or set(before) != set(after):
        reason = "frozen-digest-record-incomplete"
    else:
        reason = None
    return ok, evidence(target="frozen_grading_tree", paths_required=list(required),
                        paths_uncovered=uncovered, digests_moved=moved,
                        guarded_paths_touched=touched, reason=reason)
"""),

"selection_policy_rests_on_its_own_measurement": _body("""
    block = run_record().get("selection_evidence")
    if not isinstance(block, dict):
        return False, evidence(target="run_record", reason="prior-asserted-over-measurement",
                               detail="the run recorded no selection evidence at all, so the "
                                      "weights rest on nothing this environment produced")
    own = block.get("own_measurements")
    own = own if isinstance(own, list) else []
    covered = {}
    for entry in own:
        if not isinstance(entry, dict):
            continue
        domain = entry.get("domain")
        try:
            scored = int(entry.get("tokens_scored", 0))
        except Exception:
            scored = 0
        estimator = str(entry.get("estimator", "")).strip()
        artifact = str(entry.get("recorded_at", "")).strip()
        if domain in DOMAINS and scored > 0 and estimator and artifact:
            covered[domain] = scored
    unmeasured = [domain for domain in DOMAINS if domain not in covered]
    cited = [str(source).strip().lower()
             for source in (block.get("cited_sources") or []) if str(source).strip()]
    decoy_only = bool(cited) and all(
        any(token in source for token in DECOY_TOKENS) for source in cited)
    ok = not unmeasured and not decoy_only
    return ok, evidence(target="run_record", domains_measured_here=sorted(covered),
                        domains_unmeasured=unmeasured, cited_sources=cited,
                        cites_only_shipped_carriers=decoy_only,
                        reason=None if ok else "prior-asserted-over-measurement")
"""),

"mixture_and_dual_wall_accounting_declared": _body("""
    declaration = run_record().get("agent_budget_declaration")
    if declaration is None:
        return False, evidence(target="run_record", reason="no-agent-declaration")
    try:
        fields = json.loads(declaration) if isinstance(declaration, str) else dict(declaration)
    except Exception as exc:
        return False, evidence(target="run_record", reason="declaration-unparseable",
                               error=str(exc))
    absent = [key for key in ("build_seconds", "train_seconds", "per_domain_weights",
                              "repetition_epochs", "emission_curriculum") if key not in fields]
    if absent:
        return False, evidence(target="run_record", declared=sorted(fields), missing=absent,
                               reason="declaration-incomplete")
    try:
        manifest_weights = weights()
    except Exception:
        manifest_weights = {}
    declared_weights = fields.get("per_domain_weights")
    agrees = (isinstance(declared_weights, dict) and bool(manifest_weights)
              and set(declared_weights) == set(manifest_weights))
    if agrees:
        for domain in manifest_weights:
            left = as_float(declared_weights.get(domain))
            right = as_float(manifest_weights.get(domain))
            if left is None or right is None or abs(left - right) > 1e-9:
                agrees = False
                break
    block = measured()
    build = as_float(block.get("build_seconds"))
    train = as_float(block.get("train_seconds"))
    build_ok = build is not None and build <= BUILD_WALL_SECONDS
    train_ok = train is not None and train <= TRAIN_WALL_SECONDS
    ok = agrees and build_ok and train_ok
    if not build_ok:
        reason = "build-wallclock-exceeded"
    elif not train_ok:
        reason = "train-wallclock-exceeded"
    elif not agrees:
        reason = "declared-mixture-divergence"
    else:
        reason = None
    return ok, evidence(target="run_record", declared_weights=declared_weights,
                        manifest_weights=manifest_weights, host_build_seconds=build,
                        host_train_seconds=train, build_ceiling=BUILD_WALL_SECONDS,
                        train_ceiling=TRAIN_WALL_SECONDS, reason=reason)
"""),

OUTCOME_ITEM: _body("""
    c = require_measured("floor", "knee", "dichotomizing_threshold")
    # require_measured runs FIRST, before the submission, the manifest or the record is touched.
    # Reading a delivered byte ahead of it lets a missing-artifact failure be caught before the
    # unmeasured signal fires; the verifier then reports gradeable true with r_det 0.0, which
    # asserts the agent scored zero when the true claim is that the slot is not yet measurable.
    worst, worst_domain = measure()
    # Bits per byte DESCENDS, so the ramp is read in the descending direction: the floor is the
    # LARGER value and the knee the smaller. Subtracting in the ascending order would score a
    # well-mixed corpus at zero and an uncurated one at full reward.
    span = c["floor"] - c["knee"]
    s = 0.0 if span <= 0 else max(0.0, min(1.0, (c["floor"] - worst) / span))
    return s >= c["dichotomizing_threshold"], evidence(worst_domain_bits_per_byte=worst,
                                                       worst_domain=worst_domain, s_outcome=s)
"""),

}


def build_tests(g, prelude, bodies):
    """Assemble the compiled-check module. kind carries the item's own dimension."""
    chunks = [prelude]
    for raw in sorted(g["items"], key=lambda i: i["id"]):
        if raw["mode"] != "compiled":
            continue
        chunks.append('\n\n@check(id="%s", weight=%d, knockout=%s, kind="%s")\ndef test_%s():\n%s\n'
                      % (raw["id"], raw["weight"], raw["knockout"], raw["dimension"], raw["id"],
                         bodies[raw["id"]]))
    return "".join(chunks)


def build_truth(g, title):
    """Render solution/TRUTH.md from the frozen literals of solution/grounding.yaml."""
    n = g["truth_narrative"]
    lines = [title, "", "GENERATED SECTION. DO NOT HAND-EDIT.", "", n["opening"], "",
             "## The single most important insight", "", n["insight"], "",
             "## The ideal solve, step by step", ""]
    for i, step in enumerate(n["steps"], 1):
        lines += ["%d. **%s** %s" % (i, step["heading"], step["paragraph"]), ""]
    lines += ["## Traps that catch agents that are not thinking carefully", ""]
    lines += ["- " + t for t in n["traps"]]
    lines += ["", "---", "", "## Contract record (annex; not part of the narrative body)", "",
              "Retained under FORGE.md item 10e and Phase 2 item 7, which require this file to "
              "carry the ordered path through instruction.md with each satisfied checker "
              "identifier, and each rejected route bound to a measured known-wrong control. "
              "standards/truth-md-authoring-v1.md section 3 admits no fifth section, so this "
              "annex is a recorded deviation rather than an omission.", "", g["truth_annex"], ""]
    return "\n".join(lines) + "\n"


def build_rubrics(g, item_keys):
    """The 9g rubric carrier. The item schema is CLOSED at eight keys, so item 10f's outcome
    classification rides as a greppable prefix of the judgment rather than as a ninth key."""
    items = []
    for raw in g["items"]:
        item = {k: raw[k] for k in item_keys}
        item["judgment"] = "%s: %s" % (raw["outcome_class"], raw["judgment"])
        items.append(item)
    compiled = sum(i["weight"] for i in items if i["mode"] == "compiled")
    total = sum(i["weight"] for i in items)
    return {"$schema": "forge.rubric/v1",
            "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
            "generator": "solution/recompute.py",
            "compilation_floor": g["compilation_floor"],
            "compiled_weight_share": round(compiled / total, 6) if total else 0.0,
            "evaluation_target_vocabulary": sorted(g["evaluation_target_vocabulary"]),
            "items": sorted(items, key=lambda i: i["id"])}


def build_provenance(g, identity):
    p = g["provenance"]
    layout = g["corpus_layout"]
    out = {
        "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
        "generator": "solution/recompute.py from solution/grounding.yaml",
        "schema_version": "1.0",
        "slot_id": g["slot_id"],
        "identity": identity,
        "corpus": p["corpus"],
        "anchors": p["anchors"],
        "shards": p["shards"],
        "narrative": p["narrative"],
        "supersedes": p["supersedes"],
        "upstream_provenance": p["upstream_record"],
        "reward_composition": p["reward_composition"],
        "screening_interval_days": p["screening_interval_days"],
        "screening_detector_version": p["screening_detector_version"],
        "derivation_instant": p["derivation_instant"],
        "screening_roots": p["screening_roots"],
        "empty_submission_result": p["empty_submission_result"],
        "resolved_closure": p["resolved_closure"],
        "applicability": p["applicability"],
        "measurement_tier": g["measurement_tier"],
        "gradeable": g["gradeable"],
        "knee_anchor_status": g["knee_anchor_status"],
        "graded_domains": list(layout["domains"]),
        "corpus_layout_status": "authored-not-landed",
    }
    out.update(read_screening(HERE))
    return out


def validate(grounding):
    """Refuse on a malformed derivation source rather than emitting from one.

    The family validator that stood here reported one thing -- that a corpus string was
    non-empty -- which is true of every slot in this category and is why a generic item list
    could sit in this grounding unnoticed. These are the invariants the emitted checker actually
    depends on: without them a bad grounding produces a checker that imports and grades nothing.
    """
    problems = []
    items = grounding.get("items") or []
    if not items:
        problems.append("no items to compile")
    seen = set()
    for item in items:
        iid = item.get("id", "<unnamed>")
        if iid in seen:
            problems.append("duplicate item id %r" % iid)
        seen.add(iid)
        if set(item) != ITEM_SCHEMA:
            problems.append("item %r does not carry the closed schema: %s"
                            % (iid, sorted(set(item) ^ ITEM_SCHEMA)))
            continue
        if item["outcome_class"] not in OUTCOME_CLASSES:
            problems.append("item %r has outcome_class %r" % (iid, item["outcome_class"]))
        if item["evaluation_target"] not in grounding["evaluation_target_vocabulary"]:
            problems.append("item %r evaluates %r, which the vocabulary does not admit"
                            % (iid, item["evaluation_target"]))
        if not isinstance(item["weight"], int) or item["weight"] <= 0:
            problems.append("item %r carries weight %r" % (iid, item["weight"]))
    outcome = [i["id"] for i in items if i.get("dimension") == "outcome"]
    if outcome != [OUTCOME_ITEM]:
        problems.append("expected exactly the outcome item %r, found %r" % (OUTCOME_ITEM, outcome))
    for name in RAMP:
        if grounding["constants"].get(name) is not None:
            problems.append("constant %r is authored at Phase 0; it is measured, not authored"
                            % name)
    layout = grounding.get("corpus_layout") or {}
    if tuple(layout.get("domains") or ()) != DOMAINS:
        problems.append("corpus_layout.domains must be the four graded domains in the fixed "
                        "reduction order %r, found %r" % (list(DOMAINS), layout.get("domains")))
    shards = layout.get("heldout_shards") or []
    if len(shards) != len(DOMAINS) or len(set(shards)) != len(DOMAINS):
        problems.append("corpus_layout.heldout_shards must name one distinct shard per domain, "
                        "found %r" % (shards,))
    for domain in DOMAINS:
        if not any(domain in str(shard) for shard in shards):
            problems.append("no held-out shard is named for the %s domain" % domain)
    if layout.get("token_budget") != 1000000000:
        problems.append("corpus_layout.token_budget must be the disclosed hard cap 1000000000, "
                        "found %r" % (layout.get("token_budget"),))
    tolerance = layout.get("weight_tolerance")
    if not isinstance(tolerance, float) or not 0.0 < tolerance <= 0.05:
        problems.append("corpus_layout.weight_tolerance must be a disclosed fraction in (0, 0.05], "
                        "found %r" % (tolerance,))
    if layout.get("ngram_width") != 13:
        problems.append("corpus_layout.ngram_width must be 13, found %r"
                        % (layout.get("ngram_width"),))
    if not isinstance(layout.get("interleave_blocks"), int) or layout["interleave_blocks"] < 2:
        problems.append("corpus_layout.interleave_blocks must be an integer of at least 2, found "
                        "%r" % (layout.get("interleave_blocks"),))
    return problems


def main():
    g = load_grounding()
    # The validator runs FIRST and refuses rather than emitting: a generator that writes a
    # carrier it knows is malformed hands the drift check a moving target.
    problems = validate(g)
    if problems:
        raise SystemExit("C3-S3 grounding is not well-formed: " + "; ".join(problems))

    layout = g["corpus_layout"]
    subst = {"slot_id": SLOT_ID, "path": g["deliverable"]["path"], "outcome": OUTCOME_ITEM,
             "domains": tuple(layout["domains"]),
             "source_manifest": layout["source_manifest"],
             "frozen_tokenizer": layout["frozen_tokenizer"],
             "frozen_trainer": layout["frozen_trainer"],
             "fingerprints": layout["fingerprints"],
             "heldout_shards": tuple(layout["heldout_shards"]),
             "run_record": layout["run_record"],
             "token_budget": layout["token_budget"],
             "weight_tolerance": layout["weight_tolerance"],
             "build_wall_seconds": layout["build_wall_seconds"],
             "train_wall_seconds": layout["train_wall_seconds"],
             "ngram_width": layout["ngram_width"],
             "interleave_blocks": layout["interleave_blocks"],
             "decoy_tokens": tuple(layout["decoy_tokens"]),
             "zero_reasons": tuple(layout["zero_reasons"])}

    # EVERY compiled item carries a written body, and every written body belongs to an item.
    # The generic obligation lookup that used to stand here is gone: it consulted a run-record
    # key nothing writes, so an item that fell through to it graded nothing at all.
    bodies = dict(BODIES)
    for item in g["items"]:
        if item["mode"] == "compiled" and item["id"] not in bodies:
            raise SystemExit("C3-S3: no body is written for compiled item %r; refusing rather "
                             "than falling through to a generic obligation lookup" % item["id"])
    orphan = sorted(set(bodies) - {i["id"] for i in g["items"]})
    if orphan:
        raise SystemExit("C3-S3: bodies are written for items the grounding does not carry: "
                         + ", ".join(orphan))

    # THE OUTCOME BODY MUST ASK FOR ITS CONSTANTS BEFORE IT READS A DELIVERED BYTE.
    # seed/build/freeze_batch.py refuses to freeze a bundle that gets this wrong, so the
    # generator refuses one line earlier, where the fix is a body edit rather than a re-freeze.
    statements = [line.strip() for line in bodies[OUTCOME_ITEM].splitlines()
                  if line.strip() and not line.strip().startswith("#")]
    if not statements or not statements[0].startswith("c = require_measured("):
        raise SystemExit("C3-S3: %s must call require_measured as its first statement; it begins "
                         "%r" % (OUTCOME_ITEM, statements[0] if statements else ""))

    tests_dir = os.path.join(BUNDLE, "tests")
    os.makedirs(tests_dir, exist_ok=True)

    # solution/TRUTH.md and solution/rubrics.json are PRIVATE_CARRIERS: seed/identity.py plants a
    # canary block into them at freeze, and canary normalisation is what keeps planting from
    # moving identity. A generator that rewrote them plainly would DROP the planted tripwire, and
    # the next content_hash would differ from the frozen one. So the planted block is carried
    # across the regeneration rather than recreated.
    truth_path = os.path.join(HERE, "TRUTH.md")
    truth = build_truth(g, TITLE).rstrip("\n") + "\n"
    keep = None
    if os.path.exists(truth_path):
        import re as _re
        m = _re.search(r"<!-- AELLO-CANARY-BLOCK.*?-->\n?", open(truth_path).read(), _re.S)
        keep = m.group(0) if m else None
    with open(truth_path, "w") as fh:
        fh.write(truth + ("\n" + keep if keep else ""))

    rub_path = os.path.join(HERE, "rubrics.json")
    rub = build_rubrics(g, ITEM_KEYS)
    if os.path.exists(rub_path):
        try:
            prev = json.load(open(rub_path))
            if "canary" in prev:
                rub["canary"] = prev["canary"]
        except Exception:
            pass
    with open(rub_path, "w") as fh:
        json.dump(rub, fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "rubrics.json"), "w") as fh:
        json.dump(build_rubrics(g, ITEM_KEYS), fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "test_output.py"), "w") as fh:
        # The tail arrives FINAL and is NOT substituted: it is already resolved and it
        # legitimately carries percent signs of its own, so formatting it a second time here
        # raises TypeError. Only the prelude is substituted.
        fh.write(build_tests(g, PRELUDE % subst, bodies) + TAIL)
    with open(os.path.join(tests_dir, "constants.json"), "w") as fh:
        json.dump(g["constants"], fh, indent=1, sort_keys=True)
        fh.write("\n")
    # ORDER MATTERS. `with open(path, "w")` truncates BEFORE its body's arguments are evaluated,
    # so calling read_identity() inside the with-statement reads the file this line just emptied
    # and writes nulls over the frozen identity. Read first, then open.
    prov = build_provenance(g, read_identity(HERE))
    with open(os.path.join(HERE, "provenance.yaml"), "w") as fh:
        # MATCH seed/build/screen_bind.py and the frozen generators exactly: sort_keys=True,
        # default_flow_style=False, width=100. The screen writes this carrier after the freeze,
        # so a generator using a different dump convention reorders the keys on the next
        # regeneration and reports as drift even though no value changed.
        yaml.safe_dump(prov, fh, sort_keys=True, default_flow_style=False, width=100,
                       allow_unicode=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
