"""Derivation for AELLO-C8-S11: every canonical artifact descends from solution/grounding.yaml.

The graded object here is a KERNEL and the graded quantity is how long it takes, so every compiled
check below is about a measurement rather than about the contents of a submitted array. The
methodology parameters they read -- the warmup floor, the repetition floor, the admitted statistic
and clock rosters, the fidelity envelope, the pinned block shapes and trace seeds -- live in
grounding.yaml's corpus_layout block and are substituted into the emitted module, so a check never
carries a bound that this file's reader cannot find in the grounding.

Wired through seed/build/generator_common.py, which carries the five slot-agnostic functions
verified byte-for-byte against the three frozen generators. build_provenance stays here, per
family, for the reason recorded in that module.
"""
import json
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
# generator_common.py is VENDORED beside this file, not reached for outside the bundle. A staged
# tree could resolve seed/stage/<slug>/../../build; a DELIVERED tree at dataset/<uuid>/ cannot,
# and reaching outside would make the delivered bundle non-self-contained -- it would import in
# the stage and fail everywhere it actually ships.

SLOT_ID = 'AELLO-C8-S11'
TITLE = "# AELLO-C8-S11 -- what this task actually tests"
ITEM_KEYS = ('id', 'dimension', 'weight', 'evaluation_target', 'criterion', 'judgment', 'knockout',
             'mode')
ITEM_SCHEMA = frozenset(ITEM_KEYS + ('outcome_class',))
OUTCOME_CLASSES = frozenset(("EFFECT", "INVARIANT", "ABSENCE", "VALUE"))
RAMP = ("floor", "knee", "dichotomizing_threshold", "reward_gate_pass_threshold")
REQUIRE_FIRST = 'c = require_measured("floor", "knee", "dichotomizing_threshold")'
BLOCK_GEOMETRY_KEYS = ("id", "batch", "channels", "height", "width", "depthwise_kernel", "stride",
                       "pointwise_out", "trace_seed")


def read_identity(here):
    """Identity is an INPUT: the freeze computes it over the hashed tree and binds it into the
    carrier, which is hash-excluded, so reading it back keeps generation acyclic."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        if isinstance(doc.get("identity"), dict):
            return doc["identity"]
    return {"canonical_content_hash": None, "uuid": None,
            "normalization_domain": "aello.canary.norm/v1",
            "derivation": "uuid5(FORGE_TASK_NAMESPACE, canonical_content_hash)"}


def read_screening(here):
    """The screening instant and result are MEASURED OVER the frozen tree, so they are read back
    the way identity is; the carrier is hash-excluded, so binding them moves nothing."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        got = {k: doc[k] for k in ("screening_measured_at", "screening_expires_at",
                                   "screening_result") if k in doc}
        if got:
            return got
    return {"screening_measured_at": None, "screening_expires_at": None,
            "screening_result": None}


def load_grounding():
    with open(os.path.join(HERE, "grounding.yaml")) as fh:
        return yaml.safe_load(fh)


# --------------------------------------------------------------------------------------------
# The emitted checker module. PRELUDE is percent-substituted from corpus_layout, so every literal
# percent sign inside it is doubled. TAIL is not substituted at all.
# --------------------------------------------------------------------------------------------

PRELUDE = '''"""Compiled checks for %(slot_id)s. GENERATED by solution/recompute.py. DO NOT HAND-EDIT.

What is graded here is a MEASUREMENT, not an array. The submitted record says how long a
depthwise-separable block took on each pinned activation trace and how far its output drifted from
the vendored fp32 reference; these checks establish that the measurement was taken in a way that
means anything -- warmup discarded, a repetition floor met, a median rather than a best-of-n, a
clock that waits for the device -- and that the fidelity envelope holds on every graded shape
before any speed is credited. Every check runs against delivered bytes and references no unmeasured
quantity, except %(outcome_id)s, which raises ConstantUnmeasured while tests/constants.json carries
nulls.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
SUBMISSION = %(path)r

# The corpus layout, from solution/grounding.yaml. The activation traces are agent-visible because
# the kernel has to consume them; the fp32 reference outputs and the reference kernel's own latency
# are not, because a visible answer table is a kernel with no kernel in it.
ACTIVATION_TRACES = os.path.join(BUNDLE, %(activation_traces)r)
REFERENCE_OUTPUTS = os.path.join(BUNDLE, %(reference_outputs)r)
REFERENCE_LATENCY = os.path.join(BUNDLE, %(reference_latency)r)
RUN_RECORD = os.path.join(BUNDLE, %(run_record)r)

# The pinned graded set. Three depthwise-separable stages of the C8-S1 reference at CIFAR-100's
# 32x32 input, spatial extent halved and channels doubled at each downsample, batch held constant
# so the working set and not the batch is what changes between them.
GRADED_SHAPES = %(graded_shapes)s
PINNED_TRACE_SEEDS = %(pinned_trace_seeds)r
RECORD_KEYS = %(record_keys)r
BUDGET_KEYS = %(budget_keys)r

FUSION_BOUNDARIES = %(fusion_boundaries)r
UNFUSED_BOUNDARY = %(unfused_boundary)r
STAGE_SUM_TOLERANCE = %(stage_sum_tolerance)r
WARMUP_FLOOR = %(warmup_floor)r
TIMED_FLOOR = %(timed_floor)r
ADMITTED_STATISTICS = %(admitted_statistics)r
REJECTED_STATISTICS = %(rejected_statistics)r
ADMITTED_CLOCK_SOURCES = %(admitted_clock_sources)r
REJECTED_CLOCK_SOURCES = %(rejected_clock_sources)r
ENVELOPE = %(envelope)r
GUARDED_WRITES = %(guarded_writes)r

CHECKS = []


class ConstantUnmeasured(Exception):
    """Raised when a check needs a ramp constant that Phase 0 deliberately left null."""


def check(id, weight, knockout, kind):
    def deco(fn):
        CHECKS.append({"id": id, "weight": weight, "knockout": knockout, "kind": kind, "fn": fn})
        return fn
    return deco


def constants():
    with open(os.path.join(HERE, "constants.json")) as fh:
        return json.load(fh)


def require_measured(*names):
    c = constants()
    missing = [n for n in names if c.get(n) is None]
    if missing:
        raise ConstantUnmeasured(
            "%(slot_id)s: " + ", ".join(missing) + " are null. Phase 0 authors no measurement; "
            "the Phase 2 measurement wave writes these and this check becomes gradeable then.")
    return c


def evidence(**kw):
    return {"evaluation_target": kw.pop("target", "submitted_artifact"), "values": kw}
'''


TAIL = '''

# ------------------------------------------------------------------------------------------
# Reading the delivered bytes. One submitted record, one run record, and the two vendored
# references the verifier mounts. Absent is reported, never guessed at, and never passed over.
# ------------------------------------------------------------------------------------------

def load_submission():
    """The kernel's measurement record: one entry per graded block shape under `shapes`."""
    with open(SUBMISSION) as handle:
        doc = json.load(handle)
    if not isinstance(doc, dict):
        raise ValueError("the measurement record must be a JSON object")
    return doc


def describe(obj):
    return "keys=" + ",".join(sorted(str(k) for k in obj)[:6])


def shape_records():
    """shape id -> record, or {} when the report is absent, unparseable or carries no shapes.

    Empty covers three cases and every check that needs a record distinguishes them by its own
    reason string. None of them may take the verifier down with a decode error: a report that
    will not open is a finding about the submission, not a crash in the checker.
    """
    if not os.path.exists(SUBMISSION):
        return {}
    try:
        doc = load_submission()
    except Exception:
        return {}
    shapes = doc.get("shapes")
    if not isinstance(shapes, dict):
        return {}
    return dict((str(k), v) for k, v in shapes.items() if isinstance(v, dict))


def graded_shape_ids():
    """The pinned graded set, in the order grounding.yaml pins it."""
    return tuple(str(s["id"]) for s in GRADED_SHAPES)


def numeric(value):
    """A finite float, or None for anything that is not one -- including bools and NaN.

    A bool is an int in Python and `True` would otherwise read as an iteration count of one.
    """
    if isinstance(value, bool) or value is None:
        return None
    try:
        out = float(value)
    except (TypeError, ValueError):
        return None
    if out != out or out in (float("inf"), float("-inf")):
        return None
    return out


def token(value):
    """A declared vocabulary word, normalised the one way every roster here is written."""
    return str(value).strip().lower().replace("-", "_").replace(" ", "_")


def run_record():
    """What the graded run declared about itself.

    The agent writes this file, so it can be absent, truncated, or not JSON at all. Every one of
    those is an empty record here: an unparseable declaration declares nothing, and each check
    then reports its own missing-declaration reason instead of taking the verifier down.
    """
    if not os.path.exists(RUN_RECORD):
        return {}
    try:
        with open(RUN_RECORD) as handle:
            doc = json.load(handle)
    except Exception:
        return {}
    return doc if isinstance(doc, dict) else {}


def in_guarded_tree(path):
    """True when a written path lands in the checker tree or on a vendored corpus archive."""
    flat = "/" + str(path).replace("\\\\", "/").lstrip("./").lstrip("/")
    return any(token_ in flat for token_ in GUARDED_WRITES)


def envelope_verdict(record):
    """RECOMPUTED from the two reported errors; the record's own verdict is never taken on trust.

    Returns (ok, reason, errors). A record that reports no error at all fails here rather than
    defaulting to conforming: the envelope is a gate, and an ungated gate is worse than none.
    """
    errors = {"max_abs_error": numeric(record.get("max_abs_error")),
              "max_rel_error": numeric(record.get("max_rel_error"))}
    if errors["max_abs_error"] is None or errors["max_rel_error"] is None:
        return False, "fidelity_error_not_reported", errors
    if errors["max_abs_error"] < 0 or errors["max_rel_error"] < 0:
        return False, "negative_fidelity_error", errors
    if errors["max_abs_error"] > ENVELOPE["max_abs_error"]:
        return False, "max_abs_error_outside_envelope", errors
    if errors["max_rel_error"] > ENVELOPE["max_rel_error"]:
        return False, "max_rel_error_outside_envelope", errors
    return True, None, errors


def harness_latencies():
    """shape id -> the HARNESS's own measured kernel wall-clock in milliseconds.

    Not the report's number. Red line 2 is reporting a timing the harness did not measure, so the
    graded quantity is read from the harness's record and the submitted record is graded against
    it rather than trusted in place of it.
    """
    got = run_record().get("harness_kernel_latency_ms")
    if not isinstance(got, dict):
        return {}
    return dict((str(k), v) for k, v in got.items())


def reference_latencies():
    """shape id -> the vendored reference kernel's measured wall-clock, from tests/heldout/."""
    if not os.path.exists(REFERENCE_LATENCY):
        return {}
    try:
        with open(REFERENCE_LATENCY) as handle:
            doc = json.load(handle)
    except Exception:
        return {}
    doc = doc.get("block_ms", doc) if isinstance(doc, dict) else {}
    if not isinstance(doc, dict):
        return {}
    return dict((str(k), v) for k, v in doc.items())


def measure():
    """Geometric-mean speedup over the vendored reference kernel, zero outside the envelope.

    The geometric mean, not the arithmetic one: these are ratios across shapes whose absolute
    latencies differ by more than an order of magnitude, and an arithmetic mean over ratios lets
    one cheap shape's large ratio carry the score for two expensive shapes it says nothing about.

    The envelope is read BEFORE the ratios are formed. That ordering is the whole gate: a kernel
    outside the envelope on one of three shapes returns 0.0 here rather than a two-thirds score,
    which is what makes a fast wrong kernel worth nothing instead of worth most of it.
    """
    measured = harness_latencies()
    if not measured:
        raise ConstantUnmeasured("the harness recorded no per-shape kernel wall-clock")
    reference = reference_latencies()
    if not reference:
        raise ConstantUnmeasured("the vendored reference kernel's latency has not landed")
    records = shape_records()
    for shape_id in graded_shape_ids():
        ok, _reason, _errors = envelope_verdict(records.get(shape_id) or {})
        if not ok:
            return 0.0
    ratios = []
    for shape_id in graded_shape_ids():
        mine = numeric(measured.get(shape_id))
        theirs = numeric(reference.get(shape_id))
        if mine is None or theirs is None or mine <= 0 or theirs <= 0:
            raise ConstantUnmeasured(
                "shape %s carries no harness-measured latency pair" % shape_id)
        ratios.append(theirs / mine)
    product = 1.0
    for ratio in ratios:
        product *= ratio
    return product ** (1.0 / len(ratios))
'''


# --------------------------------------------------------------------------------------------
# BODIES. Every compiled item carries one, written for this slot. There is no generic obligation
# lookup behind them: the fallback that used to stand here consulted a run-record key nothing
# writes, so an item that fell through to it graded nothing at all and said so in no report.
# --------------------------------------------------------------------------------------------

BODIES = {
    "latency_report_lands": '''
    if not os.path.exists(SUBMISSION):
        return False, evidence(reason="submission_missing", path=SUBMISSION)
    try:
        doc = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    shapes = doc.get("shapes")
    if not isinstance(shapes, dict) or not shapes:
        return False, evidence(reason="no_per_shape_records", shape=describe(doc))
    return True, evidence(path=SUBMISSION, measured_shapes=sorted(str(k) for k in shapes))''',

    "every_graded_block_shape_measured": '''
    records = shape_records()
    if not records:
        return False, evidence(reason="no_per_shape_records")
    want, got = set(graded_shape_ids()), set(records)
    missing, unrecognised = sorted(want - got), sorted(got - want)
    incomplete = sorted(shape_id for shape_id in (want & got)
                        if [k for k in RECORD_KEYS if k not in records[shape_id]])
    ok = not (missing or unrecognised or incomplete)
    return ok, evidence(graded_shapes=list(graded_shape_ids()), missing=missing,
                        unrecognised=unrecognised, incomplete=incomplete,
                        reason=None if ok else "graded_shape_set_not_covered")''',

    "depthwise_and_pointwise_timed_as_separate_stages": '''
    records = shape_records()
    if not records:
        return False, evidence(reason="no_per_shape_records")
    findings = []
    for shape_id in sorted(records):
        record = records[shape_id]
        boundary = token(record.get("fusion_boundary"))
        if boundary not in FUSION_BOUNDARIES:
            findings.append({"shape": shape_id, "declared": boundary,
                             "reason": "unrecognised_fusion_boundary"})
            continue
        if boundary != UNFUSED_BOUNDARY:
            # A fused block has no separable stage time. A record that reports one anyway is
            # reporting an attribution it cannot have measured.
            if record.get("depthwise_ms") is not None or record.get("pointwise_ms") is not None:
                findings.append({"shape": shape_id, "declared": boundary,
                                 "reason": "fused_record_carries_a_stage_split"})
            continue
        depthwise = numeric(record.get("depthwise_ms"))
        pointwise = numeric(record.get("pointwise_ms"))
        block = numeric(record.get("block_ms"))
        if depthwise is None or pointwise is None or block is None or block <= 0:
            findings.append({"shape": shape_id, "reason": "unfused_record_missing_a_stage_time"})
        elif abs(depthwise + pointwise - block) > STAGE_SUM_TOLERANCE * block:
            findings.append({"shape": shape_id, "depthwise_ms": depthwise,
                             "pointwise_ms": pointwise, "block_ms": block,
                             "reason": "stage_times_do_not_sum_to_the_block"})
    return (not findings), evidence(stage_findings=findings,
                                    tolerance_fraction=STAGE_SUM_TOLERANCE,
                                    reason=None if not findings
                                    else "stage_decomposition_unsound")''',

    "warmup_iterations_excluded_from_the_timed_window": '''
    records = shape_records()
    if not records:
        return False, evidence(reason="no_per_shape_records")
    findings = []
    for shape_id in sorted(records):
        record = records[shape_id]
        warmup = numeric(record.get("warmup_iterations"))
        if warmup is None or warmup < WARMUP_FLOOR:
            findings.append({"shape": shape_id, "warmup_iterations": record.get(
                "warmup_iterations"), "reason": "warmup_below_floor"})
        elif record.get("warmup_excluded") is not True:
            findings.append({"shape": shape_id, "reason": "warmup_not_declared_excluded"})
    return (not findings), evidence(warmup_findings=findings, warmup_floor=WARMUP_FLOOR,
                                    reason=None if not findings
                                    else "timed_window_includes_warmup")''',

    "reported_latency_is_a_median_not_a_best_of_n": '''
    records = shape_records()
    if not records:
        return False, evidence(reason="no_per_shape_records")
    findings = []
    for shape_id in sorted(records):
        record = records[shape_id]
        statistic = token(record.get("statistic"))
        repetitions = numeric(record.get("timed_iterations"))
        if statistic in REJECTED_STATISTICS:
            findings.append({"shape": shape_id, "statistic": statistic,
                             "reason": "best_of_n_is_not_a_latency"})
        elif statistic not in ADMITTED_STATISTICS:
            findings.append({"shape": shape_id, "statistic": statistic,
                             "reason": "unrecognised_statistic"})
        elif repetitions is None or repetitions < TIMED_FLOOR:
            findings.append({"shape": shape_id,
                             "timed_iterations": record.get("timed_iterations"),
                             "reason": "repetition_count_below_floor"})
    return (not findings), evidence(statistic_findings=findings,
                                    admitted=list(ADMITTED_STATISTICS),
                                    repetition_floor=TIMED_FLOOR,
                                    reason=None if not findings
                                    else "reported_statistic_is_not_a_median")''',

    "device_synchronised_clock_not_async_launch_return": '''
    records = shape_records()
    if not records:
        return False, evidence(reason="no_per_shape_records")
    findings = []
    for shape_id in sorted(records):
        source = token(records[shape_id].get("clock_source"))
        if source in REJECTED_CLOCK_SOURCES:
            findings.append({"shape": shape_id, "clock_source": source,
                             "reason": "host_timer_around_an_async_launch"})
        elif source not in ADMITTED_CLOCK_SOURCES:
            findings.append({"shape": shape_id, "clock_source": source,
                             "reason": "unrecognised_clock_source"})
    return (not findings), evidence(clock_findings=findings,
                                    admitted=list(ADMITTED_CLOCK_SOURCES),
                                    reason=None if not findings
                                    else "clock_source_does_not_measure_the_kernel")''',

    "fidelity_envelope_holds_on_every_graded_shape": '''
    records = shape_records()
    if not records:
        return False, evidence(reason="no_per_shape_records")
    findings = []
    for shape_id in graded_shape_ids():
        record = records.get(shape_id)
        if record is None:
            findings.append({"shape": shape_id, "reason": "no_fidelity_record"})
            continue
        ok, reason, errors = envelope_verdict(record)
        if not ok:
            findings.append(dict(errors, shape=shape_id, reason=reason))
        elif record.get("within_envelope") is not True:
            # The errors clear the envelope and the record says they do not. One of the two was
            # not measured, and a self-contradicting fidelity record is not evidence of fidelity.
            findings.append(dict(errors, shape=shape_id,
                                 reason="record_contradicts_its_own_errors"))
    return (not findings), evidence(envelope=ENVELOPE, envelope_findings=findings,
                                    reason=None if not findings
                                    else "outside_fidelity_envelope")''',

    "pinned_trace_seeds_are_the_measured_inputs": '''
    declared = run_record().get("trace_seeds")
    if declared is None:
        return False, evidence(target="run_record", reason="no_trace_seeds_declared")
    try:
        seeds = sorted(int(s) for s in declared)
    except (TypeError, ValueError):
        return False, evidence(target="run_record", declared=str(declared)[:160],
                               reason="trace_seeds_unparseable")
    records = shape_records()
    unnamed = [shape["id"] for shape in GRADED_SHAPES
               if numeric((records.get(str(shape["id"])) or {}).get("trace_seed"))
               != float(shape["trace_seed"])]
    pinned = sorted(PINNED_TRACE_SEEDS)
    ok = seeds == pinned and not unnamed
    return ok, evidence(target="run_record", declared_seeds=seeds, pinned_seeds=pinned,
                        shapes_not_on_their_pinned_trace=unnamed,
                        reason=None if ok else "measured_inputs_are_not_the_pinned_traces")''',

    "vendored_traces_and_checker_tree_unwritten": '''
    record = run_record()
    # The harness's own list is the authority; the run's declaration corroborates it. A post-hoc
    # scan cannot separate a write made during the graded run from one made before it.
    harness = [p for p in record.get("guarded_paths_touched", []) if in_guarded_tree(p)]
    declared = [p for p in record.get("paths_written", []) if in_guarded_tree(p)]
    touched = sorted(set(harness) | set(declared))
    before = record.get("trace_digest_before")
    after = record.get("trace_digest_after")
    if before is None or after is None:
        return False, evidence(target="submitted_source", touched=touched,
                               reason="no_trace_digest_recorded")
    moved = before != after
    ok = (not touched) and not moved
    return ok, evidence(target="submitted_source", touched=touched, trace_digest_moved=moved,
                        reason=None if ok else ("trace_corpus_rewritten" if moved
                                                else "wrote_into_guarded_tree"))''',

    "replay_reproduces_outputs_but_not_timings": '''
    replay = run_record().get("replay")
    if not isinstance(replay, dict) or not replay:
        return False, evidence(target="submitted_source", reason="replay_unrecorded")
    records = shape_records()
    if not records:
        return False, evidence(target="submitted_source", reason="no_per_shape_records")
    diverged, identical, absent, unreported, compared = [], [], [], [], 0
    for shape_id in graded_shape_ids():
        first = records.get(shape_id)
        again = replay.get(shape_id)
        if not isinstance(first, dict):
            # Absent from the report is a coverage finding, not a divergence. Reporting it as a
            # digest mismatch would name the wrong defect on a shape that was never measured.
            unreported.append(shape_id)
            continue
        if not isinstance(again, dict):
            absent.append(shape_id)
            continue
        compared += 1
        if first.get("output_sha256") != again.get("output_sha256"):
            diverged.append(shape_id)
        one, two = numeric(first.get("block_ms")), numeric(again.get("block_ms"))
        if one is not None and two is not None and one == two:
            identical.append(shape_id)
    fabricated = compared > 0 and len(identical) == compared
    ok = compared > 0 and not unreported and not absent and not diverged and not fabricated
    return ok, evidence(target="submitted_source", shapes_compared=compared,
                        shapes_absent_from_report=unreported,
                        shapes_absent_from_replay=absent, outputs_diverged=diverged,
                        latencies_bit_identical=identical,
                        reason=None if ok else ("shape_never_measured" if unreported
                                                else "shape_absent_from_replay" if absent
                                                else "kernel_outputs_not_reproducible"
                                                if diverged
                                                else "latencies_identical_across_runs"))''',

    "measurement_budget_declared": '''
    declaration = run_record().get("agent_budget_declaration")
    if declaration is None:
        return False, evidence(target="run_record", reason="no_agent_declaration")
    try:
        declared = (json.loads(declaration) if isinstance(declaration, str)
                    else dict(declaration))
    except Exception as exc:
        return False, evidence(target="run_record", reason="declaration_unparseable",
                               error=str(exc))
    missing = [k for k in BUDGET_KEYS if k not in declared]
    not_a_count = [k for k in BUDGET_KEYS if k in declared
                   and (numeric(declared[k]) is None or numeric(declared[k]) < 0)]
    ok = not missing and not not_a_count
    return ok, evidence(target="run_record", declared=sorted(str(k) for k in declared),
                        missing=missing, not_a_count=not_a_count,
                        reason=None if ok else "measurement_budget_not_declared")''',

    "envelope_gated_speedup_ramp": '''
    # require_measured FIRST, before anything is read. Reading the submission before saying the
    # slot is not yet measurable lets a missing-file error mask the unmeasured signal, and the
    # verifier then reports gradeable=true with r_det=0.0 -- which asserts the agent scored zero
    # where the honest claim is that the slot cannot yet be scored at all.
    c = require_measured("floor", "knee", "dichotomizing_threshold")
    speedup = measure()
    span = c["knee"] - c["floor"]
    s = 0.0 if span <= 0 else max(0.0, min(1.0, (speedup - c["floor"]) / span))
    return speedup >= c["dichotomizing_threshold"], evidence(speedup=speedup, s_outcome=s)''',
}


def build_tests(g, prelude, bodies):
    """Assemble the compiled-check module. kind carries the item's own dimension."""
    chunks = [prelude]
    for raw in sorted(g["items"], key=lambda i: i["id"]):
        if raw["mode"] != "compiled":
            continue
        chunks.append('\n\n@check(id="%s", weight=%d, knockout=%s, kind="%s")\ndef test_%s():\n%s\n'
                      % (raw["id"], raw["weight"], raw["knockout"], raw["dimension"], raw["id"],
                         bodies[raw["id"]].strip("\n")))
    return "".join(chunks)


def build_truth(g, title):
    """Render solution/TRUTH.md from the frozen literals of solution/grounding.yaml."""
    n = g["truth_narrative"]
    lines = [title, "", "GENERATED SECTION. DO NOT HAND-EDIT.", "", n["opening"], "",
             "## The single most important insight", "", n["insight"], "",
             "## The ideal solve, step by step", ""]
    for i, step in enumerate(n["steps"], 1):
        lines += ["%d. **%s** %s" % (i, step["heading"], step["paragraph"]), ""]
    lines += ["## Traps that catch agents that are not thinking carefully", ""]
    lines += ["- " + t for t in n["traps"]]
    lines += ["", "---", "", "## Contract record (annex; not part of the narrative body)", "",
              "Retained under FORGE.md item 10e and Phase 2 item 7, which require this file to "
              "carry the ordered path through instruction.md with each satisfied checker "
              "identifier, and each rejected route bound to a measured known-wrong control. "
              "standards/truth-md-authoring-v1.md section 3 admits no fifth section, so this "
              "annex is a recorded deviation rather than an omission.", "", g["truth_annex"], ""]
    return "\n".join(lines) + "\n"


def build_rubrics(g, item_keys):
    """The 9g rubric carrier. The item schema is CLOSED at eight keys, so item 10f's outcome
    classification rides as a greppable prefix of the judgment rather than as a ninth key."""
    items = []
    for raw in g["items"]:
        item = {k: raw[k] for k in item_keys}
        item["judgment"] = "%s: %s" % (raw["outcome_class"], raw["judgment"])
        items.append(item)
    compiled = sum(i["weight"] for i in items if i["mode"] == "compiled")
    total = sum(i["weight"] for i in items)
    return {"$schema": "forge.rubric/v1",
            "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
            "generator": "solution/recompute.py",
            "compilation_floor": g["compilation_floor"],
            "compiled_weight_share": round(compiled / total, 6) if total else 0.0,
            "evaluation_target_vocabulary": sorted(g["evaluation_target_vocabulary"]),
            "items": sorted(items, key=lambda i: i["id"])}


def build_provenance(g, identity):
    p = g["provenance"]
    out = {
        "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
        "generator": "solution/recompute.py from solution/grounding.yaml",
        "schema_version": "1.0",
        "slot_id": g["slot_id"],
        "identity": identity,
        "corpus": p["corpus"],
        "anchors": p["anchors"],
        "shards": p["shards"],
        "narrative": p["narrative"],
        "supersedes": p["supersedes"],
        "upstream_provenance": p["upstream_record"],
        "reward_composition": p["reward_composition"],
        "screening_interval_days": p["screening_interval_days"],
        "screening_detector_version": p["screening_detector_version"],
        "derivation_instant": p["derivation_instant"],
        "screening_roots": p["screening_roots"],
        "empty_submission_result": p["empty_submission_result"],
        "resolved_closure": p["resolved_closure"],
        "applicability": p["applicability"],
        "measurement_tier": g["measurement_tier"],
        "gradeable": g["gradeable"],
        "knee_anchor_status": g["knee_anchor_status"],
        "timed_axis": True,
        "corpus_status": g["corpus_layout"]["corpus_status"],
    }
    out.update(read_screening(HERE))
    return out


def shapes_literal(shapes):
    """A deterministic Python literal for the pinned block shapes.

    Built from sorted items so the emitted module does not inherit whatever key order the YAML
    loader happened to hand back; the same grounding must produce the same bytes twice.
    """
    rows = "".join("    %r,\n" % (dict(sorted(s.items())),) for s in shapes)
    return "(\n" + rows + ")"


def validate(grounding):
    """Refuse a grounding this generator cannot honestly compile.

    A timed axis is graded on harness measurement, never on a self-reported duration, and a
    latency this slot grades is only meaningful against a pinned shape set, a pinned input and a
    published methodology. Each of those is checked here rather than assumed downstream.
    """
    problems = []
    items = grounding["items"]
    ids = [i["id"] for i in items]
    if len(set(ids)) != len(ids):
        problems.append("duplicate item ids: %r" % sorted(set(x for x in ids if ids.count(x) > 1)))
    for item in items:
        if frozenset(item) != ITEM_SCHEMA:
            problems.append("item %r does not carry the closed item schema" % item.get("id"))
            continue
        if item["outcome_class"] not in OUTCOME_CLASSES:
            problems.append("item %r has outcome_class %r" % (item["id"], item["outcome_class"]))
        if item["evaluation_target"] not in grounding["evaluation_target_vocabulary"]:
            problems.append("item %r evaluates %r, which the vocabulary does not admit"
                            % (item["id"], item["evaluation_target"]))
        if not isinstance(item["weight"], int) or item["weight"] <= 0:
            problems.append("item %r carries weight %r" % (item["id"], item["weight"]))
    targets = {i["evaluation_target"] for i in items}
    if "run_record" not in targets:
        problems.append("a timed slot must grade against the harness run record")
    unused = sorted(set(grounding["evaluation_target_vocabulary"]) - targets)
    if unused:
        problems.append("the vocabulary admits %s, which no item evaluates" % unused)
    outcome = [i["id"] for i in items if i["dimension"] == "outcome"]
    if len(outcome) != 1:
        problems.append("expected exactly one outcome item, found %r" % outcome)
    for name in RAMP:
        if grounding["constants"].get(name) is not None:
            problems.append("constant %r is authored at Phase 0; it is measured, not authored"
                            % name)

    layout = grounding.get("corpus_layout") or {}
    shapes = layout.get("graded_block_shapes") or []
    if len(shapes) < 3:
        problems.append("the graded set must pin at least three block shapes, found %d"
                        % len(shapes))
    if len({s.get("id") for s in shapes}) != len(shapes):
        problems.append("graded block shape ids are not distinct")
    for shape in shapes:
        stray = [k for k in BLOCK_GEOMETRY_KEYS if k not in shape]
        if stray:
            problems.append("block shape %r does not name %s" % (shape.get("id"), stray))
            continue
        if int(shape["depthwise_kernel"]) < 3 or int(shape["depthwise_kernel"]) % 2 == 0:
            problems.append("block shape %r has a depthwise kernel of %r; a depthwise stage is a "
                            "centred odd window wider than one"
                            % (shape["id"], shape["depthwise_kernel"]))
        if int(shape["pointwise_out"]) <= 0 or int(shape["channels"]) <= 0:
            problems.append("block shape %r has a non-positive channel count" % shape["id"])
        if shape["trace_seed"] not in (layout.get("pinned_trace_seeds") or []):
            problems.append("block shape %r names trace seed %r, which the pinned roster does not"
                            % (shape["id"], shape["trace_seed"]))
    seeds = layout.get("pinned_trace_seeds") or []
    if len(set(seeds)) != len(seeds) or len(seeds) != len(shapes):
        problems.append("the pinned seed roster must carry one distinct seed per graded shape, "
                        "found %d seeds for %d shapes" % (len(seeds), len(shapes)))

    overlap = sorted(set(layout.get("admitted_statistics") or [])
                     & set(layout.get("rejected_statistics") or []))
    if overlap:
        problems.append("statistic %s is both admitted and rejected" % overlap)
    overlap = sorted(set(layout.get("admitted_clock_sources") or [])
                     & set(layout.get("rejected_clock_sources") or []))
    if overlap:
        problems.append("clock source %s is both admitted and rejected" % overlap)
    if layout.get("unfused_boundary") not in (layout.get("fusion_boundaries") or []):
        problems.append("the unfused boundary is not a member of the published fusion roster")
    for key in ("max_abs_error", "max_rel_error"):
        bound = (layout.get("fidelity_envelope") or {}).get(key)
        if not isinstance(bound, float) or bound <= 0:
            problems.append("the fidelity envelope's %s is %r; a gate needs a positive bound"
                            % (key, bound))
    for key in ("warmup_iterations_floor", "timed_iterations_floor"):
        if not isinstance(layout.get(key), int) or layout[key] <= 0:
            problems.append("%s is %r; a methodology floor is a positive count"
                            % (key, layout.get(key)))
    tolerance = layout.get("stage_sum_tolerance_fraction")
    if not isinstance(tolerance, float) or not 0 < tolerance < 1:
        problems.append("stage_sum_tolerance_fraction is %r; it is a fraction of the block time"
                        % tolerance)
    return problems


def main():
    g = load_grounding()
    # The family validator runs FIRST and refuses rather than emitting: a generator that writes a
    # carrier it knows is malformed hands the drift check a moving target.
    problems = validate(g)
    if problems:
        raise SystemExit("AELLO-C8-S11 grounding is not well-formed: " + "; ".join(problems))

    layout = g["corpus_layout"]
    outcome_id = [i["id"] for i in g["items"] if i["dimension"] == "outcome"][0]
    subst = {
        "slot_id": SLOT_ID,
        "path": g["deliverable"]["path"],
        "outcome_id": outcome_id,
        "activation_traces": layout["activation_traces"],
        "reference_outputs": layout["reference_outputs"],
        "reference_latency": layout["reference_latency"],
        "run_record": layout["run_record"],
        "graded_shapes": shapes_literal(layout["graded_block_shapes"]),
        "pinned_trace_seeds": tuple(layout["pinned_trace_seeds"]),
        "record_keys": tuple(layout["record_keys"]),
        "budget_keys": tuple(layout["budget_keys"]),
        "fusion_boundaries": tuple(layout["fusion_boundaries"]),
        "unfused_boundary": layout["unfused_boundary"],
        "stage_sum_tolerance": layout["stage_sum_tolerance_fraction"],
        "warmup_floor": layout["warmup_iterations_floor"],
        "timed_floor": layout["timed_iterations_floor"],
        "admitted_statistics": tuple(layout["admitted_statistics"]),
        "rejected_statistics": tuple(layout["rejected_statistics"]),
        "admitted_clock_sources": tuple(layout["admitted_clock_sources"]),
        "rejected_clock_sources": tuple(layout["rejected_clock_sources"]),
        "envelope": dict(sorted(layout["fidelity_envelope"].items())),
        "guarded_writes": tuple(layout["guarded_writes"]),
    }

    # EVERY compiled item carries a written body, and the generator REFUSES when one does not.
    # The generic obligation lookup that used to stand here read a run-record key nothing writes,
    # so an item falling through to it consulted nothing and reported that it had passed.
    bodies = dict(BODIES)
    for it in g["items"]:
        if it["mode"] == "compiled" and it["id"] not in bodies:
            raise SystemExit("AELLO-C8-S11: no body written for compiled item %r; the generator "
                             "refuses rather than emitting a check that consults nothing"
                             % it["id"])
    stray = sorted(set(bodies) - {i["id"] for i in g["items"]})
    if stray:
        raise SystemExit("AELLO-C8-S11: bodies %s belong to no item in the grounding" % stray)
    # The outcome check must SAY the slot is unmeasurable before it reads anything. Reading the
    # artifact first lets a missing-file failure mask the unmeasured signal, and the verifier then
    # reports gradeable=true with r_det=0.0. seed/build/freeze_batch.py refuses that bundle.
    statements = [ln.strip() for ln in bodies[outcome_id].splitlines()
                  if ln.strip() and not ln.strip().startswith("#")]
    if not statements or statements[0] != REQUIRE_FIRST:
        raise SystemExit("AELLO-C8-S11: %r must call require_measured as its first statement, "
                         "before it reads the submission" % outcome_id)

    tests_dir = os.path.join(BUNDLE, "tests")
    os.makedirs(tests_dir, exist_ok=True)

    # solution/TRUTH.md and solution/rubrics.json are PRIVATE_CARRIERS: seed/identity.py plants a
    # canary block into them at freeze, and canary normalisation is what keeps planting from
    # moving identity. A generator that rewrote them plainly would DROP the planted tripwire, and
    # the next content_hash would differ from the frozen one. So the planted block is carried
    # across the regeneration rather than recreated.
    truth_path = os.path.join(HERE, "TRUTH.md")
    truth = build_truth(g, TITLE).rstrip("\n") + "\n"
    keep = None
    if os.path.exists(truth_path):
        import re as _re
        m = _re.search(r"<!-- AELLO-CANARY-BLOCK.*?-->\n?", open(truth_path).read(), _re.S)
        keep = m.group(0) if m else None
    with open(truth_path, "w") as fh:
        fh.write(truth + ("\n" + keep if keep else ""))

    rub_path = os.path.join(HERE, "rubrics.json")
    rub = build_rubrics(g, ITEM_KEYS)
    if os.path.exists(rub_path):
        try:
            prev = json.load(open(rub_path))
            if "canary" in prev:
                rub["canary"] = prev["canary"]
        except Exception:
            pass
    with open(rub_path, "w") as fh:
        json.dump(rub, fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "rubrics.json"), "w") as fh:
        json.dump(build_rubrics(g, ITEM_KEYS), fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "test_output.py"), "w") as fh:
        # The tail arrives FINAL and is NOT substituted: it is family-shaped, it has already
        # resolved every placeholder it owns, and it legitimately contains percent signs of its
        # own, so formatting it a second time raises TypeError. Only the prelude is substituted.
        fh.write(build_tests(g, PRELUDE % subst, bodies) + TAIL)
    with open(os.path.join(tests_dir, "constants.json"), "w") as fh:
        json.dump(g["constants"], fh, indent=1, sort_keys=True)
        fh.write("\n")
    # ORDER MATTERS. `with open(path, "w")` truncates BEFORE its body's arguments are evaluated,
    # so calling read_identity() inside the with-statement reads the file this line just emptied
    # and writes nulls over the frozen identity. Read first, then open.
    prov = build_provenance(g, read_identity(HERE))
    with open(os.path.join(HERE, "provenance.yaml"), "w") as fh:
        # MATCH seed/build/screen_bind.py and the frozen generators exactly: sort_keys=True,
        # default_flow_style=False, width=100. The screen writes this carrier after the freeze,
        # so a generator using a different dump convention reorders the keys on the next
        # regeneration and reports as drift even though no value changed.
        yaml.safe_dump(prov, fh, sort_keys=True, default_flow_style=False, width=100,
                       allow_unicode=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
