"""Derivation for AELLO-C8-S8: every canonical artifact descends from solution/grounding.yaml.

This slot grades DENSE masks from SPARSE supervision, and the compiled checks below are written
for that and for nothing else. A check that would also fit a multispectral fusion slot, a
classifier or a forecaster is measuring the family rather than the task, so the bodies here name
the things only this slot has: the 150-class label domain and its ignore sentinel, the
heterogeneous per-scene pixel grids ADE20K ships, the labelled support of the sparse annotation
that bounds what the agent may consume, and a red line that forbids READING the private dense
labels rather than writing to them.

Every compiled item carries a body written by hand. There is no generic fallback that looks an
unknown item up in an obligations table: a fallback of that shape made one bundle's outcome check
consult nothing at all, so an item without a body is a refusal to generate.
"""
import json
import os
import sys

import yaml

sys.dont_write_bytecode = True

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
# Nothing outside the bundle is imported. A staged tree could resolve seed/stage/<slug>/../../build;
# a DELIVERED tree at dataset/<uuid>/ cannot, and reaching outside would make the delivered bundle
# non-self-contained -- it would import in the stage and fail everywhere it actually ships.

SLOT_ID = 'AELLO-C8-S8'
TITLE = "# AELLO-C8-S8 -- what this task actually tests"
ITEM_KEYS = ('id', 'dimension', 'weight', 'evaluation_target', 'criterion', 'judgment', 'knockout',
             'mode')


def read_identity(here):
    """Identity is an INPUT: the freeze computes it over the hashed tree and binds it into the
    carrier, which is hash-excluded, so reading it back keeps generation acyclic."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        if isinstance(doc.get("identity"), dict):
            return doc["identity"]
    return {"canonical_content_hash": None, "uuid": None,
            "normalization_domain": "aello.canary.norm/v1",
            "derivation": "uuid5(FORGE_TASK_NAMESPACE, canonical_content_hash)"}


def read_screening(here):
    """The screening instant and result are MEASURED OVER the frozen tree, so they are read back
    the way identity is; the carrier is hash-excluded, so binding them moves nothing."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        got = {k: doc[k] for k in ("screening_measured_at", "screening_expires_at",
                                   "screening_result") if k in doc}
        if got:
            return got
    return {"screening_measured_at": None, "screening_expires_at": None,
            "screening_result": None}


def load_grounding():
    with open(os.path.join(HERE, "grounding.yaml")) as fh:
        return yaml.safe_load(fh)


# --------------------------------------------------------------------------------------
# The compiled check module. PRELUDE is substituted; BODIES and TAIL are not, so they may
# carry percent signs of their own.
# --------------------------------------------------------------------------------------

PRELUDE = '''"""Compiled checks for %(slot_id)s. GENERATED by solution/recompute.py. DO NOT HAND-EDIT.

Sparse supervision, dense grading. The shipped annotation labels a bound fraction of the training
pixels; mean intersection-over-union is taken over EVERY pixel of the private split. Every check
below runs against delivered bytes and references no unmeasured quantity, except
sparse_supervised_miou_ramp, which calls require_measured before it reads the submission and
raises ConstantUnmeasured while tests/constants.json carries nulls.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SUBMISSION = %(path)r

# The label domain, authored in solution/grounding.yaml and published to the agent in
# instruction.md. NUM_CLASSES is the corpus class count. IGNORE marks a pixel the sparse
# annotation never labelled; it sits OUTSIDE 0..NUM_CLASSES-1 on purpose, so that nothing can be
# scored for predicting it and it cannot be learned as a 151st class.
NUM_CLASSES = %(classes)d
IGNORE = %(ignore)d

# Red line 1 forbids the graded run to READ these. The private dense masks live under the first;
# the corpus's full dense annotation lives under the second and is excluded from the agent image,
# named here so a run that reaches for it is caught by name. The agent's own sparse annotation is
# under neither, and reading THAT is the task.
PRIVATE_LABEL_ROOTS = %(private_roots)r

# Red line 2 forbids the graded run to WRITE these.
GUARDED = %(guarded)r

CHECKS = []


class ConstantUnmeasured(Exception):
    """Raised when a check needs a ramp constant that Phase 0 deliberately left null."""


def check(id, weight, knockout, kind):
    def deco(fn):
        CHECKS.append({"id": id, "weight": weight, "knockout": knockout, "kind": kind, "fn": fn})
        return fn
    return deco


def constants():
    with open(os.path.join(HERE, "constants.json")) as fh:
        return json.load(fh)


def require_measured(*names):
    c = constants()
    missing = [n for n in names if c.get(n) is None]
    if missing:
        raise ConstantUnmeasured(
            "%(slot_id)s: " + ", ".join(missing) + " are null. Phase 0 authors no measurement; "
            "the Phase 2 measurement wave writes these and this check becomes gradeable then.")
    return c


def evidence(**kw):
    return {"evaluation_target": kw.pop("target", "submitted_artifact"), "values": kw}
'''


TAIL = '''

def load_submission():
    """One integer mask per graded scene, keyed by ADE20K image id.

    Strict at load, so every later check reads a mask rather than re-deciding what a mask is. A
    float or boolean array is not a mask; a three-dimensional member is a probability volume and
    is NOT silently argmaxed here, because choosing the class axis for the agent would be scoring
    a submission the agent did not make.
    """
    import numpy as np
    archive = np.load(SUBMISSION, allow_pickle=False)
    members = {}
    for name in archive.files:
        mask = np.asarray(archive[name])
        if mask.ndim != 2:
            raise ValueError("member %s has ndim %d; a scene mask is 2-D" % (name, mask.ndim))
        if mask.dtype.kind not in ("i", "u"):
            raise ValueError("member %s has dtype %s; a class id is an integer"
                             % (name, mask.dtype))
        members[str(name)] = mask
    if not members:
        raise ValueError("archive carries no members; no graded scene can be scored from nothing")
    return members


def describe(members):
    """A few scene grids, so a mis-sized submission is legible in the report."""
    return ", ".join("%s %dx%d" % (name, members[name].shape[0], members[name].shape[1])
                     for name in sorted(members)[:4])


def heldout(name):
    return os.path.join(HERE, "heldout", name)


def shipped(name):
    """A path under environment/data/, which is what the agent legitimately sees."""
    return os.path.join(HERE, "..", "environment", "data", name)


def scene_manifest():
    """Graded image id -> that scene's own (height, width).

    Derived from the private masks THEMSELVES: the graded image ids ARE their member names and
    each scene's grid IS that member's shape. A second copy of the table on the checker side would
    be a thing that can drift from the labels it describes, and ADE20K grids are heterogeneous, so
    that drift would stay invisible until a mask was scored against the wrong scene. None when the
    shard has not landed.
    """
    path = heldout("graded_masks.npz")
    if not os.path.exists(path):
        return None
    import numpy as np
    truth = np.load(path, allow_pickle=False)
    return {str(name): tuple(int(d) for d in np.asarray(truth[name]).shape)
            for name in truth.files}


def sparse_labelled_support():
    """How many pixels the shipped sparse annotation actually labels.

    This is the bound the agent's declared consumption is measured against, and it is counted from
    the delivered shard rather than read from an authored constant, so the check and the corpus
    cannot drift apart. None when the shard has not landed.
    """
    path = shipped("sparse_labels.npz")
    if not os.path.exists(path):
        return None
    import numpy as np
    archive = np.load(path, allow_pickle=False)
    return int(sum(int((np.asarray(archive[name]) != IGNORE).sum()) for name in archive.files))


def class_ids(mask):
    """The distinct class ids one scene mask carries, as plain ints.

    Every numpy call lives in this module's helpers rather than in a check body, so a check reads
    as the assertion it makes and an unreadable archive surfaces once, at load, with one reason.
    """
    import numpy as np
    return [int(v) for v in np.unique(mask)]


def predicted_classes(members):
    """Distinct class ids across the whole archive, with the ignore sentinel removed."""
    seen = set()
    for name in sorted(members):
        seen.update(class_ids(members[name]))
    seen.discard(IGNORE)
    return seen


def graded_pairs():
    """Each graded image id with its submitted mask and the private dense mask beside it."""
    import numpy as np
    submitted = load_submission()
    truth = np.load(heldout("graded_masks.npz"), allow_pickle=False)
    for name in sorted(truth.files):
        if str(name) in submitted:
            yield str(name), submitted[str(name)], np.asarray(truth[name])


def measure():
    """Mean IoU accumulated PER CLASS across the whole split, then averaged over classes present.

    Per class over the split, not per image and then over images: a scene holding two classes
    would otherwise weigh as much as a scene holding forty, and the long tail is the whole point
    of this axis. Pixels the private mask marks with the ignore sentinel enter neither accumulator,
    because the corpus does not claim a class for them and nothing should be scored on them.
    """
    import numpy as np
    intersection = [0] * NUM_CLASSES
    union = [0] * NUM_CLASSES
    for name, predicted, truth in graded_pairs():
        if predicted.shape != truth.shape:
            continue
        scored = truth != IGNORE
        p = predicted[scored]
        t = truth[scored]
        for label in set(int(v) for v in np.unique(t)) | set(int(v) for v in np.unique(p)):
            if not 0 <= label < NUM_CLASSES:
                continue
            hit = p == label
            want = t == label
            intersection[label] += int((hit & want).sum())
            union[label] += int((hit | want).sum())
    present = [intersection[k] / union[k] for k in range(NUM_CLASSES) if union[k]]
    if not present:
        raise ConstantUnmeasured("no graded scene produced a defined per-class IoU")
    return float(sum(present) / len(present))


def run_record():
    path = os.path.join(HERE, "..", "run_record.json")
    if not os.path.exists(path):
        return {}
    with open(path) as handle:
        return json.load(handle)


def declaration(key):
    """An agent-authored block from the run record, parsed. Returns (block, reason).

    Absent and unparseable are kept apart deliberately: one is an agent that declared nothing and
    the other is an agent that declared something the checker could not read, and collapsing them
    would hide which.
    """
    raw = run_record().get(key)
    if raw is None:
        return None, "no_%s_in_the_run_record" % key
    try:
        return (json.loads(raw) if isinstance(raw, str) else dict(raw)), None
    except Exception as exc:
        return None, "%s_unparseable: %s" % (key, exc)


def paths_read():
    """Paths the graded run OPENED, from the record the run itself produced.

    Red line 1 forbids a read, and a post-hoc scan is the wrong instrument twice over: it cannot
    observe a read at all, and it could not separate one made during the graded run from one made
    before it. None when the run recorded no log, which is a failure and not a pass.
    """
    return run_record().get("paths_read")


def guarded_paths_touched():
    """Paths under the checker tree or the graded fold modified during the graded run."""
    return run_record().get("guarded_paths_touched", [])
'''


BODIES = {

    "mask_archive_lands": '''    if not os.path.exists(SUBMISSION):
        return False, evidence(reason="submission_missing", path=SUBMISSION)
    try:
        members = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    return True, evidence(path=SUBMISSION, scenes=len(members), grids=describe(members))''',

    "scene_grid_per_image_id": '''    manifest = scene_manifest()
    if manifest is None:
        return False, evidence(reason="graded_scene_grids_unavailable")
    try:
        members = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_unreadable", error=str(exc))
    missing = sorted(set(manifest) - set(members))
    unknown = sorted(set(members) - set(manifest))
    off_grid = sorted(name for name in manifest
                      if name in members and tuple(members[name].shape) != manifest[name])
    ok = not (missing or unknown or off_grid)
    return ok, evidence(graded_scenes=len(manifest), submitted_scenes=len(members),
                        missing_ids=missing[:8], unknown_ids=unknown[:8],
                        off_scene_grid=off_grid[:8],
                        reason=None if ok else "masks_do_not_match_the_graded_scene_grids")''',

    "label_domain_is_the_150_classes": '''    outside = {}
    try:
        members = load_submission()
        for name in sorted(members):
            stray = [v for v in class_ids(members[name])
                     if v != IGNORE and not 0 <= v < NUM_CLASSES]
            if stray:
                outside[name] = stray[:6]
    except Exception as exc:
        return False, evidence(reason="submission_unreadable", error=str(exc))
    ok = not outside
    return ok, evidence(classes=NUM_CLASSES, ignore_index=IGNORE,
                        scenes_out_of_domain=len(outside),
                        out_of_domain=dict(sorted(outside.items())[:4]),
                        reason=None if ok else "label_outside_the_150_class_domain")''',

    "prediction_dense_despite_sparse_supervision": '''    try:
        members = load_submission()
        conceded = sum(int((members[name] == IGNORE).sum()) for name in sorted(members))
        submitted = sum(int(members[name].size) for name in sorted(members))
    except Exception as exc:
        return False, evidence(reason="submission_unreadable", error=str(exc))
    ok = conceded == 0
    return ok, evidence(conceded_pixels=conceded, submitted_pixels=submitted,
                        conceded_share=(conceded / submitted) if submitted else None,
                        reason=None if ok else "supervision_sparsity_copied_into_the_prediction")''',

    "long_tail_not_collapsed_to_modal_class": '''    try:
        classes = predicted_classes(load_submission())
    except Exception as exc:
        return False, evidence(reason="submission_unreadable", error=str(exc))
    ok = len(classes) > 1
    return ok, evidence(distinct_classes_predicted=len(classes), of_possible=NUM_CLASSES,
                        sample=sorted(classes)[:8],
                        reason=None if ok else "one_class_over_the_whole_split")''',

    "dense_private_labels_unread": '''    log = paths_read()
    if log is None:
        return False, evidence(target="run_record", reason="no_read_log_produced")
    opened = sorted(str(p) for p in log
                    if any(root in str(p).replace(os.sep, "/") for root in PRIVATE_LABEL_ROOTS))
    return (not opened), evidence(target="run_record", paths_read=len(log),
                                  private_label_roots=list(PRIVATE_LABEL_ROOTS),
                                  private_label_reads=opened[:8],
                                  reason=None if not opened
                                  else "read_the_private_splits_dense_labels")''',

    "checker_tree_and_graded_masks_untouched": '''    touched = sorted(str(p) for p in guarded_paths_touched())
    inside = [p for p in touched if any(root in p.replace(os.sep, "/") for root in GUARDED)]
    return (not inside), evidence(target="submitted_source", guarded_roots=list(GUARDED),
                                  touched=inside[:8],
                                  reason=None if not inside
                                  else "wrote_into_the_checker_tree_or_the_graded_fold")''',

    "supervision_fraction_declared_and_bounded": '''    decl, why = declaration("supervision_declaration")
    if decl is None:
        return False, evidence(target="run_record", reason=why)
    absent = [k for k in ("labelled_pixels_consumed", "pixels_total") if k not in decl]
    if absent:
        return False, evidence(target="run_record", missing=absent,
                               reason="supervision_declaration_incomplete")
    try:
        consumed = int(decl["labelled_pixels_consumed"])
        total = int(decl["pixels_total"])
    except Exception as exc:
        return False, evidence(target="run_record", reason="supervision_declaration_not_numeric",
                               error=str(exc))
    support = sparse_labelled_support()
    if support is None:
        return False, evidence(target="run_record", reason="sparse_annotation_unavailable")
    ok = total > 0 and 0 <= consumed <= support
    return ok, evidence(target="run_record", labelled_pixels_consumed=consumed,
                        shipped_labelled_support=support, pixels_total=total,
                        declared_fraction=(consumed / total) if total > 0 else None,
                        reason=None if ok
                        else "consumed_more_labelled_pixels_than_the_shard_ships")''',

    "unlabelled_pixels_masked_not_backpropagated": '''    policy = run_record().get("loss_policy")
    if policy is None:
        return False, evidence(target="run_record", reason="no_loss_policy_declared")
    text = str(policy).lower()
    taught = [w for w in ("background", "void", "zero_class", "class_zero",
                          "all_pixels_supervised", "dense_cross_entropy") if w in text]
    masked = any(w in text for w in ("ignore_index", "ignore index", "ignored", "masked",
                                     "mask_unlabelled", "partial_label", "label_mask"))
    ok = masked and not taught
    return ok, evidence(target="run_record", declared=str(policy)[:200],
                        unlabelled_masked=masked, dense_target_tokens=taught,
                        reason=None if ok else "unlabelled_pixels_taught_as_a_class")''',

    "step_budget_not_truncated_by_decoder_resolution": '''    decl, why = declaration("training_schedule")
    if decl is None:
        return False, evidence(target="run_record", reason=why)
    absent = [k for k in ("planned_steps", "completed_steps", "decoder_output_stride")
              if k not in decl]
    if absent:
        return False, evidence(target="run_record", missing=absent,
                               reason="training_schedule_incomplete")
    try:
        planned = int(decl["planned_steps"])
        completed = int(decl["completed_steps"])
        stride = int(decl["decoder_output_stride"])
    except Exception as exc:
        return False, evidence(target="run_record", reason="training_schedule_not_numeric",
                               error=str(exc))
    ok = planned > 0 and stride >= 1 and completed >= planned
    return ok, evidence(target="run_record", planned_steps=planned, completed_steps=completed,
                        decoder_output_stride=stride,
                        reason=None if ok
                        else "step_budget_truncated_at_this_decoder_resolution")''',

    "sparse_supervised_miou_ramp": '''    c = require_measured("floor", "knee", "dichotomizing_threshold")
    # require_measured IS THE FIRST STATEMENT, deliberately. Reading the submission first lets a
    # missing or malformed archive raise before the unmeasured signal is ever emitted, and the
    # verifier then reports gradeable true with r_det 0.0 -- which asserts the agent scored zero
    # when the truth is that this slot is not yet measurable at all.
    mean_iou = measure()
    span = c["knee"] - c["floor"]
    s = 0.0 if span <= 0 else max(0.0, min(1.0, (mean_iou - c["floor"]) / span))
    return mean_iou >= c["dichotomizing_threshold"], evidence(mean_iou=mean_iou, s_outcome=s)''',
}


def build_tests(g, prelude, bodies):
    """Assemble the compiled-check module.

    kind carries the item's own dimension rather than a constant, so the verifier's report says
    whether a failed check was a deliverable, an integrity or a process finding.
    """
    chunks = [prelude]
    for raw in sorted(g["items"], key=lambda i: i["id"]):
        if raw["mode"] != "compiled":
            continue
        chunks.append(
            '\n@check(id="%s", weight=%d, knockout=%s, kind="%s")\ndef test_%s():\n%s\n'
            % (raw["id"], raw["weight"], raw["knockout"], raw["dimension"], raw["id"],
               bodies[raw["id"]]))
    return "".join(chunks)


def build_truth(g, title):
    """Render solution/TRUTH.md from the frozen literals of solution/grounding.yaml."""
    n = g["truth_narrative"]
    lines = [title, "", "GENERATED SECTION. DO NOT HAND-EDIT.", "", n["opening"], "",
             "## The single most important insight", "", n["insight"], "",
             "## The ideal solve, step by step", ""]
    for i, step in enumerate(n["steps"], 1):
        lines += ["%d. **%s** %s" % (i, step["heading"], step["paragraph"]), ""]
    lines += ["## Traps that catch agents that are not thinking carefully", ""]
    lines += ["- " + t for t in n["traps"]]
    lines += ["", "---", "", "## Contract record (annex; not part of the narrative body)", "",
              "Retained under FORGE.md item 10e and Phase 2 item 7, which require this file to "
              "carry the ordered path through instruction.md with each satisfied checker "
              "identifier, and each rejected route bound to a measured known-wrong control. "
              "standards/truth-md-authoring-v1.md section 3 admits no fifth section, so this "
              "annex is a recorded deviation rather than an omission.", "", g["truth_annex"], ""]
    return "\n".join(lines) + "\n"


def build_rubrics(g, item_keys):
    """The 9g rubric carrier. The item schema is CLOSED at eight keys, so item 10f's outcome
    classification rides as a greppable prefix of the judgment rather than as a ninth key."""
    items = []
    for raw in g["items"]:
        item = {k: raw[k] for k in item_keys}
        item["judgment"] = "%s: %s" % (raw["outcome_class"], raw["judgment"])
        items.append(item)
    compiled = sum(i["weight"] for i in items if i["mode"] == "compiled")
    total = sum(i["weight"] for i in items)
    return {"$schema": "forge.rubric/v1",
            "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
            "generator": "solution/recompute.py",
            "compilation_floor": g["compilation_floor"],
            "compiled_weight_share": round(compiled / total, 6) if total else 0.0,
            "evaluation_target_vocabulary": sorted(g["evaluation_target_vocabulary"]),
            "items": sorted(items, key=lambda i: i["id"])}


def build_provenance(g, identity):
    p = g["provenance"]
    out = {
        "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
        "generator": "solution/recompute.py from solution/grounding.yaml",
        "schema_version": "1.0",
        "slot_id": g["slot_id"],
        "identity": identity,
        "corpus": p["corpus"],
        "anchors": p["anchors"],
        "shards": p["shards"],
        "narrative": p["narrative"],
        "supersedes": p["supersedes"],
        "upstream_provenance": p["upstream_record"],
        "reward_composition": p["reward_composition"],
        "screening_interval_days": p["screening_interval_days"],
        "screening_detector_version": p["screening_detector_version"],
        "derivation_instant": p["derivation_instant"],
        "screening_roots": p["screening_roots"],
        "empty_submission_result": p["empty_submission_result"],
        "resolved_closure": p["resolved_closure"],
        "applicability": p["applicability"],
        "measurement_tier": g["measurement_tier"],
        "gradeable": g["gradeable"],
        "knee_anchor_status": g["knee_anchor_status"],
        # Grading is DENSE while supervision is SPARSE, and that asymmetry is the slot. Recorded
        # on the carrier so a downstream reader does not have to infer it from the metric name.
        "dense_label_grading": True,
        "supervision_regime": g["supervision"]["regime"],
        "supervision_fraction": g["supervision"]["fraction"],
        "label_domain": {"classes": g["label_domain"]["classes"],
                         "ignore_index": g["label_domain"]["ignore_index"]},
    }
    out.update(read_screening(HERE))
    return out


def validate(grounding):
    """Refuse a grounding this generator cannot faithfully compile.

    Slot-specific, not a stub. The label domain and the ignore sentinel are emitted into the check
    module as literals, so a sentinel that collided with a real class id would silently make
    label_domain_is_the_150_classes accept an unscoreable pixel; and a compiled item whose
    evaluation target is outside the declared vocabulary would be a rubric row the verifier's
    report cannot classify.
    """
    problems = []
    domain = grounding.get("label_domain") or {}
    classes, ignore = domain.get("classes"), domain.get("ignore_index")
    if not isinstance(classes, int) or classes < 2:
        problems.append("label_domain.classes must be an integer above one; got %r" % (classes,))
    if not isinstance(ignore, int):
        problems.append("label_domain.ignore_index must be an integer; got %r" % (ignore,))
    elif isinstance(classes, int) and 0 <= ignore < classes:
        problems.append("ignore_index %d collides with class ids 0..%d; the sentinel must sit "
                        "outside the graded domain or a conceded pixel becomes scoreable"
                        % (ignore, classes - 1))
    vocabulary = set(grounding.get("evaluation_target_vocabulary") or ())
    seen = set()
    outcome = [i for i in grounding["items"] if i["dimension"] == "outcome"]
    for item in grounding["items"]:
        if item["id"] in seen:
            problems.append("duplicate item id %r" % item["id"])
        seen.add(item["id"])
        if not item["id"].isidentifier():
            problems.append("item id %r is not a Python identifier and cannot name a test"
                            % item["id"])
        if item["evaluation_target"] not in vocabulary:
            problems.append("item %s targets %r, which is outside the declared vocabulary"
                            % (item["id"], item["evaluation_target"]))
        if not isinstance(item["weight"], int) or item["weight"] <= 0:
            problems.append("item %s carries a non-positive weight" % item["id"])
    if len(outcome) != 1:
        problems.append("expected exactly one outcome item; found %d" % len(outcome))
    if not grounding["items"]:
        problems.append("no items; identifier set equality against the tests would pass vacuously")
    return problems


def main():
    g = load_grounding()
    # The validator runs FIRST and refuses rather than emitting: a generator that writes a carrier
    # it knows is malformed hands the drift check a moving target.
    problems = validate(g)
    if problems:
        raise SystemExit("AELLO-C8-S8 grounding is not well-formed: " + "; ".join(problems))

    # EVERY compiled item is written by hand. No fallback: an item that reached a generic
    # obligations lookup would emit a check that consults a run-record key nobody writes, which
    # is a check that cannot fire dressed as a check that passed.
    bodies = dict(BODIES)
    orphan = [i["id"] for i in g["items"] if i["mode"] == "compiled" and i["id"] not in bodies]
    if orphan:
        raise SystemExit("AELLO-C8-S8: no body written for compiled item(s) %s. Write the check "
                         "or drop the item; there is no generic fallback." % ", ".join(orphan))
    unused = sorted(set(bodies) - {i["id"] for i in g["items"]})
    if unused:
        raise SystemExit("AELLO-C8-S8: body written for %s, which names no item" % ", ".join(unused))

    dl = g["deliverable"]
    domain = g["label_domain"]
    subst = {"slot_id": SLOT_ID, "path": dl["path"],
             "classes": domain["classes"], "ignore": domain["ignore_index"],
             "private_roots": tuple(g["private_split"]["roots_the_agent_may_not_read"]),
             "guarded": ("tests/", "environment/data/dense_labels/", "/logs/verifier/")}

    tests_dir = os.path.join(BUNDLE, "tests")
    os.makedirs(tests_dir, exist_ok=True)

    # solution/TRUTH.md and solution/rubrics.json are PRIVATE_CARRIERS: seed/identity.py plants a
    # canary block into them at freeze, and canary normalisation is what keeps planting from
    # moving identity. A generator that rewrote them plainly would DROP the planted tripwire, and
    # the next content_hash would differ from the frozen one. So the planted block is carried
    # across the regeneration rather than recreated.
    truth_path = os.path.join(HERE, "TRUTH.md")
    truth = build_truth(g, TITLE).rstrip("\n") + "\n"
    keep = None
    if os.path.exists(truth_path):
        import re as _re
        m = _re.search(r"<!-- AELLO-CANARY-BLOCK.*?-->\n?", open(truth_path).read(), _re.S)
        keep = m.group(0) if m else None
    with open(truth_path, "w") as fh:
        fh.write(truth + ("\n" + keep if keep else ""))

    rub_path = os.path.join(HERE, "rubrics.json")
    rub = build_rubrics(g, ITEM_KEYS)
    if os.path.exists(rub_path):
        try:
            prev = json.load(open(rub_path))
            if "canary" in prev:
                rub["canary"] = prev["canary"]
        except Exception:
            pass
    with open(rub_path, "w") as fh:
        json.dump(rub, fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "rubrics.json"), "w") as fh:
        json.dump(build_rubrics(g, ITEM_KEYS), fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "test_output.py"), "w") as fh:
        # Only the PRELUDE is substituted. The tail is already resolved and legitimately carries
        # percent signs of its own inside the emitted helpers, and formatting it a second time
        # raised TypeError on the first slot that carried one.
        fh.write(build_tests(g, PRELUDE % subst, bodies) + TAIL)
    with open(os.path.join(tests_dir, "constants.json"), "w") as fh:
        json.dump(g["constants"], fh, indent=1, sort_keys=True)
        fh.write("\n")
    # ORDER MATTERS. `with open(path, "w")` truncates BEFORE its body's arguments are evaluated,
    # so calling read_identity() inside the with-statement reads the file this line just emptied
    # and writes nulls over the frozen identity. Read first, then open.
    prov = build_provenance(g, read_identity(HERE))
    with open(os.path.join(HERE, "provenance.yaml"), "w") as fh:
        # MATCH seed/build/screen_bind.py and the frozen generators exactly: sort_keys=True,
        # default_flow_style=False, width=100. The screen writes this carrier after the freeze,
        # so a generator using a different dump convention reorders the keys on the next
        # regeneration and reports as drift even though no value changed.
        yaml.safe_dump(prov, fh, sort_keys=True, default_flow_style=False, width=100,
                       allow_unicode=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
