"""Apply the bound judged-rubric gate to a deterministic reward.

GENERATED by solution/recompute.py; do not hand-edit.

WHAT THIS BUNDLE EMITS, AND WHAT IT DOES NOT. tests/verifier.py writes r_det, the deterministic
reward, from the compiled checks and the measured outcome alone. It never sees a judged verdict:
the trajectory rubrics in tests/rubrics.jsonl are graded downstream by an LLM trajectory grader,
outside this bundle and after the verifier has exited. So the bundle cannot apply the gate itself,
and this module is the composition the CONSUMER applies once those verdicts exist.

THE RULE, bound in tests/constants.json as reward_gate_form, reward_gate_ceiling and
reward_gate_pass_threshold:

    every enumerated judged rubric returns a pass  ->  r_final = r_det
    anything else                                  ->  r_final = min(r_det, ceiling)

"Anything else" is deliberately wide, and COVERAGE is part of it. The judged set this bundle
expects is enumerated in tests/rubrics.json, so the expected ids are available at the point of use.
A verdict collection that does not cover them - an empty one, a short one, one missing an id, or
one that cannot be checked because the enumeration itself is unreadable - is a FAILURE of the
conjunction and caps. That is the case a broken grader actually produces, and `all()` over an empty
collection is True, so a gate that only checked the verdicts it was handed would pass exactly when
it had been handed nothing.

The ceiling sits strictly below this task's correctness threshold, so a run with a failed judged
rubric is reported below correctness and does not count as correct, which is the obligation at
client-requirements.md:122. It sits strictly above zero, so a judged verdict lowers a score and
never zeroes it. An absent, timed-out or unparseable verdict counts as a failure, so the
composition is fail-closed on every axis: verdict value, verdict presence, and set coverage.

    python tests/compose.py --r-det 0.72 --verdicts pass,pass,fail
    python tests/compose.py --r-det 0.72 --verdicts-json /path/to/verdicts.json
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def bound_gate():
    """The gate form, ceiling and PASS THRESHOLD this bundle binds.

    reward_gate_pass_threshold used to live nowhere in the bundle. It was supplied by the
    environment variable AELLO_COUNCIL_PASS_THRESHOLD, unset everywhere, defaulting to 0.5,
    and the harness stamped its own records UNBOUND_IN_BUNDLE__harness_default. The client
    therefore could not reproduce a delivered reward from the delivered bytes: the same
    bundle and the same council scores compose to a different number at a different
    threshold. It is bound here so the bundle is self-contained.
    """
    with open(os.path.join(HERE, "constants.json")) as fh:
        c = json.load(fh)
    return (c["reward_gate_form"], float(c["reward_gate_ceiling"]),
            float(c["reward_gate_pass_threshold"]))


def enumerated_rubrics():
    """The judged rubric ids this bundle enumerates, in tests/rubrics.json.

    Returns None when the enumeration cannot be established, which is itself a failure: a gate
    that cannot learn what it must cover must not report a pass.
    """
    try:
        with open(os.path.join(HERE, "rubrics.json")) as fh:
            ids = [r["id"] for r in json.load(fh)["rubrics"]]
        return ids or None
    except Exception:
        return None


def coverage(verdicts, expected=None):
    """Resolve a verdict collection against the enumerated judged set.

    Returns (values, covered, reason). `verdicts` may be a mapping from rubric id to verdict, or
    a sequence in the enumerated order. Coverage is checked before any verdict value is read.
    """
    if expected is None:
        expected = enumerated_rubrics()
    if not expected:
        return [], False, "judged_set_unreadable"
    if hasattr(verdicts, "keys"):
        got = {str(k) for k in verdicts.keys()}
        missing = [i for i in expected if i not in got]
        values = [verdicts.get(i) for i in expected]
        if missing:
            return values, False, "verdicts_missing_for:%s" % ",".join(missing)
        return values, True, "covered"
    values = list(verdicts)
    if len(values) < len(expected):
        return values, False, ("verdict_count_%d_below_enumerated_%d"
                               % (len(values), len(expected)))
    return values, True, "covered"


def _passes(value, threshold):
    """Is one judged verdict a pass?

    The council emits DISCRETE FRACTIONS averaged across a panel, not booleans, while this
    gate consumes booleans. Nothing in the bundle defined the conversion, so the same
    verdicts composed to different rewards depending on who read them. The threshold is now
    bound in constants.json and applied here. None is unavailable and fails closed.
    """
    if value is None:
        return False
    if isinstance(value, bool):
        return value
    try:
        return float(value) >= threshold
    except (TypeError, ValueError):
        return False


def compose(r_det, verdicts, form=None, ceiling=None, expected=None, threshold=None):
    """Apply the judged residue to a deterministic reward. Never raises the value.

    A verdict of None means unavailable and counts as a failure, because an unavailable judge caps
    rather than passes. A collection that does not cover the enumerated judged set counts as a
    failure for the same reason.
    """
    bf, bc, bt = bound_gate()
    form = bf if form is None else form
    ceiling = bc if ceiling is None else ceiling
    threshold = bt if threshold is None else threshold
    if not 0.0 < threshold <= 1.0:
        raise ValueError("pass threshold %r must sit in (0, 1]" % (threshold,))
    if not 0.0 <= r_det <= 1.0:
        raise ValueError("deterministic reward %r is outside the closed unit interval" % (r_det,))
    if form != "gate":
        raise ValueError("this bundle binds the gate form, not %r" % (form,))
    if not 0.0 <= ceiling < 1.0:
        raise ValueError(
            "gate ceiling %r must sit strictly below 1.0, otherwise a failed rubric leaves full "
            "reward reachable and the gate does not bind" % (ceiling,))
    values, covered, _reason = coverage(verdicts, expected)
    all_pass = covered and all(_passes(v, threshold) for v in values)
    r_final = r_det if all_pass else min(r_det, ceiling)
    if r_final > r_det:                       # checked, not argued
        raise ValueError("judged residue raised the reward from %r to %r" % (r_det, r_final))
    return r_final


def _parse(token):
    t = str(token).strip().lower()
    if t in ("pass", "true", "1", "yes"):
        return True
    if t in ("fail", "false", "0", "no"):
        return False
    return None                               # unavailable: fail-closed


def main():
    ap = argparse.ArgumentParser(description="Apply this bundle's bound judged-rubric gate.")
    ap.add_argument("--r-det", type=float, required=True,
                    help="the deterministic reward tests/verifier.py wrote")
    ap.add_argument("--verdicts", default="",
                    help="comma-separated judged verdicts: pass, fail, or absent")
    ap.add_argument("--verdicts-json", default=None,
                    help="a JSON file mapping rubric id to pass/fail, or a JSON list")
    a = ap.parse_args()
    expected = enumerated_rubrics()
    if a.verdicts_json:
        doc = json.load(open(a.verdicts_json))
        raw = doc if isinstance(doc, dict) else list(doc)
    else:
        raw = [t for t in a.verdicts.split(",") if t.strip()]
    if hasattr(raw, "keys"):
        verdicts = dict((k, _parse(v)) for k, v in raw.items())
    else:
        verdicts = [_parse(v) for v in raw]
    values, covered, reason = coverage(verdicts, expected)
    form, ceiling, threshold = bound_gate()
    r_final = compose(a.r_det, verdicts, expected=expected)
    print(json.dumps({"r_det": a.r_det, "enumerated_judged": len(expected or []),
                      "judged_verdicts": len(values), "covered": covered, "reason": reason,
                      "all_pass": covered and all(_passes(v, threshold) for v in values),
                      "form": form, "ceiling": ceiling, "pass_threshold": threshold,
                      "r_final": r_final}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
