"""Derivation for AELLO-C8-S3: every canonical artifact descends from solution/grounding.yaml.

The graded object of this slot is a DATA SELECTION RECIPE. The trainer is frozen, so the only
channel from the agent to the score is which images the recipe puts in the shard, and every check
this module emits is a check about that channel: the callable contract the verifier invokes, the
capture-timestamp boundary, the burst structure of camera traps, the camera-site roster, the joint
wall-clock envelope the recipe and the trainer share, and the order the selection ops compose in.

The thirteen judged "obligation" items that used to stand in the items list are gone. Each one
restated a checker id from seed/contract.yaml and then fell through to a generic run-record lookup
under a key nothing writes, so it graded nothing and reported nothing. What replaced them are
compiled checks that read the emitted shard manifest, the served pool index, the verifier-held
capture-timestamp table and the harness's own op trace.
"""
import json
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
# generator_common.py is VENDORED beside this file, not reached for outside the bundle. A staged
# tree could resolve seed/stage/<slug>/../../build; a DELIVERED tree at dataset/<uuid>/ cannot,
# and reaching outside would make the delivered bundle non-self-contained -- it would import in
# the stage and fail everywhere it actually ships.

ITEM_KEYS = ('id', 'dimension', 'weight', 'evaluation_target', 'criterion', 'judgment', 'knockout',
             'mode')
ITEM_SCHEMA = frozenset(ITEM_KEYS + ('outcome_class',))
OUTCOME_CLASSES = frozenset(("EFFECT", "INVARIANT", "ABSENCE", "VALUE", "ORDERING", "DIVERGENCE"))
RAMP = ("floor", "knee", "dichotomizing_threshold", "reward_gate_pass_threshold")
REQUIRE_FIRST = 'c = require_measured("floor", "knee", "dichotomizing_threshold")'
BUILD_PARAMS = ("pool_index", "out_dir")
SLOT_ID = 'AELLO-C8-S3'
TITLE = "# AELLO-C8-S3 -- what this task actually tests"


def read_identity(here):
    """Identity is an INPUT: the freeze computes it over the hashed tree and binds it into the
    carrier, which is hash-excluded, so reading it back keeps generation acyclic."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        if isinstance(doc.get("identity"), dict):
            return doc["identity"]
    return {"canonical_content_hash": None, "uuid": None,
            "normalization_domain": "aello.canary.norm/v1",
            "derivation": "uuid5(FORGE_TASK_NAMESPACE, canonical_content_hash)"}


def read_screening(here):
    """The screening instant and result are MEASURED OVER the frozen tree, so they are read back
    the way identity is; the carrier is hash-excluded, so binding them moves nothing."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        got = {k: doc[k] for k in ("screening_measured_at", "screening_expires_at",
                                   "screening_result") if k in doc}
        if got:
            return got
    return {"screening_measured_at": None, "screening_expires_at": None,
            "screening_result": None}


def load_grounding():
    with open(os.path.join(HERE, "grounding.yaml")) as fh:
        return yaml.safe_load(fh)


# ==========================================================================================
# The emitted checker. PRELUDE carries this slot's corpus vocabulary and IS substituted from
# corpus_layout; BODIES go in verbatim under their own decorator; TAIL is the reading machinery
# and is NOT substituted, because it carries percent formatting of its own.
# ==========================================================================================

PRELUDE = '''"""Compiled checks for %(slot_id)s. GENERATED by solution/recompute.py. DO NOT HAND-EDIT.

The graded deliverable here is a callable data-selection recipe, not a model and not a prediction
array: the verifier CALLS build(pool_index, out_dir) and the frozen trainer then consumes whatever
shard that call emitted. So the delivered bytes these checks read are the recipe source, the shard
manifest build() wrote, the served pool index that carries capture timestamp, site id and burst id,
the verifier-held capture-timestamp table, and the op trace the harness recorded while build() ran.

Nothing below imports the recipe. A verifier that imports agent code to discover its interface has
already executed the recipe inside the grading environment, so the callable contract is read off
the parsed source instead.

Every check runs against those bytes and references no unmeasured quantity, except
%(outcome_id)s, which raises ConstantUnmeasured while tests/constants.json carries nulls.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SUBMISSION = %(path)r
CHECKS = []

# --- the recipe's callable contract -------------------------------------------------------
BUILD_PARAMS = %(build_params)r
FROZEN_PACKAGE = %(frozen_package)r

# --- what ships to the agent --------------------------------------------------------------
POOL_INDEX = %(pool_index)r
POOL_FIELDS = %(pool_fields)r
DATASET_CARD = %(dataset_card)r
CLASSES = %(classes)r
CLASS_COUNT = %(class_count)r

# --- what build() must leave behind -------------------------------------------------------
MANIFEST_NAME = %(manifest_name)r
MANIFEST_FIELDS = %(manifest_fields)r
DECLARED_OPS_KEY = %(declared_ops_key)r
RUN_RECORD = %(run_record)r

# --- what the verifier holds and the agent never sees -------------------------------------
CAPTURE_TIMES = %(capture_times)r
BOUNDARY = %(boundary)r
LABELS_A = %(labels_a)r
PREDICTIONS_A = %(predictions_a)r
GUARDED = %(guarded)r

# --- the selection ops, and the four precedences that are load-bearing --------------------
OP_DEDUP = %(op_dedup)r
OP_DECODE = %(op_decode)r
OP_REBALANCE = %(op_rebalance)r
OP_STATISTICS = %(op_statistics)r
AUGMENTATION_OPS = %(augmentation_ops)r
ILLUMINATION_REGIMES = %(regimes)r

# --- the declared bounds. None of these is a ramp constant; the ramp constants are null. ---
ENVELOPE_SECONDS = %(envelope_seconds)r
SAMPLE_CAP_ROWS = %(sample_cap_rows)r
SIBLING_GAP_BOUND = %(sibling_gap_bound)r
TRAINER_STEPS = %(trainer_steps)r
LOG_ACCURACY_TOLERANCE = %(log_accuracy_tolerance)r
LOG_ELAPSED_TOLERANCE = %(log_elapsed_tolerance)r
SITE_COVERAGE_FLOOR = %(site_coverage_floor)r
MAX_SINGLE_SITE_SHARE = %(max_single_site_share)r
LITERAL_PRIOR_MAX = %(literal_prior_max)r


class ConstantUnmeasured(Exception):
    """Raised when a check needs a ramp constant that Phase 0 deliberately left null."""


def check(id, weight, knockout, kind):
    def deco(fn):
        CHECKS.append({"id": id, "weight": weight, "knockout": knockout, "kind": kind, "fn": fn})
        return fn
    return deco


def constants():
    with open(os.path.join(HERE, "constants.json")) as fh:
        return json.load(fh)


def require_measured(*names):
    c = constants()
    missing = [n for n in names if c.get(n) is None]
    if missing:
        raise ConstantUnmeasured(
            "%(slot_id)s: " + ", ".join(missing) + " are null. Phase 0 authors no measurement; "
            "the Phase 2 measurement wave writes these and this check becomes gradeable then.")
    return c


def evidence(**kw):
    return {"evaluation_target": kw.pop("target", "submitted_artifact"), "values": kw}
'''


TAIL = '''

# ------------------------------------------------------------------------------------------
# Reading the delivered bytes. Five sources: the recipe source, the shard manifest build()
# wrote, the served pool index, the verifier-held tables, and the harness run record. Each is
# read the same way everywhere -- absent is REPORTED under its own name, never guessed at and
# never allowed to look like a pass.
# ------------------------------------------------------------------------------------------

def bundle(rel):
    """A path relative to the bundle root, from the checker tree."""
    return os.path.normpath(os.path.join(HERE, "..", rel))


def heldout(name):
    """A verifier-side table. Lives under tests/heldout/ and the graded run may not read it."""
    return os.path.join(HERE, "heldout", name)


def run_record():
    path = os.path.normpath(os.path.join(HERE, RUN_RECORD))
    if not os.path.exists(path):
        return {}
    try:
        with open(path) as handle:
            doc = json.load(handle)
    except Exception:
        return {}
    return doc if isinstance(doc, dict) else {}


def recipe_source():
    """The recipe as TEXT. It is never imported: importing it to inspect it would run it."""
    with open(SUBMISSION, encoding="utf-8", errors="replace") as handle:
        return handle.read()


def recipe_ast():
    """The parsed recipe. Raises SyntaxError, which every caller reports rather than swallows."""
    import ast
    return ast.parse(recipe_source(), filename=SUBMISSION)


def module_level_functions():
    """name -> node for every function defined at module level, in source order."""
    import ast
    out = {}
    try:
        tree = recipe_ast()
    except (OSError, SyntaxError):
        return out
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            out[node.name] = node
    return out


def build_signature():
    """(positional parameter names, node) for the module-level build, else (None, None)."""
    node = module_level_functions().get("build")
    if node is None:
        return None, None
    args = node.args
    return [p.arg for p in list(args.posonlyargs) + list(args.args)], node


def frozen_trainer_imports():
    """Lines where the recipe imports the frozen trainer package. The shard is the only channel."""
    import ast
    try:
        tree = recipe_ast()
    except (OSError, SyntaxError):
        return []
    hits = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            names = [a.name for a in node.names]
        elif isinstance(node, ast.ImportFrom):
            names = [node.module or ""]
        else:
            continue
        for name in names:
            if name == FROZEN_PACKAGE or name.startswith(FROZEN_PACKAGE + "."):
                hits.append([getattr(node, "lineno", 0), name])
    return hits


def manifest_path():
    """Where build() said it put the manifest, else MANIFEST_NAME under the out_dir it was given."""
    rec = run_record()
    declared = rec.get("emitted_shard_manifest")
    if declared:
        return str(declared)
    out_dir = rec.get("out_dir")
    return os.path.join(str(out_dir), MANIFEST_NAME) if out_dir else None


def shard_manifest():
    path = manifest_path()
    if not path or not os.path.exists(path):
        return None
    try:
        with open(path) as handle:
            doc = json.load(handle)
    except Exception:
        return None
    return doc if isinstance(doc, dict) else None


def manifest_rows():
    """One row per SAMPLE, so an upsampled rare-class image appears once per repeat."""
    doc = shard_manifest() or {}
    rows = doc.get("samples")
    return [r for r in rows if isinstance(r, dict)] if isinstance(rows, list) else []


def manifest_source_ids():
    return sorted({str(r.get("source_id")) for r in manifest_rows() if r.get("source_id") is not None})


def observed_ops():
    """The op names the HARNESS watched build() execute, in order. Never the recipe's own claim."""
    seq = run_record().get("observed_op_sequence")
    return [str(op) for op in seq] if isinstance(seq, list) else []


def declared_ops():
    """The op order the manifest claims. Graded against observed_ops, never trusted alone."""
    seq = (shard_manifest() or {}).get(DECLARED_OPS_KEY)
    return [str(op) for op in seq] if isinstance(seq, list) else []


def op_index(name, sequence):
    return sequence.index(name) if name in sequence else None


def pool_rows():
    """The SERVED pool index: a run-indexed rotated subsample, addressed by field not offset."""
    import csv
    path = bundle(POOL_INDEX)
    if not os.path.exists(path):
        return []
    try:
        with open(path, newline="") as handle:
            return [r for r in csv.DictReader(handle)]
    except Exception:
        return []


def pool_field(field):
    """image_id -> that field, over the served index."""
    return dict((str(r.get("image_id")), str(r.get(field)))
                for r in pool_rows() if r.get("image_id") is not None and r.get(field) is not None)


def burst_of():
    return pool_field("burst_id")


def site_of():
    return pool_field("site_id")


def served_site_ids():
    return set(site_of().values())


def capture_times():
    """source id -> capture timestamp, held VERIFIER-SIDE.

    C3-LEAK re-derives the boundary decision from this table rather than from the timestamp the
    recipe wrote into its own manifest. A recipe that mislabels its rows must not be able to
    relabel its way past the one red line the task has zero tolerance for.
    """
    import csv
    path = heldout(CAPTURE_TIMES)
    if not os.path.exists(path):
        return {}
    try:
        with open(path, newline="") as handle:
            return dict((str(r.get("image_id")), str(r.get("capture_timestamp")))
                        for r in csv.DictReader(handle))
    except Exception:
        return {}


def boundary_instant():
    """The declared boundary, as an ISO-8601 instant.

    Timestamps are compared as STRINGS. ISO-8601 in a fixed zone with fixed field widths orders
    lexicographically, which keeps the comparison free of a timezone library the verifier
    environment may not carry. Phase 1 must emit both tables in that form.
    """
    path = heldout(BOUNDARY)
    if not os.path.exists(path):
        return None
    try:
        with open(path) as handle:
            return json.load(handle).get("boundary")
    except Exception:
        return None


def last_reward_log_entry():
    """The final parseable record of the agent's own reward_log.jsonl, or None."""
    path = run_record().get("reward_log")
    if not path or not os.path.exists(str(path)):
        return None
    last = None
    try:
        with open(str(path)) as handle:
            for line in handle:
                line = line.strip()
                if not line:
                    continue
                try:
                    row = json.loads(line)
                except Exception:
                    continue
                if isinstance(row, dict):
                    last = row
    except Exception:
        return None
    return last


def graded_predictions():
    """The frozen trainer's private_A prediction vector, written verifier-side after step 6000."""
    import numpy as np
    return np.load(heldout(PREDICTIONS_A), allow_pickle=False).astype("int64").ravel()


def private_a_labels():
    import numpy as np
    return np.load(heldout(LABELS_A), allow_pickle=False).astype("int64").ravel()


def measure():
    """Macro-averaged balanced accuracy: mean per-class RECALL over the twelve classes.

    Recall per class, then a flat mean over classes -- not overall accuracy. The distinction is
    the whole point of the metric: the eleven-species-plus-empty vocabulary is heavily skewed, so
    a shard that raises overall accuracy by dropping the rare classes lowers this number.
    """
    predicted, truth = graded_predictions(), private_a_labels()
    if not len(predicted) or not len(truth):
        raise ConstantUnmeasured("the graded prediction vector or its private labels are absent")
    n = min(len(predicted), len(truth))
    predicted, truth = predicted[:n], truth[:n]
    recalls = []
    for label in range(CLASS_COUNT):
        support = truth == label
        if not support.any():
            raise ConstantUnmeasured("class %s has no support on private_A" % label)
        recalls.append(float((predicted[support] == label).mean()))
    return float(sum(recalls) / len(recalls))
'''


# ==========================================================================================
# BODIES. Every compiled item carries one, written for THIS slot. The generic obligation
# lookup that used to fill this gap is gone: it read run_record()["obligations"][<ID>], a key
# nothing in the harness writes, so an item that fell through to it consulted nothing at all
# and still reported a clean False. The generator now REFUSES on a missing body.
# ==========================================================================================

BODIES = {

    "recipe_exposes_build_pool_index_out_dir": '''
    if not os.path.exists(SUBMISSION):
        return False, evidence(reason="submission_missing", path=SUBMISSION)
    try:
        params, node = build_signature()
    except SyntaxError as exc:
        return False, evidence(reason="recipe_contract_unmet", detail="recipe does not parse",
                               error=str(exc))
    if node is None:
        return False, evidence(reason="recipe_contract_unmet",
                               detail="no module-level build; the verifier has nothing to call",
                               module_level_functions=sorted(module_level_functions()))
    ok = params == list(BUILD_PARAMS)
    return ok, evidence(parameters=params, required=list(BUILD_PARAMS),
                        reason=None if ok else "recipe_contract_unmet")
''',

    "emitted_shard_manifest_admissible": '''
    path = manifest_path()
    if not path:
        return False, evidence(target="emitted_shard", reason="shard_unreadable",
                               detail="the run record names neither out_dir nor a manifest path")
    if not os.path.exists(path):
        return False, evidence(target="emitted_shard", reason="shard_unreadable", path=path,
                               detail="build() returned without leaving %s" % MANIFEST_NAME)
    if shard_manifest() is None:
        return False, evidence(target="emitted_shard", reason="shard_unreadable", path=path,
                               detail="the manifest does not parse as a JSON object")
    rows = manifest_rows()
    if not rows:
        return False, evidence(target="emitted_shard", reason="shard_unreadable", path=path,
                               detail="the samples list is absent or empty")
    missing = sorted(set(f for f in MANIFEST_FIELDS for r in rows if f not in r))
    return (not missing), evidence(target="emitted_shard", path=path, sample_rows=len(rows),
                                   required_fields=list(MANIFEST_FIELDS), missing_fields=missing,
                                   reason=None if not missing else "shard_unreadable")
''',

    "c3_leak": '''
    boundary = boundary_instant()
    if boundary is None:
        return False, evidence(target="emitted_shard", reason="boundary_declaration_unavailable",
                               path=heldout(BOUNDARY))
    times = capture_times()
    if not times:
        return False, evidence(target="emitted_shard", reason="capture_table_unavailable",
                               path=heldout(CAPTURE_TIMES))
    ids = manifest_source_ids()
    if not ids:
        return False, evidence(target="emitted_shard", reason="shard_unreadable",
                               detail="no source ids to check against the boundary")
    unresolved = [i for i in ids if i not in times]
    at_or_after = [i for i in ids if i in times and times[i] >= boundary]
    ok = not unresolved and not at_or_after
    return ok, evidence(target="emitted_shard", boundary=boundary, source_ids=len(ids),
                        unresolved_ids=unresolved[:8], post_boundary_ids=at_or_after[:8],
                        unresolved_count=len(unresolved), post_boundary_count=len(at_or_after),
                        reason=None if ok else "temporal_leakage")
''',

    "c1_bal": '''
    rows = manifest_rows()
    if not rows:
        return False, evidence(target="emitted_shard", reason="shard_unreadable")
    present = set()
    for row in rows:
        label = row.get("label")
        present.add(str(label))
        if isinstance(label, int) and not isinstance(label, bool) and 0 <= label < len(CLASSES):
            present.add(CLASSES[label])
    missing = [name for i, name in enumerate(CLASSES)
               if name not in present and str(i) not in present]
    return (not missing), evidence(target="emitted_shard", classes=len(CLASSES),
                                   classes_present=len(CLASSES) - len(missing), missing=missing,
                                   ceiling_if_missing=round((len(CLASSES) - len(missing))
                                                            / float(len(CLASSES)), 6),
                                   reason=None if not missing else "class_absent_from_shard")
''',

    "c2_budget": '''
    rec = run_record()
    pair = (("recipe_elapsed_seconds", rec.get("recipe_elapsed_seconds")),
            ("trainer_elapsed_seconds", rec.get("trainer_elapsed_seconds")))
    absent = [k for k, v in pair if v is None]
    if absent:
        return False, evidence(target="run_record", reason="envelope_unaccounted", missing=absent,
                               detail="both halves of the joint envelope must be measured")
    try:
        recipe_s, trainer_s = float(pair[0][1]), float(pair[1][1])
    except (TypeError, ValueError) as exc:
        return False, evidence(target="run_record", reason="envelope_unaccounted", error=str(exc))
    if recipe_s <= 0 or trainer_s <= 0:
        return False, evidence(target="run_record", reason="envelope_unaccounted",
                               recipe_seconds=recipe_s, trainer_seconds=trainer_s,
                               detail="a stage reported as costing no time was not measured; the "
                                      "recipe's decode, filter, dedup and rebalance work is inside "
                                      "the same envelope as the trainer's steps")
    joint = recipe_s + trainer_s
    ok = joint <= ENVELOPE_SECONDS
    return ok, evidence(target="run_record", recipe_seconds=recipe_s, trainer_seconds=trainer_s,
                        joint_seconds=joint, envelope_seconds=ENVELOPE_SECONDS,
                        recipe_share=round(recipe_s / joint, 6),
                        reason=None if ok else "budget_exceeded")
''',

    "burst_dedup_precedes_rebalance_in_executed_ops": '''
    seq = observed_ops()
    if not seq:
        return False, evidence(target="run_record", reason="no_observed_op_sequence")
    dedup, rebalance = op_index(OP_DEDUP, seq), op_index(OP_REBALANCE, seq)
    absent = [n for n, i in ((OP_DEDUP, dedup), (OP_REBALANCE, rebalance)) if i is None]
    if absent:
        return False, evidence(target="run_record", observed=seq, absent_ops=absent,
                               reason="op_absent_from_sequence")
    ok = dedup < rebalance
    return ok, evidence(target="run_record", observed=seq, dedup_at=dedup, rebalance_at=rebalance,
                        reason=None if ok else "rebalance_multiplied_burst_duplicates")
''',

    "dedup_filters_the_index_before_any_decode": '''
    seq = observed_ops()
    if not seq:
        return False, evidence(target="run_record", reason="no_observed_op_sequence")
    dedup, decode = op_index(OP_DEDUP, seq), op_index(OP_DECODE, seq)
    absent = [n for n, i in ((OP_DEDUP, dedup), (OP_DECODE, decode)) if i is None]
    if absent:
        return False, evidence(target="run_record", observed=seq, absent_ops=absent,
                               reason="op_absent_from_sequence")
    ok = dedup < decode
    return ok, evidence(target="run_record", observed=seq, dedup_at=dedup, decode_at=decode,
                        reason=None if ok else "decoded_frames_the_recipe_then_discarded")
''',

    "at_most_one_frame_per_burst_id": '''
    ids = manifest_source_ids()
    if not ids:
        return False, evidence(target="emitted_shard", reason="shard_unreadable")
    bursts = burst_of()
    if not bursts:
        return False, evidence(target="emitted_shard", reason="pool_index_unavailable",
                               path=bundle(POOL_INDEX))
    first, collisions, unresolved = {}, [], []
    for source_id in ids:
        burst = bursts.get(source_id)
        if burst is None:
            unresolved.append(source_id)
        elif burst in first:
            collisions.append([burst, first[burst], source_id])
        else:
            first[burst] = source_id
    ok = not collisions and not unresolved
    return ok, evidence(target="emitted_shard", distinct_source_ids=len(ids),
                        distinct_bursts=len(first), collisions=collisions[:8],
                        collision_count=len(collisions), unresolved_ids=unresolved[:8],
                        reason=None if ok else "two_frames_of_one_trigger")
''',

    "night_ir_statistics_computed_before_augmentation": '''
    seq = observed_ops()
    if not seq:
        return False, evidence(target="run_record", reason="no_observed_op_sequence")
    stats_at = op_index(OP_STATISTICS, seq)
    if stats_at is None:
        return False, evidence(target="run_record", observed=seq, absent_ops=[OP_STATISTICS],
                               reason="op_absent_from_sequence")
    early = [op for op in AUGMENTATION_OPS
             if op_index(op, seq) is not None and op_index(op, seq) < stats_at]
    recorded = run_record().get("normalization_statistics")
    keyed = sorted(recorded) if isinstance(recorded, dict) else []
    pooled = [regime for regime in ILLUMINATION_REGIMES if regime not in keyed]
    ok = not early and not pooled
    return ok, evidence(target="run_record", observed=seq, statistics_at=stats_at,
                        augmentation_before_statistics=early, regimes_keyed=keyed,
                        regimes_missing=pooled,
                        reason=None if ok else "night_ir_statistics_folded_into_daylight")
''',

    "declared_op_sequence_equals_the_observed_one": '''
    observed, declared = observed_ops(), declared_ops()
    if not observed:
        return False, evidence(target="run_record", reason="no_observed_op_sequence")
    if not declared:
        return False, evidence(target="run_record", observed=observed,
                               reason="no_declared_op_sequence",
                               detail="a recipe that declares no order cannot be graded on one")
    ok = declared == observed
    divergence = next((i for i in range(max(len(declared), len(observed)))
                       if declared[i:i + 1] != observed[i:i + 1]), None)
    return ok, evidence(target="run_record", declared=declared, observed=observed,
                        first_divergence_at=divergence,
                        reason=None if ok else "declared_order_is_not_the_executed_order")
''',

    "selected_sites_span_the_served_camera_roster": '''
    rows = manifest_rows()
    if not rows:
        return False, evidence(target="emitted_shard", reason="shard_unreadable")
    sites = site_of()
    if not sites:
        return False, evidence(target="emitted_shard", reason="pool_index_unavailable",
                               path=bundle(POOL_INDEX))
    counts, unresolved = {}, 0
    for row in rows:
        site = sites.get(str(row.get("source_id")))
        if site is None:
            unresolved += 1
        else:
            counts[site] = counts.get(site, 0) + 1
    placed = sum(counts.values())
    roster = len(set(sites.values()))
    coverage = (len(counts) / float(roster)) if roster else 0.0
    largest = (max(counts.values()) / float(placed)) if placed else 1.0
    ok = (unresolved == 0 and coverage >= SITE_COVERAGE_FLOOR
          and largest <= MAX_SINGLE_SITE_SHARE)
    return ok, evidence(target="emitted_shard", sites_selected=len(counts), roster_sites=roster,
                        coverage=round(coverage, 6), coverage_floor=SITE_COVERAGE_FLOOR,
                        largest_site_share=round(largest, 6),
                        largest_site_share_cap=MAX_SINGLE_SITE_SHARE, unresolved_rows=unresolved,
                        reason=None if ok else "selection_collapsed_onto_few_cameras")
''',

    "internal_validation_holds_out_latest_preboundary_window": '''
    rec = run_record()
    policy = rec.get("split_policy")
    if policy is None:
        return False, evidence(target="run_record", reason="no_split_policy_declared")
    text = str(policy).lower()
    leaking = [w for w in ("shuffle", "shuffled", "random_split", "random split", "kfold",
                           "k-fold", "stratifiedkfold", "permut") if w in text]
    ordered = any(w in text for w in ("ordered", "chronological", "time_order", "time order",
                                      "expanding", "rolling", "latest", "holdout by date"))
    stamps = rec.get("split_timestamps") or {}
    train = sorted(str(t) for t in (stamps.get("train") or []))
    validation = sorted(str(t) for t in (stamps.get("validation") or []))
    if not train or not validation:
        return False, evidence(target="run_record", declared=str(policy)[:200],
                               reason="split_timestamps_unrecorded")
    straddles = validation[0] <= train[-1]
    ok = ordered and not leaking and not straddles
    return ok, evidence(target="run_record", declared=str(policy)[:200], leaking_tokens=leaking,
                        names_an_order=ordered, latest_train=train[-1],
                        earliest_validation=validation[0], straddles=straddles,
                        reason=None if ok else "validation_split_is_not_time_ordered")
''',

    "class_histogram_traced_to_the_served_index_not_literals": '''
    import ast
    try:
        tree = recipe_ast()
    except (OSError, SyntaxError) as exc:
        return False, evidence(target="submitted_source", reason="recipe_contract_unmet",
                               error=str(exc))
    known_sites = served_site_ids()
    long_literals, keyed_tables = [], []
    for node in ast.walk(tree):
        if isinstance(node, (ast.List, ast.Tuple, ast.Set)):
            numeric = [e for e in node.elts
                       if isinstance(e, ast.Constant)
                       and isinstance(e.value, (int, float)) and not isinstance(e.value, bool)]
            if len(numeric) == len(node.elts) and len(numeric) > LITERAL_PRIOR_MAX:
                long_literals.append([getattr(node, "lineno", 0), len(numeric)])
        elif isinstance(node, ast.Dict):
            keys = set(k.value for k in node.keys
                       if isinstance(k, ast.Constant) and isinstance(k.value, str))
            hits = sorted(keys & (set(CLASSES) | known_sites))
            if hits:
                keyed_tables.append([getattr(node, "lineno", 0), hits[:6]])
    source = run_record().get("class_histogram_source")
    traced = source is not None and POOL_INDEX in str(source)
    ok = not long_literals and not keyed_tables and traced
    return ok, evidence(target="submitted_source", long_numeric_literals=long_literals[:4],
                        literal_cap=LITERAL_PRIOR_MAX,
                        class_or_site_keyed_dicts=keyed_tables[:4],
                        histogram_source=str(source)[:200] if source is not None else None,
                        traced_to_served_index=traced,
                        reason=None if ok else "priors_unprovenanced")
''',

    "rebalancing_sized_from_pool_index_not_dataset_card": '''
    try:
        source = recipe_source()
    except OSError as exc:
        return False, evidence(target="submitted_source", reason="submission_missing",
                               error=str(exc))
    card = os.path.basename(DATASET_CARD)
    hits = [[n, line.strip()[:120]] for n, line in enumerate(source.splitlines(), 1)
            if DATASET_CARD in line or card in line]
    ok = not hits
    return ok, evidence(target="submitted_source", dataset_card=DATASET_CARD,
                        authoritative=POOL_INDEX, references=hits[:6],
                        reason=None if ok else "sized_from_the_stale_dataset_card")
''',

    "selection_keyed_to_index_fields_not_row_offsets": '''
    import ast
    try:
        source = recipe_source()
        tree = recipe_ast()
    except (OSError, SyntaxError) as exc:
        return False, evidence(target="submitted_source", reason="recipe_contract_unmet",
                               error=str(exc))
    named = sorted(f for f in POOL_FIELDS if f in source)
    poolish = ("pool", "index", "rows", "records", "catalog")
    offsets = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Subscript) or not isinstance(node.slice, ast.Slice):
            continue
        base = node.value
        name = base.id if isinstance(base, ast.Name) else getattr(base, "attr", "")
        if not any(token in str(name).lower() for token in poolish):
            continue
        bounds = [b for b in (node.slice.lower, node.slice.upper) if b is not None]
        if any(isinstance(b, ast.Constant) and isinstance(b.value, int) for b in bounds):
            offsets.append([getattr(node, "lineno", 0), str(name)])
    ok = len(named) >= 2 and not offsets
    return ok, evidence(target="submitted_source", fields_named=named,
                        fields_available=list(POOL_FIELDS), positional_slices=offsets[:6],
                        reason=None if ok else "keyed_to_row_offsets_not_fields")
''',

    "emitted_row_count_within_cap_counting_repeats": '''
    rows = manifest_rows()
    if not rows:
        return False, evidence(target="emitted_shard", reason="shard_unreadable")
    total = len(rows)
    distinct = len(manifest_source_ids())
    claimed = (shard_manifest() or {}).get("sample_count")
    misreported = False
    if claimed is not None:
        try:
            misreported = int(claimed) != total
        except (TypeError, ValueError):
            misreported = True
    over = total > SAMPLE_CAP_ROWS
    ok = not over and not misreported
    reason = "shard_cap_exceeded" if over else (
        "sample_count_counted_distinct_not_rows" if misreported else None)
    return ok, evidence(target="emitted_shard", sample_rows=total, distinct_source_ids=distinct,
                        upsampled_repeats=total - distinct, declared_sample_count=claimed,
                        cap=SAMPLE_CAP_ROWS, reason=reason)
''',

    "frozen_trainer_digests_unchanged_across_the_recipe": '''
    rec = run_record()
    before = rec.get("frozen_digests_before") or {}
    after = rec.get("frozen_digests_after") or {}
    if not isinstance(before, dict) or not isinstance(after, dict) or not before or not after:
        return False, evidence(target="run_record", reason="frozen_digests_unrecorded",
                               before=sorted(before) if isinstance(before, dict) else None,
                               after=sorted(after) if isinstance(after, dict) else None)
    moved = sorted(k for k in set(before) | set(after) if before.get(k) != after.get(k))
    touched = sorted(str(p) for p in (rec.get("guarded_paths_touched") or [])
                     if any(str(p).startswith(g) for g in GUARDED))
    imports = frozen_trainer_imports()
    ok = not moved and not touched and not imports
    return ok, evidence(target="run_record", digests_compared=sorted(set(before) | set(after)),
                        digests_moved=moved, guarded_paths_touched=touched[:8],
                        frozen_package_imports=imports[:6],
                        reason=None if ok else "trainer_modified")
''',

    "sibling_shard_gap_within_bound": '''
    rec = run_record()
    a, b = rec.get("balanced_accuracy_private_a"), rec.get("balanced_accuracy_private_b")
    if a is None or b is None:
        return False, evidence(target="graded_predictions", reason="sibling_measurement_absent",
                               private_a=a, private_b=b)
    try:
        a, b = float(a), float(b)
    except (TypeError, ValueError) as exc:
        return False, evidence(target="graded_predictions",
                               reason="sibling_measurement_absent", error=str(exc))
    gap = abs(a - b)
    ok = gap <= SIBLING_GAP_BOUND
    return ok, evidence(target="graded_predictions", private_a=a, private_b=b,
                        gap=round(gap, 6), bound=SIBLING_GAP_BOUND,
                        reason=None if ok else "sibling_gap_violation")
''',

    "replay_reproduces_shard_and_prediction_digests": '''
    rec = run_record()
    first = rec.get("first_run_digests") or {}
    replay = rec.get("replay_digests") or {}
    wanted = ("shard_manifest", "trainer_parameters", "private_a_predictions")
    if not isinstance(first, dict) or not isinstance(replay, dict):
        return False, evidence(target="run_record", reason="replay_unavailable")
    absent = [k for k in wanted if not first.get(k) or not replay.get(k)]
    if absent:
        return False, evidence(target="run_record", reason="replay_unavailable", missing=absent)
    diverged = [k for k in wanted if first[k] != replay[k]]
    return (not diverged), evidence(target="run_record", compared=list(wanted),
                                    diverged=diverged, trainer_steps=TRAINER_STEPS,
                                    reason=None if not diverged else "replay_diverged")
''',

    "c10_log": '''
    rec = run_record()
    entry = last_reward_log_entry()
    if entry is None:
        return False, evidence(target="run_record", reason="log_fabrication",
                               detail="no parseable reward_log.jsonl record",
                               path=rec.get("reward_log"))
    measured_accuracy = rec.get("balanced_accuracy_private_a")
    recipe_s, trainer_s = rec.get("recipe_elapsed_seconds"), rec.get("trainer_elapsed_seconds")
    if measured_accuracy is None or recipe_s is None or trainer_s is None:
        return False, evidence(target="run_record", reason="harness_measurement_absent",
                               detail="the agent's log can only be graded against a measurement")
    try:
        measured_accuracy = float(measured_accuracy)
        measured_elapsed = float(recipe_s) + float(trainer_s)
        claimed_accuracy = float(entry["balanced_accuracy"])
        claimed_elapsed = float(entry["elapsed_seconds"])
    except (KeyError, TypeError, ValueError) as exc:
        return False, evidence(target="run_record", reason="log_fabrication",
                               record_keys=sorted(entry), error=str(exc))
    accuracy_gap = abs(claimed_accuracy - measured_accuracy)
    elapsed_gap = (abs(claimed_elapsed - measured_elapsed) / measured_elapsed
                   if measured_elapsed else 1.0)
    ok = accuracy_gap <= LOG_ACCURACY_TOLERANCE and elapsed_gap <= LOG_ELAPSED_TOLERANCE
    return ok, evidence(target="run_record", claimed_accuracy=claimed_accuracy,
                        measured_accuracy=measured_accuracy,
                        accuracy_gap=round(accuracy_gap, 6),
                        accuracy_tolerance=LOG_ACCURACY_TOLERANCE,
                        claimed_elapsed=claimed_elapsed, measured_elapsed=measured_elapsed,
                        elapsed_relative_gap=round(elapsed_gap, 6),
                        elapsed_tolerance=LOG_ELAPSED_TOLERANCE,
                        reason=None if ok else "log_fabrication")
''',

    "balanced_accuracy_over_twelve_classes_ramp": '''
    # require_measured FIRST, before any prediction is read. Reading first lets an absent
    # prediction vector report as an ordinary failure, which makes the verifier say
    # gradeable=true with r_det=0.0 -- collapsing "this slot is not yet measurable" into "the
    # recipe scored zero". seed/build/freeze_batch.py refuses to freeze a bundle that does this.
    c = require_measured("floor", "knee", "dichotomizing_threshold")
    accuracy = measure()
    span = c["knee"] - c["floor"]
    s = 0.0 if span <= 0 else max(0.0, min(1.0, (accuracy - c["floor"]) / span))
    return accuracy >= c["dichotomizing_threshold"], evidence(
        target="graded_predictions", balanced_accuracy=accuracy, classes=CLASS_COUNT,
        floor=c["floor"], knee=c["knee"], s_outcome=s)
''',
}


def build_tests(g, prelude, bodies):
    """Assemble the compiled-check module. kind carries the item's own dimension."""
    chunks = [prelude]
    for raw in sorted(g["items"], key=lambda i: i["id"]):
        if raw["mode"] != "compiled":
            continue
        chunks.append('\n\n@check(id="%s", weight=%d, knockout=%s, kind="%s")\ndef test_%s():\n%s\n'
                      % (raw["id"], raw["weight"], raw["knockout"], raw["dimension"], raw["id"],
                         bodies[raw["id"]].strip("\n")))
    return "".join(chunks)


def build_truth(g, title):
    """Render solution/TRUTH.md from the frozen literals of solution/grounding.yaml."""
    n = g["truth_narrative"]
    lines = [title, "", "GENERATED SECTION. DO NOT HAND-EDIT.", "", n["opening"], "",
             "## The single most important insight", "", n["insight"], "",
             "## The ideal solve, step by step", ""]
    for i, step in enumerate(n["steps"], 1):
        lines += ["%d. **%s** %s" % (i, step["heading"], step["paragraph"]), ""]
    lines += ["## Traps that catch agents that are not thinking carefully", ""]
    lines += ["- " + t for t in n["traps"]]
    lines += ["", "---", "", "## Contract record (annex; not part of the narrative body)", "",
              "Retained under FORGE.md item 10e and Phase 2 item 7, which require this file to "
              "carry the ordered path through instruction.md with each satisfied checker "
              "identifier, and each rejected route bound to a measured known-wrong control. "
              "standards/truth-md-authoring-v1.md section 3 admits no fifth section, so this "
              "annex is a recorded deviation rather than an omission.", "", g["truth_annex"], ""]
    return "\n".join(lines) + "\n"


def build_rubrics(g, item_keys):
    """The 9g rubric carrier. The item schema is CLOSED at eight keys, so item 10f's outcome
    classification rides as a greppable prefix of the judgment rather than as a ninth key."""
    items = []
    for raw in g["items"]:
        item = {k: raw[k] for k in item_keys}
        item["judgment"] = "%s: %s" % (raw["outcome_class"], raw["judgment"])
        items.append(item)
    compiled = sum(i["weight"] for i in items if i["mode"] == "compiled")
    total = sum(i["weight"] for i in items)
    return {"$schema": "forge.rubric/v1",
            "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
            "generator": "solution/recompute.py",
            "compilation_floor": g["compilation_floor"],
            "compiled_weight_share": round(compiled / total, 6) if total else 0.0,
            "evaluation_target_vocabulary": sorted(g["evaluation_target_vocabulary"]),
            "items": sorted(items, key=lambda i: i["id"])}


def build_provenance(g, identity):
    p = g["provenance"]
    out = {
        "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
        "generator": "solution/recompute.py from solution/grounding.yaml",
        "schema_version": "1.0",
        "slot_id": g["slot_id"],
        "identity": identity,
        "corpus": p["corpus"],
        "anchors": p["anchors"],
        "shards": p["shards"],
        "narrative": p["narrative"],
        "supersedes": p["supersedes"],
        "upstream_provenance": p["upstream_record"],
        "reward_composition": p["reward_composition"],
        "screening_interval_days": p["screening_interval_days"],
        "screening_detector_version": p["screening_detector_version"],
        "derivation_instant": p["derivation_instant"],
        "screening_roots": p["screening_roots"],
        "empty_submission_result": p["empty_submission_result"],
        "resolved_closure": p["resolved_closure"],
        "applicability": p["applicability"],
        "measurement_tier": g["measurement_tier"],
        "gradeable": g["gradeable"],
        "knee_anchor_status": g["knee_anchor_status"],
        "graded_object": "a data selection recipe, executed by the verifier as "
                         "build(pool_index, out_dir); the trainer it feeds is byte-frozen",
        "corpus_layout_status": g["corpus_layout"]["status"],
    }
    out.update(read_screening(HERE))
    return out


def validate(grounding):
    """Refuse on a malformed derivation source rather than emitting a checker from one.

    The family validator that stood here asserted one thing -- that a `deliverable_shape` item
    existed and was a knockout -- which was true of a bundle whose every other item graded
    nothing. These are the invariants the emitted checker actually depends on.
    """
    problems = []
    items = grounding.get("items") or []
    if not items:
        problems.append("no items to compile")
    seen = set()
    for item in items:
        iid = item.get("id", "<unnamed>")
        if iid in seen:
            problems.append("duplicate item id %r" % iid)
        seen.add(iid)
        if set(item) != ITEM_SCHEMA:
            problems.append("item %r does not carry the closed schema: %s"
                            % (iid, sorted(set(item) ^ ITEM_SCHEMA)))
            continue
        if item["outcome_class"] not in OUTCOME_CLASSES:
            problems.append("item %r has outcome_class %r" % (iid, item["outcome_class"]))
        if item["evaluation_target"] not in grounding["evaluation_target_vocabulary"]:
            problems.append("item %r evaluates %r, which the vocabulary does not admit"
                            % (iid, item["evaluation_target"]))
        if not isinstance(item["weight"], int) or item["weight"] <= 0:
            problems.append("item %r carries weight %r" % (iid, item["weight"]))

    outcome = [i["id"] for i in items if i.get("dimension") == "outcome"]
    if len(outcome) != 1:
        problems.append("expected exactly one outcome item, found %r" % outcome)

    for name in RAMP:
        if grounding["constants"].get(name) is not None:
            problems.append("constant %r is authored at Phase 0; it is measured, not authored"
                            % name)

    if grounding["deliverable"].get("kind") != "python_module":
        problems.append("the graded deliverable of this slot is a callable recipe module, not %r"
                        % grounding["deliverable"].get("kind"))

    layout = grounding.get("corpus_layout") or {}
    classes = layout.get("classes") or []
    if len(classes) != layout.get("class_count"):
        problems.append("the class roster holds %d labels and class_count says %r"
                        % (len(classes), layout.get("class_count")))
    if len(set(classes)) != len(classes):
        problems.append("the class roster repeats a label")

    known_ops = set((layout.get("op_names") or {}).values())
    stray = sorted({op for pair in (layout.get("required_op_precedences") or []) for op in pair}
                   - known_ops)
    if stray:
        problems.append("required_op_precedences names %s, which op_names does not" % stray)
    stray = sorted(set(layout.get("augmentation_ops") or []) - known_ops)
    if stray:
        problems.append("augmentation_ops names %s, which op_names does not" % stray)

    # The two site bounds are AUTHORED, not measured, so the one thing that can be checked here
    # is that they are fractions and that they are not silently a pass for everything.
    for key in ("site_coverage_floor", "max_single_site_share"):
        value = layout.get(key)
        if not isinstance(value, float) or not 0.0 < value <= 1.0:
            problems.append("corpus_layout %s is %r, which is not a fraction in (0,1]"
                            % (key, value))
    return problems


def main():
    g = load_grounding()
    # The validator runs FIRST and refuses rather than emitting: a generator that writes a
    # carrier it knows is malformed hands the drift check a moving target.
    problems = validate(g)
    if problems:
        raise SystemExit("AELLO-C8-S3 grounding is not well-formed: " + "; ".join(problems))

    layout = g["corpus_layout"]
    ops = layout["op_names"]
    outcome_id = [i["id"] for i in g["items"] if i["dimension"] == "outcome"][0]
    subst = {
        "slot_id": SLOT_ID,
        "path": g["deliverable"]["path"],
        "outcome_id": outcome_id,
        "build_params": tuple(BUILD_PARAMS),
        "frozen_package": layout["frozen_trainer_package"],
        "pool_index": layout["pool_index"],
        "pool_fields": tuple(layout["pool_index_fields"]),
        "dataset_card": layout["dataset_card"],
        "classes": tuple(layout["classes"]),
        "class_count": layout["class_count"],
        "manifest_name": layout["emitted_shard_manifest_name"],
        "manifest_fields": tuple(layout["manifest_sample_fields"]),
        "declared_ops_key": layout["manifest_declared_op_key"],
        "run_record": layout["run_record"],
        "capture_times": os.path.basename(layout["capture_times"]),
        "boundary": os.path.basename(layout["boundary_declaration"]),
        "labels_a": os.path.basename(layout["private_a_labels"]),
        "predictions_a": os.path.basename(layout["private_a_predictions"]),
        "guarded": tuple(layout["guarded_prefixes"]),
        "op_dedup": ops["dedup"],
        "op_decode": ops["decode"],
        "op_rebalance": ops["rebalance"],
        "op_statistics": ops["statistics"],
        "augmentation_ops": tuple(layout["augmentation_ops"]),
        "regimes": tuple(layout["illumination_regimes"]),
        "envelope_seconds": layout["joint_envelope_seconds"],
        "sample_cap_rows": layout["sample_cap_rows"],
        "sibling_gap_bound": layout["sibling_gap_bound"],
        "trainer_steps": layout["trainer_steps"],
        "log_accuracy_tolerance": layout["log_balanced_accuracy_tolerance"],
        "log_elapsed_tolerance": layout["log_elapsed_tolerance_fraction"],
        "site_coverage_floor": layout["site_coverage_floor"],
        "max_single_site_share": layout["max_single_site_share"],
        "literal_prior_max": layout["literal_prior_max_elements"],
    }

    # EVERY compiled item carries a written body. The generic obligation lookup that used to
    # stand here is gone: it read a run-record key nothing writes, so any item falling through
    # to it graded nothing at all and said so in no report. Refuse instead of falling through.
    bodies = dict(BODIES)
    for it in g["items"]:
        if it["mode"] == "compiled" and it["id"] not in bodies:
            raise SystemExit("AELLO-C8-S3: no body written for compiled item %r; the generator "
                             "refuses rather than emitting a check that consults nothing"
                             % it["id"])

    # The outcome check must SAY the slot is unmeasurable before it reads anything at all. If it
    # reads first, a missing prediction vector reports as an ordinary failure and the verifier
    # then says gradeable=true with r_det=0.0, collapsing two different claims into one.
    statements = [ln.strip() for ln in bodies[outcome_id].splitlines()
                  if ln.strip() and not ln.strip().startswith("#")]
    if not statements or statements[0] != REQUIRE_FIRST:
        raise SystemExit("AELLO-C8-S3: %r must call require_measured as its first statement, "
                         "before it reads any prediction" % outcome_id)

    tests_dir = os.path.join(BUNDLE, "tests")
    os.makedirs(tests_dir, exist_ok=True)

    # solution/TRUTH.md and solution/rubrics.json are PRIVATE_CARRIERS: seed/identity.py plants a
    # canary block into them at freeze, and canary normalisation is what keeps planting from
    # moving identity. A generator that rewrote them plainly would DROP the planted tripwire, and
    # the next content_hash would differ from the frozen one. So the planted block is carried
    # across the regeneration rather than recreated.
    truth_path = os.path.join(HERE, "TRUTH.md")
    truth = build_truth(g, TITLE).rstrip("\n") + "\n"
    keep = None
    if os.path.exists(truth_path):
        import re as _re
        m = _re.search(r"<!-- AELLO-CANARY-BLOCK.*?-->\n?", open(truth_path).read(), _re.S)
        keep = m.group(0) if m else None
    with open(truth_path, "w") as fh:
        fh.write(truth + ("\n" + keep if keep else ""))

    rub_path = os.path.join(HERE, "rubrics.json")
    rub = build_rubrics(g, ITEM_KEYS)
    if os.path.exists(rub_path):
        try:
            prev = json.load(open(rub_path))
            if "canary" in prev:
                rub["canary"] = prev["canary"]
        except Exception:
            pass
    with open(rub_path, "w") as fh:
        json.dump(rub, fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "rubrics.json"), "w") as fh:
        json.dump(build_rubrics(g, ITEM_KEYS), fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "test_output.py"), "w") as fh:
        # The tail arrives FINAL and UNSUBSTITUTED. It carries percent formatting of its own
        # inside the emitted helpers, so formatting it a second time raises TypeError.
        fh.write(build_tests(g, PRELUDE % subst, bodies) + TAIL)
    with open(os.path.join(tests_dir, "constants.json"), "w") as fh:
        json.dump(g["constants"], fh, indent=1, sort_keys=True)
        fh.write("\n")
    # ORDER MATTERS. `with open(path, "w")` truncates BEFORE its body's arguments are evaluated,
    # so calling read_identity() inside the with-statement reads the file this line just emptied
    # and writes nulls over the frozen identity. Read first, then open.
    prov = build_provenance(g, read_identity(HERE))
    with open(os.path.join(HERE, "provenance.yaml"), "w") as fh:
        # MATCH seed/build/screen_bind.py and the frozen generators exactly: sort_keys=True,
        # default_flow_style=False, width=100. The screen writes this carrier after the freeze,
        # so a generator using a different dump convention reorders the keys on the next
        # regeneration and reports as drift even though no value changed.
        yaml.safe_dump(prov, fh, sort_keys=True, default_flow_style=False, width=100,
                       allow_unicode=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
