"""Compiled checks for AELLO-C8-S9. GENERATED by solution/recompute.py. DO NOT HAND-EDIT.

Every check below runs against delivered bytes and references no unmeasured quantity, except
graded_metric, which raises ConstantUnmeasured while tests/constants.json carries nulls.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SUBMISSION = '/submission/forecast.npy'
CHECKS = []


class ConstantUnmeasured(Exception):
    """Raised when a check needs a ramp constant that Phase 0 deliberately left null."""


def check(id, weight, knockout, kind):
    def deco(fn):
        CHECKS.append({"id": id, "weight": weight, "knockout": knockout, "kind": kind, "fn": fn})
        return fn
    return deco


def constants():
    with open(os.path.join(HERE, "constants.json")) as fh:
        return json.load(fh)


def require_measured(*names):
    c = constants()
    missing = [n for n in names if c.get(n) is None]
    if missing:
        raise ConstantUnmeasured(
            "AELLO-C8-S9: " + ", ".join(missing) + " are null. Phase 0 authors no measurement; "
            "the Phase 2 measurement wave writes these and this check becomes gradeable then.")
    return c


def evidence(**kw):
    return {"evaluation_target": kw.pop("target", "submitted_artifact"), "values": kw}

@check(id="forecast_lands", weight=5, knockout=True, kind="process")
def test_forecast_lands():
    if not os.path.exists(SUBMISSION):
        return False, evidence(reason="submission_missing", path=SUBMISSION)
    try:
        arr = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    return True, evidence(path=SUBMISSION, dtype=str(arr.dtype), shape=str(arr.shape))

@check(id="forecast_origin_causality", weight=5, knockout=True, kind="process")
def test_forecast_origin_causality():
    rec = run_record().get("forecast_origins")
    if not rec:
        return False, evidence(target="run_record", reason="no_origin_record")
    bad = [o for o in rec
           if o.get("max_consumed_index") is None
           or o["max_consumed_index"] >= o["origin_index"]]
    return (not bad), evidence(target="run_record", origins=len(rec),
                               violations=len(bad),
                               reason=None if not bad else "consumed_at_or_after_origin")

@check(id="forecast_within_observed_envelope", weight=3, knockout=False, kind="process")
def test_forecast_within_observed_envelope():
    import numpy as np
    try:
        arr = np.asarray(load_submission(), dtype="float64").ravel()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    if not np.isfinite(arr).all():
        return False, evidence(reason="non_finite_forecast")
    hist = np.load(os.path.join(HERE, "..", "environment", "data",
                                "ettm1_train.npy"))[:, -1].astype("float64")
    pad = float(hist.std())
    lo, hi = float(hist.min()) - pad, float(hist.max()) + pad
    out = int(((arr < lo) | (arr > hi)).sum())
    return out == 0, evidence(outside_envelope=out, envelope=[lo, hi],
                              reason=None if out == 0 else "forecast_outside_envelope")

@check(id="horizon_grid_alignment", weight=5, knockout=True, kind="process")
def test_horizon_grid_alignment():
    import numpy as np
    try:
        arr = np.asarray(load_submission(), dtype="float64").ravel()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    want = len(np.load(heldout("ettm1_graded_targets.npy")))
    ok = arr.size == want
    return ok, evidence(submitted=int(arr.size), graded_origins=int(want),
                        reason=None if ok else "horizon_grid_mismatch")

@check(id="lookback_budget_declared", weight=3, knockout=False, kind="process")
def test_lookback_budget_declared():
    rec = run_record().get("agent_budget_declaration")
    if rec is None:
        return False, evidence(target="run_record", reason="no_agent_declaration")
    try:
        d = json.loads(rec) if isinstance(rec, str) else dict(rec)
    except Exception as exc:
        return False, evidence(target="run_record", reason="declaration_unparseable",
                               error=str(exc))
    missing = [k for k in ("lookback", "split_budget") if k not in d]
    return (not missing), evidence(target="run_record", declared=sorted(d),
                                   missing=missing,
                                   reason=None if not missing else "declaration_incomplete")

@check(id="persistence_skill_ramp", weight=10, knockout=True, kind="process")
def test_persistence_skill_ramp():
    # require_measured FIRST. Reading the submission before saying the slot is not yet
    # measurable lets an unrelated failure mask the unmeasured signal, which reports
    # gradeable=true with r_det=0.0 and collapses two different claims into one.
    c = require_measured("floor", "knee", "dichotomizing_threshold")
    skill = measure()
    span = c["knee"] - c["floor"]
    s = 0.0 if span <= 0 else max(0.0, min(1.0, (skill - c["floor"]) / span))
    return skill >= c["dichotomizing_threshold"], evidence(skill_score=skill,
                                                          s_outcome=s)

@check(id="time_order_split_declared", weight=5, knockout=True, kind="process")
def test_time_order_split_declared():
    decl = run_record().get("split_policy")
    if decl is None:
        return False, evidence(target="run_record", reason="no_split_policy_declared")
    text = str(decl).lower()
    leaking = [w for w in ("shuffle", "shuffled", "random_split", "kfold", "permut")
               if w in text]
    ordered = any(w in text for w in ("ordered", "chronological", "time_order",
                                      "expanding", "rolling"))
    ok = ordered and not leaking
    return ok, evidence(target="run_record", declared=str(decl)[:200],
                        leaking_tokens=leaking,
                        reason=None if ok else "split_policy_not_time_ordered")

def load_submission():
    """A dense array deliverable: float array (n_windows, horizon, n_targets)"""
    import numpy as np
    arr = np.load(SUBMISSION, allow_pickle=False)
    if arr.dtype == object:
        raise ValueError("object arrays are not a valid deliverable")
    return arr


def describe(obj):
    return "%s%s" % (obj.dtype, obj.shape)


def shape_ok(obj):
    if getattr(obj, "ndim", 0) < 1:
        return False, "not_an_array"
    if obj.size == 0:
        return False, "empty_array"
    import numpy as np
    if not np.isfinite(np.asarray(obj, dtype="float64")).all():
        return False, "non_finite_entries"
    return True, None

def graded_series():
    """Forecast, private future truth, and the persistence anchor for the same window."""
    import numpy as np
    forecast = np.asarray(load_submission(), dtype="float64").ravel()
    truth = np.load(heldout("ettm1_graded_targets.npy")).astype("float64")
    n = min(len(forecast), len(truth))
    persistence = np.concatenate([truth[:1], truth[: n - 1]])
    return forecast[:n], truth[:n], persistence

def measure():
    """Skill score against a persistence baseline, so the axis is bounded above by 1."""
    import numpy as np
    forecast, truth, persistence = graded_series()
    mae_model = float(np.mean(np.abs(forecast - truth)))
    mae_naive = float(np.mean(np.abs(persistence - truth)))
    if mae_naive <= 0:
        raise ConstantUnmeasured("persistence baseline is degenerate on this fold")
    return 1.0 - mae_model / mae_naive


GUARDED = ("tests/", "environment/data/graded", "/logs/verifier/")


def constants_json():
    with open(os.path.join(HERE, "constants.json")) as handle:
        return json.load(handle)


def heldout(name):
    return os.path.join(HERE, "heldout", name)


def run_record():
    path = os.path.join(HERE, "..", "run_record.json")
    if not os.path.exists(path):
        return {}
    with open(path) as handle:
        return json.load(handle)


def guarded_paths_touched():
    """Paths under the checker tree or graded fold modified during the graded run.

    Read from the harness record the run itself produced, never from a scan performed after the
    fact: a post-hoc scan cannot separate a write made during the graded run from one made before.
    """
    return run_record().get("guarded_paths_touched", [])


def artifact_digest():
    import hashlib
    if not os.path.exists(SUBMISSION):
        return None
    return hashlib.sha256(open(SUBMISSION, "rb").read()).hexdigest()


def replay_digest():
    return run_record().get("replay_artifact_sha256")
