"""Derivation for AELLO-C8-S6: every canonical artifact descends from solution/grounding.yaml.

WHAT THIS GENERATOR EMITS AND WHY IT LOOKS LIKE THIS. The checks below are written about ONE
graded object: a scored box list per image, graded by the correct-localisation rate at a single
hard IoU of 0.5, learned from a fixed small fraction of training images that carry a box. That
metric is a per-image binary decided by the single highest-scoring box, so the emitted checker
walks per-image box lists, resolves each list's top box, tests it against that image's own native
pixel frame, and refuses a list whose top score is tied -- because a tie hands the graded binary
to serialisation order. None of that means anything on a segmenter, a classifier, a forecaster or
a retrieval chain: they have no top-1 box, no per-image cliff at 0.5, and no supervision fraction
to confine a run to.

The paths, the pixel-frame convention, the trimap tokens and the IoU threshold the emitted checks
read live in grounding.yaml's corpus_layout block and are substituted into the emitted prelude, so
the derivation source really is the source and this generator holds no corpus fact of its own.

Every compiled item carries a hand-written body. There is no generic fallback: an item without a
body is a REFUSAL, because the fallback this generator used to carry looked up an obligation
record that nothing writes, and a check that consults nothing passes for the wrong reason.
"""
import json
import os

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
# generator_common.py is NOT reached for. A staged tree could resolve seed/stage/<slug>/../../build;
# a DELIVERED tree at dataset/<uuid>/ cannot, and reaching outside would make the delivered bundle
# non-self-contained -- it would import in the stage and fail everywhere it actually ships.

SLOT_ID = 'AELLO-C8-S6'
TITLE = "# AELLO-C8-S6 -- what this task actually tests"
ITEM_KEYS = ('id', 'dimension', 'weight', 'evaluation_target', 'criterion', 'judgment', 'knockout',
             'mode')
ITEM_SCHEMA = frozenset(ITEM_KEYS + ('outcome_class',))
OUTCOME_CLASSES = frozenset(("EFFECT", "INVARIANT", "ABSENCE", "VALUE"))
RAMP = ("floor", "knee", "dichotomizing_threshold", "reward_gate_pass_threshold")
REQUIRE_FIRST = 'c = require_measured("floor", "knee", "dichotomizing_threshold")'
LAYOUT_KEYS = ("graded_image_index", "labelled_box_index", "training_image_index", "graded_boxes",
               "withheld_trimap_dir", "run_record", "iou_threshold", "box_order", "trimap_tokens",
               "guarded_writes")


def read_identity(here):
    """Identity is an INPUT: the freeze computes it over the hashed tree and binds it into the
    carrier, which is hash-excluded, so reading it back keeps generation acyclic."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        if isinstance(doc.get("identity"), dict):
            return doc["identity"]
    return {"canonical_content_hash": None, "uuid": None,
            "normalization_domain": "aello.canary.norm/v1",
            "derivation": "uuid5(FORGE_TASK_NAMESPACE, canonical_content_hash)"}


def read_screening(here):
    """The screening instant and result are MEASURED OVER the frozen tree, so they are read back
    the way identity is; the carrier is hash-excluded, so binding them moves nothing."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        got = {k: doc[k] for k in ("screening_measured_at", "screening_expires_at",
                                   "screening_result") if k in doc}
        if got:
            return got
    return {"screening_measured_at": None, "screening_expires_at": None,
            "screening_result": None}


def load_grounding():
    with open(os.path.join(HERE, "grounding.yaml")) as fh:
        return yaml.safe_load(fh)


# ==========================================================================================
# The emitted checker. PRELUDE carries the corpus layout and the metric's constants and IS
# substituted; BODIES go in verbatim under their own decorator; TAIL is the box arithmetic and
# is NOT substituted, because it carries percent formatting of its own.
# ==========================================================================================

PRELUDE = '''"""Compiled checks for %(slot_id)s. GENERATED by solution/recompute.py. DO NOT HAND-EDIT.

One graded object: a scored box list per graded image, at /submission/detections.json. One graded
quantity: the share of the private split whose TOP-SCORING box reaches IoU %(iou)r against that
image's single ground-truth box. Every check below runs against delivered bytes -- the submitted
box lists, the shipped image and box indexes, and the record the graded run wrote -- and
references no unmeasured quantity, except %(outcome_id)s, which raises ConstantUnmeasured while
tests/constants.json carries nulls.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
SUBMISSION = %(path)r

# The corpus layout, from solution/grounding.yaml. The graded IMAGES are agent-visible because the
# agent has to predict on them; the graded BOXES are not, and red line 1 is what keeps the
# distinction. The trimap directory is named so that its ABSENCE can be checked.
GRADED_IMAGE_INDEX = os.path.join(BUNDLE, %(graded_image_index)r)
LABELLED_BOX_INDEX = os.path.join(BUNDLE, %(labelled_box_index)r)
TRAINING_IMAGE_INDEX = os.path.join(BUNDLE, %(training_image_index)r)
GRADED_BOXES = os.path.join(BUNDLE, %(graded_boxes)r)
WITHHELD_TRIMAP_DIR = os.path.join(BUNDLE, %(withheld_trimap_dir)r)
RUN_RECORD = os.path.join(BUNDLE, %(run_record)r)

# Constants of the METRIC, not measurements of this slot. IOU_THRESHOLD is where
# correct-localisation is defined; floor, knee and the dichotomizing threshold stay null.
IOU_THRESHOLD = %(iou)r
BOX_ORDER = %(box_order)r
TRIMAP_TOKENS = %(trimap_tokens)r
GUARDED_WRITES = %(guarded_writes)r

CHECKS = []


class ConstantUnmeasured(Exception):
    """Raised when a check needs a ramp constant that Phase 0 deliberately left null."""


def check(id, weight, knockout, kind):
    def deco(fn):
        CHECKS.append({"id": id, "weight": weight, "knockout": knockout, "kind": kind, "fn": fn})
        return fn
    return deco


def constants():
    with open(os.path.join(HERE, "constants.json")) as fh:
        return json.load(fh)


def require_measured(*names):
    c = constants()
    missing = [n for n in names if c.get(n) is None]
    if missing:
        raise ConstantUnmeasured(
            "%(slot_id)s: " + ", ".join(missing) + " are null. Phase 0 authors no measurement; "
            "the Phase 2 measurement wave writes these and this check becomes gradeable then.")
    return c


def evidence(**kw):
    return {"evaluation_target": kw.pop("target", "submitted_artifact"), "values": kw}
'''


TAIL = '''

# ------------------------------------------------------------------------------------------
# Reading the delivered bytes. Three shipped indexes, one private box index and one record,
# each read the same way every check reads it: absent is reported, never guessed at.
# ------------------------------------------------------------------------------------------

def load_submission():
    """The scored box lists: one per graded image id, under the `detections` member."""
    with open(SUBMISSION) as handle:
        doc = json.load(handle)
    if not isinstance(doc, dict):
        raise ValueError("the deliverable must be a JSON object, not a %s" % type(doc).__name__)
    table = doc.get("detections")
    if not isinstance(table, dict):
        raise ValueError("the deliverable carries no `detections` object keyed by image id")
    if not table:
        raise ValueError("`detections` names no graded image")
    return dict((str(image), entry) for image, entry in table.items())


def describe(table):
    return ",".join("%s:%d" % (image, len(table[image]) if isinstance(table[image], list) else -1)
                    for image in sorted(table)[:4])


def json_index(path):
    """One shipped index as an image-keyed mapping; empty when it will not read.

    Empty covers two cases and the checks distinguish them by what else is available: the index
    has not landed in this tree, or it landed and no longer parses. The second is a write into a
    guarded path happening in front of the verifier, so it must produce a report rather than an
    unhandled traceback -- an index that will not open is a finding, not a crash.
    """
    if not os.path.exists(path):
        return {}
    try:
        with open(path) as handle:
            doc = json.load(handle)
    except Exception:
        return {}
    return dict((str(k), v) for k, v in doc.items()) if isinstance(doc, dict) else {}


def graded_image_sizes():
    """graded image id -> (width, height): the native frame that image's boxes are scored in."""
    sizes = {}
    for image, meta in json_index(GRADED_IMAGE_INDEX).items():
        if not isinstance(meta, dict):
            continue
        try:
            width, height = int(meta["width"]), int(meta["height"])
        except Exception:
            continue
        if width > 0 and height > 0:
            sizes[image] = (width, height)
    return sizes


def graded_image_ids():
    """The graded split. The private box index names it; the shipped image index stands in.

    Verifier-side both are mounted and they agree. In a staged tree neither may have landed, and
    every check that needs the split says so rather than passing over an empty one.
    """
    for source in (GRADED_BOXES, GRADED_IMAGE_INDEX):
        table = json_index(source)
        if table:
            return sorted(table)
    return []


def labelled_image_ids():
    """The fixed small fraction: the only training images whose ground-truth box ships."""
    return sorted(json_index(LABELLED_BOX_INDEX))


def training_image_ids():
    """Every training image, labelled or not. Its size is the fraction's denominator."""
    return sorted(json_index(TRAINING_IMAGE_INDEX))


def as_number(value):
    """A finite number, or None. Booleans are not numbers here: True is a declaration, not 1."""
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return None
    number = float(value)
    if number != number or number in (float("inf"), float("-inf")):
        return None
    return number


def parsed_boxes(entry):
    """Every (coords, score) in one image's list. Raises on anything that is not a box list."""
    if not isinstance(entry, list):
        raise ValueError("the entry is a %s, not a list of scored boxes" % type(entry).__name__)
    parsed = []
    for record in entry:
        if not isinstance(record, dict):
            raise ValueError("a record is a %s, not an object with a box and a score"
                             % type(record).__name__)
        box, score = record.get("box"), record.get("score")
        if not isinstance(box, list) or len(box) != 4:
            raise ValueError("a record's box is not four coordinates in the order %s"
                             % ",".join(BOX_ORDER))
        coords = [as_number(value) for value in box]
        if None in coords:
            raise ValueError("a box coordinate is not a finite number: %r" % (box,))
        number = as_number(score)
        if number is None:
            raise ValueError("a box carries score %r, which is not a finite number" % (score,))
        parsed.append((coords, number))
    return parsed


def top_box(entry):
    """The one box correct-localisation reads, with the reason there is none.

    Returns (coords, reason). A tie at the top is NOT resolved here by taking the first: the
    graded binary would then be a property of the writer's iteration order rather than of the
    model, which is exactly what top_scoring_box_is_unambiguous refuses.
    """
    boxes = parsed_boxes(entry)
    if not boxes:
        return None, "empty_box_list"
    best = max(score for _, score in boxes)
    winners = [coords for coords, score in boxes if score == best]
    if len(winners) != 1:
        return None, "tied_top_score"
    return winners[0], None


def intersection_over_union(a, b):
    """Half-open pixel rectangles: width is x2 - x1, so a zero-width box has no area."""
    overlap_x = max(0.0, min(a[2], b[2]) - max(a[0], b[0]))
    overlap_y = max(0.0, min(a[3], b[3]) - max(a[1], b[1]))
    intersection = overlap_x * overlap_y
    area_a = max(0.0, a[2] - a[0]) * max(0.0, a[3] - a[1])
    area_b = max(0.0, b[2] - b[0]) * max(0.0, b[3] - b[1])
    union = area_a + area_b - intersection
    return 0.0 if union <= 0.0 else intersection / union


def decisive_digest():
    """sha256 over the decision, not over the file.

    One line per submitted image in sorted id order: the top box's four coordinates floored to
    their integer pixel, or `none` where the list is empty or its top score is tied. Reordering
    the inert boxes below the top one changes no localisation and must not read as divergence;
    a top box that moves one pixel can cross IoU %s and flip a graded image, so it must.
    """ % IOU_THRESHOLD
    import hashlib
    import math
    table = load_submission()
    digest = hashlib.sha256()
    for image in sorted(table):
        try:
            coords, _ = top_box(table[image])
        except Exception:
            coords = None
        if coords is None:
            digest.update(("%s|none\\n" % image).encode("utf-8"))
        else:
            digest.update(("%s|%d,%d,%d,%d\\n"
                           % (image, math.floor(coords[0]), math.floor(coords[1]),
                              math.floor(coords[2]), math.floor(coords[3]))).encode("utf-8"))
    return digest.hexdigest()


def measure():
    """The correct-localisation rate at IoU %s over the PRIVATE SPLIT.

    The denominator is the size of the graded split and never the number of images the submission
    chose to answer, so an omitted image is a miss and answering fewer images can only lower the
    rate. The comparison is inclusive: a box at exactly the threshold counts.
    """ % IOU_THRESHOLD
    truth = json_index(GRADED_BOXES)
    if not truth:
        raise ConstantUnmeasured("the private box index has not landed; the rate has no "
                                 "denominator and reporting 0.0 would assert the agent missed "
                                 "every image")
    try:
        table = load_submission()
    except Exception:
        table = {}
    localised = 0
    for image in sorted(truth):
        entry = table.get(image)
        if entry is None:
            continue
        try:
            coords, _ = top_box(entry)
        except Exception:
            continue
        if coords is None:
            continue
        reference = [as_number(value) for value in truth[image]] \\
            if isinstance(truth[image], list) and len(truth[image]) == 4 else [None]
        if None in reference:
            continue
        if intersection_over_union(coords, reference) >= IOU_THRESHOLD:
            localised += 1
    return localised / float(len(truth))


def run_record():
    """What the graded run declared about itself.

    The agent writes this file, so it can be absent, truncated, or not JSON at all. Every one of
    those is an empty record here: an unparseable declaration declares nothing, and each check
    then reports its own missing-declaration reason instead of taking the verifier down with a
    decode error and returning no report about anything.
    """
    if not os.path.exists(RUN_RECORD):
        return {}
    try:
        with open(RUN_RECORD) as handle:
            doc = json.load(handle)
    except Exception:
        return {}
    return doc if isinstance(doc, dict) else {}


def declared_ids(key):
    """One declared image-id set from the record, or None when it was never declared."""
    value = run_record().get(key)
    if isinstance(value, dict):
        value = list(value)
    if not isinstance(value, list):
        return None
    return set(str(item) for item in value)


def declared_paths(key):
    """One declared path list from the record, or None when it was never declared."""
    value = run_record().get(key)
    if not isinstance(value, list):
        return None
    return [str(item) for item in value]


def in_guarded_tree(path):
    """True when a declared write lands on the checker tree or on a shipped index."""
    text = str(path).replace("\\\\", "/")
    return any(marker in text for marker in GUARDED_WRITES)


def names_a_trimap(path):
    """True when a declared read names the per-pixel supervision this slot withholds."""
    text = str(path).replace("\\\\", "/").lower()
    return any(token in text for token in TRIMAP_TOKENS)


def tree_holds_trimaps():
    """True when the withheld trimap directory exists in the delivered tree after all."""
    return os.path.exists(WITHHELD_TRIMAP_DIR)
'''


BODIES = {

    "detections_manifest_lands": '''
    if not os.path.exists(SUBMISSION):
        return False, evidence(reason="submission_missing", path=SUBMISSION)
    try:
        table = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    malformed = []
    for image in sorted(table):
        try:
            parsed_boxes(table[image])
        except Exception as exc:
            malformed.append("%s: %s" % (image, exc))
    return (not malformed), evidence(path=SUBMISSION, images=len(table), shape=describe(table),
                                     malformed_lists=malformed[:6],
                                     reason=None if not malformed
                                     else "box_record_is_not_a_box_and_a_score")''',

    "no_abstention_every_graded_image_localised": '''
    try:
        table = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    graded = graded_image_ids()
    if not graded:
        return False, evidence(reason="graded_image_index_unavailable", path=GRADED_IMAGE_INDEX)
    unanswered, empty = [], []
    for image in graded:
        entry = table.get(image)
        if entry is None:
            unanswered.append(image)
        elif isinstance(entry, list) and not entry:
            empty.append(image)
    reason = ("graded_image_carries_no_entry" if unanswered else
              "graded_image_carries_an_empty_box_list" if empty else None)
    return (reason is None), evidence(graded_images=len(graded), answered=len(table),
                                      unanswered=unanswered[:6], empty_lists=empty[:6],
                                      reason=reason)''',

    "boxes_in_native_pixel_frame": '''
    try:
        table = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    sizes = graded_image_sizes()
    if not sizes:
        return False, evidence(reason="graded_image_index_unavailable", path=GRADED_IMAGE_INDEX)
    no_area, outside, widest = [], [], 0.0
    for image in sorted(sizes):
        entry = table.get(image)
        if entry is None:
            continue
        try:
            boxes = parsed_boxes(entry)
        except Exception:
            continue
        width, height = sizes[image]
        for coords, _ in boxes:
            widest = max(widest, coords[2], coords[3])
            if not (coords[2] > coords[0] and coords[3] > coords[1]):
                no_area.append("%s:%s" % (image, coords))
            elif (coords[0] < 0 or coords[1] < 0 or coords[2] > width or coords[3] > height):
                outside.append("%s:%s>%dx%d" % (image, coords, width, height))
    normalised = 0.0 < widest <= 1.0
    reason = ("every_coordinate_at_most_one_so_the_boxes_are_normalised" if normalised else
              "box_has_no_positive_area" if no_area else
              "box_leaves_its_own_image" if outside else None)
    return (reason is None), evidence(images_with_a_published_frame=len(sizes),
                                      widest_coordinate=widest, boxes_without_area=no_area[:6],
                                      boxes_outside_their_image=outside[:6], reason=reason)''',

    "top_scoring_box_is_unambiguous": '''
    try:
        table = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    tied, unusable = [], []
    for image in sorted(table):
        try:
            boxes = parsed_boxes(table[image])
        except Exception as exc:
            unusable.append("%s: %s" % (image, exc))
            continue
        if not boxes:
            continue
        scores = [score for _, score in boxes]
        best = max(scores)
        if scores.count(best) != 1:
            tied.append("%s: %d boxes at %r" % (image, scores.count(best), best))
    reason = ("box_score_is_not_a_finite_number" if unusable else
              "two_boxes_share_the_top_score" if tied else None)
    return (reason is None), evidence(images=len(table), tied_at_the_top=tied[:6],
                                      unusable_scores=unusable[:6], reason=reason)''',

    "box_supervision_confined_to_the_labelled_fraction": '''
    labelled = set(labelled_image_ids())
    if not labelled:
        return False, evidence(target="run_record", reason="labelled_box_index_unavailable",
                               path=LABELLED_BOX_INDEX)
    declared = declared_ids("box_supervised_image_ids")
    if declared is None:
        return False, evidence(target="run_record", reason="no_box_supervision_declaration")
    beyond = sorted(declared - labelled)
    training = training_image_ids()
    shipped = (len(labelled) / float(len(training))) if training else None
    stated = as_number(run_record().get("labelled_fraction"))
    misdeclared = shipped is not None and (stated is None or abs(stated - shipped) > 1e-6)
    reason = ("box_read_outside_the_labelled_fraction" if beyond else
              "declared_fraction_is_not_the_shipped_fraction" if misdeclared else None)
    return (reason is None), evidence(target="run_record", labelled_images=len(labelled),
                                      declared_images=len(declared),
                                      beyond_the_fraction=beyond[:6], shipped_fraction=shipped,
                                      declared_fraction=stated, reason=reason)''',

    "private_split_boxes_unread": '''
    graded = set(graded_image_ids())
    if not graded:
        return False, evidence(target="run_record", reason="graded_image_index_unavailable",
                               path=GRADED_IMAGE_INDEX)
    declared = declared_ids("box_supervised_image_ids")
    opened = declared_paths("paths_read")
    if declared is None or opened is None:
        return False, evidence(target="run_record",
                               reason="no_box_supervision_declaration" if declared is None
                               else "no_read_declaration")
    from_the_answer_key = sorted(declared & graded)
    private_reads = sorted(path for path in opened
                           if os.path.basename(GRADED_BOXES) in path or "heldout" in path)
    reason = ("trained_on_a_graded_image_box" if from_the_answer_key else
              "opened_the_private_box_index" if private_reads else None)
    return (reason is None), evidence(target="run_record", graded_images=len(graded),
                                      graded_boxes_consumed=from_the_answer_key[:6],
                                      private_reads=private_reads[:6], reason=reason)''',

    "trimaps_withheld_and_unread": '''
    present = tree_holds_trimaps()
    opened = declared_paths("paths_read")
    if opened is None:
        return False, evidence(target="submitted_source", reason="no_read_declaration")
    reads = sorted(path for path in opened if names_a_trimap(path))
    reason = ("withheld_trimap_directory_is_present_in_the_delivered_tree" if present else
              "graded_run_declares_a_trimap_read" if reads else None)
    return (reason is None), evidence(target="submitted_source", trimap_dir=WITHHELD_TRIMAP_DIR,
                                      trimap_dir_present=present, declared_reads=len(opened),
                                      trimap_reads=reads[:6], reason=reason)''',

    "pseudo_boxes_gated_and_disjoint_from_labelled": '''
    accounting = run_record().get("pseudo_box_accounting")
    if not isinstance(accounting, dict):
        return False, evidence(target="run_record", reason="no_pseudo_box_accounting")
    proposed = as_number(accounting.get("proposed"))
    retained = as_number(accounting.get("retained"))
    gate = as_number(accounting.get("confidence_gate"))
    if proposed is None or retained is None or gate is None:
        return False, evidence(target="run_record", reason="pseudo_box_accounting_incomplete",
                               declared_keys=sorted(accounting))
    placed = declared_ids("pseudo_box_image_ids")
    labelled = set(labelled_image_ids())
    already_labelled = sorted(placed & labelled) if placed is not None else []
    reason = ("no_pseudo_box_image_ids_declared" if placed is None else
              "confidence_gate_is_not_a_probability" if not 0.0 < gate < 1.0 else
              "retained_more_pseudo_boxes_than_it_proposed" if retained > proposed else
              "pseudo_box_placed_on_an_image_that_already_carries_one" if already_labelled else
              "gate_admitted_every_proposed_pseudo_box"
              if proposed > 0 and retained == proposed else None)
    return (reason is None), evidence(target="run_record", proposed=proposed, retained=retained,
                                      confidence_gate=gate,
                                      images_receiving_a_pseudo_box=0 if placed is None
                                      else len(placed),
                                      on_already_labelled_images=already_labelled[:6],
                                      reason=reason)''',

    "checker_tree_and_box_indexes_untouched": '''
    written = declared_paths("paths_written")
    if written is None:
        return False, evidence(target="submitted_source", reason="no_write_manifest")
    guarded = sorted(path for path in written if in_guarded_tree(path))
    return (not guarded), evidence(target="submitted_source", paths_written=len(written),
                                   guarded_paths_written=guarded[:6],
                                   reason=None if not guarded else "wrote_into_a_guarded_path")''',

    "top_box_replay_digest": '''
    stated = run_record().get("replay_top_box_sha256")
    if not isinstance(stated, str) or not stated.strip():
        return False, evidence(target="submitted_source", reason="no_replay_digest_declared")
    try:
        observed = decisive_digest()
    except Exception as exc:
        return False, evidence(target="submitted_source", reason="submission_malformed",
                               error=str(exc))
    stated = stated.strip().lower()
    return stated == observed, evidence(target="submitted_source", declared=stated[:16],
                                        observed=observed[:16],
                                        reason=None if stated == observed
                                        else "replay_moved_a_top_box")''',

    "localisation_budget_declared": '''
    declaration = run_record().get("agent_budget_declaration")
    if not isinstance(declaration, dict):
        return False, evidence(target="run_record", reason="no_agent_declaration")
    used = as_number(declaration.get("labelled_images_used"))
    seconds = as_number(declaration.get("graded_run_seconds"))
    optimised_for = as_number(declaration.get("optimised_for_iou"))
    scales = declaration.get("inference_scales")
    numeric = ([as_number(scale) for scale in scales] if isinstance(scales, list) else [])
    usable_scales = (bool(numeric) and None not in numeric and min(numeric) > 0.0
                     and len(set(numeric)) == len(numeric))
    labelled = len(labelled_image_ids())
    reason = ("declaration_incomplete" if None in (used, seconds, optimised_for) else
              "inference_scales_are_not_distinct_positive_numbers" if not usable_scales else
              "optimised_for_an_iou_this_slot_does_not_grade"
              if abs(optimised_for - IOU_THRESHOLD) > 1e-9 else
              "declared_more_labelled_images_than_the_fraction_ships"
              if labelled and used > labelled else None)
    return (reason is None), evidence(target="run_record", labelled_images_used=used,
                                      labelled_images_shipped=labelled, graded_run_seconds=seconds,
                                      inference_scales=numeric, optimised_for_iou=optimised_for,
                                      reason=reason)''',

    "correct_localisation_rate_at_iou_half": '''
    c = require_measured("floor", "knee", "dichotomizing_threshold")
    rate = measure()
    span = c["knee"] - c["floor"]
    s = 0.0 if span <= 0 else max(0.0, min(1.0, (rate - c["floor"]) / span))
    return rate >= c["dichotomizing_threshold"], evidence(correct_localisation_rate=rate,
                                                          iou_threshold=IOU_THRESHOLD,
                                                          s_outcome=s)''',

}


def build_tests(g, prelude, bodies):
    """Assemble the compiled-check module. kind carries the item's own dimension."""
    chunks = [prelude]
    for raw in sorted(g["items"], key=lambda i: i["id"]):
        if raw["mode"] != "compiled":
            continue
        chunks.append('\n\n@check(id="%s", weight=%d, knockout=%s, kind="%s")\ndef test_%s():\n%s\n'
                      % (raw["id"], raw["weight"], raw["knockout"], raw["dimension"], raw["id"],
                         bodies[raw["id"]].strip("\n")))
    return "".join(chunks)


def build_truth(g, title):
    """Render solution/TRUTH.md from the frozen literals of solution/grounding.yaml."""
    n = g["truth_narrative"]
    lines = [title, "", "GENERATED SECTION. DO NOT HAND-EDIT.", "", n["opening"], "",
             "## The single most important insight", "", n["insight"], "",
             "## The ideal solve, step by step", ""]
    for i, step in enumerate(n["steps"], 1):
        lines += ["%d. **%s** %s" % (i, step["heading"], step["paragraph"]), ""]
    lines += ["## Traps that catch agents that are not thinking carefully", ""]
    lines += ["- " + t for t in n["traps"]]
    lines += ["", "---", "", "## Contract record (annex; not part of the narrative body)", "",
              "Retained under FORGE.md item 10e and Phase 2 item 7, which require this file to "
              "carry the ordered path through instruction.md with each satisfied checker "
              "identifier, and each rejected route bound to a measured known-wrong control. "
              "standards/truth-md-authoring-v1.md section 3 admits no fifth section, so this "
              "annex is a recorded deviation rather than an omission.", "", g["truth_annex"], ""]
    return "\n".join(lines) + "\n"


def build_rubrics(g, item_keys):
    """The 9g rubric carrier. The item schema is CLOSED at eight keys, so item 10f's outcome
    classification rides as a greppable prefix of the judgment rather than as a ninth key."""
    items = []
    for raw in g["items"]:
        item = {k: raw[k] for k in item_keys}
        item["judgment"] = "%s: %s" % (raw["outcome_class"], raw["judgment"])
        items.append(item)
    compiled = sum(i["weight"] for i in items if i["mode"] == "compiled")
    total = sum(i["weight"] for i in items)
    return {"$schema": "forge.rubric/v1",
            "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
            "generator": "solution/recompute.py",
            "compilation_floor": g["compilation_floor"],
            "compiled_weight_share": round(compiled / total, 6) if total else 0.0,
            "evaluation_target_vocabulary": sorted(g["evaluation_target_vocabulary"]),
            "items": sorted(items, key=lambda i: i["id"])}


def build_provenance(g, identity):
    p = g["provenance"]
    layout = g["corpus_layout"]
    out = {
        "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
        "generator": "solution/recompute.py from solution/grounding.yaml",
        "schema_version": "1.0",
        "slot_id": g["slot_id"],
        "identity": identity,
        "corpus": p["corpus"],
        "anchors": p["anchors"],
        "shards": p["shards"],
        "narrative": p["narrative"],
        "supersedes": p["supersedes"],
        "upstream_provenance": p["upstream_record"],
        "reward_composition": p["reward_composition"],
        "screening_interval_days": p["screening_interval_days"],
        "screening_detector_version": p["screening_detector_version"],
        "derivation_instant": p["derivation_instant"],
        "screening_roots": p["screening_roots"],
        "empty_submission_result": p["empty_submission_result"],
        "resolved_closure": p["resolved_closure"],
        "applicability": p["applicability"],
        "measurement_tier": g["measurement_tier"],
        "gradeable": g["gradeable"],
        "knee_anchor_status": g["knee_anchor_status"],
        # Grading facts particular to this slot, so the carrier says what was graded and how.
        "box_localisation_grading": True,
        "localisation_iou_threshold": layout["iou_threshold"],
        "supervision_regime": "sparse box supervision: a fixed small fraction of training images "
                              "ships a ground-truth box and no other box supervision exists",
        "dense_supervision_withheld": layout["withheld_trimap_dir"],
        "corpus_landed": layout["landed"],
    }
    out.update(read_screening(HERE))
    return out


def validate(grounding):
    """Refuse on a malformed derivation source rather than emitting from one.

    The family validator that stood here returned an empty list unconditionally, which is a check
    that consults nothing. These are the invariants the emitted checker actually depends on:
    without them a bad grounding produces a checker that imports and grades the wrong thing.
    """
    problems = []
    items = grounding.get("items") or []
    if not items:
        problems.append("no items to compile")
    seen = set()
    for item in items:
        iid = item.get("id", "<unnamed>")
        if iid in seen:
            problems.append("duplicate item id %r" % iid)
        seen.add(iid)
        if set(item) != ITEM_SCHEMA:
            problems.append("item %r does not carry the closed schema: %s"
                            % (iid, sorted(set(item) ^ ITEM_SCHEMA)))
            continue
        if item["outcome_class"] not in OUTCOME_CLASSES:
            problems.append("item %r has outcome_class %r" % (iid, item["outcome_class"]))
        if item["evaluation_target"] not in grounding["evaluation_target_vocabulary"]:
            problems.append("item %r evaluates %r, which the vocabulary does not admit"
                            % (iid, item["evaluation_target"]))
        if not isinstance(item["weight"], int) or item["weight"] <= 0:
            problems.append("item %r carries weight %r" % (iid, item["weight"]))
    outcome = [i["id"] for i in items if i.get("dimension") == "outcome"]
    if len(outcome) != 1:
        problems.append("expected exactly one outcome item, found %r" % outcome)
    for name in RAMP:
        if grounding["constants"].get(name) is not None:
            problems.append("constant %r is authored at Phase 0; it is measured, not authored"
                            % name)
    layout = grounding.get("corpus_layout") or {}
    for key in LAYOUT_KEYS:
        if key not in layout:
            problems.append("corpus_layout does not name %r, which the emitted checker reads"
                            % key)
    # The metric's own threshold is authored; a knee or a floor smuggled in as an IoU is not.
    threshold = layout.get("iou_threshold")
    if not isinstance(threshold, float) or not 0.0 < threshold < 1.0:
        problems.append("iou_threshold %r is not a threshold in (0, 1)" % (threshold,))
    if list(layout.get("box_order") or []) != ["x1", "y1", "x2", "y2"]:
        problems.append("box_order %r is not the published corner order"
                        % (layout.get("box_order"),))
    if not layout.get("trimap_tokens"):
        problems.append("corpus_layout names no trimap token, so the withheld dense supervision "
                        "cannot be recognised in a read declaration")
    if not layout.get("guarded_writes"):
        problems.append("corpus_layout names no guarded write path, so red line 2 is unstatable")
    return problems


def main():
    g = load_grounding()
    # The validator runs FIRST and refuses rather than emitting: a generator that writes a carrier
    # it knows is malformed hands the drift check a moving target.
    problems = validate(g)
    if problems:
        raise SystemExit("AELLO-C8-S6 grounding is not well-formed: " + "; ".join(problems))

    layout = g["corpus_layout"]
    outcome_id = [i["id"] for i in g["items"] if i["dimension"] == "outcome"][0]
    subst = {"slot_id": SLOT_ID, "path": g["deliverable"]["path"], "outcome_id": outcome_id,
             "graded_image_index": layout["graded_image_index"],
             "labelled_box_index": layout["labelled_box_index"],
             "training_image_index": layout["training_image_index"],
             "graded_boxes": layout["graded_boxes"],
             "withheld_trimap_dir": layout["withheld_trimap_dir"],
             "run_record": layout["run_record"],
             "iou": float(layout["iou_threshold"]),
             "box_order": tuple(layout["box_order"]),
             "trimap_tokens": tuple(layout["trimap_tokens"]),
             "guarded_writes": tuple(layout["guarded_writes"])}

    # EVERY compiled item carries a written body. The generic obligation lookup that used to stand
    # here is gone: it consulted a run-record key nothing writes, so an item that fell through to
    # it graded nothing at all and said so in no report.
    bodies = dict(BODIES)
    for it in g["items"]:
        if it["mode"] == "compiled" and it["id"] not in bodies:
            raise SystemExit("AELLO-C8-S6: no body written for compiled item %r; the generator "
                             "refuses rather than emitting a check that consults nothing"
                             % it["id"])
    # The outcome check must SAY the slot is unmeasurable before it reads anything. Reading the
    # submission first lets a missing-file failure mask the unmeasured signal, and the verifier
    # then reports gradeable=true with r_det=0.0 -- which seed/build/freeze_batch.py refuses.
    statements = [ln.strip() for ln in bodies[outcome_id].splitlines()
                  if ln.strip() and not ln.strip().startswith("#")]
    if not statements or statements[0] != REQUIRE_FIRST:
        raise SystemExit("AELLO-C8-S6: %r must call require_measured as its first statement, "
                         "before it reads the submission" % outcome_id)

    tests_dir = os.path.join(BUNDLE, "tests")
    os.makedirs(tests_dir, exist_ok=True)

    # solution/TRUTH.md and solution/rubrics.json are PRIVATE_CARRIERS: seed/identity.py plants a
    # canary block into them at freeze, and canary normalisation is what keeps planting from
    # moving identity. A generator that rewrote them plainly would DROP the planted tripwire, and
    # the next content_hash would differ from the frozen one. So the planted block is carried
    # across the regeneration rather than recreated.
    truth_path = os.path.join(HERE, "TRUTH.md")
    truth = build_truth(g, TITLE).rstrip("\n") + "\n"
    keep = None
    if os.path.exists(truth_path):
        import re as _re
        m = _re.search(r"<!-- AELLO-CANARY-BLOCK.*?-->\n?", open(truth_path).read(), _re.S)
        keep = m.group(0) if m else None
    with open(truth_path, "w") as fh:
        fh.write(truth + ("\n" + keep if keep else ""))

    rub_path = os.path.join(HERE, "rubrics.json")
    rub = build_rubrics(g, ITEM_KEYS)
    if os.path.exists(rub_path):
        try:
            prev = json.load(open(rub_path))
            if "canary" in prev:
                rub["canary"] = prev["canary"]
        except Exception:
            pass
    with open(rub_path, "w") as fh:
        json.dump(rub, fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "rubrics.json"), "w") as fh:
        json.dump(build_rubrics(g, ITEM_KEYS), fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "test_output.py"), "w") as fh:
        # The tail arrives FINAL and is NOT substituted: it is written against the emitted
        # prelude's names, it has already resolved every placeholder it owns, and it legitimately
        # carries percent formatting of its own, so formatting it a second time raises TypeError.
        # Only the prelude is substituted.
        fh.write(build_tests(g, PRELUDE % subst, bodies) + TAIL)
    with open(os.path.join(tests_dir, "constants.json"), "w") as fh:
        json.dump(g["constants"], fh, indent=1, sort_keys=True)
        fh.write("\n")
    # ORDER MATTERS. `with open(path, "w")` truncates BEFORE its body's arguments are evaluated,
    # so calling read_identity() inside the with-statement reads the file this line just emptied
    # and writes nulls over the frozen identity. Read first, then open.
    prov = build_provenance(g, read_identity(HERE))
    with open(os.path.join(HERE, "provenance.yaml"), "w") as fh:
        # MATCH seed/build/screen_bind.py and the frozen generators exactly: sort_keys=True,
        # default_flow_style=False, width=100. The screen writes this carrier after the freeze, so
        # a generator using a different dump convention reorders the keys on the next
        # regeneration and reports as drift even though no value changed.
        yaml.safe_dump(prov, fh, sort_keys=True, default_flow_style=False, width=100,
                       allow_unicode=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
