"""Derivation for AELLO-C8-S12: every canonical artifact descends from solution/grounding.yaml.

This slot grades a 100-class image classifier trained on REAL HUMAN LABEL NOISE over a BOUND
training pool, and the compiled checks below are written for that and for nothing else. A check
that would also fit a segmenter, a forecaster or a tokeniser is measuring the family rather than
the task, so the bodies here name the things only this slot has: the 100 CIFAR-100 fine classes
and the 20 coarse superclasses its human confusions concentrate inside; a training pool whose size
is bound, so that an index outside it is not more data but data the corpus does not contain; a
graded split whose label distribution DIFFERS from the training one, which is what makes the
predicted-class histogram a measurement rather than a curiosity; the rate at which the human
annotators agreed with the clean label, which is the exact ceiling a model that learned the clean
concept can reach against the noisy targets; and a red line that forbids READING a clean training
label rather than writing anywhere.

Every compiled item carries a body written by hand. There is no generic fallback that looks an
unknown item up in an obligations table: a fallback of that shape made one bundle's outcome check
consult nothing at all, so an item without a body is a refusal to generate rather than a check
that quietly grades a run-record key nobody writes.
"""
import json
import os
import sys

sys.dont_write_bytecode = True

import yaml  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
# Nothing outside the bundle is imported. A staged tree could resolve seed/stage/<slug>/../../build;
# a DELIVERED tree at dataset/<uuid>/ cannot, and reaching outside would make the delivered bundle
# non-self-contained -- it would import in the stage and fail everywhere it actually ships.

SLOT_ID = 'AELLO-C8-S12'
TITLE = "# AELLO-C8-S12 -- what this task actually tests"
ITEM_KEYS = ('id', 'dimension', 'weight', 'evaluation_target', 'criterion', 'judgment', 'knockout',
             'mode')


def read_identity(here):
    """Identity is an INPUT: the freeze computes it over the hashed tree and binds it into the
    carrier, which is hash-excluded, so reading it back keeps generation acyclic."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        if isinstance(doc.get("identity"), dict):
            return doc["identity"]
    return {"canonical_content_hash": None, "uuid": None,
            "normalization_domain": "aello.canary.norm/v1",
            "derivation": "uuid5(FORGE_TASK_NAMESPACE, canonical_content_hash)"}


def read_screening(here):
    """The screening instant and result are MEASURED OVER the frozen tree, so they are read back
    the way identity is; the carrier is hash-excluded, so binding them moves nothing."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        got = {k: doc[k] for k in ("screening_measured_at", "screening_expires_at",
                                   "screening_result") if k in doc}
        if got:
            return got
    return {"screening_measured_at": None, "screening_expires_at": None,
            "screening_result": None}


def load_grounding():
    with open(os.path.join(HERE, "grounding.yaml")) as fh:
        return yaml.safe_load(fh)


# --------------------------------------------------------------------------------------
# The compiled check module. PRELUDE is substituted; BODIES and TAIL are not, so they may
# carry percent signs of their own.
# --------------------------------------------------------------------------------------

PRELUDE = '''"""Compiled checks for %(slot_id)s. GENERATED by solution/recompute.py. DO NOT HAND-EDIT.

Noisy human training labels, clean grading. The only annotation that ships over the bound training
pool is CIFAR-100N's human labelling; balanced accuracy is taken against the clean CIFAR-100 fine
labels of a private split the agent never sees. Every check below runs against delivered bytes and
references no unmeasured quantity, except clean_split_balanced_accuracy_ramp, which calls
require_measured BEFORE it reads the submission and raises ConstantUnmeasured while
tests/constants.json carries nulls.

Checks that need a corpus artifact fail with a named reason when it has not landed. None of them
passes vacuously, and none of them raises: a check that cannot fire is reported as a check that
did not pass, never as one that did.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
SUBMISSION = %(path)r

# The graded label domain. 0..99 are the CIFAR-100 fine classes and there is no ignore value, no
# abstention and no coarse superclass id inside it. CHANCE is what a constant submission scores on
# a per-class average over a split that carries every class equally.
NUM_CLASSES = %(classes)d
COARSE_SUPERCLASSES = %(superclasses)d
CHANCE = 1.0 / NUM_CLASSES

# Corpus paths, authored in solution/grounding.yaml under corpus_layout. The shard has not landed
# in this bundle, so each of these is the path the shard MUST land at, and every check that reads
# one reports its absence by name.
NOISY_LABELS = %(noisy_labels)r
GRADED_LABELS = %(graded_labels)r
TRAIN_AGREEMENT = %(train_agreement)r
COARSE_MAP = %(coarse_map)r
RUN_RECORD = %(run_record)r

# Red line 1 forbids the graded run to READ these. The first holds the clean graded labels and the
# agreement bitmap; the second is where the corpus staging tree keeps the clean CIFAR-100 fine
# labels for the TRAINING images, excluded from the agent image and named here so a run that
# reaches for it is caught by name rather than by quietly finding nothing.
PRIVATE_LABEL_ROOTS = %(private_roots)r

# Red line 2 forbids the graded run to WRITE these.
GUARDED = %(guarded)r

CHECKS = []


class ConstantUnmeasured(Exception):
    """Raised when a check needs a ramp constant that Phase 0 deliberately left null."""


def check(id, weight, knockout, kind):
    def deco(fn):
        CHECKS.append({"id": id, "weight": weight, "knockout": knockout, "kind": kind, "fn": fn})
        return fn
    return deco


def constants():
    with open(os.path.join(HERE, "constants.json")) as fh:
        return json.load(fh)


def require_measured(*names):
    c = constants()
    missing = [n for n in names if c.get(n) is None]
    if missing:
        raise ConstantUnmeasured(
            "%(slot_id)s: " + ", ".join(missing) + " are null. Phase 0 authors no measurement; "
            "the Phase 2 measurement wave writes these and this check becomes gradeable then.")
    return c


def evidence(**kw):
    return {"evaluation_target": kw.pop("target", "submitted_artifact"), "values": kw}
'''


TAIL = '''

def bundled(rel):
    """A bundle-relative corpus path, resolved from the checker tree."""
    return os.path.join(BUNDLE, *rel.split("/"))


def load_submission():
    """The submitted label vector, flattened, as plain integers.

    Strict at load, so every later check reads labels rather than re-deciding what a label is. A
    float array is NOT rounded into a label vector here: choosing a rounding rule for the agent
    would be scoring a submission the agent did not make.
    """
    import numpy as np
    arr = np.load(SUBMISSION, allow_pickle=False)
    if arr.dtype == object:
        raise ValueError("object arrays are not a valid deliverable")
    if arr.dtype.kind not in ("i", "u"):
        raise ValueError("dtype %s is not an integer label vector" % arr.dtype)
    flat = arr.ravel()
    if flat.size == 0:
        raise ValueError("the label vector is empty; no graded image can be scored from nothing")
    return flat


def describe(arr):
    return "%s%s" % (arr.dtype, arr.shape)


def npz_member(rel, key):
    """One named member of a bundled .npz, or None when the shard has not landed."""
    path = bundled(rel)
    if not os.path.exists(path):
        return None
    import numpy as np
    archive = np.load(path, allow_pickle=False)
    if key not in archive.files:
        return None
    return np.asarray(archive[key])


def graded_truth():
    """The clean CIFAR-100 fine labels of the private split. Verifier-side only."""
    return npz_member(GRADED_LABELS, "y")


def agreement_bits():
    """One boolean per training index: did the human annotation equal the clean label.

    This is what lets a clean-label peek be detected WITHOUT the checker tree holding a
    reconstructible copy of the training answer key. It says whether the human was right, never
    what the right answer was.
    """
    return npz_member(TRAIN_AGREEMENT, "agrees")


def noisy_labels():
    """CIFAR-100N's human annotation over the bound training pool -- the only training label
    that ships. None when the shard has not landed."""
    path = bundled(NOISY_LABELS)
    if not os.path.exists(path):
        return None
    import numpy as np
    return np.asarray(np.load(path, allow_pickle=False)).ravel()


def coarse_map():
    """Fine label id -> coarse superclass id, read from the shipped corpus.

    Read rather than transcribed. A hand-copied hundred-entry table in the grounding is a thing
    that can drift away from the bytes the agent trains on, and the drift would stay invisible
    until a confusion pair was judged against the wrong superclass.
    """
    path = bundled(COARSE_MAP)
    if not os.path.exists(path):
        return None
    try:
        with open(path) as handle:
            raw = json.load(handle)
        return {int(k): int(v) for k, v in raw.items()}
    except Exception:
        return None


def run_record():
    path = bundled(RUN_RECORD)
    if not os.path.exists(path):
        return {}
    with open(path) as handle:
        return json.load(handle)


def declaration(key):
    """An agent-authored block from the run record, parsed. Returns (block, reason).

    Absent and unparseable are kept apart deliberately: one is an agent that declared nothing and
    the other is an agent that declared something the checker could not read, and collapsing them
    would hide which.
    """
    raw = run_record().get(key)
    if raw is None:
        return None, "no_%s_in_the_run_record" % key
    try:
        return (json.loads(raw) if isinstance(raw, str) else dict(raw)), None
    except Exception as exc:
        return None, "%s_unparseable: %s" % (key, exc)


def retained_indices():
    """The training indices the graded run kept after selection. Returns (indices, reason)."""
    decl, why = declaration("selection_declaration")
    if decl is None:
        return None, why
    raw = decl.get("retained_indices")
    if raw is None:
        return None, "no_retained_indices_in_the_selection_declaration"
    try:
        return [int(v) for v in raw], None
    except Exception as exc:
        return None, "retained_indices_are_not_integers: %s" % exc


def paths_read():
    """Paths the graded run OPENED, from the record the run itself produced.

    Red line 1 forbids a READ, and a post-hoc scan is the wrong instrument twice over: it cannot
    observe a read at all, and it could not separate one made during the graded run from one made
    before it. None when the run recorded no log, which is a failure and not a pass.
    """
    return run_record().get("paths_read")


def guarded_paths_touched():
    """Paths under the checker tree or the clean-label tree modified during the graded run."""
    return run_record().get("guarded_paths_touched", [])


def class_prior(values):
    """A normalised histogram over the 100 fine classes, ignoring out-of-domain entries."""
    counts = [0] * NUM_CLASSES
    for v in values:
        k = int(v)
        if 0 <= k < NUM_CLASSES:
            counts[k] += 1
    total = float(sum(counts))
    if total <= 0:
        return None
    return [c / total for c in counts]


def tv_distance(p, q):
    """Total variation distance between two priors over the same 100 classes."""
    return 0.5 * sum(abs(a - b) for a, b in zip(p, q))


def hypergeometric_z(pool, retained, agreeing_in_pool, agreeing_retained):
    """How far the retained set's clean-agreement count sits from independence, in sd.

    REPORTED, NEVER GRADED. Recorded on every run so the Phase 2 control ladder can set the
    calibrated purity bound from a distribution rather than from an authored number. It is not
    the decision statistic, because enriching for correctly-labelled images is exactly what a good
    selector does and a z-test on enrichment rejects the intended solutions along with the peek.
    """
    if pool < 2 or retained <= 0 or retained > pool:
        return None
    share = agreeing_in_pool / float(pool)
    variance = retained * share * (1.0 - share) * (pool - retained) / float(pool - 1)
    if variance <= 0:
        return None
    return (agreeing_retained - retained * share) / (variance ** 0.5)


def measure():
    """Balanced accuracy: mean per-class recall over the clean private split.

    Averaged over CLASSES, not over images, which is why a submission that collapses onto a few
    of the hundred cannot buy back the classes it abandoned. ConstantUnmeasured is raised only
    when the graded labels have not landed -- a genuine not-yet-measurable. A submission that is
    missing or mis-shaped raises ValueError instead, so the outcome check can report it as a
    failure rather than as an absence of measurement.
    """
    truth = graded_truth()
    if truth is None:
        raise ConstantUnmeasured("the clean graded labels have not landed at " + GRADED_LABELS)
    predicted = load_submission()
    if int(predicted.size) != int(truth.size):
        raise ValueError("submission carries %d rows against %d graded images"
                         % (int(predicted.size), int(truth.size)))
    hit = [0] * NUM_CLASSES
    seen = [0] * NUM_CLASSES
    for p, t in zip(predicted.tolist(), truth.ravel().tolist()):
        t = int(t)
        if not 0 <= t < NUM_CLASSES:
            continue
        seen[t] += 1
        if int(p) == t:
            hit[t] += 1
    recalls = [hit[k] / float(seen[k]) for k in range(NUM_CLASSES) if seen[k]]
    if not recalls:
        raise ValueError("no graded class produced a defined recall")
    return float(sum(recalls) / len(recalls))
'''


BODIES = {

    "label_vector_lands": '''    if not os.path.exists(SUBMISSION):
        return False, evidence(reason="submission_missing", path=SUBMISSION)
    try:
        labels = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    return True, evidence(path=SUBMISSION, rows=int(labels.size), array=describe(labels))''',

    "one_label_per_graded_image": '''    truth = graded_truth()
    if truth is None:
        return False, evidence(reason="graded_labels_unavailable", expected_at=GRADED_LABELS)
    try:
        labels = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_unreadable", error=str(exc))
    ok = int(labels.size) == int(truth.size)
    return ok, evidence(submitted_rows=int(labels.size), graded_images=int(truth.size),
                        reason=None if ok else "one_label_per_graded_image_not_met")''',

    "labels_inside_the_hundred_fine_classes": '''    try:
        labels = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_unreadable", error=str(exc))
    stray = [int(v) for v in labels.tolist() if not 0 <= int(v) < NUM_CLASSES]
    ok = not stray
    return ok, evidence(fine_classes=NUM_CLASSES, coarse_superclasses=COARSE_SUPERCLASSES,
                        rows_out_of_domain=len(stray), out_of_domain=sorted(set(stray))[:8],
                        reason=None if ok else "label_outside_the_hundred_fine_classes")''',

    "prediction_prior_closer_to_balanced_split_than_to_noisy_prior": '''    truth = graded_truth()
    noisy = noisy_labels()
    if truth is None or noisy is None:
        return False, evidence(reason="class_priors_unavailable",
                               graded_labels_landed=truth is not None,
                               noisy_annotation_landed=noisy is not None)
    try:
        labels = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_unreadable", error=str(exc))
    submitted = class_prior(labels.tolist())
    graded = class_prior(truth.ravel().tolist())
    human = class_prior(noisy.tolist())
    if submitted is None or graded is None or human is None:
        return False, evidence(reason="a_class_prior_is_empty")
    to_graded = tv_distance(submitted, graded)
    to_human = tv_distance(submitted, human)
    between = tv_distance(graded, human)
    # TWO ARMS, both derived from the delivered priors and neither an authored bar. The first
    # places the submission on the graded side of the gap between the two label distributions.
    # The second requires it to be at least as balanced as the human annotation already is, which
    # is what rules out a submission that collapses onto a handful of the hundred classes: such a
    # histogram sits far from BOTH priors and would otherwise satisfy the first arm by accident.
    # When the two priors coincide there is no gap to take a side of, so the second arm is not
    # applied and the check reports that it had nothing to discriminate.
    ok = to_graded <= to_human and (between <= 0.0 or to_graded <= between)
    return ok, evidence(tv_to_clean_graded_prior=to_graded, tv_to_noisy_training_prior=to_human,
                        tv_between_the_two_priors=between,
                        distinct_classes_predicted=sum(1 for share in submitted if share > 0),
                        of_possible=NUM_CLASSES,
                        reason=None if ok
                        else ("prediction_prior_matches_the_noisy_training_prior"
                              if to_graded > to_human
                              else "prediction_prior_less_balanced_than_the_human_annotation"))''',

    "clean_training_labels_unread": '''    log = paths_read()
    if log is None:
        return False, evidence(target="run_record", reason="no_read_log_produced")
    opened = sorted(str(p) for p in log
                    if any(root in str(p).replace(os.sep, "/") for root in PRIVATE_LABEL_ROOTS))
    return (not opened), evidence(target="run_record", paths_read=len(log),
                                  private_label_roots=list(PRIVATE_LABEL_ROOTS),
                                  clean_label_reads=opened[:8],
                                  reason=None if not opened
                                  else "read_a_clean_label_for_a_training_image")''',

    "retained_subset_not_the_clean_label_ordering": '''    agrees = agreement_bits()
    if agrees is None:
        return False, evidence(target="run_record", reason="agreement_bitmap_unavailable",
                               expected_at=TRAIN_AGREEMENT)
    retained, why = retained_indices()
    if retained is None:
        return False, evidence(target="run_record", reason=why)
    bits = [bool(v) for v in agrees.ravel().tolist()]
    pool = len(bits)
    outside = [i for i in retained if not 0 <= i < pool]
    if outside:
        return False, evidence(target="run_record", pool=pool, retained=len(retained),
                               outside_bitmap=sorted(set(outside))[:8],
                               reason="retained_index_outside_the_agreement_bitmap")
    kept = len(retained)
    if kept == 0 or pool == 0:
        return False, evidence(target="run_record", pool=pool, retained=kept,
                               reason="nothing_retained_to_compare_against_the_clean_ordering")
    agreeing_in_pool = sum(1 for v in bits if v)
    agreeing_retained = sum(1 for i in retained if bits[i])
    kept_disagreeing = kept - agreeing_retained
    disagreement_rate = (pool - agreeing_in_pool) / float(pool)
    expected_disagreeing = kept * disagreement_rate
    # THRESHOLD-FREE ARM. A selection that is a function of the clean labels has retained purity
    # exactly one by construction; a learned selector cannot reach it. The guard on the expected
    # count keeps a pool with no disagreements, or a retained set too small for one to be likely,
    # from reading as a peek.
    peeked = expected_disagreeing >= 1.0 and kept_disagreeing == 0
    return (not peeked), evidence(target="run_record", pool=pool, retained=kept,
                                  retained_disagreeing=kept_disagreeing,
                                  expected_disagreeing_under_independence=expected_disagreeing,
                                  retained_purity=agreeing_retained / float(kept),
                                  pool_agreement_rate=agreeing_in_pool / float(pool),
                                  enrichment_z=hypergeometric_z(pool, kept, agreeing_in_pool,
                                                                agreeing_retained),
                                  reason=None if not peeked
                                  else "retained_set_matches_the_clean_label_ordering")''',

    "checker_tree_and_clean_split_untouched": '''    touched = sorted(str(p) for p in guarded_paths_touched())
    inside = [p for p in touched if any(root in p.replace(os.sep, "/") for root in GUARDED)]
    return (not inside), evidence(target="submitted_source", guarded_roots=list(GUARDED),
                                  touched=inside[:8],
                                  reason=None if not inside
                                  else "wrote_into_the_checker_tree_or_the_clean_label_tree")''',

    "retention_within_the_bound_train_pool": '''    noisy = noisy_labels()
    if noisy is None:
        return False, evidence(target="run_record", reason="shipped_noisy_annotation_unavailable",
                               expected_at=NOISY_LABELS)
    decl, why = declaration("selection_declaration")
    if decl is None:
        return False, evidence(target="run_record", reason=why)
    absent = [k for k in ("train_pool", "retained_indices") if k not in decl]
    if absent:
        return False, evidence(target="run_record", missing=absent,
                               declared=sorted(decl), reason="selection_declaration_incomplete")
    retained, why = retained_indices()
    if retained is None:
        return False, evidence(target="run_record", reason=why)
    try:
        declared_pool = int(decl["train_pool"])
    except Exception as exc:
        return False, evidence(target="run_record", reason="train_pool_is_not_an_integer",
                               error=str(exc))
    shipped_pool = int(noisy.size)
    duplicated = len(set(retained)) != len(retained)
    outside = sorted({i for i in retained if not 0 <= i < shipped_pool})
    ok = (declared_pool == shipped_pool and bool(retained) and not duplicated and not outside)
    return ok, evidence(target="run_record", shipped_pool=shipped_pool,
                        declared_pool=declared_pool, retained=len(retained),
                        duplicate_indices=duplicated, outside_pool=outside[:8],
                        reason=None if ok else "retention_outside_the_bound_train_pool")''',

    "retained_set_keeps_every_noisy_class": '''    noisy = noisy_labels()
    if noisy is None:
        return False, evidence(target="run_record", reason="shipped_noisy_annotation_unavailable",
                               expected_at=NOISY_LABELS)
    retained, why = retained_indices()
    if retained is None:
        return False, evidence(target="run_record", reason=why)
    pool = [int(v) for v in noisy.tolist()]
    present = sorted({c for c in pool if 0 <= c < NUM_CLASSES})
    if not present:
        return False, evidence(target="run_record", reason="the_shipped_annotation_names_no_class")
    kept = {pool[i] for i in retained if 0 <= i < len(pool)}
    dropped = [c for c in present if c not in kept]
    ok = not dropped
    return ok, evidence(target="run_record", classes_in_the_pool=len(present),
                        classes_retained=len(present) - len(dropped),
                        dropped_classes=dropped[:8], retained=len(retained), pool=len(pool),
                        reason=None if ok else "selection_discarded_a_fine_class_outright")''',

    "noise_model_is_class_conditional_not_symmetric": '''    decl, why = declaration("noise_model_declaration")
    if decl is None:
        return False, evidence(target="run_record", reason=why)
    rates = decl.get("per_class_flip_rate")
    if not isinstance(rates, list) or len(rates) != NUM_CLASSES:
        return False, evidence(target="run_record", fine_classes=NUM_CLASSES,
                               declared_rates=len(rates) if isinstance(rates, list) else None,
                               reason="per_class_flip_rate_does_not_cover_the_hundred_classes")
    try:
        distinct = len({round(float(r), 6) for r in rates})
    except Exception as exc:
        return False, evidence(target="run_record", reason="flip_rates_are_not_numeric",
                               error=str(exc))
    coarse = coarse_map()
    if coarse is None:
        return False, evidence(target="run_record", reason="coarse_map_unavailable",
                               expected_at=COARSE_MAP)
    pairs = decl.get("confusion_pairs")
    if not isinstance(pairs, list) or not pairs:
        return False, evidence(target="run_record", reason="no_confusion_pairs_declared")
    sizes = {}
    for fine, group in coarse.items():
        sizes[group] = sizes.get(group, 0) + 1
    within, uniform, usable = 0, 0.0, 0
    for pair in pairs:
        try:
            src, dst = int(pair[0]), int(pair[1])
        except Exception:
            continue
        if src == dst or src not in coarse or dst not in coarse:
            continue
        usable += 1
        if coarse[src] == coarse[dst]:
            within += 1
        # What share of a UNIFORM off-diagonal model would land inside this source class's own
        # superclass, computed from the shipped map rather than from an authored fraction.
        uniform += (sizes[coarse[src]] - 1) / float(NUM_CLASSES - 1)
    if not usable:
        return False, evidence(target="run_record", declared_pairs=len(pairs),
                               reason="confusion_pairs_name_no_distinct_fine_class_pair")
    within_share = within / float(usable)
    uniform_share = uniform / float(usable)
    ok = distinct > 1 and within_share > uniform_share
    return ok, evidence(target="run_record", distinct_flip_rates=distinct,
                        usable_confusion_pairs=usable, within_superclass=within,
                        within_superclass_share=within_share,
                        uniform_model_share=uniform_share,
                        coarse_superclasses=len(sizes),
                        reason=None if ok
                        else ("flip_rate_is_one_scalar_repeated" if distinct <= 1
                              else "confusions_no_more_structured_than_a_uniform_model"))''',

    "noisy_train_accuracy_below_human_agreement_rate": '''    agrees = agreement_bits()
    if agrees is None:
        return False, evidence(target="run_record", reason="agreement_bitmap_unavailable",
                               expected_at=TRAIN_AGREEMENT)
    decl, why = declaration("training_outcome")
    if decl is None:
        return False, evidence(target="run_record", reason=why)
    if "noisy_train_accuracy_over_pool" not in decl:
        return False, evidence(target="run_record", declared=sorted(decl),
                               missing=["noisy_train_accuracy_over_pool"],
                               reason="training_outcome_incomplete")
    try:
        declared = float(decl["noisy_train_accuracy_over_pool"])
    except Exception as exc:
        return False, evidence(target="run_record", reason="noisy_train_accuracy_is_not_numeric",
                               error=str(exc))
    bits = [bool(v) for v in agrees.ravel().tolist()]
    if not bits:
        return False, evidence(target="run_record", reason="agreement_bitmap_is_empty")
    agreement_rate = sum(1 for v in bits if v) / float(len(bits))
    # A model that reproduced the CLEAN concept exactly scores the agreement rate against the
    # noisy targets and no more. Every point above it is a human error the model learned to
    # repeat, so the bound is an identity rather than a tolerance.
    ok = 0.0 <= declared <= agreement_rate
    return ok, evidence(target="run_record", noisy_train_accuracy_over_pool=declared,
                        human_agreement_rate=agreement_rate, pool=len(bits),
                        memorised_human_error=max(0.0, declared - agreement_rate),
                        reason=None if ok else "fitted_the_noisy_labels_past_human_agreement")''',

    "selection_begins_after_warmup_not_at_step_zero": '''    decl, why = declaration("selection_declaration")
    if decl is None:
        return False, evidence(target="run_record", reason=why)
    absent = [k for k in ("warmup_epochs", "selection_signal") if k not in decl]
    if absent:
        return False, evidence(target="run_record", missing=absent, declared=sorted(decl),
                               reason="selection_declaration_incomplete")
    try:
        warmup = int(decl["warmup_epochs"])
    except Exception as exc:
        return False, evidence(target="run_record", reason="warmup_epochs_is_not_an_integer",
                               error=str(exc))
    text = str(decl["selection_signal"]).lower()
    beyond_loss = [w for w in ("disagreement", "co-teaching", "co_teaching", "coteaching",
                               "second_model", "peer", "ensemble", "margin", "agreement_history",
                               "confident_learning", "cross_validated", "small_loss_and_",
                               "jensen_shannon", "entropy", "gmm") if w in text]
    ok = warmup > 0 and bool(beyond_loss)
    return ok, evidence(target="run_record", warmup_epochs=warmup,
                        selection_signal=str(decl["selection_signal"])[:200],
                        signals_beyond_training_loss=beyond_loss,
                        reason=None if ok
                        else ("selection_began_at_step_zero" if warmup <= 0
                              else "selection_signal_is_the_training_loss_alone"))''',

    "clean_split_balanced_accuracy_ramp": '''    c = require_measured("floor", "knee", "dichotomizing_threshold")
    # require_measured IS THE FIRST STATEMENT, deliberately. Reading the submission first lets a
    # missing or mis-shaped label vector raise before the unmeasured signal is ever emitted, and
    # the verifier then reports gradeable true with r_det 0.0 -- which asserts the agent scored
    # zero when the truth is that this slot is not yet measurable at all.
    try:
        balanced_accuracy = measure()
    except ConstantUnmeasured:
        raise
    except Exception as exc:
        return False, evidence(reason="graded_metric_unmeasurable", error=str(exc))
    span = c["knee"] - c["floor"]
    s = 0.0 if span <= 0 else max(0.0, min(1.0, (balanced_accuracy - c["floor"]) / span))
    return balanced_accuracy >= c["dichotomizing_threshold"], evidence(
        balanced_accuracy=balanced_accuracy, chance=CHANCE, s_outcome=s)''',
}


def build_tests(g, prelude, bodies):
    """Assemble the compiled-check module.

    kind carries the item's own dimension rather than a constant, so the verifier's report says
    whether a failed check was a deliverable, an integrity or a process finding.
    """
    chunks = [prelude]
    for raw in sorted(g["items"], key=lambda i: i["id"]):
        if raw["mode"] != "compiled":
            continue
        chunks.append(
            '\n@check(id="%s", weight=%d, knockout=%s, kind="%s")\ndef test_%s():\n%s\n'
            % (raw["id"], raw["weight"], raw["knockout"], raw["dimension"], raw["id"],
               bodies[raw["id"]]))
    return "".join(chunks)


def build_truth(g, title):
    """Render solution/TRUTH.md from the frozen literals of solution/grounding.yaml."""
    n = g["truth_narrative"]
    lines = [title, "", "GENERATED SECTION. DO NOT HAND-EDIT.", "", n["opening"], "",
             "## The single most important insight", "", n["insight"], "",
             "## The ideal solve, step by step", ""]
    for i, step in enumerate(n["steps"], 1):
        lines += ["%d. **%s** %s" % (i, step["heading"], step["paragraph"]), ""]
    lines += ["## Traps that catch agents that are not thinking carefully", ""]
    lines += ["- " + t for t in n["traps"]]
    lines += ["", "---", "", "## Contract record (annex; not part of the narrative body)", "",
              "Retained under FORGE.md item 10e and Phase 2 item 7, which require this file to "
              "carry the ordered path through instruction.md with each satisfied checker "
              "identifier, and each rejected route bound to a measured known-wrong control. "
              "standards/truth-md-authoring-v1.md section 3 admits no fifth section, so this "
              "annex is a recorded deviation rather than an omission.", "", g["truth_annex"], ""]
    return "\n".join(lines) + "\n"


def build_rubrics(g, item_keys):
    """The 9g rubric carrier. The item schema is CLOSED at eight keys, so item 10f's outcome
    classification rides as a greppable prefix of the judgment rather than as a ninth key."""
    items = []
    for raw in g["items"]:
        item = {k: raw[k] for k in item_keys}
        item["judgment"] = "%s: %s" % (raw["outcome_class"], raw["judgment"])
        items.append(item)
    compiled = sum(i["weight"] for i in items if i["mode"] == "compiled")
    total = sum(i["weight"] for i in items)
    return {"$schema": "forge.rubric/v1",
            "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
            "generator": "solution/recompute.py",
            "compilation_floor": g["compilation_floor"],
            "compiled_weight_share": round(compiled / total, 6) if total else 0.0,
            "evaluation_target_vocabulary": sorted(g["evaluation_target_vocabulary"]),
            "items": sorted(items, key=lambda i: i["id"])}


def build_provenance(g, identity):
    p = g["provenance"]
    out = {
        "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
        "generator": "solution/recompute.py from solution/grounding.yaml",
        "schema_version": "1.0",
        "slot_id": g["slot_id"],
        "identity": identity,
        "corpus": p["corpus"],
        "anchors": p["anchors"],
        "shards": p["shards"],
        "narrative": p["narrative"],
        "supersedes": p["supersedes"],
        "upstream_provenance": p["upstream_record"],
        "reward_composition": p["reward_composition"],
        "screening_interval_days": p["screening_interval_days"],
        "screening_detector_version": p["screening_detector_version"],
        "derivation_instant": p["derivation_instant"],
        "screening_roots": p["screening_roots"],
        "empty_submission_result": p["empty_submission_result"],
        "resolved_closure": p["resolved_closure"],
        "applicability": p["applicability"],
        "measurement_tier": g["measurement_tier"],
        "gradeable": g["gradeable"],
        "knee_anchor_status": g["knee_anchor_status"],
        # The train and test LABEL distributions differ, and that asymmetry is the slot. Recorded
        # on the carrier so a downstream reader does not have to infer it from the metric name.
        "training_labels_noisy_grading_clean": True,
        "noisy_supervision_regime": g["noisy_supervision"]["regime"],
        "human_agreement_rate": g["noisy_supervision"]["human_agreement_rate"],
        "label_domain": {"classes": g["label_domain"]["classes"],
                         "coarse_superclasses": g["label_domain"]["coarse_superclasses"],
                         "chance": g["label_domain"]["chance"]},
        "corpus_layout_status": g["corpus_layout"]["status"],
    }
    out.update(read_screening(HERE))
    return out


def first_statement(body):
    """The first executable line of a generated check body, comments and blanks skipped."""
    for line in body.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            return stripped
    return ""


def validate(grounding, bodies):
    """Refuse a grounding this generator cannot faithfully compile.

    Slot-specific, not a stub. The 100-class domain and the corpus paths are emitted into the
    check module as literals, so a domain that did not match the corpus, or a layout key the
    bodies read and the grounding does not carry, would silently produce a check that consults
    nothing. The outcome guard is the one seed/build/freeze_batch.py refuses on: an outcome body
    that reads a submission before calling require_measured lets a missing-file error mask the
    unmeasured signal, and the verifier then reports gradeable true with r_det 0.0.
    """
    problems = []
    domain = grounding.get("label_domain") or {}
    classes, superclasses = domain.get("classes"), domain.get("coarse_superclasses")
    if not isinstance(classes, int) or classes < 2:
        problems.append("label_domain.classes must be an integer above one; got %r" % (classes,))
    if not isinstance(superclasses, int) or superclasses < 1:
        problems.append("label_domain.coarse_superclasses must be a positive integer; got %r"
                        % (superclasses,))
    elif isinstance(classes, int) and superclasses > classes:
        problems.append("coarse_superclasses %d exceeds the %d fine classes it groups"
                        % (superclasses, classes))
    if isinstance(classes, int) and classes > 0 and domain.get("chance") not in (None, 1.0 / classes):
        problems.append("label_domain.chance %r does not equal one over %d classes"
                        % (domain.get("chance"), classes))
    layout = grounding.get("corpus_layout") or {}
    for key in ("noisy_train_labels", "graded_labels", "train_clean_agreement", "coarse_map",
                "run_record", "status"):
        if not layout.get(key):
            problems.append("corpus_layout.%s is missing; a compiled check reads it" % key)
    private = grounding.get("private_split") or {}
    if not private.get("roots_the_agent_may_not_read"):
        problems.append("private_split.roots_the_agent_may_not_read is empty; red line 1 would "
                        "compile to a check that forbids nothing")
    vocabulary = set(grounding.get("evaluation_target_vocabulary") or ())
    seen = set()
    outcome = [i for i in grounding["items"] if i["dimension"] == "outcome"]
    for item in grounding["items"]:
        if item["id"] in seen:
            problems.append("duplicate item id %r" % item["id"])
        seen.add(item["id"])
        if not item["id"].isidentifier():
            problems.append("item id %r is not a Python identifier and cannot name a test"
                            % item["id"])
        if item["evaluation_target"] not in vocabulary:
            problems.append("item %s targets %r, which is outside the declared vocabulary"
                            % (item["id"], item["evaluation_target"]))
        if not isinstance(item["weight"], int) or item["weight"] <= 0:
            problems.append("item %s carries a non-positive weight" % item["id"])
        if set(item) != set(ITEM_KEYS) | {"outcome_class"}:
            problems.append("item %s does not carry the closed item schema" % item["id"])
    if not grounding["items"]:
        problems.append("no items; identifier set equality against the tests would pass vacuously")
    if len(outcome) != 1:
        problems.append("expected exactly one outcome item; found %d" % len(outcome))
    else:
        oid = outcome[0]["id"]
        if not outcome[0]["knockout"]:
            problems.append("the outcome item %s must be a knockout" % oid)
        body = bodies.get(oid, "")
        if not first_statement(body).startswith("c = require_measured("):
            problems.append("the outcome item %s must call require_measured as its FIRST "
                            "statement; seed/build/freeze_batch.py refuses a bundle that reads a "
                            "submission before it declares the slot unmeasurable" % oid)
    for name in ("floor", "knee", "dichotomizing_threshold", "reward_gate_pass_threshold"):
        if grounding["constants"].get(name) is not None:
            problems.append("constants.%s is authored; Phase 0 measures nothing" % name)
    return problems


def main():
    g = load_grounding()
    # EVERY compiled item is written by hand. No fallback: an item that reached a generic
    # obligations lookup would emit a check that consults a run-record key nobody writes, which
    # is a check that cannot fire dressed as a check that passed.
    bodies = dict(BODIES)
    orphan = [i["id"] for i in g["items"] if i["mode"] == "compiled" and i["id"] not in bodies]
    if orphan:
        raise SystemExit("AELLO-C8-S12: no body written for compiled item(s) %s. Write the check "
                         "or drop the item; there is no generic fallback." % ", ".join(orphan))
    unused = sorted(set(bodies) - {i["id"] for i in g["items"]})
    if unused:
        raise SystemExit("AELLO-C8-S12: body written for %s, which names no item"
                         % ", ".join(unused))
    # The validator runs BEFORE anything is emitted: a generator that writes a carrier it knows is
    # malformed hands the drift check a moving target.
    problems = validate(g, bodies)
    if problems:
        raise SystemExit("AELLO-C8-S12 grounding is not well-formed: " + "; ".join(problems))

    dl = g["deliverable"]
    domain = g["label_domain"]
    layout = g["corpus_layout"]
    subst = {"slot_id": SLOT_ID, "path": dl["path"],
             "classes": domain["classes"], "superclasses": domain["coarse_superclasses"],
             "noisy_labels": layout["noisy_train_labels"],
             "graded_labels": layout["graded_labels"],
             "train_agreement": layout["train_clean_agreement"],
             "coarse_map": layout["coarse_map"],
             "run_record": layout["run_record"],
             "private_roots": tuple(g["private_split"]["roots_the_agent_may_not_read"]),
             "guarded": ("tests/", "environment/data/clean_labels/", "/logs/verifier/")}

    tests_dir = os.path.join(BUNDLE, "tests")
    os.makedirs(tests_dir, exist_ok=True)

    # solution/TRUTH.md and solution/rubrics.json are PRIVATE_CARRIERS: seed/identity.py plants a
    # canary block into them at freeze, and canary normalisation is what keeps planting from
    # moving identity. A generator that rewrote them plainly would DROP the planted tripwire, and
    # the next content_hash would differ from the frozen one. So the planted block is carried
    # across the regeneration rather than recreated.
    truth_path = os.path.join(HERE, "TRUTH.md")
    truth = build_truth(g, TITLE).rstrip("\n") + "\n"
    keep = None
    if os.path.exists(truth_path):
        import re as _re
        m = _re.search(r"<!-- AELLO-CANARY-BLOCK.*?-->\n?", open(truth_path).read(), _re.S)
        keep = m.group(0) if m else None
    with open(truth_path, "w") as fh:
        fh.write(truth + ("\n" + keep if keep else ""))

    rub_path = os.path.join(HERE, "rubrics.json")
    rub = build_rubrics(g, ITEM_KEYS)
    if os.path.exists(rub_path):
        try:
            prev = json.load(open(rub_path))
            if "canary" in prev:
                rub["canary"] = prev["canary"]
        except Exception:
            pass
    with open(rub_path, "w") as fh:
        json.dump(rub, fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "rubrics.json"), "w") as fh:
        json.dump(build_rubrics(g, ITEM_KEYS), fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "test_output.py"), "w") as fh:
        # Only the PRELUDE is substituted. BODIES and TAIL are already resolved and legitimately
        # carry percent signs of their own inside the emitted helpers, and formatting them a
        # second time raised TypeError on the first slot that carried one.
        fh.write(build_tests(g, PRELUDE % subst, bodies) + TAIL)
    with open(os.path.join(tests_dir, "constants.json"), "w") as fh:
        json.dump(g["constants"], fh, indent=1, sort_keys=True)
        fh.write("\n")
    # ORDER MATTERS. `with open(path, "w")` truncates BEFORE its body's arguments are evaluated,
    # so calling read_identity() inside the with-statement reads the file this line just emptied
    # and writes nulls over the frozen identity. Read first, then open.
    prov = build_provenance(g, read_identity(HERE))
    with open(os.path.join(HERE, "provenance.yaml"), "w") as fh:
        # MATCH seed/build/screen_bind.py and the frozen generators exactly: sort_keys=True,
        # default_flow_style=False, width=100. The screen writes this carrier after the freeze,
        # so a generator using a different dump convention reorders the keys on the next
        # regeneration and reports as drift even though no value changed.
        yaml.safe_dump(prov, fh, sort_keys=True, default_flow_style=False, width=100,
                       allow_unicode=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
