"""Compiled checks for AELLO-C8-S11. GENERATED by solution/recompute.py. DO NOT HAND-EDIT.

What is graded here is a MEASUREMENT, not an array. The submitted record says how long a
depthwise-separable block took on each pinned activation trace and how far its output drifted from
the vendored fp32 reference; these checks establish that the measurement was taken in a way that
means anything -- warmup discarded, a repetition floor met, a median rather than a best-of-n, a
clock that waits for the device -- and that the fidelity envelope holds on every graded shape
before any speed is credited. Every check runs against delivered bytes and references no unmeasured
quantity, except envelope_gated_speedup_ramp, which raises ConstantUnmeasured while tests/constants.json carries
nulls.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
SUBMISSION = '/submission/kernel_report.json'

# The corpus layout, from solution/grounding.yaml. The activation traces are agent-visible because
# the kernel has to consume them; the fp32 reference outputs and the reference kernel's own latency
# are not, because a visible answer table is a kernel with no kernel in it.
ACTIVATION_TRACES = os.path.join(BUNDLE, 'environment/data/c8s1_activation_traces.npz')
REFERENCE_OUTPUTS = os.path.join(BUNDLE, 'tests/heldout/c8s1_reference_outputs.npz')
REFERENCE_LATENCY = os.path.join(BUNDLE, 'tests/heldout/reference_kernel_latency.json')
RUN_RECORD = os.path.join(BUNDLE, 'run_record.json')

# The pinned graded set. Three depthwise-separable stages of the C8-S1 reference at CIFAR-100's
# 32x32 input, spatial extent halved and channels doubled at each downsample, batch held constant
# so the working set and not the batch is what changes between them.
GRADED_SHAPES = (
    {'batch': 256, 'channels': 128, 'depthwise_kernel': 3, 'height': 32, 'id': 'dws32_c128', 'pointwise_out': 128, 'stride': 1, 'trace_seed': 20260814, 'width': 32},
    {'batch': 256, 'channels': 256, 'depthwise_kernel': 3, 'height': 16, 'id': 'dws16_c256', 'pointwise_out': 256, 'stride': 1, 'trace_seed': 20260815, 'width': 16},
    {'batch': 256, 'channels': 512, 'depthwise_kernel': 3, 'height': 8, 'id': 'dws8_c512', 'pointwise_out': 512, 'stride': 1, 'trace_seed': 20260816, 'width': 8},
)
PINNED_TRACE_SEEDS = (20260814, 20260815, 20260816)
RECORD_KEYS = ('block_ms', 'warmup_iterations', 'warmup_excluded', 'timed_iterations', 'statistic', 'clock_source', 'fusion_boundary', 'max_abs_error', 'max_rel_error', 'within_envelope', 'trace_seed', 'output_sha256')
BUDGET_KEYS = ('warmup_iterations', 'timed_iterations', 'autotune_trials')

FUSION_BOUNDARIES = ('unfused', 'fused_pointwise_epilogue', 'fully_fused')
UNFUSED_BOUNDARY = 'unfused'
STAGE_SUM_TOLERANCE = 0.05
WARMUP_FLOOR = 25
TIMED_FLOOR = 100
ADMITTED_STATISTICS = ('median', 'p50', 'quantile_0.50')
REJECTED_STATISTICS = ('min', 'minimum', 'best', 'best_of_n', 'fastest')
ADMITTED_CLOCK_SOURCES = ('cuda_event_elapsed_time', 'device_synchronised_perf_counter', 'cupti_kernel_duration')
REJECTED_CLOCK_SOURCES = ('host_perf_counter_no_sync', 'time_time_around_launch', 'python_wall_clock_async')
ENVELOPE = {'max_abs_error': 0.002, 'max_rel_error': 0.005}
GUARDED_WRITES = ('/tests/', 'c8s1_activation_traces.npz', 'c8s1_reference_outputs.npz', 'reference_kernel_latency.json', 'graded_block_shapes.json')

CHECKS = []


class ConstantUnmeasured(Exception):
    """Raised when a check needs a ramp constant that Phase 0 deliberately left null."""


def check(id, weight, knockout, kind):
    def deco(fn):
        CHECKS.append({"id": id, "weight": weight, "knockout": knockout, "kind": kind, "fn": fn})
        return fn
    return deco


def constants():
    with open(os.path.join(HERE, "constants.json")) as fh:
        return json.load(fh)


def require_measured(*names):
    c = constants()
    missing = [n for n in names if c.get(n) is None]
    if missing:
        raise ConstantUnmeasured(
            "AELLO-C8-S11: " + ", ".join(missing) + " are null. Phase 0 authors no measurement; "
            "the Phase 2 measurement wave writes these and this check becomes gradeable then.")
    return c


def evidence(**kw):
    return {"evaluation_target": kw.pop("target", "submitted_artifact"), "values": kw}


@check(id="depthwise_and_pointwise_timed_as_separate_stages", weight=3, knockout=False, kind="deliverable")
def test_depthwise_and_pointwise_timed_as_separate_stages():
    records = shape_records()
    if not records:
        return False, evidence(reason="no_per_shape_records")
    findings = []
    for shape_id in sorted(records):
        record = records[shape_id]
        boundary = token(record.get("fusion_boundary"))
        if boundary not in FUSION_BOUNDARIES:
            findings.append({"shape": shape_id, "declared": boundary,
                             "reason": "unrecognised_fusion_boundary"})
            continue
        if boundary != UNFUSED_BOUNDARY:
            # A fused block has no separable stage time. A record that reports one anyway is
            # reporting an attribution it cannot have measured.
            if record.get("depthwise_ms") is not None or record.get("pointwise_ms") is not None:
                findings.append({"shape": shape_id, "declared": boundary,
                                 "reason": "fused_record_carries_a_stage_split"})
            continue
        depthwise = numeric(record.get("depthwise_ms"))
        pointwise = numeric(record.get("pointwise_ms"))
        block = numeric(record.get("block_ms"))
        if depthwise is None or pointwise is None or block is None or block <= 0:
            findings.append({"shape": shape_id, "reason": "unfused_record_missing_a_stage_time"})
        elif abs(depthwise + pointwise - block) > STAGE_SUM_TOLERANCE * block:
            findings.append({"shape": shape_id, "depthwise_ms": depthwise,
                             "pointwise_ms": pointwise, "block_ms": block,
                             "reason": "stage_times_do_not_sum_to_the_block"})
    return (not findings), evidence(stage_findings=findings,
                                    tolerance_fraction=STAGE_SUM_TOLERANCE,
                                    reason=None if not findings
                                    else "stage_decomposition_unsound")


@check(id="device_synchronised_clock_not_async_launch_return", weight=5, knockout=True, kind="process")
def test_device_synchronised_clock_not_async_launch_return():
    records = shape_records()
    if not records:
        return False, evidence(reason="no_per_shape_records")
    findings = []
    for shape_id in sorted(records):
        source = token(records[shape_id].get("clock_source"))
        if source in REJECTED_CLOCK_SOURCES:
            findings.append({"shape": shape_id, "clock_source": source,
                             "reason": "host_timer_around_an_async_launch"})
        elif source not in ADMITTED_CLOCK_SOURCES:
            findings.append({"shape": shape_id, "clock_source": source,
                             "reason": "unrecognised_clock_source"})
    return (not findings), evidence(clock_findings=findings,
                                    admitted=list(ADMITTED_CLOCK_SOURCES),
                                    reason=None if not findings
                                    else "clock_source_does_not_measure_the_kernel")


@check(id="envelope_gated_speedup_ramp", weight=10, knockout=True, kind="outcome")
def test_envelope_gated_speedup_ramp():
    # require_measured FIRST, before anything is read. Reading the submission before saying the
    # slot is not yet measurable lets a missing-file error mask the unmeasured signal, and the
    # verifier then reports gradeable=true with r_det=0.0 -- which asserts the agent scored zero
    # where the honest claim is that the slot cannot yet be scored at all.
    c = require_measured("floor", "knee", "dichotomizing_threshold")
    speedup = measure()
    span = c["knee"] - c["floor"]
    s = 0.0 if span <= 0 else max(0.0, min(1.0, (speedup - c["floor"]) / span))
    return speedup >= c["dichotomizing_threshold"], evidence(speedup=speedup, s_outcome=s)


@check(id="every_graded_block_shape_measured", weight=5, knockout=True, kind="deliverable")
def test_every_graded_block_shape_measured():
    records = shape_records()
    if not records:
        return False, evidence(reason="no_per_shape_records")
    want, got = set(graded_shape_ids()), set(records)
    missing, unrecognised = sorted(want - got), sorted(got - want)
    incomplete = sorted(shape_id for shape_id in (want & got)
                        if [k for k in RECORD_KEYS if k not in records[shape_id]])
    ok = not (missing or unrecognised or incomplete)
    return ok, evidence(graded_shapes=list(graded_shape_ids()), missing=missing,
                        unrecognised=unrecognised, incomplete=incomplete,
                        reason=None if ok else "graded_shape_set_not_covered")


@check(id="fidelity_envelope_holds_on_every_graded_shape", weight=5, knockout=True, kind="integrity")
def test_fidelity_envelope_holds_on_every_graded_shape():
    records = shape_records()
    if not records:
        return False, evidence(reason="no_per_shape_records")
    findings = []
    for shape_id in graded_shape_ids():
        record = records.get(shape_id)
        if record is None:
            findings.append({"shape": shape_id, "reason": "no_fidelity_record"})
            continue
        ok, reason, errors = envelope_verdict(record)
        if not ok:
            findings.append(dict(errors, shape=shape_id, reason=reason))
        elif record.get("within_envelope") is not True:
            # The errors clear the envelope and the record says they do not. One of the two was
            # not measured, and a self-contradicting fidelity record is not evidence of fidelity.
            findings.append(dict(errors, shape=shape_id,
                                 reason="record_contradicts_its_own_errors"))
    return (not findings), evidence(envelope=ENVELOPE, envelope_findings=findings,
                                    reason=None if not findings
                                    else "outside_fidelity_envelope")


@check(id="latency_report_lands", weight=5, knockout=True, kind="deliverable")
def test_latency_report_lands():
    if not os.path.exists(SUBMISSION):
        return False, evidence(reason="submission_missing", path=SUBMISSION)
    try:
        doc = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    shapes = doc.get("shapes")
    if not isinstance(shapes, dict) or not shapes:
        return False, evidence(reason="no_per_shape_records", shape=describe(doc))
    return True, evidence(path=SUBMISSION, measured_shapes=sorted(str(k) for k in shapes))


@check(id="measurement_budget_declared", weight=3, knockout=False, kind="process")
def test_measurement_budget_declared():
    declaration = run_record().get("agent_budget_declaration")
    if declaration is None:
        return False, evidence(target="run_record", reason="no_agent_declaration")
    try:
        declared = (json.loads(declaration) if isinstance(declaration, str)
                    else dict(declaration))
    except Exception as exc:
        return False, evidence(target="run_record", reason="declaration_unparseable",
                               error=str(exc))
    missing = [k for k in BUDGET_KEYS if k not in declared]
    not_a_count = [k for k in BUDGET_KEYS if k in declared
                   and (numeric(declared[k]) is None or numeric(declared[k]) < 0)]
    ok = not missing and not not_a_count
    return ok, evidence(target="run_record", declared=sorted(str(k) for k in declared),
                        missing=missing, not_a_count=not_a_count,
                        reason=None if ok else "measurement_budget_not_declared")


@check(id="pinned_trace_seeds_are_the_measured_inputs", weight=3, knockout=False, kind="integrity")
def test_pinned_trace_seeds_are_the_measured_inputs():
    declared = run_record().get("trace_seeds")
    if declared is None:
        return False, evidence(target="run_record", reason="no_trace_seeds_declared")
    try:
        seeds = sorted(int(s) for s in declared)
    except (TypeError, ValueError):
        return False, evidence(target="run_record", declared=str(declared)[:160],
                               reason="trace_seeds_unparseable")
    records = shape_records()
    unnamed = [shape["id"] for shape in GRADED_SHAPES
               if numeric((records.get(str(shape["id"])) or {}).get("trace_seed"))
               != float(shape["trace_seed"])]
    pinned = sorted(PINNED_TRACE_SEEDS)
    ok = seeds == pinned and not unnamed
    return ok, evidence(target="run_record", declared_seeds=seeds, pinned_seeds=pinned,
                        shapes_not_on_their_pinned_trace=unnamed,
                        reason=None if ok else "measured_inputs_are_not_the_pinned_traces")


@check(id="replay_reproduces_outputs_but_not_timings", weight=3, knockout=False, kind="process")
def test_replay_reproduces_outputs_but_not_timings():
    replay = run_record().get("replay")
    if not isinstance(replay, dict) or not replay:
        return False, evidence(target="submitted_source", reason="replay_unrecorded")
    records = shape_records()
    if not records:
        return False, evidence(target="submitted_source", reason="no_per_shape_records")
    diverged, identical, absent, unreported, compared = [], [], [], [], 0
    for shape_id in graded_shape_ids():
        first = records.get(shape_id)
        again = replay.get(shape_id)
        if not isinstance(first, dict):
            # Absent from the report is a coverage finding, not a divergence. Reporting it as a
            # digest mismatch would name the wrong defect on a shape that was never measured.
            unreported.append(shape_id)
            continue
        if not isinstance(again, dict):
            absent.append(shape_id)
            continue
        compared += 1
        if first.get("output_sha256") != again.get("output_sha256"):
            diverged.append(shape_id)
        one, two = numeric(first.get("block_ms")), numeric(again.get("block_ms"))
        if one is not None and two is not None and one == two:
            identical.append(shape_id)
    fabricated = compared > 0 and len(identical) == compared
    ok = compared > 0 and not unreported and not absent and not diverged and not fabricated
    return ok, evidence(target="submitted_source", shapes_compared=compared,
                        shapes_absent_from_report=unreported,
                        shapes_absent_from_replay=absent, outputs_diverged=diverged,
                        latencies_bit_identical=identical,
                        reason=None if ok else ("shape_never_measured" if unreported
                                                else "shape_absent_from_replay" if absent
                                                else "kernel_outputs_not_reproducible"
                                                if diverged
                                                else "latencies_identical_across_runs"))


@check(id="reported_latency_is_a_median_not_a_best_of_n", weight=5, knockout=True, kind="process")
def test_reported_latency_is_a_median_not_a_best_of_n():
    records = shape_records()
    if not records:
        return False, evidence(reason="no_per_shape_records")
    findings = []
    for shape_id in sorted(records):
        record = records[shape_id]
        statistic = token(record.get("statistic"))
        repetitions = numeric(record.get("timed_iterations"))
        if statistic in REJECTED_STATISTICS:
            findings.append({"shape": shape_id, "statistic": statistic,
                             "reason": "best_of_n_is_not_a_latency"})
        elif statistic not in ADMITTED_STATISTICS:
            findings.append({"shape": shape_id, "statistic": statistic,
                             "reason": "unrecognised_statistic"})
        elif repetitions is None or repetitions < TIMED_FLOOR:
            findings.append({"shape": shape_id,
                             "timed_iterations": record.get("timed_iterations"),
                             "reason": "repetition_count_below_floor"})
    return (not findings), evidence(statistic_findings=findings,
                                    admitted=list(ADMITTED_STATISTICS),
                                    repetition_floor=TIMED_FLOOR,
                                    reason=None if not findings
                                    else "reported_statistic_is_not_a_median")


@check(id="vendored_traces_and_checker_tree_unwritten", weight=5, knockout=True, kind="integrity")
def test_vendored_traces_and_checker_tree_unwritten():
    record = run_record()
    # The harness's own list is the authority; the run's declaration corroborates it. A post-hoc
    # scan cannot separate a write made during the graded run from one made before it.
    harness = [p for p in record.get("guarded_paths_touched", []) if in_guarded_tree(p)]
    declared = [p for p in record.get("paths_written", []) if in_guarded_tree(p)]
    touched = sorted(set(harness) | set(declared))
    before = record.get("trace_digest_before")
    after = record.get("trace_digest_after")
    if before is None or after is None:
        return False, evidence(target="submitted_source", touched=touched,
                               reason="no_trace_digest_recorded")
    moved = before != after
    ok = (not touched) and not moved
    return ok, evidence(target="submitted_source", touched=touched, trace_digest_moved=moved,
                        reason=None if ok else ("trace_corpus_rewritten" if moved
                                                else "wrote_into_guarded_tree"))


@check(id="warmup_iterations_excluded_from_the_timed_window", weight=5, knockout=True, kind="process")
def test_warmup_iterations_excluded_from_the_timed_window():
    records = shape_records()
    if not records:
        return False, evidence(reason="no_per_shape_records")
    findings = []
    for shape_id in sorted(records):
        record = records[shape_id]
        warmup = numeric(record.get("warmup_iterations"))
        if warmup is None or warmup < WARMUP_FLOOR:
            findings.append({"shape": shape_id, "warmup_iterations": record.get(
                "warmup_iterations"), "reason": "warmup_below_floor"})
        elif record.get("warmup_excluded") is not True:
            findings.append({"shape": shape_id, "reason": "warmup_not_declared_excluded"})
    return (not findings), evidence(warmup_findings=findings, warmup_floor=WARMUP_FLOOR,
                                    reason=None if not findings
                                    else "timed_window_includes_warmup")


# ------------------------------------------------------------------------------------------
# Reading the delivered bytes. One submitted record, one run record, and the two vendored
# references the verifier mounts. Absent is reported, never guessed at, and never passed over.
# ------------------------------------------------------------------------------------------

def load_submission():
    """The kernel's measurement record: one entry per graded block shape under `shapes`."""
    with open(SUBMISSION) as handle:
        doc = json.load(handle)
    if not isinstance(doc, dict):
        raise ValueError("the measurement record must be a JSON object")
    return doc


def describe(obj):
    return "keys=" + ",".join(sorted(str(k) for k in obj)[:6])


def shape_records():
    """shape id -> record, or {} when the report is absent, unparseable or carries no shapes.

    Empty covers three cases and every check that needs a record distinguishes them by its own
    reason string. None of them may take the verifier down with a decode error: a report that
    will not open is a finding about the submission, not a crash in the checker.
    """
    if not os.path.exists(SUBMISSION):
        return {}
    try:
        doc = load_submission()
    except Exception:
        return {}
    shapes = doc.get("shapes")
    if not isinstance(shapes, dict):
        return {}
    return dict((str(k), v) for k, v in shapes.items() if isinstance(v, dict))


def graded_shape_ids():
    """The pinned graded set, in the order grounding.yaml pins it."""
    return tuple(str(s["id"]) for s in GRADED_SHAPES)


def numeric(value):
    """A finite float, or None for anything that is not one -- including bools and NaN.

    A bool is an int in Python and `True` would otherwise read as an iteration count of one.
    """
    if isinstance(value, bool) or value is None:
        return None
    try:
        out = float(value)
    except (TypeError, ValueError):
        return None
    if out != out or out in (float("inf"), float("-inf")):
        return None
    return out


def token(value):
    """A declared vocabulary word, normalised the one way every roster here is written."""
    return str(value).strip().lower().replace("-", "_").replace(" ", "_")


def run_record():
    """What the graded run declared about itself.

    The agent writes this file, so it can be absent, truncated, or not JSON at all. Every one of
    those is an empty record here: an unparseable declaration declares nothing, and each check
    then reports its own missing-declaration reason instead of taking the verifier down.
    """
    if not os.path.exists(RUN_RECORD):
        return {}
    try:
        with open(RUN_RECORD) as handle:
            doc = json.load(handle)
    except Exception:
        return {}
    return doc if isinstance(doc, dict) else {}


def in_guarded_tree(path):
    """True when a written path lands in the checker tree or on a vendored corpus archive."""
    flat = "/" + str(path).replace("\\", "/").lstrip("./").lstrip("/")
    return any(token_ in flat for token_ in GUARDED_WRITES)


def envelope_verdict(record):
    """RECOMPUTED from the two reported errors; the record's own verdict is never taken on trust.

    Returns (ok, reason, errors). A record that reports no error at all fails here rather than
    defaulting to conforming: the envelope is a gate, and an ungated gate is worse than none.
    """
    errors = {"max_abs_error": numeric(record.get("max_abs_error")),
              "max_rel_error": numeric(record.get("max_rel_error"))}
    if errors["max_abs_error"] is None or errors["max_rel_error"] is None:
        return False, "fidelity_error_not_reported", errors
    if errors["max_abs_error"] < 0 or errors["max_rel_error"] < 0:
        return False, "negative_fidelity_error", errors
    if errors["max_abs_error"] > ENVELOPE["max_abs_error"]:
        return False, "max_abs_error_outside_envelope", errors
    if errors["max_rel_error"] > ENVELOPE["max_rel_error"]:
        return False, "max_rel_error_outside_envelope", errors
    return True, None, errors


def harness_latencies():
    """shape id -> the HARNESS's own measured kernel wall-clock in milliseconds.

    Not the report's number. Red line 2 is reporting a timing the harness did not measure, so the
    graded quantity is read from the harness's record and the submitted record is graded against
    it rather than trusted in place of it.
    """
    got = run_record().get("harness_kernel_latency_ms")
    if not isinstance(got, dict):
        return {}
    return dict((str(k), v) for k, v in got.items())


def reference_latencies():
    """shape id -> the vendored reference kernel's measured wall-clock, from tests/heldout/."""
    if not os.path.exists(REFERENCE_LATENCY):
        return {}
    try:
        with open(REFERENCE_LATENCY) as handle:
            doc = json.load(handle)
    except Exception:
        return {}
    doc = doc.get("block_ms", doc) if isinstance(doc, dict) else {}
    if not isinstance(doc, dict):
        return {}
    return dict((str(k), v) for k, v in doc.items())


def measure():
    """Geometric-mean speedup over the vendored reference kernel, zero outside the envelope.

    The geometric mean, not the arithmetic one: these are ratios across shapes whose absolute
    latencies differ by more than an order of magnitude, and an arithmetic mean over ratios lets
    one cheap shape's large ratio carry the score for two expensive shapes it says nothing about.

    The envelope is read BEFORE the ratios are formed. That ordering is the whole gate: a kernel
    outside the envelope on one of three shapes returns 0.0 here rather than a two-thirds score,
    which is what makes a fast wrong kernel worth nothing instead of worth most of it.
    """
    measured = harness_latencies()
    if not measured:
        raise ConstantUnmeasured("the harness recorded no per-shape kernel wall-clock")
    reference = reference_latencies()
    if not reference:
        raise ConstantUnmeasured("the vendored reference kernel's latency has not landed")
    records = shape_records()
    for shape_id in graded_shape_ids():
        ok, _reason, _errors = envelope_verdict(records.get(shape_id) or {})
        if not ok:
            return 0.0
    ratios = []
    for shape_id in graded_shape_ids():
        mine = numeric(measured.get(shape_id))
        theirs = numeric(reference.get(shape_id))
        if mine is None or theirs is None or mine <= 0 or theirs <= 0:
            raise ConstantUnmeasured(
                "shape %s carries no harness-measured latency pair" % shape_id)
        ratios.append(theirs / mine)
    product = 1.0
    for ratio in ratios:
        product *= ratio
    return product ** (1.0 / len(ratios))
