"""Derivation for AELLO-C6-S2: every canonical artifact descends from solution/grounding.yaml.

The graded object of this slot is a COUPLED PAIR. For every solution in a private held-out set the
pipeline emits a per-step label sequence over the three human classes AND a single integer
first-error index, and the two must agree -- the first error is the first step labelled bad, and the
no-error case is the exact sentinel -1. Every check this module emits is a check about that pair or
about the state that makes it honest: the internal agreement of the two outputs, the per-stratum
neutral rate of the middle class, the nine-cell confusion matrix and its live neutral row and
column, the four ways an emitted index can meet a human one, the two subgroups whose floors are hard
zeros, the sibling shard, the harness's own seconds, and the private label store the graded run may
not hold a copy of.

The thirteen judged "obligation" items that used to stand in the items list are gone. Each restated a
checker id from seed/contract.yaml and then fell through to a generic run-record lookup under a key
nothing in the harness writes, so it consulted nothing at all and still reported a clean verdict.
What replaced them are compiled checks that read the submitted bytes, the two private shards under
tests/heldout/ and the harness run record.
"""
import json
import os
import sys

import yaml

sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
# Nothing here reaches outside the bundle. A staged tree could resolve seed/stage/<slug>/../../build;
# a DELIVERED tree at dataset/<uuid>/ cannot, and reaching outside would make the delivered bundle
# non-self-contained -- it would import in the stage and fail everywhere it actually ships.

ITEM_KEYS = ('id', 'dimension', 'weight', 'evaluation_target', 'criterion', 'judgment', 'knockout',
             'mode')
ITEM_SCHEMA = frozenset(ITEM_KEYS + ('outcome_class',))
OUTCOME_CLASSES = frozenset(("EFFECT", "INVARIANT", "ABSENCE", "VALUE", "ORDERING", "DIVERGENCE"))
RAMP = ("floor", "knee", "dichotomizing_threshold", "reward_gate_pass_threshold")
REQUIRE_FIRST = 'c = require_measured("floor", "knee", "dichotomizing_threshold")'
SLOT_ID = 'AELLO-C6-S2'
TITLE = "# AELLO-C6-S2 -- what this task actually tests"


def read_identity(here):
    """Identity is an INPUT: the freeze computes it over the hashed tree and binds it into the
    carrier, which is hash-excluded, so reading it back keeps generation acyclic."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        if isinstance(doc.get("identity"), dict):
            return doc["identity"]
    return {"canonical_content_hash": None, "uuid": None,
            "normalization_domain": "aello.canary.norm/v1",
            "derivation": "uuid5(FORGE_TASK_NAMESPACE, canonical_content_hash)"}


def read_screening(here):
    """The screening instant and result are MEASURED OVER the frozen tree, so they are read back
    the way identity is; the carrier is hash-excluded, so binding them moves nothing."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        got = {k: doc[k] for k in ("screening_measured_at", "screening_expires_at",
                                   "screening_result") if k in doc}
        if got:
            return got
    return {"screening_measured_at": None, "screening_expires_at": None,
            "screening_result": None}


def load_grounding():
    with open(os.path.join(HERE, "grounding.yaml")) as fh:
        return yaml.safe_load(fh)


# ==========================================================================================
# The emitted checker. PRELUDE carries this slot's own vocabulary -- the three step classes, the
# sentinel, the two private shards, the six timed stages and the Phase 0.5 bound constants -- and
# IS substituted from corpus_layout. BODIES go in verbatim under their own decorator. TAIL is the
# reading and counting machinery and is NOT substituted, because it carries percent formatting of
# its own inside the emitted helpers.
# ==========================================================================================

PRELUDE = '''"""Compiled checks for %(slot_id)s. GENERATED by solution/recompute.py. DO NOT HAND-EDIT.

The graded deliverable here is TWO COUPLED OUTPUTS per solution: a per-step label sequence over
%(labels)s and one integer first-error index whose no-error value is the exact sentinel %(sentinel)d.
So the delivered bytes these checks read are the submitted pair itself, the private human label
vectors of the graded shard and of its sibling, the private manifest carrying each solution's step
count under the private re-segmentation, its difficulty stratum and its two subgroup flags, and the
harness run record.

Nothing below imports agent code and nothing below reads a quality number the agent reports. Every
rate is formed from integer counts accumulated in canonical sorted id order, never in the order the
artifact shipped -- the held-out solutions are privately permuted per graded run, and an aggregation
that depended on presentation order would be measuring the permutation.

Every check runs against those bytes and references no unmeasured quantity, except %(outcome_id)s,
which raises ConstantUnmeasured while tests/constants.json carries nulls.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SUBMISSION = %(path)r
CHECKS = []

# --- the three human step classes, and the one value that is not a step class ---------------
LABELS = %(labels)r
GOOD, NEUTRAL, BAD = LABELS
SENTINEL = %(sentinel)d
LABELS_KEY = %(labels_key)r
INDEX_KEY = %(index_key)r
POSITIONAL_KEYS = %(positional_keys)r

# --- the two private shards the verifier holds and the graded run may not read ---------------
GRADED_MANIFEST = %(graded_manifest)r
GRADED_LABELS = %(graded_labels)r
SIBLING_MANIFEST = %(sibling_manifest)r
SIBLING_LABELS = %(sibling_labels)r
STRATA = %(strata)r

# --- what the harness records about the one timed invocation --------------------------------
RUN_RECORD = %(run_record)r
REWARD_LOG = %(reward_log)r
TIMED_STAGES = %(timed_stages)r
GUARDED = %(guarded)r

# --- the Phase 0.5 BOUND constants. None of these is a ramp constant; those four are null. ---
T_F1 = %(t_f1)r
T_LOC = %(t_loc)r
F1_CHANCE = %(f1_chance)r
LOC_CHANCE = %(loc_chance)r
NEUTRAL_BAND = %(neutral_band)r
SIBLING_GAP_CAP = %(sibling_gap_cap)r
LONG_SOLUTION_MIN_STEPS = %(long_min_steps)r
LONG_SOLUTION_MIN_INDEX = %(long_min_index)r
LONG_SOLUTION_FLOOR = %(long_floor)r
CORRECT_ANSWER_FLOOR = %(answer_floor)r
SUB_GATE_CEILING = %(sub_gate_ceiling)r
GATE_VALUE = %(gate_value)r
LOG_RATE_TOLERANCE = %(log_rate_tolerance)r
LOG_ELAPSED_TOLERANCE = %(log_elapsed_tolerance)r


class ConstantUnmeasured(Exception):
    """Raised when a check needs a ramp constant that Phase 0 deliberately left null."""


def check(id, weight, knockout, kind):
    def deco(fn):
        CHECKS.append({"id": id, "weight": weight, "knockout": knockout, "kind": kind, "fn": fn})
        return fn
    return deco


def constants():
    with open(os.path.join(HERE, "constants.json")) as fh:
        return json.load(fh)


def require_measured(*names):
    c = constants()
    missing = [n for n in names if c.get(n) is None]
    if missing:
        raise ConstantUnmeasured(
            "%(slot_id)s: " + ", ".join(missing) + " are null. Phase 0 authors no measurement; "
            "the Phase 2 measurement wave writes these and this check becomes gradeable then.")
    return c


def evidence(**kw):
    return {"evaluation_target": kw.pop("target", "submitted_artifact"), "values": kw}
'''


TAIL = '''

# ------------------------------------------------------------------------------------------
# Reading the delivered bytes. Four sources: the coupled artifact the graded run wrote, the two
# private shards under tests/heldout/, and the harness run record. Absence is REPORTED under its
# own name everywhere -- never guessed at, and never allowed to look like a pass.
# ------------------------------------------------------------------------------------------

def heldout(name):
    """A private table. Lives under tests/heldout/ and the graded run may not read it."""
    return os.path.join(HERE, "heldout", os.path.basename(name))


def read_json(path):
    if not os.path.exists(path):
        return None
    try:
        with open(path) as handle:
            return json.load(handle)
    except Exception:
        return None


def run_record():
    doc = read_json(os.path.normpath(os.path.join(HERE, RUN_RECORD)))
    return doc if isinstance(doc, dict) else {}


def load_submission():
    """The coupled deliverable: one label sequence and one first-error index per solution."""
    with open(SUBMISSION) as handle:
        doc = json.load(handle)
    if not isinstance(doc, dict):
        raise ValueError("the deliverable must be a JSON object, not a %s" % type(doc).__name__)
    ids, outputs = doc.get("ids"), doc.get("outputs")
    if not isinstance(ids, list):
        raise ValueError("the deliverable carries no ids list")
    if not isinstance(outputs, list):
        raise ValueError("the deliverable carries no outputs list")
    if len(ids) != len(outputs):
        raise ValueError("ids carries %d entries and outputs carries %d" % (len(ids), len(outputs)))
    return doc


def submitted_records():
    """(solution id, record) in the order the artifact shipped them.

    That is the run's own presentation order, which is privately permuted per graded run. It is
    read here so one check can prove the graded counts do not depend on it; every other reader
    goes through the canonical sorted order instead.
    """
    try:
        doc = load_submission()
    except Exception:
        return []
    return [(str(i), r) for i, r in zip(doc["ids"], doc["outputs"])]


def label_sequence(record):
    if not isinstance(record, dict):
        return None
    sequence = record.get(LABELS_KEY)
    return sequence if isinstance(sequence, list) else None


def emitted_index(record):
    """The index as an EXACT integer.

    A bool is refused rather than coerced: True == 1 compares equal to step one, so a record
    carrying True would be read as naming the second step as its first error and would be graded
    against a human index it never meant.
    """
    if not isinstance(record, dict):
        return None
    value = record.get(INDEX_KEY)
    if isinstance(value, bool) or not isinstance(value, int):
        return None
    return value


def first_bad_position(sequence):
    """The position of the first bad label in a vector, or the no-error sentinel."""
    for position, label in enumerate(sequence):
        if label == BAD:
            return position
    return SENTINEL


def prefix_divergences(records):
    """Solutions whose emitted index is not the first bad position of their OWN vector.

    No human label is consulted. This is the coupling of the two emitted outputs to each other,
    which is what separates one monotone decode from two heads reconciled afterwards.
    """
    out = []
    for solution_id, record in records:
        sequence = label_sequence(record)
        index = emitted_index(record)
        if sequence is None or index is None:
            out.append({"id": solution_id, "emitted_index": index, "first_bad": None,
                        "why": "output_unreadable"})
            continue
        expected = first_bad_position(sequence)
        if index != expected:
            before = sequence[:index] if index >= 0 else []
            out.append({"id": solution_id, "emitted_index": index, "first_bad": expected,
                        "bad_before_index": sum(1 for label in before if label == BAD),
                        "why": "index_is_not_the_first_bad_label"})
    return out


def shard_rows(manifest_name, labels_name):
    """One row per solution present in the submission AND in that shard, canonical id order.

    Canonical means sorted by solution id. The held-out solutions are privately permuted per
    graded run, so a positional prior sees a different sequence every time while every integer
    count taken here runs over the same order every time.
    """
    manifest = read_json(heldout(manifest_name))
    labels = read_json(heldout(labels_name))
    if not isinstance(manifest, dict) or not isinstance(labels, dict):
        return None
    emitted = dict(submitted_records())
    rows = []
    for solution_id in sorted(set(manifest) & set(labels) & set(emitted)):
        record = emitted[solution_id]
        human = labels[solution_id]
        entry = manifest[solution_id]
        sequence = label_sequence(record)
        if sequence is None or not isinstance(human, dict) or not isinstance(entry, dict):
            continue
        rows.append({"id": solution_id,
                     "emitted": sequence,
                     "emitted_index": emitted_index(record),
                     "human": human.get(LABELS_KEY) or [],
                     "human_index": human.get(INDEX_KEY),
                     "stratum": entry.get("stratum"),
                     "step_count": entry.get("step_count"),
                     "long_solution": bool(entry.get("long_solution")),
                     "correct_answer_bad_step": bool(entry.get("correct_answer_bad_step"))})
    return rows


def graded_rows():
    return shard_rows(GRADED_MANIFEST, GRADED_LABELS)


def sibling_rows():
    return shard_rows(SIBLING_MANIFEST, SIBLING_LABELS)


def rows_as_presented(rows):
    """The same rows, reordered into the order the artifact shipped them."""
    position = dict((solution_id, n) for n, (solution_id, _r) in enumerate(submitted_records()))
    return sorted(rows, key=lambda row: position.get(row["id"], -1))


# ------------------------------------------------------------------------------------------
# Counting. Every quantity below is an integer count or a ratio of two, formed over the three
# human classes or over the emitted-versus-human index pair. Nothing is a float accumulation.
# ------------------------------------------------------------------------------------------

def confusion_cells(rows):
    """The nine cells as integers, keyed "human>emitted".

    Steps beyond the shorter of the two vectors are not counted. A length mismatch is its own
    check with its own knockout, and it must not leak in here as a silent truncation that
    nobody reported.
    """
    cells = dict(("%s>%s" % (human, emitted), 0) for human in LABELS for emitted in LABELS)
    for row in rows:
        for human, emitted in zip(row["human"], row["emitted"]):
            key = "%s>%s" % (human, emitted)
            if key in cells:
                cells[key] += 1
    return cells


def class_scores(cells):
    """Precision, recall and F1 per class, plus each class's emitted and human support."""
    out = {}
    for label in LABELS:
        hit = cells["%s>%s" % (label, label)]
        emitted_total = sum(cells["%s>%s" % (human, label)] for human in LABELS)
        human_total = sum(cells["%s>%s" % (label, emitted)] for emitted in LABELS)
        precision = hit / float(emitted_total) if emitted_total else 0.0
        recall = hit / float(human_total) if human_total else 0.0
        f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) else 0.0
        out[label] = {"precision": round(precision, 6), "recall": round(recall, 6),
                      "f1": round(f1, 6), "emitted": emitted_total, "human": human_total}
    return out


def macro_f1(cells):
    """The flat mean of the three per-class F1 terms. Three, including the middle class."""
    scores = class_scores(cells)
    return sum(scores[label]["f1"] for label in LABELS) / float(len(LABELS))


def decisive(label):
    """The two-valued reading a collapsed pipeline is really working in."""
    return BAD if label == BAD else GOOD


def binary_step_accuracy(cells):
    """Step accuracy after folding neutral into good.

    Reported beside macro-F1 wherever the neutral class is in question, because a run that has
    collapsed the middle class reads respectably here and poorly there, and the pair of numbers
    is what makes the collapse legible.
    """
    hit = total = 0
    for human in LABELS:
        for emitted in LABELS:
            count = cells["%s>%s" % (human, emitted)]
            total += count
            if decisive(human) == decisive(emitted):
                hit += count
    return hit / float(total) if total else 0.0


def localization_breakdown(rows):
    """The four ways an emitted index can meet a human one, counted separately.

    both_sentinel and both_indexed_equal are matches. kind_mismatch -- one side the sentinel and
    the other a position -- is a miss, always: -1 is a class on this axis and never a wildcard,
    and treating it as compatible with any index would convert the whole no-error population,
    which is large on a step-level process corpus, into free score.
    """
    out = {"both_sentinel": 0, "both_indexed_equal": 0, "both_indexed_unequal": 0,
           "kind_mismatch": 0, "unusable_index": 0, "offsets": []}
    for row in rows:
        emitted, human = row["emitted_index"], row["human_index"]
        if emitted is None or isinstance(human, bool) or not isinstance(human, int):
            out["unusable_index"] += 1
        elif emitted == SENTINEL and human == SENTINEL:
            out["both_sentinel"] += 1
        elif emitted == SENTINEL or human == SENTINEL:
            out["kind_mismatch"] += 1
        elif emitted == human:
            out["both_indexed_equal"] += 1
            out["offsets"].append(0)
        else:
            out["both_indexed_unequal"] += 1
            out["offsets"].append(emitted - human)
    out["matched"] = out["both_sentinel"] + out["both_indexed_equal"]
    out["total"] = len(rows)
    return out


def localization_rate(rows):
    breakdown = localization_breakdown(rows)
    return breakdown["matched"] / float(breakdown["total"]) if breakdown["total"] else 0.0


def joint_quality(rows):
    """The mean of macro-F1 and the exact-match localisation rate.

    Formed the same way on both private shards, so the sibling gap compares like with like.
    """
    return (macro_f1(confusion_cells(rows)) + localization_rate(rows)) / 2.0


def neutral_rate_table(rows):
    """Per stratum: the emitted and the human neutral step counts, their rates and the gap."""
    table = {}
    for row in rows:
        cell = table.setdefault(str(row["stratum"]),
                                {"stratum": str(row["stratum"]), "steps": 0,
                                 "emitted_neutral": 0, "human_neutral": 0})
        for human, emitted in zip(row["human"], row["emitted"]):
            cell["steps"] += 1
            cell["emitted_neutral"] += int(emitted == NEUTRAL)
            cell["human_neutral"] += int(human == NEUTRAL)
    for cell in table.values():
        steps = float(cell["steps"]) if cell["steps"] else 1.0
        cell["emitted_rate"] = round(cell["emitted_neutral"] / steps, 6)
        cell["human_rate"] = round(cell["human_neutral"] / steps, 6)
        cell["deviation"] = round(abs(cell["emitted_rate"] - cell["human_rate"]), 6)
    return [table[key] for key in sorted(table)]


def subgroup(rows, flag):
    """One of the two floored subgroups, with the sentinel share it was answered with."""
    members = [row for row in rows if row[flag]]
    if not members:
        return None
    sentinel = sum(1 for row in members if row["emitted_index"] == SENTINEL)
    return {"flag": flag, "size": len(members),
            "matched": localization_breakdown(members)["matched"],
            "rate": localization_rate(members),
            "sentinel_share": round(sentinel / float(len(members)), 6)}


def graded_seconds():
    """t: the harness's integer seconds, ceil of the interval it timed. Never the agent's."""
    record = run_record()
    start, end = record.get("first_data_touch_ns"), record.get("artefacts_written_ns")
    if isinstance(start, bool) or isinstance(end, bool):
        return None
    if not isinstance(start, int) or not isinstance(end, int) or end < start:
        return None
    return -(-(end - start) // 10 ** 9)


def stage_spans():
    spans = run_record().get("stage_spans")
    return spans if isinstance(spans, dict) else {}


def reward_log_entries():
    name = run_record().get("reward_log") or REWARD_LOG
    path = os.path.normpath(os.path.join(HERE, "..", str(name)))
    if not os.path.exists(path):
        return []
    entries = []
    with open(path) as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                entries.append(json.loads(line))
            except ValueError:
                continue
    return [entry for entry in entries if isinstance(entry, dict)]


def agent_source_root():
    return os.path.normpath(os.path.join(HERE, "..", "agent_src"))


def sha256_of(path):
    import hashlib
    with open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def carries_value(node, wanted, depth=0):
    """Whether a decoded payload holds `wanted` anywhere inside it.

    A file digest catches only a byte-identical copy. The private state of this slot can be held
    at three coarser granularities -- the first-error index vector, the per-id step-count map and
    the per-id stratum map -- and each of those can be re-serialised into a payload of the agent's
    own shape, so the search is by VALUE and not by digest.
    """
    if depth > 6:
        return False
    if node == wanted:
        return True
    if isinstance(node, dict):
        return any(carries_value(value, wanted, depth + 1) for value in node.values())
    if isinstance(node, list):
        return any(carries_value(value, wanted, depth + 1) for value in node)
    return False


def decoded_payloads(text):
    """Every JSON payload in a text file: the whole document, or one per JSONL line."""
    out = []
    try:
        out.append(json.loads(text))
    except ValueError:
        for line in text.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except ValueError:
                continue
    return out


def clamp(value):
    return max(0.0, min(1.0, value))


def hard_constraints(rows, sibling):
    """Every Stage-1 quantity the contract names, from integer counts alone.

    nb worst per-stratum neutral deviation, pc prefix divergences over the submitted bytes alone,
    sib the sibling joint-quality gap, ca and ls the two subgroup exact-match rates, t the
    harness's integer seconds. No submission-reported number enters any of them.
    """
    table = neutral_rate_table(rows)
    long_group = subgroup(rows, "long_solution")
    answer_group = subgroup(rows, "correct_answer_bad_step")
    return {"nb": max([cell["deviation"] for cell in table] or [1.0]),
            "pc": len(prefix_divergences(submitted_records())),
            "sib": abs(joint_quality(rows) - joint_quality(sibling)) if sibling else None,
            "ca": answer_group["rate"] if answer_group else None,
            "ls": long_group["rate"] if long_group else None,
            "t": graded_seconds()}
'''


# ==========================================================================================
# BODIES. Every compiled item carries one, written for THIS slot. The generic obligation lookup
# that used to fill this gap is gone: it read run_record()["obligations"][<ID>], a key nothing in
# the harness writes, so an item that fell through to it consulted nothing at all and still
# reported a clean False. The generator now REFUSES on a missing body.
# ==========================================================================================

BODIES = {

    "both_outputs_present_for_every_graded_solution": '''
    if not os.path.exists(SUBMISSION):
        return False, evidence(reason="submission_missing", path=SUBMISSION)
    try:
        load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    records = submitted_records()
    if not records:
        return False, evidence(reason="submission_malformed",
                               detail="the artifact parses but carries no id/output pair")
    labels_absent = [i for i, record in records if label_sequence(record) is None]
    index_absent = [i for i, record in records
                    if isinstance(record, dict) and INDEX_KEY not in record]
    reason = ("labels_absent" if labels_absent else "index_absent" if index_absent else None)
    return (reason is None), evidence(solutions=len(records),
                                      labels_absent=sorted(labels_absent)[:8],
                                      index_absent=sorted(index_absent)[:8], reason=reason)
''',

    "labels_drawn_from_the_three_human_classes": '''
    records = submitted_records()
    if not records:
        return False, evidence(reason="submission_malformed",
                               detail="there is nothing to read step labels from")
    offending, histogram = [], {}
    for solution_id, record in records:
        sequence = label_sequence(record)
        if sequence is None:
            offending.append({"id": solution_id, "step": None, "value": "labels_absent"})
            continue
        for step, label in enumerate(sequence):
            if label in LABELS:
                histogram[label] = histogram.get(label, 0) + 1
            elif len(offending) < 64:
                offending.append({"id": solution_id, "step": step, "value": repr(label)[:40]})
    return (not offending), evidence(solutions=len(records), emitted_classes=sorted(histogram),
                                     class_histogram=histogram, offending=offending[:8],
                                     reason=None if not offending else "label_outside_vocabulary")
''',

    "ids_and_step_counts_match_the_graded_manifest": '''
    manifest = read_json(heldout(GRADED_MANIFEST))
    if not isinstance(manifest, dict):
        return False, evidence(target="graded_shard", reason="graded_manifest_unavailable",
                               path=heldout(GRADED_MANIFEST))
    # BOTH private shards, because the agent is shipped the features of both and cannot know
    # which one is graded. Emitting for the graded shard alone would leave the sibling gap
    # uncomputable, and that gap is what bounds fitting to the graded shard's own feedback.
    known = dict(manifest)
    sibling = read_json(heldout(SIBLING_MANIFEST))
    if isinstance(sibling, dict):
        known.update(sibling)
    records = submitted_records()
    if not records:
        return False, evidence(reason="submission_malformed")
    submitted = [i for i, _record in records]
    seen, duplicates = set(), set()
    for solution_id in submitted:
        (duplicates if solution_id in seen else seen).add(solution_id)
    absent = sorted(set(known) - seen)
    unknown = sorted(seen - set(known))
    mismatched = []
    for solution_id, record in records:
        entry, sequence = known.get(solution_id), label_sequence(record)
        if not isinstance(entry, dict) or sequence is None:
            continue
        expected = entry.get("step_count")
        if isinstance(expected, int) and len(sequence) != expected:
            mismatched.append({"id": solution_id, "emitted": len(sequence),
                               "manifest": expected})
    reason = ("duplicate_ids" if duplicates else
              "id_absent_from_submission" if absent else
              "id_not_in_manifest" if unknown else
              "step_count_mismatch" if mismatched else None)
    return (reason is None), evidence(target="graded_shard", graded_ids=len(manifest),
                                      expected_ids=len(known), submitted_ids=len(submitted),
                                      duplicate_ids=sorted(duplicates)[:8], absent=absent[:8],
                                      unknown=unknown[:8], step_count_mismatched=mismatched[:8],
                                      reason=reason)
''',

    "first_error_index_equals_first_bad_label_in_its_own_vector": '''
    records = submitted_records()
    if not records:
        return False, evidence(reason="submission_malformed",
                               detail="neither output is present to be compared with the other")
    divergent = prefix_divergences(records)
    late = sum(1 for entry in divergent
               if isinstance(entry["first_bad"], int) and isinstance(entry["emitted_index"], int)
               and entry["first_bad"] != SENTINEL and entry["emitted_index"] > entry["first_bad"])
    early = sum(1 for entry in divergent
                if isinstance(entry["first_bad"], int) and isinstance(entry["emitted_index"], int)
                and entry["emitted_index"] != SENTINEL and entry["emitted_index"] < entry["first_bad"])
    return (not divergent), evidence(solutions=len(records),
                                     prefix_divergence_count=len(divergent),
                                     index_after_first_bad=late, index_before_first_bad=early,
                                     divergent=divergent[:8],
                                     reason=None if not divergent
                                     else "prefix_ordering_divergence")
''',

    "no_error_sentinel_is_typed_minus_one_not_a_wildcard": '''
    records = submitted_records()
    if not records:
        return False, evidence(reason="submission_malformed")
    offending, sentinel_emitted = [], 0
    for solution_id, record in records:
        raw = record.get(INDEX_KEY) if isinstance(record, dict) else None
        index, sequence = emitted_index(record), label_sequence(record)
        if index is None:
            offending.append({"id": solution_id, "value": repr(raw)[:40], "why": "not_an_int"})
        elif index == SENTINEL:
            sentinel_emitted += 1
        elif sequence is None or not 0 <= index < len(sequence):
            offending.append({"id": solution_id, "value": index,
                              "steps": None if sequence is None else len(sequence),
                              "why": "outside_its_own_vector"})
    return (not offending), evidence(solutions=len(records), sentinel_emitted=sentinel_emitted,
                                     sentinel_share=round(sentinel_emitted / float(len(records)), 6),
                                     offending=offending[:8],
                                     reason=None if not offending
                                     else "index_not_an_exact_class")
''',

    "constant_label_or_constant_index_submission_rejected": '''
    records = submitted_records()
    if not records:
        return False, evidence(reason="submission_malformed")
    label_histogram, index_histogram, steps = {}, {}, 0
    for _solution_id, record in records:
        for label in (label_sequence(record) or []):
            label_histogram[str(label)] = label_histogram.get(str(label), 0) + 1
            steps += 1
        key = str(emitted_index(record))
        index_histogram[key] = index_histogram.get(key, 0) + 1
    constant_labels = steps > 0 and len(label_histogram) == 1
    # One solution cannot be constant in a meaningful sense; the degenerate route this rejects is
    # a whole-shard emission, and CTRL_S2_LIST_ALL is exactly that over ten thousand solutions.
    constant_index = len(records) > 1 and len(index_histogram) == 1
    dominant = max(label_histogram.values()) / float(steps) if steps else 0.0
    return (not (constant_labels or constant_index)), evidence(
        steps=steps, solutions=len(records), class_histogram=label_histogram,
        dominant_class_share=round(dominant, 6),
        distinct_indices=len(index_histogram), constant_labels=constant_labels,
        constant_index=constant_index,
        reason=("degenerate_constant_output" if (constant_labels or constant_index) else None))
''',

    "per_stratum_neutral_rate_inside_the_band": '''
    rows = graded_rows()
    if rows is None:
        return False, evidence(target="graded_shard", reason="graded_shard_unavailable",
                               manifest=heldout(GRADED_MANIFEST), labels=heldout(GRADED_LABELS))
    if not rows:
        return False, evidence(target="graded_shard", reason="no_graded_solution_scored",
                               detail="no submitted id is named by both the manifest and the "
                                      "private label store")
    table = neutral_rate_table(rows)
    worst = max(table, key=lambda cell: cell["deviation"])
    ok = worst["deviation"] <= NEUTRAL_BAND
    return ok, evidence(target="graded_shard", band=NEUTRAL_BAND, strata=table,
                        worst_stratum=worst["stratum"], worst_deviation=worst["deviation"],
                        graded_solutions=len(rows),
                        reason=None if ok else "neutral_band_violated")
''',

    "every_stratum_carries_emitted_neutral_support": '''
    rows = graded_rows()
    if not rows:
        return False, evidence(target="graded_shard",
                               reason="graded_shard_unavailable" if rows is None
                               else "no_graded_solution_scored")
    table = neutral_rate_table(rows)
    dead = [cell["stratum"] for cell in table if cell["emitted_neutral"] == 0]
    displacement = {}
    for stratum in dead:
        members = [row for row in rows if str(row["stratum"]) == stratum
                   and isinstance(row["emitted_index"], int)
                   and isinstance(row["human_index"], int)
                   and row["emitted_index"] != SENTINEL and row["human_index"] != SENTINEL]
        if members:
            shift = sum(row["emitted_index"] - row["human_index"] for row in members)
            displacement[stratum] = round(shift / float(len(members)), 6)
    return (not dead), evidence(
        target="graded_shard", strata=len(table), dead_neutral_strata=dead,
        human_neutral_rate=dict((cell["stratum"], cell["human_rate"]) for cell in table),
        signed_index_displacement=displacement,
        displacement_reading="positive means the emitted first error arrives late, which is the "
                             "signature of folding neutral into good; negative means early, "
                             "which is the signature of folding it into bad",
        reason=None if not dead else "neutral_class_collapsed")
''',

    "neutral_row_and_column_of_the_confusion_matrix_are_live": '''
    rows = graded_rows()
    if not rows:
        return False, evidence(target="graded_shard",
                               reason="graded_shard_unavailable" if rows is None
                               else "no_graded_solution_scored")
    cells = confusion_cells(rows)
    scores = class_scores(cells)
    counted = sum(cells.values())
    comparable = sum(min(len(row["human"]), len(row["emitted"])) for row in rows)
    live_row, live_column = scores[NEUTRAL]["human"] > 0, scores[NEUTRAL]["emitted"] > 0
    closes = counted == comparable and counted > 0
    reason = (None if (live_row and live_column and closes) else
              "neutral_class_has_no_prediction_mass" if not live_column else
              "neutral_class_has_no_support" if not live_row else
              "confusion_matrix_does_not_close")
    return (reason is None), evidence(
        target="graded_shard", cells=cells, per_class=scores,
        macro_f1=round(macro_f1(cells), 6),
        binary_step_accuracy=round(binary_step_accuracy(cells), 6),
        steps_counted=counted, steps_comparable=comparable, reason=reason)
''',

    "index_exact_match_scores_minus_one_as_its_own_class": '''
    rows = graded_rows()
    if not rows:
        return False, evidence(target="graded_shard",
                               reason="graded_shard_unavailable" if rows is None
                               else "no_graded_solution_scored")
    breakdown = localization_breakdown(rows)
    near = {}
    for offset in breakdown["offsets"]:
        key = str(offset) if abs(offset) <= 3 else "beyond_3"
        near[key] = near.get(key, 0) + 1
    ok = breakdown["unusable_index"] == 0 and breakdown["total"] > 0
    return ok, evidence(
        target="graded_shard", localization_rate=round(localization_rate(rows), 6),
        both_sentinel=breakdown["both_sentinel"],
        both_indexed_equal=breakdown["both_indexed_equal"],
        both_indexed_unequal=breakdown["both_indexed_unequal"],
        kind_mismatch=breakdown["kind_mismatch"], unusable_index=breakdown["unusable_index"],
        near_miss_histogram=near, graded_solutions=breakdown["total"],
        sentinel_is_a_class="a sentinel against a position is a miss in both directions",
        reason=None if ok else "index_pair_unusable")
''',

    "global_index_offset_rejected": '''
    rows = graded_rows()
    if not rows:
        return False, evidence(target="graded_shard",
                               reason="graded_shard_unavailable" if rows is None
                               else "no_graded_solution_scored")
    offsets = [row["emitted_index"] - row["human_index"] for row in rows
               if isinstance(row["emitted_index"], int) and isinstance(row["human_index"], int)
               and row["emitted_index"] != SENTINEL and row["human_index"] != SENTINEL]
    if not offsets:
        return False, evidence(target="graded_shard", reason="no_indexed_pair_to_compare",
                               detail="every graded pair is a sentinel on one side or the other, "
                                      "so no indexing convention is observable")
    counts, histogram = {}, {}
    for offset in offsets:
        counts[offset] = counts.get(offset, 0) + 1
        key = (str(offset) if abs(offset) <= 3
               else "beyond_3" if offset > 0 else "below_minus_3")
        histogram[key] = histogram.get(key, 0) + 1
    dominant = max(sorted(counts), key=lambda offset: counts[offset])
    share = counts[dominant] / float(len(offsets))
    ok = dominant == 0 or share <= 0.5
    return ok, evidence(target="graded_shard", indexed_pairs=len(offsets),
                        dominant_offset=dominant, dominant_share=round(share, 6),
                        offset_histogram=histogram,
                        reason=None if ok else "global_index_offset")
''',

    "long_solution_first_error_subgroup_floor": '''
    rows = graded_rows()
    if not rows:
        return False, evidence(target="graded_shard",
                               reason="graded_shard_unavailable" if rows is None
                               else "no_graded_solution_scored")
    misflagged = [row["id"] for row in rows
                  if row["long_solution"] != (isinstance(row["step_count"], int)
                                              and row["step_count"] >= LONG_SOLUTION_MIN_STEPS
                                              and isinstance(row["human_index"], int)
                                              and row["human_index"] >= LONG_SOLUTION_MIN_INDEX)]
    if misflagged:
        return False, evidence(target="graded_shard", reason="subgroup_definition_disagrees",
                               misflagged=sorted(misflagged)[:8],
                               min_steps=LONG_SOLUTION_MIN_STEPS,
                               min_first_error_index=LONG_SOLUTION_MIN_INDEX)
    group = subgroup(rows, "long_solution")
    if group is None:
        return False, evidence(target="graded_shard", reason="subgroup_absent",
                               detail="no graded solution carries at least the minimum step count "
                                      "with its human first error at or beyond the minimum index; "
                                      "a floor over an empty subgroup cannot fire")
    whole = localization_rate(rows)
    ok = group["rate"] >= LONG_SOLUTION_FLOOR
    return ok, evidence(target="graded_shard", subgroup_size=group["size"],
                        matched=group["matched"], subgroup_rate=round(group["rate"], 6),
                        floor=LONG_SOLUTION_FLOOR, whole_shard_rate=round(whole, 6),
                        gap=round(whole - group["rate"], 6),
                        min_steps=LONG_SOLUTION_MIN_STEPS,
                        min_first_error_index=LONG_SOLUTION_MIN_INDEX,
                        reason=None if ok else "long_solution_subgroup_below_floor")
''',

    "correct_answer_bad_step_subgroup_floor": '''
    rows = graded_rows()
    if not rows:
        return False, evidence(target="graded_shard",
                               reason="graded_shard_unavailable" if rows is None
                               else "no_graded_solution_scored")
    misflagged = [row["id"] for row in rows
                  if row["correct_answer_bad_step"] and BAD not in row["human"]]
    if misflagged:
        return False, evidence(target="graded_shard", reason="subgroup_definition_disagrees",
                               misflagged=sorted(misflagged)[:8],
                               detail="a member of this subgroup must carry a human-labelled bad "
                                      "step; the flag names solutions whose answer is right and "
                                      "whose process is not")
    group = subgroup(rows, "correct_answer_bad_step")
    if group is None:
        return False, evidence(target="graded_shard", reason="subgroup_absent",
                               detail="no graded solution reaches the gold answer through a "
                                      "human-labelled bad step; a floor over an empty subgroup "
                                      "cannot fire")
    ok = group["rate"] >= CORRECT_ANSWER_FLOOR
    return ok, evidence(target="graded_shard", subgroup_size=group["size"],
                        matched=group["matched"], subgroup_rate=round(group["rate"], 6),
                        floor=CORRECT_ANSWER_FLOOR, sentinel_share=group["sentinel_share"],
                        sentinel_reading="a high sentinel share here is a pipeline reading the "
                                         "final answer instead of the process",
                        reason=None if ok else "correct_answer_subgroup_below_floor")
''',

    "sibling_shard_joint_quality_gap": '''
    rows, sibling = graded_rows(), sibling_rows()
    if not rows:
        return False, evidence(target="graded_shard",
                               reason="graded_shard_unavailable" if rows is None
                               else "no_graded_solution_scored")
    if not sibling:
        return False, evidence(target="sibling_shard", reason="sibling_shard_unavailable",
                               manifest=heldout(SIBLING_MANIFEST),
                               labels=heldout(SIBLING_LABELS),
                               detail="a missing comparator is not agreement")
    graded_f1, graded_loc = macro_f1(confusion_cells(rows)), localization_rate(rows)
    sibling_f1, sibling_loc = macro_f1(confusion_cells(sibling)), localization_rate(sibling)
    gap = abs((graded_f1 + graded_loc) / 2.0 - (sibling_f1 + sibling_loc) / 2.0)
    ok = gap <= SIBLING_GAP_CAP
    return ok, evidence(target="sibling_shard", cap=SIBLING_GAP_CAP, gap=round(gap, 6),
                        graded_macro_f1=round(graded_f1, 6),
                        graded_localization=round(graded_loc, 6),
                        graded_joint=round((graded_f1 + graded_loc) / 2.0, 6),
                        sibling_macro_f1=round(sibling_f1, 6),
                        sibling_localization=round(sibling_loc, 6),
                        sibling_joint=round((sibling_f1 + sibling_loc) / 2.0, 6),
                        graded_solutions=len(rows), sibling_solutions=len(sibling),
                        reason=None if ok else "sibling_gap_exceeded")
''',

    "counts_invariant_under_the_presentation_permutation": '''
    rows = graded_rows()
    if not rows:
        return False, evidence(target="graded_shard",
                               reason="graded_shard_unavailable" if rows is None
                               else "no_graded_solution_scored")
    presented = rows_as_presented(rows)
    canonical_cells, presented_cells = confusion_cells(rows), confusion_cells(presented)
    canonical_match = localization_breakdown(rows)["matched"]
    presented_match = localization_breakdown(presented)["matched"]
    positional = sorted(set(key for _i, record in submitted_records()
                            if isinstance(record, dict)
                            for key in record if key in POSITIONAL_KEYS))
    stable = canonical_cells == presented_cells and canonical_match == presented_match
    reason = (None if (stable and not positional) else
              "order_dependent_aggregation" if not stable else "positional_key_in_output")
    return (reason is None), evidence(
        target="submitted_artifact", canonical_cells=canonical_cells,
        presented_cells=presented_cells, canonical_matched=canonical_match,
        presented_matched=presented_match, positional_keys=positional,
        graded_solutions=len(rows), reason=reason)
''',

    "human_labels_and_stratum_map_not_held_agent_side": '''
    touched = [str(path) for path in (run_record().get("guarded_paths_touched") or [])]
    if touched:
        named = [path for path in touched
                 if any(guard in path for guard in GUARDED) or path.startswith("tests/")]
        return False, evidence(target="submitted_source", touched=touched[:8],
                               guarded_named=named[:8], reason="wrote_into_guarded_tree")
    root = agent_source_root()
    if not os.path.isdir(root):
        return False, evidence(target="submitted_source", reason="agent_source_unavailable",
                               root=root)
    digests = {}
    for name in (GRADED_LABELS, SIBLING_LABELS, GRADED_MANIFEST):
        path = heldout(name)
        if os.path.exists(path):
            digests[sha256_of(path)] = os.path.basename(name)
    labels = read_json(heldout(GRADED_LABELS)) or {}
    manifest = read_json(heldout(GRADED_MANIFEST)) or {}
    shapes = [("first_error_index_vector",
               [labels[key].get(INDEX_KEY) for key in sorted(labels)
                if isinstance(labels[key], dict)]),
              ("step_count_map",
               dict((key, manifest[key].get("step_count")) for key in sorted(manifest)
                    if isinstance(manifest[key], dict))),
              ("stratum_map",
               dict((key, manifest[key].get("stratum")) for key in sorted(manifest)
                    if isinstance(manifest[key], dict)))]
    hits, scanned = [], 0
    for dirpath, _dirs, filenames in os.walk(root):
        for filename in sorted(filenames):
            full = os.path.join(dirpath, filename)
            try:
                blob = open(full, "rb").read()
            except Exception:
                continue
            scanned += 1
            relative = os.path.relpath(full, root)
            digest = sha256_of(full)
            if digest in digests:
                hits.append({"path": relative, "match": digests[digest],
                             "how": "byte_identical"})
                continue
            if not filename.endswith((".json", ".jsonl", ".txt", ".yaml", ".yml")):
                continue
            try:
                text = blob.decode("utf-8")
            except UnicodeDecodeError:
                continue
            payloads = decoded_payloads(text)
            for shape, wanted in shapes:
                if not wanted:
                    continue
                if any(carries_value(payload, wanted) for payload in payloads):
                    hits.append({"path": relative, "match": shape, "how": "value_identical"})
    return (not hits), evidence(target="submitted_source", files_scanned=scanned,
                                shapes_searched=[shape for shape, _w in shapes],
                                matches=hits[:8],
                                reason=None if not hits else "private_labels_held_agent_side")
''',

    "six_named_stages_inside_one_timed_invocation": '''
    record = run_record()
    start, end = record.get("first_data_touch_ns"), record.get("artefacts_written_ns")
    harness_seconds = graded_seconds()
    if harness_seconds is None:
        return False, evidence(target="run_record", reason="timed_region_unmeasured",
                               first_data_touch_ns=start, artefacts_written_ns=end)
    spans, missing, outside = stage_spans(), [], []
    for stage in TIMED_STAGES:
        span = spans.get(stage)
        if span is None:
            missing.append(stage)
            continue
        if not isinstance(span, (list, tuple)) or len(span) != 2:
            outside.append({"stage": stage, "why": "unreadable_span"})
            continue
        try:
            began, ended = int(span[0]), int(span[1])
        except (TypeError, ValueError):
            outside.append({"stage": stage, "why": "unreadable_span"})
            continue
        if began < start or ended > end or ended < began:
            outside.append({"stage": stage, "span": [began, ended], "why": "outside_timed_region"})
    declared = record.get("elapsed_seconds")
    faithful = isinstance(declared, int) and not isinstance(declared, bool) \\
        and declared == harness_seconds
    reason = ("stage_closure_missing" if (missing or outside) else
              None if faithful else "elapsed_seconds_not_the_harness_measurement")
    return (reason is None), evidence(
        target="run_record", stages=list(TIMED_STAGES), missing_stages=missing,
        stages_outside_timed_region=outside, declared_seconds=declared,
        harness_seconds=harness_seconds,
        detail="calibrating per-stratum thresholds before the timer starts is the ordinary way a "
               "wall-clock axis is defeated, so stage closure is checked stage by stage",
        reason=reason)
''',

    "reward_log_matches_recomputed_f1_and_localization": '''
    entries = reward_log_entries()
    if not entries:
        return False, evidence(target="run_record", reason="reward_log_absent",
                               path=str(run_record().get("reward_log") or REWARD_LOG))
    rows = graded_rows()
    if not rows:
        return False, evidence(target="graded_shard",
                               reason="graded_shard_unavailable" if rows is None
                               else "no_graded_solution_scored")
    entry = entries[-1]
    recomputed = {"macro_f1": macro_f1(confusion_cells(rows)),
                  "localization_rate": localization_rate(rows),
                  "elapsed_seconds": graded_seconds()}
    absent = [field for field in sorted(recomputed) if entry.get(field) is None]
    if absent:
        return False, evidence(target="run_record", reason="log_incomplete", missing=absent,
                               entry_keys=sorted(entry))
    disagreements = []
    for field in ("macro_f1", "localization_rate"):
        try:
            claimed = float(entry[field])
        except (TypeError, ValueError):
            disagreements.append({"field": field, "claimed": repr(entry[field])[:40],
                                  "why": "unreadable"})
            continue
        gap = abs(claimed - recomputed[field])
        if gap > LOG_RATE_TOLERANCE:
            disagreements.append({"field": field, "claimed": claimed,
                                  "recomputed": round(recomputed[field], 6),
                                  "gap": round(gap, 6), "tolerance": LOG_RATE_TOLERANCE})
    measured = recomputed["elapsed_seconds"]
    if measured is None:
        disagreements.append({"field": "elapsed_seconds", "why": "harness_did_not_measure"})
    else:
        try:
            claimed = float(entry["elapsed_seconds"])
            relative = abs(claimed - measured) / float(measured if measured else 1)
            if relative > LOG_ELAPSED_TOLERANCE:
                disagreements.append({"field": "elapsed_seconds", "claimed": claimed,
                                      "recomputed": measured, "relative_gap": round(relative, 6),
                                      "tolerance": LOG_ELAPSED_TOLERANCE})
        except (TypeError, ValueError):
            disagreements.append({"field": "elapsed_seconds",
                                  "claimed": repr(entry["elapsed_seconds"])[:40],
                                  "why": "unreadable"})
    return (not disagreements), evidence(
        target="run_record", entries=len(entries),
        recomputed_macro_f1=round(recomputed["macro_f1"], 6),
        recomputed_localization=round(recomputed["localization_rate"], 6),
        recomputed_seconds=measured, disagreements=disagreements,
        reason=None if not disagreements else "log_fabrication")
''',

    "both_coupled_artefacts_replay_byte_identically": '''
    if not os.path.exists(SUBMISSION):
        return False, evidence(target="submitted_source", reason="submission_missing",
                               path=SUBMISSION)
    replay = run_record().get("replay_artifact_sha256")
    if not isinstance(replay, str) or not replay:
        return False, evidence(target="submitted_source", reason="replay_unavailable",
                               detail="an unperformed replay is not a successful one")
    first = sha256_of(SUBMISSION)
    ok = first == replay
    return ok, evidence(target="submitted_source", first_run=first, replay=replay,
                        detail="byte identity of the whole artifact, because the two outputs are "
                               "coupled: a replay that reproduces the label vectors while "
                               "re-deriving the indices has not reproduced the run",
                        reason=None if ok else "replay_diverged")
''',

    "staged_r_det_speed_ramp_behind_the_joint_quality_gate": '''
    c = require_measured("floor", "knee", "dichotomizing_threshold")
    # require_measured FIRST, before any submitted byte is read. Reading first lets an absent
    # artifact report as an ordinary failure, which makes the verifier say gradeable=true with
    # r_det=0.0 -- collapsing "this slot is not yet measurable" into "the agent scored zero".
    # seed/build/freeze_batch.py refuses to freeze a bundle that does this.
    import math
    rows, sibling = graded_rows(), sibling_rows()
    if not rows:
        return False, evidence(target="graded_shard",
                               reason="graded_shard_unavailable" if rows is None
                               else "no_graded_solution_scored")
    gates = hard_constraints(rows, sibling)
    cells = confusion_cells(rows)
    f1, loc = macro_f1(cells), localization_rate(rows)
    zeroed = []
    if gates["t"] is None:
        zeroed.append("timed-region-unmeasured")
    elif gates["t"] > c["floor"]:
        zeroed.append("budget-exceeded")
    if gates["nb"] > NEUTRAL_BAND:
        zeroed.append("neutral-band-violated")
    if gates["pc"] > 0:
        zeroed.append("prefix-ordering-divergence")
    if gates["sib"] is None or gates["sib"] > SIBLING_GAP_CAP:
        zeroed.append("sibling-gap-exceeded")
    if gates["ca"] is None or gates["ca"] < CORRECT_ANSWER_FLOOR:
        zeroed.append("correct-answer-subgroup-below-floor")
    if gates["ls"] is None or gates["ls"] < LONG_SOLUTION_FLOOR:
        zeroed.append("long-solution-subgroup-below-floor")
    if zeroed:
        stage, value = 1, 0.0
    elif f1 < T_F1 or loc < T_LOC:
        stage = 2
        value = SUB_GATE_CEILING * min(clamp((f1 - F1_CHANCE) / (T_F1 - F1_CHANCE)),
                                       clamp((loc - LOC_CHANCE) / (T_LOC - LOC_CHANCE)))
    else:
        stage = 3
        span = math.log(c["floor"]) - math.log(c["knee"])
        ramp = 0.0 if span <= 0 else clamp((math.log(c["floor"])
                                            - math.log(max(gates["t"], 1))) / span)
        value = GATE_VALUE + (1.0 - GATE_VALUE) * ramp
    return value >= c["dichotomizing_threshold"], evidence(
        target="graded_shard", stage=stage, r_det=value, zero_reasons=zeroed,
        macro_f1=round(f1, 6), localization_rate=round(loc, 6),
        worst_neutral_deviation=round(gates["nb"], 6), prefix_divergences=gates["pc"],
        sibling_gap=None if gates["sib"] is None else round(gates["sib"], 6),
        correct_answer_subgroup=None if gates["ca"] is None else round(gates["ca"], 6),
        long_solution_subgroup=None if gates["ls"] is None else round(gates["ls"], 6),
        graded_seconds=gates["t"], slow_end=c["floor"], fast_end=c["knee"])
''',
}


def build_tests(g, prelude, bodies):
    """Assemble the compiled-check module. kind carries the item's own dimension."""
    chunks = [prelude]
    for raw in sorted(g["items"], key=lambda item: item["id"]):
        if raw["mode"] != "compiled":
            continue
        chunks.append('\n\n@check(id="%s", weight=%d, knockout=%s, kind="%s")\ndef test_%s():\n%s\n'
                      % (raw["id"], raw["weight"], raw["knockout"], raw["dimension"], raw["id"],
                         bodies[raw["id"]].strip("\n")))
    return "".join(chunks)


def build_truth(g, title):
    """Render solution/TRUTH.md from the frozen literals of solution/grounding.yaml."""
    n = g["truth_narrative"]
    lines = [title, "", "GENERATED SECTION. DO NOT HAND-EDIT.", "", n["opening"], "",
             "## The single most important insight", "", n["insight"], "",
             "## The ideal solve, step by step", ""]
    for i, step in enumerate(n["steps"], 1):
        lines += ["%d. **%s** %s" % (i, step["heading"], step["paragraph"]), ""]
    lines += ["## Traps that catch agents that are not thinking carefully", ""]
    lines += ["- " + t for t in n["traps"]]
    lines += ["", "---", "", "## Contract record (annex; not part of the narrative body)", "",
              "Retained under FORGE.md item 10e and Phase 2 item 7, which require this file to "
              "carry the ordered path through instruction.md with each satisfied checker "
              "identifier, and each rejected route bound to a measured known-wrong control. "
              "standards/truth-md-authoring-v1.md section 3 admits no fifth section, so this "
              "annex is a recorded deviation rather than an omission.", "", g["truth_annex"], ""]
    return "\n".join(lines) + "\n"


def build_rubrics(g, item_keys):
    """The 9g rubric carrier. The item schema is CLOSED at eight keys, so item 10f's outcome
    classification rides as a greppable prefix of the judgment rather than as a ninth key."""
    items = []
    for raw in g["items"]:
        item = {k: raw[k] for k in item_keys}
        item["judgment"] = "%s: %s" % (raw["outcome_class"], raw["judgment"])
        items.append(item)
    compiled = sum(i["weight"] for i in items if i["mode"] == "compiled")
    total = sum(i["weight"] for i in items)
    return {"$schema": "forge.rubric/v1",
            "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
            "generator": "solution/recompute.py",
            "compilation_floor": g["compilation_floor"],
            "compiled_weight_share": round(compiled / total, 6) if total else 0.0,
            "evaluation_target_vocabulary": sorted(g["evaluation_target_vocabulary"]),
            "items": sorted(items, key=lambda i: i["id"])}


def build_provenance(g, identity):
    p = g["provenance"]
    out = {
        "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
        "generator": "solution/recompute.py from solution/grounding.yaml",
        "schema_version": "1.0",
        "slot_id": g["slot_id"],
        "identity": identity,
        "corpus": p["corpus"],
        "anchors": p["anchors"],
        "shards": p["shards"],
        "narrative": p["narrative"],
        "supersedes": p["supersedes"],
        "upstream_provenance": p["upstream_record"],
        "reward_composition": p["reward_composition"],
        "screening_interval_days": p["screening_interval_days"],
        "screening_detector_version": p["screening_detector_version"],
        "derivation_instant": p["derivation_instant"],
        "screening_roots": p["screening_roots"],
        "empty_submission_result": p["empty_submission_result"],
        "resolved_closure": p["resolved_closure"],
        "applicability": p["applicability"],
        "measurement_tier": g["measurement_tier"],
        "gradeable": g["gradeable"],
        "knee_anchor_status": g["knee_anchor_status"],
        "coupled_outputs_per_solution": 2,
        "step_label_classes": len(g["corpus_layout"]["label_vocabulary"]),
        "no_error_sentinel": g["corpus_layout"]["no_error_sentinel"],
        "corpus_landed": os.path.isdir(os.path.join(BUNDLE, "environment", "data")),
    }
    out.update(read_screening(HERE))
    return out


def validate(grounding):
    """Refuse on a malformed derivation source rather than emitting a checker from one.

    These are the invariants the emitted checker actually depends on. A generator that writes a
    carrier it knows is malformed hands the drift check a moving target.
    """
    problems = []
    items = grounding.get("items") or []
    if not items:
        problems.append("no items to compile")
    seen = set()
    for item in items:
        iid = item.get("id", "<unnamed>")
        if iid in seen:
            problems.append("duplicate item id %r" % iid)
        seen.add(iid)
        if set(item) != ITEM_SCHEMA:
            problems.append("item %r does not carry the closed schema: %s"
                            % (iid, sorted(set(item) ^ ITEM_SCHEMA)))
            continue
        if item["outcome_class"] not in OUTCOME_CLASSES:
            problems.append("item %r has outcome_class %r" % (iid, item["outcome_class"]))
        if item["evaluation_target"] not in grounding["evaluation_target_vocabulary"]:
            problems.append("item %r evaluates %r, which the vocabulary does not admit"
                            % (iid, item["evaluation_target"]))
        if not isinstance(item["weight"], int) or item["weight"] <= 0:
            problems.append("item %r carries weight %r" % (iid, item["weight"]))

    outcome = [i["id"] for i in items if i.get("dimension") == "outcome"]
    if len(outcome) != 1:
        problems.append("expected exactly one outcome item, found %r" % outcome)

    for name in RAMP:
        if grounding["constants"].get(name) is not None:
            problems.append("constant %r is authored at Phase 0; it is measured, not authored"
                            % name)

    if grounding["deliverable"].get("kind") != "json":
        problems.append("the graded deliverable of this slot is a json object carrying two "
                        "coupled outputs per solution, not %r"
                        % grounding["deliverable"].get("kind"))

    layout = grounding.get("corpus_layout") or {}
    labels = layout.get("label_vocabulary") or []
    # THREE classes, and the middle one is the whole task. A two-valued vocabulary would make the
    # neutral band, the live-neutral-row item and the abstention reading of AR7 all vacuous.
    if len(labels) != 3 or len(set(labels)) != 3:
        problems.append("the step label vocabulary is %r; this slot grades three human classes"
                        % (labels,))
    if layout.get("no_error_sentinel") in labels:
        problems.append("the no-error sentinel %r is also a step label; it is a value on the "
                        "index axis and must not be one on the label axis"
                        % layout.get("no_error_sentinel"))
    strata = layout.get("strata") or []
    if len(strata) < 2 or len(set(strata)) != len(strata):
        problems.append("the disclosed strata are %r; a per-stratum band needs at least two "
                        "distinct strata to say anything a global rate does not" % (strata,))
    stages = layout.get("timed_stages") or []
    if len(set(stages)) != len(stages) or not stages:
        problems.append("the timed stage list is %r" % (stages,))

    bound = layout.get("bound_constants") or {}
    for key in ("t_f1", "t_loc", "f1_chance", "loc_chance", "neutral_band", "sibling_gap_cap",
                "long_solution_floor", "correct_answer_bad_step_floor", "sub_gate_ceiling",
                "gate_value", "log_rate_tolerance", "log_elapsed_tolerance_fraction"):
        value = bound.get(key)
        if not isinstance(value, float) or not 0.0 < value < 1.0:
            problems.append("bound constant %s is %r, which is not a fraction in (0,1)"
                            % (key, value))
    # The two sub-gate denominators. A chance level at or above its gate would divide by zero or
    # by a negative number and turn the conjunctive ramp into a silent sign error.
    if isinstance(bound.get("t_f1"), float) and isinstance(bound.get("f1_chance"), float):
        if bound["t_f1"] <= bound["f1_chance"]:
            problems.append("t_f1 %r is not above f1_chance %r, so the sub-gate ramp has no span"
                            % (bound["t_f1"], bound["f1_chance"]))
    if isinstance(bound.get("t_loc"), float) and isinstance(bound.get("loc_chance"), float):
        if bound["t_loc"] <= bound["loc_chance"]:
            problems.append("t_loc %r is not above loc_chance %r, so the sub-gate ramp has no span"
                            % (bound["t_loc"], bound["loc_chance"]))
    # The sub-gate ceiling must sit strictly UNDER the gate value, or clearing both quality gates
    # could pay less than missing them.
    if isinstance(bound.get("sub_gate_ceiling"), float) and isinstance(bound.get("gate_value"),
                                                                      float):
        if bound["sub_gate_ceiling"] >= bound["gate_value"]:
            problems.append("sub_gate_ceiling %r is not below gate_value %r"
                            % (bound["sub_gate_ceiling"], bound["gate_value"]))
    for key in ("long_solution_min_steps", "long_solution_min_first_error_index"):
        if not isinstance(bound.get(key), int) or bound[key] < 0:
            problems.append("bound constant %s is %r, which is not a step count" % (key, bound.get(key)))
    if (isinstance(bound.get("long_solution_min_steps"), int)
            and isinstance(bound.get("long_solution_min_first_error_index"), int)
            and bound["long_solution_min_first_error_index"] >= bound["long_solution_min_steps"]):
        problems.append("the long-solution subgroup requires a first error at index %r inside a "
                        "solution of only %r steps, which no solution can satisfy"
                        % (bound["long_solution_min_first_error_index"],
                           bound["long_solution_min_steps"]))
    for key in ("graded_manifest", "graded_labels", "sibling_manifest", "sibling_labels"):
        if not str(layout.get(key, "")).startswith("tests/heldout/"):
            problems.append("corpus_layout %s is %r; the private shards live under tests/heldout/"
                            % (key, layout.get(key)))
    return problems


def main():
    g = load_grounding()
    # The validator runs FIRST and refuses rather than emitting.
    problems = validate(g)
    if problems:
        raise SystemExit("AELLO-C6-S2 grounding is not well-formed: " + "; ".join(problems))

    layout = g["corpus_layout"]
    bound = layout["bound_constants"]
    outcome_id = [i["id"] for i in g["items"] if i["dimension"] == "outcome"][0]
    subst = {
        "slot_id": SLOT_ID,
        "path": g["deliverable"]["path"],
        "outcome_id": outcome_id,
        "labels": tuple(layout["label_vocabulary"]),
        "sentinel": layout["no_error_sentinel"],
        "labels_key": "labels",
        "index_key": "first_error_index",
        "positional_keys": ("order", "position", "presentation_index", "rank", "row", "row_index"),
        "graded_manifest": os.path.basename(layout["graded_manifest"]),
        "graded_labels": os.path.basename(layout["graded_labels"]),
        "sibling_manifest": os.path.basename(layout["sibling_manifest"]),
        "sibling_labels": os.path.basename(layout["sibling_labels"]),
        "strata": tuple(layout["strata"]),
        "run_record": layout["run_record"],
        "reward_log": layout["reward_log"],
        "timed_stages": tuple(layout["timed_stages"]),
        "guarded": tuple(layout["guarded_prefixes"]),
        "t_f1": bound["t_f1"],
        "t_loc": bound["t_loc"],
        "f1_chance": bound["f1_chance"],
        "loc_chance": bound["loc_chance"],
        "neutral_band": bound["neutral_band"],
        "sibling_gap_cap": bound["sibling_gap_cap"],
        "long_min_steps": bound["long_solution_min_steps"],
        "long_min_index": bound["long_solution_min_first_error_index"],
        "long_floor": bound["long_solution_floor"],
        "answer_floor": bound["correct_answer_bad_step_floor"],
        "sub_gate_ceiling": bound["sub_gate_ceiling"],
        "gate_value": bound["gate_value"],
        "log_rate_tolerance": bound["log_rate_tolerance"],
        "log_elapsed_tolerance": bound["log_elapsed_tolerance_fraction"],
    }

    # EVERY compiled item carries a written body. The generic obligation lookup that used to stand
    # here is gone: it read a run-record key nothing writes, so any item falling through to it
    # graded nothing at all and said so in no report. Refuse instead of falling through.
    bodies = dict(BODIES)
    for it in g["items"]:
        if it["mode"] == "compiled" and it["id"] not in bodies:
            raise SystemExit("AELLO-C6-S2: no body written for compiled item %r; the generator "
                             "refuses rather than emitting a check that consults nothing"
                             % it["id"])
    orphans = sorted(set(bodies) - set(i["id"] for i in g["items"]))
    if orphans:
        raise SystemExit("AELLO-C6-S2: bodies written for items the grounding does not carry: %s"
                         % orphans)

    # The outcome check must SAY the slot is unmeasurable before it reads anything at all. If it
    # reads first, an absent artifact reports as an ordinary failure and the verifier then says
    # gradeable=true with r_det=0.0, collapsing two different claims into one.
    statements = [ln.strip() for ln in bodies[outcome_id].splitlines()
                  if ln.strip() and not ln.strip().startswith("#")]
    if not statements or statements[0] != REQUIRE_FIRST:
        raise SystemExit("AELLO-C6-S2: %r must call require_measured as its first statement, "
                         "before it reads any submitted byte" % outcome_id)

    tests_dir = os.path.join(BUNDLE, "tests")
    os.makedirs(tests_dir, exist_ok=True)

    # solution/TRUTH.md and solution/rubrics.json are PRIVATE_CARRIERS: seed/identity.py plants a
    # canary block into them at freeze, and canary normalisation is what keeps planting from
    # moving identity. A generator that rewrote them plainly would DROP the planted tripwire, and
    # the next content_hash would differ from the frozen one. So the planted block is carried
    # across the regeneration rather than recreated.
    truth_path = os.path.join(HERE, "TRUTH.md")
    truth = build_truth(g, TITLE).rstrip("\n") + "\n"
    keep = None
    if os.path.exists(truth_path):
        import re as _re
        m = _re.search(r"<!-- AELLO-CANARY-BLOCK.*?-->\n?", open(truth_path).read(), _re.S)
        keep = m.group(0) if m else None
    with open(truth_path, "w") as fh:
        fh.write(truth + ("\n" + keep if keep else ""))

    rub_path = os.path.join(HERE, "rubrics.json")
    rub = build_rubrics(g, ITEM_KEYS)
    if os.path.exists(rub_path):
        try:
            prev = json.load(open(rub_path))
            if "canary" in prev:
                rub["canary"] = prev["canary"]
        except Exception:
            pass
    with open(rub_path, "w") as fh:
        json.dump(rub, fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "rubrics.json"), "w") as fh:
        json.dump(build_rubrics(g, ITEM_KEYS), fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "test_output.py"), "w") as fh:
        # The tail arrives FINAL and UNSUBSTITUTED. It carries percent formatting of its own
        # inside the emitted helpers, so formatting it a second time raises TypeError.
        fh.write(build_tests(g, PRELUDE % subst, bodies) + TAIL)
    with open(os.path.join(tests_dir, "constants.json"), "w") as fh:
        json.dump(g["constants"], fh, indent=1, sort_keys=True)
        fh.write("\n")
    # ORDER MATTERS. `with open(path, "w")` truncates BEFORE its body's arguments are evaluated,
    # so calling read_identity() inside the with-statement reads the file this line just emptied
    # and writes nulls over the frozen identity. Read first, then open.
    prov = build_provenance(g, read_identity(HERE))
    with open(os.path.join(HERE, "provenance.yaml"), "w") as fh:
        # MATCH seed/build/screen_bind.py and the frozen generators exactly: sort_keys=True,
        # default_flow_style=False, width=100. The screen writes this carrier after the freeze,
        # so a generator using a different dump convention reorders the keys on the next
        # regeneration and reports as drift even though no value changed.
        yaml.safe_dump(prov, fh, sort_keys=True, default_flow_style=False, width=100,
                       allow_unicode=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
