"""Derivation for AELLO-C8-S7: every canonical artifact descends from solution/grounding.yaml.

Two quantities are bound to one forward pass here -- top-1 keyword accuracy over a balanced 35-way
Speech Commands split, and the wall clock of each single inference -- so the compiled checks are
about keeping those two measurements on the SAME inference as much as they are about either
number. The corpus facts they read (the pinned keyword roster, the balanced graded count, the
utterance length, the per-utterance latency bound, the declarable front-end envelope, the vendored
background clips) live in grounding.yaml's corpus_layout block and are substituted into the
emitted module, so no check carries a bound a reader of this file cannot find in the grounding.

Wired through seed/build/generator_common.py, which carries the five slot-agnostic functions
verified byte-for-byte against the three frozen generators. build_provenance stays here, per
family, for the reason recorded in that module.
"""
import json
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
# generator_common.py is VENDORED beside this file, not reached for outside the bundle. A staged
# tree could resolve seed/stage/<slug>/../../build; a DELIVERED tree at dataset/<uuid>/ cannot,
# and reaching outside would make the delivered bundle non-self-contained -- it would import in
# the stage and fail everywhere it actually ships.

SLOT_ID = 'AELLO-C8-S7'
TITLE = "# AELLO-C8-S7 -- what this task actually tests"
ITEM_KEYS = ('id', 'dimension', 'weight', 'evaluation_target', 'criterion', 'judgment', 'knockout',
             'mode')
ITEM_SCHEMA = frozenset(ITEM_KEYS + ('outcome_class',))
OUTCOME_CLASSES = frozenset(("EFFECT", "INVARIANT", "ABSENCE", "VALUE"))
RAMP = ("floor", "knee", "dichotomizing_threshold", "reward_gate_pass_threshold")
REQUIRE_FIRST = 'c = require_measured("floor", "knee", "dichotomizing_threshold")'
# The six recordings in the release's _background_noise_ directory. Named here as well as in the
# grounding so the generator can refuse a roster that has drifted from the corpus it describes.
VENDORED_NOISE_CLIPS = frozenset(("doing_the_dishes", "dude_miaowing", "exercise_bike",
                                  "pink_noise", "running_tap", "white_noise"))
FRONT_END_RANGES = ("window_samples", "hop_samples", "mel_bands")


def read_identity(here):
    """Identity is an INPUT: the freeze computes it over the hashed tree and binds it into the
    carrier, which is hash-excluded, so reading it back keeps generation acyclic."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        if isinstance(doc.get("identity"), dict):
            return doc["identity"]
    return {"canonical_content_hash": None, "uuid": None,
            "normalization_domain": "aello.canary.norm/v1",
            "derivation": "uuid5(FORGE_TASK_NAMESPACE, canonical_content_hash)"}


def read_screening(here):
    """The screening instant and result are MEASURED OVER the frozen tree, so they are read back
    the way identity is; the carrier is hash-excluded, so binding them moves nothing."""
    path = os.path.join(here, "provenance.yaml")
    if os.path.exists(path):
        doc = yaml.safe_load(open(path)) or {}
        got = {k: doc[k] for k in ("screening_measured_at", "screening_expires_at",
                                   "screening_result") if k in doc}
        if got:
            return got
    return {"screening_measured_at": None, "screening_expires_at": None,
            "screening_result": None}


def load_grounding():
    with open(os.path.join(HERE, "grounding.yaml")) as fh:
        return yaml.safe_load(fh)


# --------------------------------------------------------------------------------------------
# The emitted checker module. PRELUDE is percent-substituted from corpus_layout, so it carries no
# literal percent sign of its own. TAIL is not substituted at all.
# --------------------------------------------------------------------------------------------

PRELUDE = '''"""Compiled checks for %(slot_id)s. GENERATED by solution/recompute.py. DO NOT HAND-EDIT.

This slot grades one forward pass against two quantities at once: which of 35 keywords it decided,
and how long that single decision took. The checks below establish that the decisions are
well-formed and mean the keywords the roster pins, that every one of the graded inferences was
timed by the harness rather than by the process being timed, that the gate over those timings is
the maximum the instruction publishes and not a mean that hides one slow inference, and that the
front end which was timed is the front end which was scored. Every check runs against delivered
bytes and references no unmeasured quantity, except %(outcome_id)s, which raises ConstantUnmeasured
while tests/constants.json carries nulls.
"""
import hashlib
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.dirname(HERE)
SUBMISSION = %(path)r

# The corpus layout, from solution/grounding.yaml. The graded utterances are agent-visible and
# unlabelled because inference has to run over them and the harness has to time that inference on
# the same bytes; their keyword labels are verifier-side only.
TRAIN_AUDIO = os.path.join(BUNDLE, %(train_audio)r)
GRADED_AUDIO = os.path.join(BUNDLE, %(graded_audio)r)
KEYWORD_INDEX_FILE = os.path.join(BUNDLE, %(keyword_index_file)r)
GRADED_LABELS = os.path.join(BUNDLE, %(graded_labels)r)
RUN_RECORD = os.path.join(BUNDLE, %(run_record)r)

# The 35 keyword folders of Speech Commands v0.02 in lexicographic order. Class index 0 is
# backward and class index 34 is zero; a model built against any other ordering emits a vector of
# in-range integers that scores near one in thirty-five and looks like a modelling failure.
KEYWORD_ROSTER = %(keyword_roster)s
KEYWORD_COUNT = %(keyword_count)r
UTTERANCES_PER_KEYWORD = %(utterances_per_keyword)r
GRADED_UTTERANCE_COUNT = %(graded_utterance_count)r
BALANCED_KEYWORD_SHARE = 1.0 / KEYWORD_COUNT
MAX_KEYWORD_SHARE = %(max_single_keyword_share)r

SAMPLE_RATE_HZ = %(sample_rate_hz)r
UTTERANCE_SAMPLES = %(utterance_samples)r
LATENCY_BOUND_MS = %(latency_bound_ms)r
LATENCY_GATE_STATISTIC = %(latency_gate_statistic)r
ADMITTED_LATENCY_SOURCES = %(admitted_latency_sources)r
REJECTED_LATENCY_SOURCES = %(rejected_latency_sources)r
AGENT_TIMING_FIELDS = %(agent_timing_fields)r

FRONT_END_KEYS = %(front_end_keys)r
WINDOW_RANGE = %(window_range)r
HOP_RANGE = %(hop_range)r
MEL_RANGE = %(mel_range)r

NOISE_CLIPS = %(noise_clips)r
NOISE_SNR_RANGE = %(noise_snr_range)r
TRAINING_SPLIT_TOKENS = %(training_split_tokens)r
BUDGET_KEYS = %(budget_keys)r
GUARDED_WRITES = %(guarded_writes)r

CHECKS = []


class ConstantUnmeasured(Exception):
    """Raised when a check needs a ramp constant that Phase 0 deliberately left null."""


def check(id, weight, knockout, kind):
    def deco(fn):
        CHECKS.append({"id": id, "weight": weight, "knockout": knockout, "kind": kind, "fn": fn})
        return fn
    return deco


def constants():
    with open(os.path.join(HERE, "constants.json")) as fh:
        return json.load(fh)


def require_measured(*names):
    c = constants()
    missing = [n for n in names if c.get(n) is None]
    if missing:
        raise ConstantUnmeasured(
            "%(slot_id)s: " + ", ".join(missing) + " are null. Phase 0 authors no measurement; "
            "the Phase 2 measurement wave writes these and this check becomes gradeable then.")
    return c


def evidence(**kw):
    return {"evaluation_target": kw.pop("target", "submitted_artifact"), "values": kw}
'''


TAIL = r'''

# ------------------------------------------------------------------------------------------
# Reading the delivered bytes: one label vector, one run record, and the two corpus archives the
# verifier mounts. An absence is reported under its own reason and never guessed at, and no read
# here is allowed to take the verifier down -- a submission that will not open is a finding about
# the submission, not a traceback in the checker.
# ------------------------------------------------------------------------------------------

def load_submission():
    """The keyword decision vector: one integer per graded utterance."""
    import numpy as np
    array = np.load(SUBMISSION, allow_pickle=False)
    if array.dtype == object:
        raise ValueError("an object array is not a keyword decision vector")
    return array


def describe(array):
    return "%s%s" % (array.dtype, array.shape)


def integral(array):
    """True when the dtype itself is integral. A float vector of whole numbers is not.

    The deliverable is a decision, and a decision has no fractional part. Accepting float64
    because its entries happen to be whole would also accept a posterior row that was rounded on
    its way out, which is a different object with a different failure mode.
    """
    return array.dtype.kind in ("i", "u")


def label_rows(array):
    """The decisions as a flat list of Python ints, whatever shape or dtype they arrived in."""
    return [int(value) for value in array.ravel().tolist()]


def keyword_name(index):
    """The word a class index means, or a legible placeholder when it means none of them."""
    if 0 <= index < len(KEYWORD_ROSTER):
        return KEYWORD_ROSTER[index]
    return "index_" + str(index)


def keyword_histogram(array):
    """class index -> how many graded utterances were decided that way."""
    counts = {}
    for value in label_rows(array):
        counts[value] = counts.get(value, 0) + 1
    return counts


def graded_utterance_ids():
    """The graded roster in its pinned order, or None when the archive has not landed.

    None is not an empty roster. Every caller distinguishes the two: a check that cannot find the
    roster falls back to the pinned COUNT and says in its evidence which source it used, rather
    than passing because it had nothing to compare against.
    """
    if not os.path.exists(GRADED_AUDIO):
        return None
    try:
        import numpy as np
        archive = np.load(GRADED_AUDIO, allow_pickle=False)
        if "utterance_id" not in archive.files:
            return None
        return [str(u) for u in archive["utterance_id"].tolist()]
    except Exception:
        return None


def graded_truth():
    """(utterance ids, keyword indices) from the private labels, or None when they are absent."""
    if not os.path.exists(GRADED_LABELS):
        return None
    try:
        import numpy as np
        archive = np.load(GRADED_LABELS, allow_pickle=False)
        return ([str(u) for u in archive["utterance_id"].tolist()],
                [int(v) for v in archive["y"].tolist()])
    except Exception:
        return None


def run_record():
    """What the graded run and the harness recorded about the run.

    The agent writes most of this file, so it can be absent, truncated, or not JSON at all. Every
    one of those is an empty record here, and each check then reports its own missing-declaration
    reason instead of raising.
    """
    if not os.path.exists(RUN_RECORD):
        return {}
    try:
        with open(RUN_RECORD) as handle:
            doc = json.load(handle)
    except Exception:
        return {}
    return doc if isinstance(doc, dict) else {}


def numeric(value):
    """A finite float, or None for anything that is not one -- including bools and NaN.

    A bool is an int in Python, and True would otherwise read as a latency of one millisecond.
    """
    if isinstance(value, bool) or value is None:
        return None
    try:
        out = float(value)
    except (TypeError, ValueError):
        return None
    if out != out or out in (float("inf"), float("-inf")):
        return None
    return out


def token(value):
    """A declared vocabulary word, normalised the one way every roster here is written."""
    return str(value).strip().lower().replace("-", "_").replace(" ", "_")


def digest_field(record, key):
    """A recorded digest, lowercased and stripped, or the empty string when it is absent."""
    return str(record.get(key) or "").strip().lower()


# ------------------------------------------------------------------------------------------
# The latency side. Every millisecond a check reads comes from the harness's own series; nothing
# below consults a duration the graded process reported about itself.
# ------------------------------------------------------------------------------------------

def harness_latencies():
    """utterance id -> the HARNESS's measured wall clock for that one inference, as recorded.

    Red line 2 is measuring latency with a clock the agent controls, so the graded quantity is
    read from the harness's record and an agent-supplied series is never substituted for it.
    """
    got = run_record().get("harness_utterance_latency_ms")
    if not isinstance(got, dict):
        return {}
    return dict((str(k), v) for k, v in got.items())


def readable_latencies():
    """The harness series with every unreadable entry dropped, so a caller can count both."""
    out = {}
    for utterance, value in harness_latencies().items():
        milliseconds = numeric(value)
        if milliseconds is not None:
            out[utterance] = milliseconds
    return out


def gate_statistics():
    """(worst, mean, utterances over the bound) recomputed from the harness series.

    The maximum and the mean are computed side by side on purpose. The gate is the maximum; the
    mean is carried so the check that reads this can name the substitution when a run's own
    verdict agrees with the mean and disagrees with the maximum.
    """
    series = readable_latencies()
    if not series:
        return None, None, []
    values = list(series.values())
    over = sorted(u for u, ms in series.items() if ms > LATENCY_BOUND_MS)
    return max(values), sum(values) / float(len(values)), over


# ------------------------------------------------------------------------------------------
# The declaration side: the front end, its digest, and where a write landed.
# ------------------------------------------------------------------------------------------

def front_end_block():
    """The declared front-end configuration, or {} when the run declared none."""
    block = run_record().get("front_end")
    return block if isinstance(block, dict) and block else {}


def front_end_digest(block):
    """sha256 over the canonical form of a front-end block.

    Recomputed here rather than taken from the record, because the whole point of the two
    recorded digests is that they can be checked against the configuration they claim to cover.
    """
    canonical = json.dumps(dict((str(k), block[k]) for k in sorted(block)),
                           sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def recomputed_frames(window, hop):
    """Frames a one-second utterance yields at this window and hop, or None when it yields none."""
    if window < 1 or hop < 1 or window > UTTERANCE_SAMPLES:
        return None
    return 1 + (UTTERANCE_SAMPLES - window) // hop


def positive_frequency_bins(window):
    """The bin count a real FFT of this window returns, which caps the mel filterbank."""
    return window // 2 + 1


def guarded_root(path):
    """The guarded root a written path lands in, or None when it lands outside all of them."""
    flat = "/" + str(path).replace("\\", "/").lstrip("./").lstrip("/")
    for root in GUARDED_WRITES:
        needle = root if root.startswith("/") else "/" + root
        if needle in flat:
            return root
    return None


def artifact_digest():
    """sha256 of the delivered label vector, or None when nothing was delivered."""
    if not os.path.exists(SUBMISSION):
        return None
    with open(SUBMISSION, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def measure():
    """Top-1 keyword accuracy over the private split, gated per utterance before it is counted.

    The gate is applied FIRST and it is absolute: one inference above the bound returns 0.0, not a
    proportional penalty and not the accuracy that inference helped earn. That ordering is the
    whole shape of this slot's reward -- accuracy bought by exceeding the per-utterance budget is
    worth nothing, because a keyword spotter that answers late has not answered.

    Three conditions raise ConstantUnmeasured rather than returning a number, and all three are
    statements about this bundle rather than about the agent: no harness timings, no landed
    labels, and a landed roster whose order disagrees with the labels. Returning 0.0 for any of
    them would report that the agent scored nothing when the truth is that nothing was measurable.
    """
    declared = harness_latencies()
    if not declared:
        raise ConstantUnmeasured("the harness recorded no per-utterance latency, so the gate this "
                                 "metric applies before it counts anything cannot be evaluated")
    series = readable_latencies()
    if len(series) != len(declared):
        raise ConstantUnmeasured("the harness latency series carries an entry that is not a "
                                 "finite number of milliseconds")
    if max(series.values()) > LATENCY_BOUND_MS:
        return 0.0
    truth = graded_truth()
    if truth is None:
        raise ConstantUnmeasured("the private keyword labels have not landed under tests/heldout")
    utterances, gold = truth
    roster = graded_utterance_ids()
    if roster is not None and roster != utterances:
        raise ConstantUnmeasured("the landed graded roster and the private labels disagree on "
                                 "utterance order; that is a corpus landing to repair, not a "
                                 "score to report")
    try:
        predicted = label_rows(load_submission())
    except Exception:
        return 0.0
    if len(predicted) != len(gold):
        return 0.0
    hits = 0
    for guess, answer in zip(predicted, gold):
        if guess == answer:
            hits += 1
    return hits / float(len(gold))
'''


# --------------------------------------------------------------------------------------------
# BODIES. Every compiled item carries one, written for this slot against this slot's bytes. There
# is no generic obligation lookup behind them: the fallback that used to stand here read a
# run-record key nothing writes, so an item that fell through to it consulted nothing at all and
# still reported a verdict.
# --------------------------------------------------------------------------------------------

BODIES = {
    "keyword_label_vector_lands": '''
    if not os.path.exists(SUBMISSION):
        return False, evidence(reason="submission_missing", path=SUBMISSION)
    try:
        labels = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    if labels.ndim != 1:
        # A 35-wide score matrix is not a decision. Taking the argmax here would grade a keyword
        # choice the agent never made, and would do it silently.
        return False, evidence(reason="not_a_one_dimensional_label_vector",
                               shape=describe(labels))
    if not integral(labels):
        return False, evidence(reason="labels_are_not_of_integer_dtype", shape=describe(labels))
    return True, evidence(path=SUBMISSION, shape=describe(labels), rows=int(labels.size))''',

    "one_label_per_graded_utterance": '''
    try:
        labels = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    rows = int(labels.size)
    roster = graded_utterance_ids()
    expected = GRADED_UTTERANCE_COUNT if roster is None else len(roster)
    # Length is CHECKED, never repaired. Truncating to the label length would grade a prefix of
    # the submission and reward a run that decided a fraction of the split; padding would grade
    # rows nobody wrote. Short and long are separate reasons because they are separate mistakes.
    ok = rows == expected
    return ok, evidence(rows=rows, expected=expected,
                        utterances_per_keyword=UTTERANCES_PER_KEYWORD,
                        roster_source="pinned_layout" if roster is None else "landed_archive",
                        reason=None if ok else ("fewer_rows_than_graded_utterances"
                                                if rows < expected
                                                else "more_rows_than_graded_utterances"))''',

    "labels_inside_the_thirty_five_keyword_index": '''
    try:
        labels = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    distinct = sorted(set(label_rows(labels)))
    if not distinct:
        return False, evidence(reason="empty_label_vector", keyword_count=KEYWORD_COUNT)
    outside = [v for v in distinct if v < 0 or v >= KEYWORD_COUNT]
    # An index of 35, or of -1, names no keyword in this formulation. The twelve-class reading of
    # this corpus adds a silence class and an unknown bucket; both are out of domain here, and an
    # out-of-domain index is reported rather than clipped into range.
    ok = not outside
    return ok, evidence(distinct_keywords=len(distinct), keyword_count=KEYWORD_COUNT,
                        outside_index=outside[:12],
                        lowest=distinct[0], highest=distinct[-1],
                        reason=None if ok else "label_outside_the_keyword_index")''',

    "class_index_maps_to_the_pinned_keyword_roster": '''
    declared = run_record().get("keyword_index")
    if declared is None:
        return False, evidence(target="run_record", reason="no_keyword_index_declared")
    if not isinstance(declared, list):
        return False, evidence(target="run_record", reason="keyword_index_is_not_a_list",
                               declared=str(declared)[:120])
    words = [token(w) for w in declared]
    if len(words) != KEYWORD_COUNT:
        return False, evidence(target="run_record", declared_count=len(words),
                               expected_count=KEYWORD_COUNT,
                               reason="keyword_index_is_not_thirty_five_words")
    misplaced = [{"index": i, "declared": got, "pinned": want}
                 for i, (got, want) in enumerate(zip(words, KEYWORD_ROSTER)) if got != want]
    ok = not misplaced
    # permutation_only separates the two failures that look identical in the artifact: the same
    # 35 words in a different order (a label encoder built by walking the corpus), and different
    # words entirely (a model built to the twelve-class formulation).
    return ok, evidence(target="run_record", misplaced=misplaced[:8],
                        misplaced_count=len(misplaced),
                        permutation_only=(not ok) and sorted(words) == sorted(KEYWORD_ROSTER),
                        reason=None if ok else "class_index_is_not_the_pinned_roster")''',

    "no_keyword_claims_more_than_the_balanced_share_cap": '''
    try:
        labels = load_submission()
    except Exception as exc:
        return False, evidence(reason="submission_malformed", error=str(exc))
    counts = keyword_histogram(labels)
    rows = sum(counts.values())
    if not rows:
        return False, evidence(reason="empty_label_vector")
    modal_index = max(sorted(counts), key=lambda index: counts[index])
    share = counts[modal_index] / float(rows)
    ok = share <= MAX_KEYWORD_SHARE
    return ok, evidence(rows=rows, distinct_keywords=len(counts), modal_index=modal_index,
                        modal_keyword=keyword_name(modal_index), modal_rows=counts[modal_index],
                        modal_share=round(share, 6),
                        balanced_share=round(BALANCED_KEYWORD_SHARE, 6),
                        share_cap=MAX_KEYWORD_SHARE,
                        reason=None if ok else "decisions_collapsed_onto_one_keyword")''',

    "every_graded_utterance_timed_by_the_harness": '''
    timings = harness_latencies()
    if not timings:
        return False, evidence(target="run_record", reason="no_harness_latency_series")
    roster = graded_utterance_ids()
    if roster is None:
        # The roster archive has not landed. The pinned count is still a real assertion, and the
        # evidence says which source was used rather than letting the absence read as a pass.
        ok = len(timings) == GRADED_UTTERANCE_COUNT
        return ok, evidence(target="run_record", timed=len(timings),
                            expected=GRADED_UTTERANCE_COUNT, roster_source="pinned_layout",
                            reason=None if ok else "latency_series_does_not_cover_the_roster")
    untimed = [u for u in roster if u not in timings]
    off_roster = sorted(set(timings) - set(roster))
    unreadable = sorted(u for u in roster if u in timings and numeric(timings[u]) is None)
    ok = not untimed and not off_roster and not unreadable
    return ok, evidence(target="run_record", timed=len(timings), roster=len(roster),
                        untimed=untimed[:8], untimed_count=len(untimed),
                        timed_but_not_graded=off_roster[:8], unreadable=unreadable[:8],
                        roster_source="landed_archive",
                        reason=None if ok else ("graded_utterance_never_timed" if untimed
                                                else "latency_reported_for_an_ungraded_utterance"
                                                if off_roster else "latency_is_not_a_number"))''',

    "latency_gate_is_a_per_utterance_maximum_not_a_mean": '''
    worst, mean, over = gate_statistics()
    if worst is None:
        return False, evidence(target="run_record", reason="no_readable_harness_latency")
    inside = not over
    declared = run_record().get("latency_gate_passed")
    if declared is None:
        return False, evidence(target="run_record", worst_ms=worst, mean_ms=mean,
                               bound_ms=LATENCY_BOUND_MS, reason="no_gate_verdict_declared")
    agrees = bool(declared) is inside
    ok = agrees and inside
    # The named case: the mean clears the bound, the maximum does not, and the run says it
    # passed. That is the substitution a per-utterance gate exists to refuse, and it is reported
    # under its own name so a reviewer sees the arithmetic rather than a bare failure.
    if ok:
        reason = None
    elif bool(declared) and not inside and mean <= LATENCY_BOUND_MS:
        reason = "gate_taken_on_the_mean"
    elif not agrees:
        reason = "gate_verdict_contradicts_the_measured_maximum"
    else:
        reason = "an_inference_exceeded_the_per_utterance_bound"
    return ok, evidence(target="run_record", statistic=LATENCY_GATE_STATISTIC,
                        worst_ms=round(worst, 6), mean_ms=round(mean, 6),
                        bound_ms=LATENCY_BOUND_MS, over_bound=len(over), first_over=over[:8],
                        declared_pass=bool(declared), recomputed_pass=inside, reason=reason)''',

    "latency_measured_by_the_harness_clock_not_the_agents": '''
    record = run_record()
    source = token(record.get("latency_source"))
    if source in REJECTED_LATENCY_SOURCES:
        return False, evidence(target="run_record", latency_source=source,
                               reason="latency_taken_from_a_clock_the_agent_controls")
    if source not in ADMITTED_LATENCY_SOURCES:
        return False, evidence(target="run_record", latency_source=source,
                               admitted=list(ADMITTED_LATENCY_SOURCES),
                               reason="unrecognised_latency_source")
    if not harness_latencies():
        # The declaration names the harness timer and the harness series is not there. What the
        # record describes is a measurement nothing in this tree can find.
        return False, evidence(target="run_record", latency_source=source,
                               reason="no_harness_latency_series")
    offered = sorted(field for field in AGENT_TIMING_FIELDS if field in record)
    ok = not offered
    # A duration reported by the process being timed is not a measurement of that process: a
    # batch mean is not the per-utterance cost, and a timer opened after the front end has run
    # charges nothing for the front end. Nothing in this checker reads an agent millisecond.
    return ok, evidence(target="run_record", latency_source=source,
                        agent_timing_fields=offered,
                        reason=None if ok else "agent_reported_timings_offered_for_grading")''',

    "timed_front_end_is_the_scoring_front_end": '''
    record = run_record()
    block = front_end_block()
    if not block:
        return False, evidence(target="run_record", reason="no_front_end_declared")
    recomputed = front_end_digest(block)
    at_timing = digest_field(record, "front_end_digest_at_timing")
    at_prediction = digest_field(record, "front_end_digest_at_prediction")
    if not at_timing or not at_prediction:
        return False, evidence(target="run_record", recomputed=recomputed,
                               at_timing=at_timing, at_prediction=at_prediction,
                               reason="front_end_digest_missing_on_one_of_the_two_passes")
    same_pass = at_timing == at_prediction
    declared_truthfully = at_prediction == recomputed
    ok = same_pass and declared_truthfully
    # This slot binds a latency gate and an accuracy metric to ONE inference, and the cheapest
    # dishonest way to satisfy both is to satisfy them separately: time a 20-band, hop-320 front
    # end and score an 80-band, hop-64 one. Two digests plus a recomputation closes that.
    if ok:
        why = None
    elif not same_pass:
        why = "timed_a_different_front_end_than_it_scored"
    else:
        why = "recorded_digest_is_not_the_declared_block"
    return ok, evidence(target="run_record", at_timing=at_timing, at_prediction=at_prediction,
                        recomputed=recomputed, reason=why,
                        declared_front_end=dict((k, block[k]) for k in sorted(block)))''',

    "front_end_frame_count_follows_from_window_and_hop": '''
    block = front_end_block()
    if not block:
        return False, evidence(target="run_record", reason="no_front_end_declared")
    absent = [key for key in FRONT_END_KEYS if key not in block]
    if absent:
        return False, evidence(target="run_record", missing=absent,
                               reason="front_end_declaration_incomplete")
    values = dict((key, numeric(block[key])) for key in FRONT_END_KEYS)
    unreadable = sorted(key for key, value in values.items() if value is None)
    if unreadable:
        return False, evidence(target="run_record", unreadable=unreadable,
                               reason="front_end_value_is_not_a_number")
    window, hop = int(values["window_samples"]), int(values["hop_samples"])
    mel, frames = int(values["mel_bands"]), int(values["frames_per_utterance"])
    findings = []
    if int(values["sample_rate_hz"]) != SAMPLE_RATE_HZ:
        findings.append({"field": "sample_rate_hz", "declared": int(values["sample_rate_hz"]),
                         "pinned": SAMPLE_RATE_HZ, "reason": "not_the_corpus_sample_rate"})
    for field, got, span in (("window_samples", window, WINDOW_RANGE),
                             ("hop_samples", hop, HOP_RANGE),
                             ("mel_bands", mel, MEL_RANGE)):
        if got < span[0] or got > span[1]:
            findings.append({"field": field, "declared": got, "admitted": list(span),
                             "reason": "outside_the_declared_envelope"})
    if hop > window:
        # Audio between the end of one frame and the start of the next is never read, and a
        # keyword onset can land entirely inside that gap.
        findings.append({"field": "hop_samples", "declared": hop, "window_samples": window,
                         "reason": "audio_between_frames_is_never_read"})
    bins = positive_frequency_bins(window)
    if mel > bins:
        findings.append({"field": "mel_bands", "declared": mel, "positive_frequency_bins": bins,
                         "reason": "more_mel_bands_than_spectrum_bins"})
    expected = recomputed_frames(window, hop)
    if expected is None:
        findings.append({"field": "window_samples", "declared": window,
                         "utterance_samples": UTTERANCE_SAMPLES,
                         "reason": "window_does_not_fit_inside_the_utterance"})
    elif frames != expected:
        findings.append({"field": "frames_per_utterance", "declared": frames,
                         "recomputed": expected,
                         "reason": "frame_count_does_not_follow_from_window_and_hop"})
    ok = not findings
    return ok, evidence(target="run_record", front_end_findings=findings,
                        utterance_samples=UTTERANCE_SAMPLES,
                        reason=None if ok else "front_end_declaration_is_not_realisable")''',

    "graded_audio_and_checker_tree_unwritten": '''
    record = run_record()
    # The harness's own list is the authority and the run's declaration corroborates it. A
    # post-hoc scan is not used at all: it cannot separate a write made during the graded run
    # from one made before it.
    landed = {}
    for path in list(record.get("guarded_paths_touched", [])) + list(record.get("paths_written",
                                                                                [])):
        root = guarded_root(path)
        if root is not None:
            landed.setdefault(root, set()).add(str(path))
    before = digest_field(record, "graded_audio_digest_before")
    after = digest_field(record, "graded_audio_digest_after")
    if not before or not after:
        return False, evidence(target="submitted_source",
                               guarded_roots_written=sorted(landed),
                               reason="no_graded_audio_digest_recorded")
    remixed = before != after
    ok = not landed and not remixed
    # On an audio task red line 1 has a specific shape: re-mixing the graded utterances at a
    # friendlier signal-to-noise ratio, or trimming them below the second, raises accuracy and
    # lowers latency at once by changing the input rather than the model.
    return ok, evidence(target="submitted_source",
                        writes_by_guarded_root=dict((root, sorted(paths)[:4])
                                                    for root, paths in sorted(landed.items())),
                        graded_audio_remixed=remixed, digest_before=before, digest_after=after,
                        reason=None if ok else ("graded_utterances_were_rewritten" if remixed
                                                else "wrote_into_a_guarded_root"))''',

    "noise_augmentation_confined_to_the_training_split": '''
    augmentation = run_record().get("augmentation")
    if augmentation is None:
        return False, evidence(target="run_record", reason="no_augmentation_declared")
    if not isinstance(augmentation, dict):
        return False, evidence(target="run_record", reason="augmentation_is_not_a_mapping",
                               declared=str(augmentation)[:120])
    applied = token(augmentation.get("applied_to"))
    clips = [token(c).replace(".wav", "") for c in (augmentation.get("background_clips") or [])]
    if not clips:
        # A run that does not use the lever declares that it does not. Silence about a lever and
        # a declaration that it was left alone are different statements.
        ok = applied in tuple(TRAINING_SPLIT_TOKENS) + ("none",)
        return ok, evidence(target="run_record", background_clips=[], applied_to=applied,
                            reason=None if ok else "noise_mixed_outside_the_training_split")
    findings = []
    if applied not in TRAINING_SPLIT_TOKENS:
        findings.append({"field": "applied_to", "declared": applied,
                         "admitted": list(TRAINING_SPLIT_TOKENS),
                         "reason": "noise_mixed_outside_the_training_split"})
    unvendored = sorted(set(clips) - set(NOISE_CLIPS))
    if unvendored:
        findings.append({"field": "background_clips", "unrecognised": unvendored,
                         "vendored": list(NOISE_CLIPS),
                         "reason": "clip_did_not_ship_with_the_corpus"})
    span = augmentation.get("snr_db_range") or []
    low = numeric(span[0]) if len(span) > 0 else None
    high = numeric(span[1]) if len(span) > 1 else None
    if low is None or high is None or low > high:
        findings.append({"field": "snr_db_range", "declared": str(span)[:60],
                         "reason": "snr_range_is_not_an_ordered_pair"})
    elif low < NOISE_SNR_RANGE[0] or high > NOISE_SNR_RANGE[1]:
        findings.append({"field": "snr_db_range", "declared": [low, high],
                         "admitted": list(NOISE_SNR_RANGE),
                         "reason": "snr_outside_the_published_range"})
    ok = not findings
    return ok, evidence(target="run_record", augmentation_findings=findings,
                        background_clips=sorted(set(clips)), applied_to=applied,
                        reason=None if ok else "background_mixing_declaration_unsound")''',

    "replay_reproduces_the_label_vector_under_the_recorded_front_end": '''
    record = run_record()
    replay = record.get("replay")
    if not isinstance(replay, dict) or not replay:
        return False, evidence(target="submitted_source", reason="replay_unrecorded")
    delivered = artifact_digest()
    if delivered is None:
        return False, evidence(target="submitted_source", reason="submission_missing")
    replayed = digest_field(replay, "artifact_sha256")
    if not replayed:
        return False, evidence(target="submitted_source", graded=delivered,
                               reason="replay_recorded_no_artifact_digest")
    graded_front_end = digest_field(record, "front_end_digest_at_prediction")
    replay_front_end = digest_field(replay, "front_end_digest")
    labels_reproduce = replayed == delivered
    # Keyword decisions are deterministic under a fixed seed even though the milliseconds that
    # gate them are not, so the labels are required bit-for-bit and no timing is compared here.
    # A replay under a different front end reproduces the answer without reproducing the run.
    same_front_end = bool(graded_front_end) and replay_front_end == graded_front_end
    ok = labels_reproduce and same_front_end
    return ok, evidence(target="submitted_source", graded=delivered, replay=replayed,
                        graded_front_end=graded_front_end, replay_front_end=replay_front_end,
                        reason=None if ok else ("label_vector_is_not_reproducible"
                                                if not labels_reproduce
                                                else "replayed_under_a_different_front_end"))''',

    "budget_declared_in_training_seconds_and_timed_utterances": '''
    declaration = run_record().get("agent_budget_declaration")
    if declaration is None:
        return False, evidence(target="run_record", reason="no_agent_declaration")
    try:
        declared = (json.loads(declaration) if isinstance(declaration, str)
                    else dict(declaration))
    except Exception as exc:
        return False, evidence(target="run_record", reason="declaration_unparseable",
                               error=str(exc))
    absent = [key for key in BUDGET_KEYS if key not in declared]
    not_a_count = [key for key in BUDGET_KEYS if key in declared
                   and (numeric(declared[key]) is None or numeric(declared[key]) < 0)]
    ok = not absent and not not_a_count
    # inference_utterances_timed is the key this slot adds: latency here is a property of the
    # design rather than of the run, and a front end tuned against a dozen clips has not been
    # measured against a gate it has to clear on every one of the graded utterances.
    return ok, evidence(target="run_record", declared=sorted(str(k) for k in declared),
                        missing=absent, not_a_count=not_a_count,
                        graded_utterances=GRADED_UTTERANCE_COUNT,
                        reason=None if ok else "budget_not_declared_in_this_slots_terms")''',

    "latency_gated_keyword_accuracy_ramp": '''
    # require_measured FIRST, before anything is read. Reading the submission before saying the
    # slot is not yet measurable lets a missing-file error mask the unmeasured signal, and the
    # verifier then reports gradeable=true with r_det=0.0 -- which asserts the agent scored zero
    # where the honest claim is that the slot cannot yet be scored at all.
    c = require_measured("floor", "knee", "dichotomizing_threshold")
    accuracy = measure()
    span = c["knee"] - c["floor"]
    s = 0.0 if span <= 0 else max(0.0, min(1.0, (accuracy - c["floor"]) / span))
    return accuracy >= c["dichotomizing_threshold"], evidence(keyword_accuracy=accuracy,
                                                              s_outcome=s)''',
}


def build_tests(g, prelude, bodies):
    """Assemble the compiled-check module. kind carries the item's own dimension."""
    chunks = [prelude]
    for raw in sorted(g["items"], key=lambda i: i["id"]):
        if raw["mode"] != "compiled":
            continue
        chunks.append('\n\n@check(id="%s", weight=%d, knockout=%s, kind="%s")\ndef test_%s():\n%s\n'
                      % (raw["id"], raw["weight"], raw["knockout"], raw["dimension"], raw["id"],
                         bodies[raw["id"]].strip("\n")))
    return "".join(chunks)


def build_truth(g, title):
    """Render solution/TRUTH.md from the frozen literals of solution/grounding.yaml."""
    n = g["truth_narrative"]
    lines = [title, "", "GENERATED SECTION. DO NOT HAND-EDIT.", "", n["opening"], "",
             "## The single most important insight", "", n["insight"], "",
             "## The ideal solve, step by step", ""]
    for i, step in enumerate(n["steps"], 1):
        lines += ["%d. **%s** %s" % (i, step["heading"], step["paragraph"]), ""]
    lines += ["## Traps that catch agents that are not thinking carefully", ""]
    lines += ["- " + t for t in n["traps"]]
    lines += ["", "---", "", "## Contract record (annex; not part of the narrative body)", "",
              "Retained under FORGE.md item 10e and Phase 2 item 7, which require this file to "
              "carry the ordered path through instruction.md with each satisfied checker "
              "identifier, and each rejected route bound to a measured known-wrong control. "
              "standards/truth-md-authoring-v1.md section 3 admits no fifth section, so this "
              "annex is a recorded deviation rather than an omission.", "", g["truth_annex"], ""]
    return "\n".join(lines) + "\n"


def build_rubrics(g, item_keys):
    """The 9g rubric carrier. The item schema is CLOSED at eight keys, so item 10f's outcome
    classification rides as a greppable prefix of the judgment rather than as a ninth key."""
    items = []
    for raw in g["items"]:
        item = {k: raw[k] for k in item_keys}
        item["judgment"] = "%s: %s" % (raw["outcome_class"], raw["judgment"])
        items.append(item)
    compiled = sum(i["weight"] for i in items if i["mode"] == "compiled")
    total = sum(i["weight"] for i in items)
    return {"$schema": "forge.rubric/v1",
            "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
            "generator": "solution/recompute.py",
            "compilation_floor": g["compilation_floor"],
            "compiled_weight_share": round(compiled / total, 6) if total else 0.0,
            "evaluation_target_vocabulary": sorted(g["evaluation_target_vocabulary"]),
            "items": sorted(items, key=lambda i: i["id"])}


def build_provenance(g, identity):
    p = g["provenance"]
    out = {
        "banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
        "generator": "solution/recompute.py from solution/grounding.yaml",
        "schema_version": "1.0",
        "slot_id": g["slot_id"],
        "identity": identity,
        "corpus": p["corpus"],
        "anchors": p["anchors"],
        "shards": p["shards"],
        "narrative": p["narrative"],
        "supersedes": p["supersedes"],
        "upstream_provenance": p["upstream_record"],
        "reward_composition": p["reward_composition"],
        "screening_interval_days": p["screening_interval_days"],
        "screening_detector_version": p["screening_detector_version"],
        "derivation_instant": p["derivation_instant"],
        "screening_roots": p["screening_roots"],
        "empty_submission_result": p["empty_submission_result"],
        "resolved_closure": p["resolved_closure"],
        "applicability": p["applicability"],
        "measurement_tier": g["measurement_tier"],
        "gradeable": g["gradeable"],
        "knee_anchor_status": g["knee_anchor_status"],
        "corpus_status": g["corpus_layout"]["corpus_status"],
        "per_utterance_latency_bound_ms": g["corpus_layout"]["per_utterance_latency_bound_ms"],
    }
    out.update(read_screening(HERE))
    return out


def roster_literal(words):
    """A deterministic Python literal for the pinned keyword roster, five words to a line.

    Written out of the grounding's own order rather than sorted here: the ORDER is the fact being
    pinned, and re-sorting it in the generator would quietly repair exactly the drift the check
    that reads it exists to catch.
    """
    rows = [words[i:i + 5] for i in range(0, len(words), 5)]
    return "(\n" + "".join("    " + " ".join("%r," % (w,) for w in row) + "\n"
                           for row in rows) + ")"


def validate(grounding):
    """Refuse a grounding this generator cannot honestly compile.

    Two families of problem are checked. The first is structural and applies to any slot: a closed
    item schema, one outcome item, an evaluation-target vocabulary with nothing unused in it, and
    ramp constants left null. The second is this slot's own arithmetic -- a 35-word roster in
    lexicographic order, a graded count that is the balanced product of the two counts that make
    it, a latency bound that is a positive number of milliseconds read as a maximum, a front-end
    envelope whose ranges are ordered and fit inside a one-second utterance, and a share cap that
    sits strictly between the balanced share and the whole vector. Each is checked here because a
    check emitted against a bound that contradicts the corpus is worse than no check at all.
    """
    problems = []
    items = grounding["items"]
    ids = [i["id"] for i in items]
    if len(set(ids)) != len(ids):
        problems.append("duplicate item ids: %r" % sorted(set(x for x in ids if ids.count(x) > 1)))
    for item in items:
        if frozenset(item) != ITEM_SCHEMA:
            problems.append("item %r does not carry the closed item schema" % item.get("id"))
            continue
        if item["outcome_class"] not in OUTCOME_CLASSES:
            problems.append("item %r has outcome_class %r" % (item["id"], item["outcome_class"]))
        if item["evaluation_target"] not in grounding["evaluation_target_vocabulary"]:
            problems.append("item %r evaluates %r, which the vocabulary does not admit"
                            % (item["id"], item["evaluation_target"]))
        if not isinstance(item["weight"], int) or item["weight"] <= 0:
            problems.append("item %r carries weight %r" % (item["id"], item["weight"]))
    targets = {i["evaluation_target"] for i in items}
    if "run_record" not in targets:
        problems.append("a gated slot must grade against the harness run record")
    unused = sorted(set(grounding["evaluation_target_vocabulary"]) - targets)
    if unused:
        problems.append("the vocabulary admits %s, which no item evaluates" % unused)
    outcome = [i["id"] for i in items if i["dimension"] == "outcome"]
    if len(outcome) != 1:
        problems.append("expected exactly one outcome item, found %r" % outcome)
    for name in RAMP:
        if grounding["constants"].get(name) is not None:
            problems.append("constant %r is authored at Phase 0; it is measured, not authored"
                            % name)

    layout = grounding.get("corpus_layout") or {}
    roster = list(layout.get("keyword_roster") or [])
    if len(roster) != layout.get("keyword_count") or len(set(roster)) != len(roster):
        problems.append("the keyword roster carries %d entries against a declared count of %r"
                        % (len(roster), layout.get("keyword_count")))
    if roster != sorted(roster):
        problems.append("the keyword roster is not in the lexicographic order it claims to pin")
    if any(word != word.strip().lower() for word in roster):
        problems.append("a keyword is not the lowercase folder name the corpus ships")
    per_keyword = layout.get("utterances_per_keyword")
    if not isinstance(per_keyword, int) or per_keyword <= 0:
        problems.append("utterances_per_keyword is %r; a balanced split needs a positive count"
                        % per_keyword)
    elif per_keyword * len(roster) != layout.get("graded_utterance_count"):
        problems.append("the graded count %r is not %d keywords times %d utterances"
                        % (layout.get("graded_utterance_count"), len(roster), per_keyword))
    if layout.get("class_balance_ratio") != 1.0:
        problems.append("the split is declared at ratio %r; this slot's metric is plain accuracy "
                        "and needs the 1.00:1 balance it publishes"
                        % layout.get("class_balance_ratio"))

    bound = layout.get("per_utterance_latency_bound_ms")
    if not isinstance(bound, float) or bound <= 0:
        problems.append("the per-utterance latency bound is %r; a gate needs a positive number of "
                        "milliseconds" % bound)
    if layout.get("latency_gate_statistic") != "maximum":
        problems.append("the gate statistic is %r; this slot's instruction says every inference, "
                        "and only a maximum says that" % layout.get("latency_gate_statistic"))
    overlap = sorted(set(layout.get("admitted_latency_sources") or [])
                     & set(layout.get("rejected_latency_sources") or []))
    if overlap:
        problems.append("latency source %s is both admitted and rejected" % overlap)
    if not layout.get("admitted_latency_sources"):
        problems.append("no admitted latency source; the gate would have nothing to read")
    if not layout.get("agent_timing_fields_refused"):
        problems.append("red line 2 needs the agent-timed fields it refuses named")

    rate = layout.get("sample_rate_hz")
    samples = layout.get("utterance_samples")
    if rate != samples:
        problems.append("a one-second utterance at %r Hz is %r samples, not %r"
                        % (rate, rate, samples))
    envelope = layout.get("front_end_envelope") or {}
    for field in FRONT_END_RANGES:
        span = envelope.get(field)
        if not (isinstance(span, list) and len(span) == 2
                and all(isinstance(v, int) for v in span) and 0 < span[0] <= span[1]):
            problems.append("front-end range %s is %r; it must be an ordered pair of positive "
                            "integers" % (field, span))
    window = envelope.get("window_samples")
    if isinstance(window, list) and len(window) == 2 and isinstance(samples, int):
        if window[1] > samples:
            problems.append("the widest declarable window %r does not fit inside a %r-sample "
                            "utterance" % (window[1], samples))
    for key in ("sample_rate_hz", "window_samples", "hop_samples", "mel_bands",
                "frames_per_utterance"):
        if key not in (layout.get("front_end_keys") or []):
            problems.append("front_end_keys does not name %r, which the frame arithmetic reads"
                            % key)

    cap = layout.get("max_single_keyword_share")
    if not isinstance(cap, float) or not (1.0 / max(len(roster), 1)) < cap < 1.0:
        problems.append("the share cap is %r; it must sit strictly between the balanced share and "
                        "the whole vector" % cap)
    clips = set(layout.get("background_noise_clips") or [])
    if clips != VENDORED_NOISE_CLIPS:
        problems.append("the background roster %s is not the six clips the release ships"
                        % sorted(clips))
    snr = layout.get("noise_snr_db_range")
    if not (isinstance(snr, list) and len(snr) == 2 and snr[0] < snr[1]):
        problems.append("the mixing range is %r; it must be an ordered pair of decibels" % snr)
    if not layout.get("budget_keys"):
        problems.append("no budget keys; the declaration check would grade an empty roster")
    guarded = layout.get("guarded_writes") or []
    if "tests/" not in guarded or layout.get("graded_audio") not in guarded:
        problems.append("the guarded roots %s do not cover the checker tree and the graded audio"
                        % guarded)
    return problems


def main():
    g = load_grounding()
    # The family validator runs FIRST and refuses rather than emitting: a generator that writes a
    # carrier it knows is malformed hands the drift check a moving target.
    problems = validate(g)
    if problems:
        raise SystemExit("AELLO-C8-S7 grounding is not well-formed: " + "; ".join(problems))

    layout = g["corpus_layout"]
    envelope = layout["front_end_envelope"]
    outcome_id = [i["id"] for i in g["items"] if i["dimension"] == "outcome"][0]
    subst = {
        "slot_id": SLOT_ID,
        "path": g["deliverable"]["path"],
        "outcome_id": outcome_id,
        "train_audio": layout["train_audio"],
        "graded_audio": layout["graded_audio"],
        "keyword_index_file": layout["keyword_index_file"],
        "graded_labels": layout["graded_labels"],
        "run_record": layout["run_record"],
        "keyword_roster": roster_literal(list(layout["keyword_roster"])),
        "keyword_count": layout["keyword_count"],
        "utterances_per_keyword": layout["utterances_per_keyword"],
        "graded_utterance_count": layout["graded_utterance_count"],
        "max_single_keyword_share": layout["max_single_keyword_share"],
        "sample_rate_hz": layout["sample_rate_hz"],
        "utterance_samples": layout["utterance_samples"],
        "latency_bound_ms": layout["per_utterance_latency_bound_ms"],
        "latency_gate_statistic": layout["latency_gate_statistic"],
        "admitted_latency_sources": tuple(layout["admitted_latency_sources"]),
        "rejected_latency_sources": tuple(layout["rejected_latency_sources"]),
        "agent_timing_fields": tuple(layout["agent_timing_fields_refused"]),
        "front_end_keys": tuple(layout["front_end_keys"]),
        "window_range": tuple(envelope["window_samples"]),
        "hop_range": tuple(envelope["hop_samples"]),
        "mel_range": tuple(envelope["mel_bands"]),
        "noise_clips": tuple(layout["background_noise_clips"]),
        "noise_snr_range": tuple(layout["noise_snr_db_range"]),
        "training_split_tokens": tuple(layout["training_split_tokens"]),
        "budget_keys": tuple(layout["budget_keys"]),
        "guarded_writes": tuple(layout["guarded_writes"]),
    }

    # EVERY compiled item carries a written body, and the generator REFUSES when one does not.
    # The generic obligation lookup that used to stand here read a run-record key nothing writes,
    # so an item falling through to it consulted nothing and reported that it had passed.
    bodies = dict(BODIES)
    for it in g["items"]:
        if it["mode"] == "compiled" and it["id"] not in bodies:
            raise SystemExit("AELLO-C8-S7: no body written for compiled item %r; the generator "
                             "refuses rather than emitting a check that consults nothing"
                             % it["id"])
    stray = sorted(set(bodies) - {i["id"] for i in g["items"]})
    if stray:
        raise SystemExit("AELLO-C8-S7: bodies %s belong to no item in the grounding" % stray)
    # The outcome check must SAY the slot is unmeasurable before it reads anything. Reading the
    # artifact first lets a missing-file failure mask the unmeasured signal, and the verifier then
    # reports gradeable=true with r_det=0.0. seed/build/freeze_batch.py refuses that bundle.
    statements = [ln.strip() for ln in bodies[outcome_id].splitlines()
                  if ln.strip() and not ln.strip().startswith("#")]
    if not statements or statements[0] != REQUIRE_FIRST:
        raise SystemExit("AELLO-C8-S7: %r must call require_measured as its first statement, "
                         "before it reads the submission" % outcome_id)

    tests_dir = os.path.join(BUNDLE, "tests")
    os.makedirs(tests_dir, exist_ok=True)

    # solution/TRUTH.md and solution/rubrics.json are PRIVATE_CARRIERS: seed/identity.py plants a
    # canary block into them at freeze, and canary normalisation is what keeps planting from
    # moving identity. A generator that rewrote them plainly would DROP the planted tripwire, and
    # the next content_hash would differ from the frozen one. So the planted block is carried
    # across the regeneration rather than recreated.
    truth_path = os.path.join(HERE, "TRUTH.md")
    truth = build_truth(g, TITLE).rstrip("\n") + "\n"
    keep = None
    if os.path.exists(truth_path):
        import re as _re
        m = _re.search(r"<!-- AELLO-CANARY-BLOCK.*?-->\n?", open(truth_path).read(), _re.S)
        keep = m.group(0) if m else None
    with open(truth_path, "w") as fh:
        fh.write(truth + ("\n" + keep if keep else ""))

    rub_path = os.path.join(HERE, "rubrics.json")
    rub = build_rubrics(g, ITEM_KEYS)
    if os.path.exists(rub_path):
        try:
            prev = json.load(open(rub_path))
            if "canary" in prev:
                rub["canary"] = prev["canary"]
        except Exception:
            pass
    with open(rub_path, "w") as fh:
        json.dump(rub, fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "rubrics.json"), "w") as fh:
        json.dump(build_rubrics(g, ITEM_KEYS), fh, indent=1, sort_keys=True)
        fh.write("\n")
    with open(os.path.join(tests_dir, "test_output.py"), "w") as fh:
        # The tail arrives FINAL and is NOT substituted: it is family-shaped, it has already
        # resolved every placeholder it owns, and it legitimately contains percent signs of its
        # own, so formatting it a second time raises TypeError. Only the prelude is substituted.
        fh.write(build_tests(g, PRELUDE % subst, bodies) + TAIL)
    with open(os.path.join(tests_dir, "constants.json"), "w") as fh:
        json.dump(g["constants"], fh, indent=1, sort_keys=True)
        fh.write("\n")
    # ORDER MATTERS. `with open(path, "w")` truncates BEFORE its body's arguments are evaluated,
    # so calling read_identity() inside the with-statement reads the file this line just emptied
    # and writes nulls over the frozen identity. Read first, then open.
    prov = build_provenance(g, read_identity(HERE))
    with open(os.path.join(HERE, "provenance.yaml"), "w") as fh:
        # MATCH seed/build/screen_bind.py and the frozen generators exactly: sort_keys=True,
        # default_flow_style=False, width=100. The screen writes this carrier after the freeze,
        # so a generator using a different dump convention reorders the keys on the next
        # regeneration and reports as drift even though no value changed.
        yaml.safe_dump(prov, fh, sort_keys=True, default_flow_style=False, width=100,
                       allow_unicode=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
